// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Image_ColorRGF: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into Image_ColorRGF.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.Image;

[StructLayout(LayoutKind.Explicit, Size = 8)]
public partial struct Image_ColorRGF
{
    [FieldOffset(0)] public float v_0;
    [FieldOffset(4)] public float v_1;

    public Image_ColorRGF()
    {
        this = default;
        ImageModule.NetOcc_Image_ColorRGF_New(ref this);
    }

    public static int Length() => ImageModule.NetOcc_Image_ColorRGF_Length();
    public readonly float r() => ImageModule.NetOcc_Image_ColorRGF_r_0(in this);
    public readonly float g() => ImageModule.NetOcc_Image_ColorRGF_g_0(in this);
}
