// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;

// NUnit
using NUnit.Framework;

namespace NetOcc.Generator.Tests;

/// <summary>
/// The whole generate pipeline (libclang, registry, mapper, writer) over a fake OCCT tree in <c>Golden/</c>,
/// compared with <c>Golden/expected/</c>. After an intended output change, rerun with NETOCC_UPDATE_GOLDEN=1
/// and review the diff of the expected files.
/// </summary>
[TestFixture]
public class GoldenTests
{
    private static readonly string Fixture = Path.Combine(SourceDirectory(), "Golden");

    // a struct the package no longer has, the nested header of a package without nested types
    private static readonly string[] StaleOutputs = ["core/src/NetOcc/Demo/Demo_Gone.g.cs", "core/src/SWIG_files/headers/Standard_nested.hxx"];

    private string _work = null!;

    // generated file -> expected file
    private static IEnumerable<TestCaseData> Outputs()
    {
        yield return Output("core/src/SWIG_files/wrapper/Standard.i", "Standard.i");
        yield return Output("core/src/SWIG_files/headers/Standard_module.hxx", "Standard_module.hxx");
        yield return Output("core/src/SWIG_files/wrapper/Demo.i", "Demo.i");
        yield return Output("core/src/SWIG_files/headers/Demo_module.hxx", "Demo_module.hxx");
        yield return Output("core/src/NetOcc/Demo/Demo_Vec.g.cs", "Demo_Vec.g.cs");
        yield return Output("core/src/NetOcc/Demo/Demo_Curve_ResD1.g.cs", "Demo_Curve_ResD1.g.cs");
        yield return Output("core/src/NetOcc/Demo/Demo_Result.g.cs", "Demo_Result.g.cs");
        yield return Output("core/src/NetOcc/Demo/Demo_FaceId.g.cs", "Demo_FaceId.g.cs");
        yield return Output("core/src/NetOcc/Demo/Demo_TypedId_3.g.cs", "Demo_TypedId_3.g.cs");
        yield return Output("core/src/NetOcc/Standard/Standard_UUID.g.cs", "Standard_UUID.g.cs");
        yield return Output("core/src/SWIG_files/headers/Demo_nested.hxx", "Demo_nested.hxx");
        yield return Output("core/src/SWIG_files/wrapper/TColDemo.i", "TColDemo.i");
        yield return Output("core/src/SWIG_files/headers/TColDemo_module.hxx", "TColDemo_module.hxx");
        yield return Output("core/src/SWIG_files/modules.json", "modules.json");
        yield return Output("log/skips/Standard.txt", "Standard.skips.txt");
        yield return Output("log/skips/Demo.txt", "Demo.skips.txt");
    }

    [OneTimeSetUp]
    public void Generate()
    {
        _work = Path.Combine(Path.GetTempPath(), $"netocc-gen-golden-{Guid.NewGuid():N}");
        var include = Directory.CreateDirectory(Path.Combine(_work, "include")).FullName;
        foreach (var header in Directory.EnumerateFiles(Path.Combine(Fixture, "occt"), "*.hxx", SearchOption.AllDirectories))
        {
            File.Copy(header, Path.Combine(include, Path.GetFileName(header)));
        }

        var config = Directory.CreateDirectory(Path.Combine(_work, "config")).FullName;
        foreach (var file in Directory.EnumerateFiles(Path.Combine(Fixture, "config")))
        {
            File.Copy(file, Path.Combine(config, Path.GetFileName(file)));
        }

        var swigFiles = Path.Combine(_work, "core", "src", "SWIG_files");
        Directory.CreateDirectory(Path.Combine(swigFiles, "wrapper"));
        Directory.CreateDirectory(Path.Combine(swigFiles, "headers"));
        Directory.CreateDirectory(Path.Combine(swigFiles, "extras"));
        File.Copy(Path.Combine(Fixture, "extras", "Demo.i"), Path.Combine(swigFiles, "extras", "Demo.i"));
        var structs = Directory.CreateDirectory(Path.Combine(_work, "core", "src", "NetOcc", "Demo")).FullName;
        File.Copy(Path.Combine(Fixture, "partials", "Demo_Vec.cs"), Path.Combine(structs, "Demo_Vec.cs"));
        // outputs of an earlier run whose types went away
        foreach (var stale in StaleOutputs)
        {
            File.WriteAllText(Path.Combine(_work, stale), "// generated by netocc-gen\n");
        }

        // no OCCT libraries: callability falls back to definitions and dllexport attributes
        var exit = Generator.Generate.Run(Path.Combine(Fixture, "occt"), include, Path.Combine(_work, "no-libraries"), Path.Combine(_work, "core"),
            Path.Combine(config, "modules.yaml"), [], TextWriter.Null);
        Assert.That(exit, Is.Zero, "netocc-gen generate failed on the golden fixture");
    }

    [OneTimeTearDown]
    public void DeleteWork() => Directory.Delete(_work, true);

    [TestCaseSource(nameof(Outputs))]
    public void Generate_MatchesTheExpectedOutput(string generated, string expected)
    {
        // Arrange
        var expectedPath = Path.Combine(Fixture, "expected", expected);

        // Act
        var actual = File.ReadAllText(Path.Combine(_work, generated));

        // Assert
        if (Environment.GetEnvironmentVariable("NETOCC_UPDATE_GOLDEN") == "1")
        {
            File.WriteAllText(expectedPath, actual);
            Assert.Pass($"updated {expected}");
        }

        Assert.That(actual, Is.EqualTo(File.ReadAllText(expectedPath).Replace("\r\n", "\n")), $"{expected} differs; if intended, rerun with NETOCC_UPDATE_GOLDEN=1");
    }

    [Test]
    public void Generate_RemovesOutputsItNoLongerWrites()
    {
        // Arrange
        // (the stale files written before the run)

        // Act
        var left = StaleOutputs.Where(stale => File.Exists(Path.Combine(_work, stale)));

        // Assert
        Assert.That(left, Is.Empty);
    }

    private static TestCaseData Output(string generated, string expected) => new TestCaseData(generated, expected).SetArgDisplayNames(expected);

    // the fixture lives next to this file in the source tree, so NETOCC_UPDATE_GOLDEN writes there, not into bin/
    private static string SourceDirectory([CallerFilePath] string path = "") => Path.GetDirectoryName(path)!;
}
