// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// gp_Hypr2d: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into gp_Hypr2d.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.gp;

[StructLayout(LayoutKind.Explicit, Size = 64)]
public partial struct gp_Hypr2d
{
    [FieldOffset(0)] private gp_Ax22d pos;
    [FieldOffset(48)] private double majorRadius;
    [FieldOffset(56)] private double minorRadius;

    public gp_Hypr2d()
    {
        this = default;
        gpModule.NetOcc_gp_Hypr2d_New_0(ref this);
    }

    public gp_Hypr2d(in gp_Ax2d theMajorAxis, double theMajorRadius, double theMinorRadius)
    {
        this = default;
        gpModule.NetOcc_gp_Hypr2d_New_1(ref this, in theMajorAxis, theMajorRadius, theMinorRadius);
    }

    public gp_Hypr2d(in gp_Ax2d theMajorAxis, double theMajorRadius, double theMinorRadius, bool theIsSense)
    {
        this = default;
        gpModule.NetOcc_gp_Hypr2d_New_1(ref this, in theMajorAxis, theMajorRadius, theMinorRadius, theIsSense);
    }

    public gp_Hypr2d(in gp_Ax22d theA, double theMajorRadius, double theMinorRadius)
    {
        this = default;
        gpModule.NetOcc_gp_Hypr2d_New_2(ref this, in theA, theMajorRadius, theMinorRadius);
    }

    public void SetLocation(in gp_Pnt2d theP) => gpModule.NetOcc_gp_Hypr2d_SetLocation(ref this, in theP);
    public void SetMajorRadius(double theMajorRadius) => gpModule.NetOcc_gp_Hypr2d_SetMajorRadius(ref this, theMajorRadius);
    public void SetMinorRadius(double theMinorRadius) => gpModule.NetOcc_gp_Hypr2d_SetMinorRadius(ref this, theMinorRadius);
    public void SetAxis(in gp_Ax22d theA) => gpModule.NetOcc_gp_Hypr2d_SetAxis(ref this, in theA);
    public void SetXAxis(in gp_Ax2d theA) => gpModule.NetOcc_gp_Hypr2d_SetXAxis(ref this, in theA);
    public void SetYAxis(in gp_Ax2d theA) => gpModule.NetOcc_gp_Hypr2d_SetYAxis(ref this, in theA);
    public readonly gp_Ax2d Asymptote1() => gpModule.NetOcc_gp_Hypr2d_Asymptote1(in this);
    public readonly gp_Ax2d Asymptote2() => gpModule.NetOcc_gp_Hypr2d_Asymptote2(in this);
    public readonly void Coefficients(ref double theA, ref double theB, ref double theC, ref double theD, ref double theE, ref double theF) => gpModule.NetOcc_gp_Hypr2d_Coefficients(in this, ref theA, ref theB, ref theC, ref theD, ref theE, ref theF);
    public readonly gp_Hypr2d ConjugateBranch1() => gpModule.NetOcc_gp_Hypr2d_ConjugateBranch1(in this);
    public readonly gp_Hypr2d ConjugateBranch2() => gpModule.NetOcc_gp_Hypr2d_ConjugateBranch2(in this);
    public readonly gp_Ax2d Directrix1() => gpModule.NetOcc_gp_Hypr2d_Directrix1(in this);
    public readonly gp_Ax2d Directrix2() => gpModule.NetOcc_gp_Hypr2d_Directrix2(in this);
    public readonly double Eccentricity() => gpModule.NetOcc_gp_Hypr2d_Eccentricity(in this);
    public readonly double Focal() => gpModule.NetOcc_gp_Hypr2d_Focal(in this);
    public readonly gp_Pnt2d Focus1() => gpModule.NetOcc_gp_Hypr2d_Focus1(in this);
    public readonly gp_Pnt2d Focus2() => gpModule.NetOcc_gp_Hypr2d_Focus2(in this);
    public readonly gp_Pnt2d Location() => gpModule.NetOcc_gp_Hypr2d_Location(in this);
    public readonly double MajorRadius() => gpModule.NetOcc_gp_Hypr2d_MajorRadius(in this);
    public readonly double MinorRadius() => gpModule.NetOcc_gp_Hypr2d_MinorRadius(in this);
    public readonly gp_Hypr2d OtherBranch() => gpModule.NetOcc_gp_Hypr2d_OtherBranch(in this);
    public readonly double Parameter() => gpModule.NetOcc_gp_Hypr2d_Parameter(in this);
    public readonly gp_Ax22d Axis() => gpModule.NetOcc_gp_Hypr2d_Axis(in this);
    public readonly gp_Ax2d XAxis() => gpModule.NetOcc_gp_Hypr2d_XAxis(in this);
    public readonly gp_Ax2d YAxis() => gpModule.NetOcc_gp_Hypr2d_YAxis(in this);
    public void Reverse() => gpModule.NetOcc_gp_Hypr2d_Reverse(ref this);
    public readonly gp_Hypr2d Reversed() => gpModule.NetOcc_gp_Hypr2d_Reversed(in this);
    public readonly bool IsDirect() => gpModule.NetOcc_gp_Hypr2d_IsDirect(in this);
    public void Mirror(in gp_Pnt2d theP) => gpModule.NetOcc_gp_Hypr2d_Mirror_0(ref this, in theP);
    public void Mirror(in gp_Ax2d theA) => gpModule.NetOcc_gp_Hypr2d_Mirror_1(ref this, in theA);
    public readonly gp_Hypr2d Mirrored(in gp_Pnt2d theP) => gpModule.NetOcc_gp_Hypr2d_Mirrored_0(in this, in theP);
    public readonly gp_Hypr2d Mirrored(in gp_Ax2d theA) => gpModule.NetOcc_gp_Hypr2d_Mirrored_1(in this, in theA);
    public void Rotate(in gp_Pnt2d theP, double theAng) => gpModule.NetOcc_gp_Hypr2d_Rotate(ref this, in theP, theAng);
    public readonly gp_Hypr2d Rotated(in gp_Pnt2d theP, double theAng) => gpModule.NetOcc_gp_Hypr2d_Rotated(in this, in theP, theAng);
    public void Scale(in gp_Pnt2d theP, double theS) => gpModule.NetOcc_gp_Hypr2d_Scale(ref this, in theP, theS);
    public readonly gp_Hypr2d Scaled(in gp_Pnt2d theP, double theS) => gpModule.NetOcc_gp_Hypr2d_Scaled(in this, in theP, theS);
    public void Transform(in gp_Trsf2d theT) => gpModule.NetOcc_gp_Hypr2d_Transform(ref this, in theT);
    public readonly gp_Hypr2d Transformed(in gp_Trsf2d theT) => gpModule.NetOcc_gp_Hypr2d_Transformed(in this, in theT);
    public void Translate(in gp_Vec2d theV) => gpModule.NetOcc_gp_Hypr2d_Translate_0(ref this, in theV);
    public void Translate(in gp_Pnt2d theP1, in gp_Pnt2d theP2) => gpModule.NetOcc_gp_Hypr2d_Translate_1(ref this, in theP1, in theP2);
    public readonly gp_Hypr2d Translated(in gp_Vec2d theV) => gpModule.NetOcc_gp_Hypr2d_Translated_0(in this, in theV);
    public readonly gp_Hypr2d Translated(in gp_Pnt2d theP1, in gp_Pnt2d theP2) => gpModule.NetOcc_gp_Hypr2d_Translated_1(in this, in theP1, in theP2);
}
