// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// HLRAlgo_PolyHidingData_TriangleIndices: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into HLRAlgo_PolyHidingData_TriangleIndices.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.HLRAlgo;

[StructLayout(LayoutKind.Explicit, Size = 12)]
public partial struct HLRAlgo_PolyHidingData_TriangleIndices
{
    [FieldOffset(0)] public int Index;
    [FieldOffset(4)] public int Min;
    [FieldOffset(8)] public int Max;

    public HLRAlgo_PolyHidingData_TriangleIndices()
    {
        this = default;
        HLRAlgoModule.NetOcc_HLRAlgo_PolyHidingData_TriangleIndices_New(ref this);
    }
}
