// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// HLRAlgo_PolyInternalNode_NodeData: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into HLRAlgo_PolyInternalNode_NodeData.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.HLRAlgo;

using OCC.Core.gp;

[StructLayout(LayoutKind.Explicit, Size = 88)]
public partial struct HLRAlgo_PolyInternalNode_NodeData
{
    [FieldOffset(0)] public gp_XYZ Point;
    [FieldOffset(24)] public gp_XYZ Normal;
    [FieldOffset(48)] public gp_XY UV;
    [FieldOffset(64)] public double PCu1;
    [FieldOffset(72)] public double PCu2;
    [FieldOffset(80)] public double Scal;

    public HLRAlgo_PolyInternalNode_NodeData()
    {
        this = default;
        HLRAlgoModule.NetOcc_HLRAlgo_PolyInternalNode_NodeData_New(ref this);
    }
}
