// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Bnd_Box2d: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into Bnd_Box2d.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.Bnd;

using OCC.Core.gp;

[StructLayout(LayoutKind.Explicit, Size = 48)]
public partial struct Bnd_Box2d
{
    [FieldOffset(0)] private double Xmin;
    [FieldOffset(8)] private double Xmax;
    [FieldOffset(16)] private double Ymin;
    [FieldOffset(24)] private double Ymax;
    [FieldOffset(32)] private double Gap;
    [FieldOffset(40)] private int Flags;

    public Bnd_Box2d()
    {
        this = default;
        BndModule.NetOcc_Bnd_Box2d_New(ref this);
    }

    public void SetWhole() => BndModule.NetOcc_Bnd_Box2d_SetWhole(ref this);
    public void SetVoid() => BndModule.NetOcc_Bnd_Box2d_SetVoid(ref this);
    public void Set(in gp_Pnt2d thePnt) => BndModule.NetOcc_Bnd_Box2d_Set_0(ref this, in thePnt);
    public void Set(in gp_Pnt2d thePnt, in gp_Dir2d theDir) => BndModule.NetOcc_Bnd_Box2d_Set_1(ref this, in thePnt, in theDir);
    public void Update(double aXmin, double aYmin, double aXmax, double aYmax) => BndModule.NetOcc_Bnd_Box2d_Update_0(ref this, aXmin, aYmin, aXmax, aYmax);
    public void Update(double X, double Y) => BndModule.NetOcc_Bnd_Box2d_Update_1(ref this, X, Y);
    public readonly double GetGap() => BndModule.NetOcc_Bnd_Box2d_GetGap(in this);
    public void SetGap(double Tol) => BndModule.NetOcc_Bnd_Box2d_SetGap(ref this, Tol);
    public void Enlarge(double theTol) => BndModule.NetOcc_Bnd_Box2d_Enlarge(ref this, theTol);
    public readonly void Get(ref double aXmin, ref double aYmin, ref double aXmax, ref double aYmax) => BndModule.NetOcc_Bnd_Box2d_Get_0(in this, ref aXmin, ref aYmin, ref aXmax, ref aYmax);
    public readonly Bnd_Box2d_Limits Get() => BndModule.NetOcc_Bnd_Box2d_Get_1(in this);
    public readonly double GetXMin() => BndModule.NetOcc_Bnd_Box2d_GetXMin(in this);
    public readonly double GetXMax() => BndModule.NetOcc_Bnd_Box2d_GetXMax(in this);
    public readonly double GetYMin() => BndModule.NetOcc_Bnd_Box2d_GetYMin(in this);
    public readonly double GetYMax() => BndModule.NetOcc_Bnd_Box2d_GetYMax(in this);
    public readonly gp_Pnt2d? Center() => BndModule.NetOcc_Bnd_Box2d_Center(in this);
    public void OpenXmin() => BndModule.NetOcc_Bnd_Box2d_OpenXmin(ref this);
    public void OpenXmax() => BndModule.NetOcc_Bnd_Box2d_OpenXmax(ref this);
    public void OpenYmin() => BndModule.NetOcc_Bnd_Box2d_OpenYmin(ref this);
    public void OpenYmax() => BndModule.NetOcc_Bnd_Box2d_OpenYmax(ref this);
    public readonly bool IsOpenXmin() => BndModule.NetOcc_Bnd_Box2d_IsOpenXmin(in this);
    public readonly bool IsOpenXmax() => BndModule.NetOcc_Bnd_Box2d_IsOpenXmax(in this);
    public readonly bool IsOpenYmin() => BndModule.NetOcc_Bnd_Box2d_IsOpenYmin(in this);
    public readonly bool IsOpenYmax() => BndModule.NetOcc_Bnd_Box2d_IsOpenYmax(in this);
    public readonly bool IsWhole() => BndModule.NetOcc_Bnd_Box2d_IsWhole(in this);
    public readonly bool IsVoid() => BndModule.NetOcc_Bnd_Box2d_IsVoid(in this);
    public readonly Bnd_Box2d Transformed(in gp_Trsf2d T) => BndModule.NetOcc_Bnd_Box2d_Transformed(in this, in T);
    public void Add(in Bnd_Box2d Other) => BndModule.NetOcc_Bnd_Box2d_Add_0(ref this, in Other);
    public void Add(in gp_Pnt2d thePnt) => BndModule.NetOcc_Bnd_Box2d_Add_1(ref this, in thePnt);
    public void Add(in gp_Pnt2d thePnt, in gp_Dir2d theDir) => BndModule.NetOcc_Bnd_Box2d_Add_2(ref this, in thePnt, in theDir);
    public void Add(in gp_Dir2d D) => BndModule.NetOcc_Bnd_Box2d_Add_3(ref this, in D);
    public readonly bool IsOut(in gp_Pnt2d P) => BndModule.NetOcc_Bnd_Box2d_IsOut_0(in this, in P);
    public readonly bool IsOut(in gp_Lin2d theL) => BndModule.NetOcc_Bnd_Box2d_IsOut_1(in this, in theL);
    public readonly bool IsOut(in gp_Pnt2d theP0, in gp_Pnt2d theP1) => BndModule.NetOcc_Bnd_Box2d_IsOut_2(in this, in theP0, in theP1);
    public readonly bool IsOut(in Bnd_Box2d Other) => BndModule.NetOcc_Bnd_Box2d_IsOut_3(in this, in Other);
    public readonly bool IsOut(in Bnd_Box2d theOther, in gp_Trsf2d theTrsf) => BndModule.NetOcc_Bnd_Box2d_IsOut_4(in this, in theOther, in theTrsf);
    public readonly bool IsOut(in gp_Trsf2d T1, in Bnd_Box2d Other, in gp_Trsf2d T2) => BndModule.NetOcc_Bnd_Box2d_IsOut_5(in this, in T1, in Other, in T2);
    public readonly bool Contains(in gp_Pnt2d theP) => BndModule.NetOcc_Bnd_Box2d_Contains(in this, in theP);
    public readonly bool Intersects(in Bnd_Box2d theOther) => BndModule.NetOcc_Bnd_Box2d_Intersects(in this, in theOther);
    public readonly double Distance(in Bnd_Box2d theOther) => BndModule.NetOcc_Bnd_Box2d_Distance(in this, in theOther);
    public readonly void Dump() => BndModule.NetOcc_Bnd_Box2d_Dump(in this);
    public readonly double SquareExtent() => BndModule.NetOcc_Bnd_Box2d_SquareExtent(in this);
}
