// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Geom2d_Curve_ResD1: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into Geom2d_Curve_ResD1.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.Geom2d;

using OCC.Core.gp;

[StructLayout(LayoutKind.Explicit, Size = 32)]
public partial struct Geom2d_Curve_ResD1
{
    [FieldOffset(0)] public gp_Pnt2d Point;
    [FieldOffset(16)] public gp_Vec2d D1;

    public Geom2d_Curve_ResD1()
    {
        this = default;
        Geom2dModule.NetOcc_Geom2d_Curve_ResD1_New(ref this);
    }
}
