// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* AdvApprox: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module AdvApproxModule

%include "NetOcc.i"

%{
#include <AdvApprox_module.hxx>
%}

%import "GeomAbs.i"
%import "Standard.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "gp.i"
%import "TColgp.i"
%import "math.i"
%import "PLib.i"
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.math; using OCC.Core.PLib;)

%nodefaultctor AdvApprox_EvaluatorFunction;
%occt_valueclass(AdvApprox_ApproxAFunction)
%nodefaultctor AdvApprox_ApproxAFunction;
%feature("valuewrapper") AdvApprox_ApproxAFunction;
%nodefaultctor AdvApprox_Cutting;
%occt_valueclass(AdvApprox_DichoCutting)
%occt_valueclass(AdvApprox_PrefAndRec)
%nodefaultctor AdvApprox_PrefAndRec;
%feature("valuewrapper") AdvApprox_PrefAndRec;
%occt_valueclass(AdvApprox_PrefCutting)
%nodefaultctor AdvApprox_PrefCutting;
%feature("valuewrapper") AdvApprox_PrefCutting;
%occt_valueclass(AdvApprox_SimpleApprox)
%nodefaultctor AdvApprox_SimpleApprox;
%feature("valuewrapper") AdvApprox_SimpleApprox;

class AdvApprox_EvaluatorFunction {
public:
  void Evaluate(int* Dimension, double* StartEnd, double* Parameter, int* DerivativeRequest, double* Result, int* ErrorCode);
};

class AdvApprox_ApproxAFunction {
public:
  AdvApprox_ApproxAFunction(int Num1DSS, int Num2DSS, int Num3DSS, const opencascade::handle<NCollection_HArray1<double>>& OneDTol, const opencascade::handle<NCollection_HArray1<double>>& TwoDTol, const opencascade::handle<NCollection_HArray1<double>>& ThreeDTol, double First, double Last, GeomAbs_Shape Continuity, int MaxDeg, int MaxSeg, const AdvApprox_EvaluatorFunction& Func);
  AdvApprox_ApproxAFunction(int Num1DSS, int Num2DSS, int Num3DSS, const opencascade::handle<NCollection_HArray1<double>>& OneDTol, const opencascade::handle<NCollection_HArray1<double>>& TwoDTol, const opencascade::handle<NCollection_HArray1<double>>& ThreeDTol, double First, double Last, GeomAbs_Shape Continuity, int MaxDeg, int MaxSeg, const AdvApprox_EvaluatorFunction& Func, const AdvApprox_Cutting& CutTool);
  static void Approximation(int TotalDimension, int TotalNumSS, const NCollection_Array1<int>& LocalDimension, double First, double Last, AdvApprox_EvaluatorFunction& Evaluator, const AdvApprox_Cutting& CutTool, int ContinuityOrder, int NumMaxCoeffs, int MaxSegments, const NCollection_Array1<double>& TolerancesArray, int code_precis, int& NumCurves, NCollection_Array1<int>& NumCoeffPerCurveArray, NCollection_Array1<double>& LocalCoefficientArray, NCollection_Array1<double>& IntervalsArray, NCollection_Array1<double>& ErrorMaxArray, NCollection_Array1<double>& AverageErrorArray, int& ErrorCode);
  bool IsDone() const;
  bool HasResult() const;
  opencascade::handle<NCollection_HArray2<double>> Poles1d() const;
  opencascade::handle<NCollection_HArray2<gp_Pnt2d>> Poles2d() const;
  opencascade::handle<NCollection_HArray2<gp_Pnt>> Poles() const;
  int NbPoles() const;
  void Poles1d(int Index, NCollection_Array1<double>& P) const;
  void Poles2d(int Index, NCollection_Array1<gp_Pnt2d>& P) const;
  void Poles(int Index, NCollection_Array1<gp_Pnt>& P) const;
  int Degree() const;
  int NbKnots() const;
  int NumSubSpaces(int Dimension) const;
  opencascade::handle<NCollection_HArray1<double>> Knots() const;
  opencascade::handle<NCollection_HArray1<int>> Multiplicities() const;
  opencascade::handle<NCollection_HArray1<double>> MaxError(int Dimension) const;
  opencascade::handle<NCollection_HArray1<double>> AverageError(int Dimension) const;
  double MaxError(int Dimension, int Index) const;
  double AverageError(int Dimension, int Index) const;
  void Dump(std::ostream& o) const;
};

class AdvApprox_Cutting {
public:
  bool Value(double a, double b, double& cuttingvalue) const;
};

class AdvApprox_DichoCutting : public AdvApprox_Cutting {
public:
  AdvApprox_DichoCutting();
  bool Value(double a, double b, double& cuttingvalue) const;
};

class AdvApprox_PrefAndRec : public AdvApprox_Cutting {
public:
  AdvApprox_PrefAndRec(const NCollection_Array1<double>& RecomendedCut, const NCollection_Array1<double>& PrefferedCut, double Weight = 5);
  bool Value(double a, double b, double& cuttingvalue) const;
};

class AdvApprox_PrefCutting : public AdvApprox_Cutting {
public:
  AdvApprox_PrefCutting(const NCollection_Array1<double>& CutPnts);
  bool Value(double a, double b, double& cuttingvalue) const;
};

class AdvApprox_SimpleApprox {
public:
  AdvApprox_SimpleApprox(int TotalDimension, int TotalNumSS, GeomAbs_Shape Continuity, int WorkDegree, int NbGaussPoints, const PLib_JacobiPolynomial& JacobiBase, const AdvApprox_EvaluatorFunction& Func);
  void Perform(const NCollection_Array1<int>& LocalDimension, const NCollection_Array1<double>& LocalTolerancesArray, double First, double Last, int MaxDegree);
  bool IsDone() const;
  int Degree() const;
  opencascade::handle<NCollection_HArray1<double>> Coefficients() const;
  opencascade::handle<NCollection_HArray2<double>> FirstConstr() const;
  opencascade::handle<NCollection_HArray2<double>> LastConstr() const;
  opencascade::handle<NCollection_HArray1<double>> SomTab() const;
  opencascade::handle<NCollection_HArray1<double>> DifTab() const;
  double MaxError(int Index) const;
  double AverageError(int Index) const;
  void Dump(std::ostream& o) const;
};
