// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* BinLDrivers: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module BinLDriversModule

%include "NetOcc.i"

%{
#include <BinLDrivers_module.hxx>
%}

%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "NCollection.i"
%import "Storage.i"
%import "TDF.i"
%import "BinObjMgt.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "BinMDF.i"
%import "Resource.i"
%import "CDM.i"
%import "LDOM.i"
%import "PCDM.i"
%import "CDF.i"
%import "TDocStd.i"
%netocc_csimports(using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.Storage; using OCC.Core.TDF; using OCC.Core.BinObjMgt; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.BinMDF; using OCC.Core.Resource; using OCC.Core.CDM; using OCC.Core.LDOM; using OCC.Core.PCDM; using OCC.Core.CDF; using OCC.Core.TDocStd;)

%occt_valueclass(BinLDrivers)
%occt_valueclass(BinLDrivers_DocumentSection)
%occt_transient(BinLDrivers_DocumentRetrievalDriver)
%occt_transient(BinLDrivers_DocumentStorageDriver)

enum BinLDrivers_Marker {
  BinLDrivers_ENDATTRLIST = -1,
  BinLDrivers_ENDLABEL = -2,
};

class BinLDrivers {
public:
  BinLDrivers();
  static const opencascade::handle<Standard_Transient>& Factory(const Standard_GUID& theGUID);
  static void DefineFormat(const opencascade::handle<TDocStd_Application>& theApp);
  static opencascade::handle<BinMDF_ADriverTable> AttributeDrivers(const opencascade::handle<Message_Messenger>& MsgDrv);
};

class BinLDrivers_DocumentSection {
public:
  BinLDrivers_DocumentSection();
  BinLDrivers_DocumentSection(const TCollection_AsciiString& theName, bool isPostRead);
  const TCollection_AsciiString& Name() const;
  bool IsPostRead() const;
  unsigned long long Offset() const;
  void SetOffset(unsigned long long theOffset);
  unsigned long long Length() const;
  void SetLength(unsigned long long theLength);
  void WriteTOC(std::ostream& theOS, TDocStd_FormatVersion theDocFormatVersion);
  void Write(std::ostream& theOS, unsigned long long theOffset, TDocStd_FormatVersion theDocFormatVersion);
  static bool ReadTOC(BinLDrivers_DocumentSection& theSection, std::istream& theIS, TDocStd_FormatVersion theDocFormatVersion);
};

class BinLDrivers_DocumentRetrievalDriver : public PCDM_RetrievalDriver {
public:
  BinLDrivers_DocumentRetrievalDriver();
  void Read(const TCollection_ExtendedString& theFileName, const opencascade::handle<CDM_Document>& theNewDocument, const opencascade::handle<CDM_Application>& theApplication, const opencascade::handle<PCDM_ReaderFilter>& theFilter = occ::handle<PCDM_ReaderFilter>());
  void Read(std::istream& theIStream, const opencascade::handle<Storage_Data>& theStorageData, const opencascade::handle<CDM_Document>& theDoc, const opencascade::handle<CDM_Application>& theApplication, const opencascade::handle<PCDM_ReaderFilter>& theFilter = occ::handle<PCDM_ReaderFilter>());
  opencascade::handle<BinMDF_ADriverTable> AttributeDrivers(const opencascade::handle<Message_Messenger>& theMsgDriver);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class BinLDrivers_DocumentStorageDriver : public PCDM_StorageDriver {
public:
  BinLDrivers_DocumentStorageDriver();
  void Write(const opencascade::handle<CDM_Document>& theDocument, const TCollection_ExtendedString& theFileName);
  void Write(const opencascade::handle<CDM_Document>& theDocument, std::ostream& theOStream);
  opencascade::handle<BinMDF_ADriverTable> AttributeDrivers(const opencascade::handle<Message_Messenger>& theMsgDriver);
  void AddSection(const TCollection_AsciiString& theName, bool isPostRead = true);
  bool IsQuickPart(int theVersion) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};
