// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* BinMDocStd: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module BinMDocStdModule

%include "NetOcc.i"

%{
#include <BinMDocStd_module.hxx>
%}

%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "NCollection.i"
%import "Storage.i"
%import "TDF.i"
%import "BinObjMgt.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "BinMDF.i"
%netocc_csimports(using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.Storage; using OCC.Core.TDF; using OCC.Core.BinObjMgt; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.BinMDF;)

%occt_valueclass(BinMDocStd)
%occt_transient(BinMDocStd_XLinkDriver)
%nodefaultctor BinMDocStd_XLinkDriver;
%feature("valuewrapper") BinMDocStd_XLinkDriver;

class BinMDocStd {
public:
  BinMDocStd();
  static void AddDrivers(const opencascade::handle<BinMDF_ADriverTable>& theDriverTable, const opencascade::handle<Message_Messenger>& aMsgDrv);
};

class BinMDocStd_XLinkDriver : public BinMDF_ADriver {
public:
  BinMDocStd_XLinkDriver(const opencascade::handle<Message_Messenger>& theMessageDriver);
  opencascade::handle<TDF_Attribute> NewEmpty() const;
  bool Paste(const BinObjMgt_Persistent& Source, const opencascade::handle<TDF_Attribute>& Target, BinObjMgt_RRelocationTable& RelocTable) const;
  void Paste(const opencascade::handle<TDF_Attribute>& Source, BinObjMgt_Persistent& Target, NCollection_IndexedMap<opencascade::handle<Standard_Transient>, NCollection_DefaultHasher<opencascade::handle<Standard_Transient>>>& RelocTable) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};
