// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* BRepTopAdaptor: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module BRepTopAdaptorModule

%include "NetOcc.i"

%{
#include <BRepTopAdaptor_module.hxx>
%}

%import "GeomAbs.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "gp.i"
%import "TColgp.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "GeomEval.i"
%import "Geom.i"
%import "TopAbs.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "TopLoc.i"
%import "TopoDS.i"
%import "BRepAdaptor.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "IntCurvesFace.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "BVH.i"
%import "Bnd.i"
%import "TopTools.i"
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.TopAbs; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.TopLoc; using OCC.Core.TopoDS; using OCC.Core.BRepAdaptor; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.IntCurvesFace; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.BVH; using OCC.Core.Bnd; using OCC.Core.TopTools;)

%nodefaultctor BRepTopAdaptor_FClass2d;
%feature("valuewrapper") BRepTopAdaptor_FClass2d;
%occt_transient(BRepTopAdaptor_HVertex)
%nodefaultctor BRepTopAdaptor_HVertex;
%feature("valuewrapper") BRepTopAdaptor_HVertex;
%occt_valueclass(BRepTopAdaptor_Tool)
%occt_transient(BRepTopAdaptor_TopolTool)

%occt_datamap(BRepTopAdaptor_MapOfShapeTool, TopoDS_Shape, BRepTopAdaptor_Tool, TopTools_ShapeMapHasher, TopoDS_Shape, BRepTopAdaptor_Tool)

class BRepTopAdaptor_FClass2d {
public:
  BRepTopAdaptor_FClass2d(const TopoDS_Face& F, double Tol);
  TopAbs_State PerformInfinitePoint() const;
  TopAbs_State Perform(const gp_Pnt2d& Puv, bool RecadreOnPeriodic = true) const;
  void Destroy();
  const BRepTopAdaptor_FClass2d& Copy(const BRepTopAdaptor_FClass2d& Other) const;
  TopAbs_State TestOnRestriction(const gp_Pnt2d& Puv, double Tol, bool RecadreOnPeriodic = true) const;
};

class BRepTopAdaptor_HVertex : public Adaptor3d_HVertex {
public:
  BRepTopAdaptor_HVertex(const TopoDS_Vertex& Vtx, const opencascade::handle<BRepAdaptor_Curve2d>& Curve);
  const TopoDS_Vertex& Vertex() const;
  TopoDS_Vertex& ChangeVertex();
  gp_Pnt2d Value();
  double Parameter(const opencascade::handle<Adaptor2d_Curve2d>& C);
  double Resolution(const opencascade::handle<Adaptor2d_Curve2d>& C);
  TopAbs_Orientation Orientation();
  bool IsSame(const opencascade::handle<Adaptor3d_HVertex>& Other);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class BRepTopAdaptor_Tool {
public:
  BRepTopAdaptor_Tool();
  BRepTopAdaptor_Tool(const TopoDS_Face& F, double Tol2d);
  BRepTopAdaptor_Tool(const opencascade::handle<Adaptor3d_Surface>& Surface, double Tol2d);
  void Init(const TopoDS_Face& F, double Tol2d);
  void Init(const opencascade::handle<Adaptor3d_Surface>& Surface, double Tol2d);
  opencascade::handle<BRepTopAdaptor_TopolTool> GetTopolTool();
  void SetTopolTool(const opencascade::handle<BRepTopAdaptor_TopolTool>& TT);
  opencascade::handle<Adaptor3d_Surface> GetSurface();
  void Destroy();
};

class BRepTopAdaptor_TopolTool : public Adaptor3d_TopolTool {
public:
  BRepTopAdaptor_TopolTool();
  BRepTopAdaptor_TopolTool(const opencascade::handle<Adaptor3d_Surface>& Surface);
  void Initialize();
  void Initialize(const opencascade::handle<Adaptor3d_Surface>& S);
  void Initialize(const opencascade::handle<Adaptor2d_Curve2d>& Curve);
  void Init();
  bool More();
  opencascade::handle<Adaptor2d_Curve2d> Value();
  void Next();
  void* Edge() const;
  void InitVertexIterator();
  bool MoreVertex();
  opencascade::handle<Adaptor3d_HVertex> Vertex();
  void NextVertex();
  TopAbs_State Classify(const gp_Pnt2d& P2d, double Tol, bool RecadreOnPeriodic = true);
  bool IsThePointOn(const gp_Pnt2d& P2d, double Tol, bool RecadreOnPeriodic = true);
  TopAbs_Orientation Orientation(const opencascade::handle<Adaptor2d_Curve2d>& C);
  TopAbs_Orientation Orientation(const opencascade::handle<Adaptor3d_HVertex>& C);
  void Destroy();
  bool Has3d() const;
  double Tol3d(const opencascade::handle<Adaptor2d_Curve2d>& C) const;
  double Tol3d(const opencascade::handle<Adaptor3d_HVertex>& V) const;
  gp_Pnt Pnt(const opencascade::handle<Adaptor3d_HVertex>& V) const;
  void ComputeSamplePoints();
  int NbSamplesU();
  int NbSamplesV();
  int NbSamples();
  void SamplePoint(int Index, gp_Pnt2d& P2d, gp_Pnt& P3d);
  bool DomainIsInfinite();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};
