// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* BRepOffset: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module BRepOffsetModule

%include "NetOcc.i"

%{
#include <BRepOffset_module.hxx>
%}

%import "GeomAbs.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "gp.i"
%import "TColgp.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "GeomEval.i"
%import "Geom.i"
%import "TopAbs.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "TopLoc.i"
%import "TopoDS.i"
%import "BRepAdaptor.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "IntCurvesFace.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "BVH.i"
%import "Bnd.i"
%import "TopTools.i"
%import "BRepAlgo.i"
%import "TShort.i"
%import "Poly.i"
%import "BRep.i"
%import "BRepTools.i"
%import "Law.i"
%import "ChFiDS.i"
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.TopAbs; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.TopLoc; using OCC.Core.TopoDS; using OCC.Core.BRepAdaptor; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.IntCurvesFace; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.BVH; using OCC.Core.Bnd; using OCC.Core.TopTools; using OCC.Core.BRepAlgo; using OCC.Core.TShort; using OCC.Core.Poly; using OCC.Core.BRep; using OCC.Core.BRepTools; using OCC.Core.Law; using OCC.Core.ChFiDS;)

%occt_valueclass(BRepOffset)
%occt_valueclass(BRepOffset_Interval)
%occt_valueclass(BRepOffset_Analyse)
%occt_valueclass(BRepOffset_Inter2d)
%occt_valueclass(BRepOffset_Offset)
%occt_valueclass(BRepOffset_Inter3d)
%nodefaultctor BRepOffset_Inter3d;
%feature("valuewrapper") BRepOffset_Inter3d;
%occt_valueclass(BRepOffset_MakeLoops)
%occt_valueclass(BRepOffset_MakeOffset)
%occt_valueclass(BRepOffset_MakeSimpleOffset)
%occt_transient(BRepOffset_SimpleOffset)
%nodefaultctor BRepOffset_SimpleOffset;
%feature("valuewrapper") BRepOffset_SimpleOffset;
%occt_valueclass(BRepOffset_Tool)

enum BRepOffset_Status {
  BRepOffset_Good = 0,
  BRepOffset_Reversed = 1,
  BRepOffset_Degenerated = 2,
  BRepOffset_Unknown = 3,
};

enum BRepOffset_Error {
  BRepOffset_NoError = 0,
  BRepOffset_UnknownError = 1,
  BRepOffset_BadNormalsOnGeometry = 2,
  BRepOffset_C0Geometry = 3,
  BRepOffset_NullOffset = 4,
  BRepOffset_NotConnectedShell = 5,
  BRepOffset_CannotTrimEdges = 6,
  BRepOffset_CannotFuseVertices = 7,
  BRepOffset_CannotExtentEdge = 8,
  BRepOffset_UserBreak = 9,
  BRepOffset_MixedConnectivity = 10,
};

enum BRepOffset_Mode {
  BRepOffset_Skin = 0,
  BRepOffset_Pipe = 1,
  BRepOffset_RectoVerso = 2,
};

enum BRepOffsetSimple_Status {
  BRepOffsetSimple_OK = 0,
  BRepOffsetSimple_NullInputShape = 1,
  BRepOffsetSimple_ErrorOffsetComputation = 2,
  BRepOffsetSimple_ErrorWallFaceComputation = 3,
  BRepOffsetSimple_ErrorInvalidNbShells = 4,
  BRepOffsetSimple_ErrorNonClosedShell = 5,
};

%occt_datamap(BRepOffset_DataMapOfShapeOffset, TopoDS_Shape, BRepOffset_Offset, TopTools_ShapeMapHasher, TopoDS_Shape, BRepOffset_Offset)
%occt_list(BRepOffset_ListOfInterval, BRepOffset_Interval, BRepOffset_Interval)

class BRepOffset {
public:
  BRepOffset();
  static opencascade::handle<Geom_Surface> Surface(const opencascade::handle<Geom_Surface>& Surface, double Offset, BRepOffset_Status& theStatus, bool allowC0 = false);
  static opencascade::handle<Geom_Surface> CollapseSingularities(const opencascade::handle<Geom_Surface>& theSurface, const TopoDS_Face& theFace, double thePrecision);
};

class BRepOffset_Interval {
public:
  BRepOffset_Interval();
  BRepOffset_Interval(double U1, double U2, ChFiDS_TypeOfConcavity Type);
  void First(double U);
  void Last(double U);
  void Type(ChFiDS_TypeOfConcavity T);
  double First() const;
  double Last() const;
  ChFiDS_TypeOfConcavity Type() const;
};

class BRepOffset_Analyse {
public:
  BRepOffset_Analyse();
  BRepOffset_Analyse(const TopoDS_Shape& theS, double theAngle);
  void Perform(const TopoDS_Shape& theS, double theAngle);
  bool IsDone() const;
  const NCollection_List<BRepOffset_Interval>& Type(const TopoDS_Edge& theE) const;
  void Edges(const TopoDS_Vertex& theV, ChFiDS_TypeOfConcavity theType, NCollection_List<TopoDS_Shape>& theL) const;
  void Edges(const TopoDS_Face& theF, ChFiDS_TypeOfConcavity theType, NCollection_List<TopoDS_Shape>& theL) const;
  void TangentEdges(const TopoDS_Edge& theEdge, const TopoDS_Vertex& theVertex, NCollection_List<TopoDS_Shape>& theEdges) const;
  bool HasAncestor(const TopoDS_Shape& theS) const;
  const NCollection_List<TopoDS_Shape>& Ancestors(const TopoDS_Shape& theS) const;
  void Explode(NCollection_List<TopoDS_Shape>& theL, ChFiDS_TypeOfConcavity theType) const;
  void Explode(NCollection_List<TopoDS_Shape>& theL, ChFiDS_TypeOfConcavity theType1, ChFiDS_TypeOfConcavity theType2) const;
  void AddFaces(const TopoDS_Face& theFace, TopoDS_Compound& theCo, NCollection_Map<TopoDS_Shape, TopTools_ShapeMapHasher>& theMap, ChFiDS_TypeOfConcavity theType) const;
  void AddFaces(const TopoDS_Face& theFace, TopoDS_Compound& theCo, NCollection_Map<TopoDS_Shape, TopTools_ShapeMapHasher>& theMap, ChFiDS_TypeOfConcavity theType1, ChFiDS_TypeOfConcavity theType2) const;
  void SetOffsetValue(double theOffset);
  void SetFaceOffsetMap(const NCollection_DataMap<TopoDS_Shape, double, TopTools_ShapeMapHasher>& theMap);
  const NCollection_List<TopoDS_Shape>& NewFaces() const;
  TopoDS_Shape Generated(const TopoDS_Shape& theS) const;
  bool HasGenerated(const TopoDS_Shape& theS) const;
  const TopoDS_Edge& EdgeReplacement(const TopoDS_Face& theFace, const TopoDS_Edge& theEdge) const;
  const NCollection_List<TopoDS_Shape>* Descendants(const TopoDS_Shape& theS, bool theUpdate = false) const;
  void Clear();
};

class BRepOffset_Inter2d {
public:
  BRepOffset_Inter2d();
  static void Compute(const opencascade::handle<BRepAlgo_AsDes>& AsDes, const TopoDS_Face& F, const NCollection_IndexedMap<TopoDS_Shape, TopTools_ShapeMapHasher>& NewEdges, double Tol, const NCollection_DataMap<TopoDS_Shape, NCollection_List<TopoDS_Shape>, TopTools_ShapeMapHasher>& theEdgeIntEdges, NCollection_IndexedDataMap<TopoDS_Shape, NCollection_List<TopoDS_Shape>, TopTools_ShapeMapHasher>& theDMVV, const Message_ProgressRange& theRange);
  static bool ConnexIntByInt(const TopoDS_Face& FI, BRepOffset_Offset& OFI, NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& MES, const NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& Build, const opencascade::handle<BRepAlgo_AsDes>& theAsDes, const opencascade::handle<BRepAlgo_AsDes>& AsDes2d, double Offset, double Tol, const BRepOffset_Analyse& Analyse, NCollection_IndexedMap<TopoDS_Shape, TopTools_ShapeMapHasher>& FacesWithVerts, BRepAlgo_Image& theImageVV, NCollection_DataMap<TopoDS_Shape, NCollection_List<TopoDS_Shape>, TopTools_ShapeMapHasher>& theEdgeIntEdges, NCollection_IndexedDataMap<TopoDS_Shape, NCollection_List<TopoDS_Shape>, TopTools_ShapeMapHasher>& theDMVV, const Message_ProgressRange& theRange);
  static void ConnexIntByIntInVert(const TopoDS_Face& FI, BRepOffset_Offset& OFI, NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& MES, const NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& Build, const opencascade::handle<BRepAlgo_AsDes>& AsDes, const opencascade::handle<BRepAlgo_AsDes>& AsDes2d, double Tol, const BRepOffset_Analyse& Analyse, NCollection_IndexedDataMap<TopoDS_Shape, NCollection_List<TopoDS_Shape>, TopTools_ShapeMapHasher>& theDMVV, const Message_ProgressRange& theRange);
  static bool FuseVertices(const NCollection_IndexedDataMap<TopoDS_Shape, NCollection_List<TopoDS_Shape>, TopTools_ShapeMapHasher>& theDMVV, const opencascade::handle<BRepAlgo_AsDes>& theAsDes, BRepAlgo_Image& theImageVV);
  static bool ExtentEdge(const TopoDS_Edge& E, TopoDS_Edge& NE, double theOffset);
};

class BRepOffset_Offset {
public:
  BRepOffset_Offset();
  BRepOffset_Offset(const TopoDS_Face& Face, double Offset, bool OffsetOutside = true, GeomAbs_JoinType JoinType = GeomAbs_Arc);
  BRepOffset_Offset(const TopoDS_Face& Face, double Offset, const NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& Created, bool OffsetOutside = true, GeomAbs_JoinType JoinType = GeomAbs_Arc);
  BRepOffset_Offset(const TopoDS_Edge& Path, const TopoDS_Edge& Edge1, const TopoDS_Edge& Edge2, double Offset, bool Polynomial = false, double Tol = 1.0e-4, GeomAbs_Shape Conti = GeomAbs_C1);
  BRepOffset_Offset(const TopoDS_Edge& Path, const TopoDS_Edge& Edge1, const TopoDS_Edge& Edge2, double Offset, const TopoDS_Edge& FirstEdge, const TopoDS_Edge& LastEdge, bool Polynomial = false, double Tol = 1.0e-4, GeomAbs_Shape Conti = GeomAbs_C1);
  BRepOffset_Offset(const TopoDS_Vertex& Vertex, const NCollection_List<TopoDS_Shape>& LEdge, double Offset, bool Polynomial = false, double Tol = 1.0e-4, GeomAbs_Shape Conti = GeomAbs_C1);
  void Init(const TopoDS_Face& Face, double Offset, bool OffsetOutside = true, GeomAbs_JoinType JoinType = GeomAbs_Arc);
  void Init(const TopoDS_Face& Face, double Offset, const NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& Created, bool OffsetOutside = true, GeomAbs_JoinType JoinType = GeomAbs_Arc);
  void Init(const TopoDS_Edge& Path, const TopoDS_Edge& Edge1, const TopoDS_Edge& Edge2, double Offset, bool Polynomial = false, double Tol = 1.0e-4, GeomAbs_Shape Conti = GeomAbs_C1);
  void Init(const TopoDS_Edge& Path, const TopoDS_Edge& Edge1, const TopoDS_Edge& Edge2, double Offset, const TopoDS_Edge& FirstEdge, const TopoDS_Edge& LastEdge, bool Polynomial = false, double Tol = 1.0e-4, GeomAbs_Shape Conti = GeomAbs_C1);
  void Init(const TopoDS_Vertex& Vertex, const NCollection_List<TopoDS_Shape>& LEdge, double Offset, bool Polynomial = false, double Tol = 1.0e-4, GeomAbs_Shape Conti = GeomAbs_C1);
  void Init(const TopoDS_Edge& Edge, double Offset);
  const TopoDS_Shape& InitialShape() const;
  const TopoDS_Face& Face() const;
  TopoDS_Shape Generated(const TopoDS_Shape& Shape) const;
  BRepOffset_Status Status() const;
};

class BRepOffset_Inter3d {
public:
  BRepOffset_Inter3d(const opencascade::handle<BRepAlgo_AsDes>& AsDes, TopAbs_State Side, double Tol);
  void CompletInt(const NCollection_List<TopoDS_Shape>& SetOfFaces, const BRepAlgo_Image& InitOffsetFace, const Message_ProgressRange& theRange);
  void FaceInter(const TopoDS_Face& F1, const TopoDS_Face& F2, const BRepAlgo_Image& InitOffsetFace);
  void ConnexIntByArc(const NCollection_List<TopoDS_Shape>& SetOfFaces, const TopoDS_Shape& ShapeInit, const BRepOffset_Analyse& Analyse, const BRepAlgo_Image& InitOffsetFace, const Message_ProgressRange& theRange);
  void ConnexIntByInt(const TopoDS_Shape& SI, const NCollection_DataMap<TopoDS_Shape, BRepOffset_Offset, TopTools_ShapeMapHasher>& MapSF, const BRepOffset_Analyse& A, NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& MES, NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& Build, NCollection_List<TopoDS_Shape>& Failed, const Message_ProgressRange& theRange, bool bIsPlanar = false);
  void ContextIntByInt(const NCollection_IndexedMap<TopoDS_Shape, TopTools_ShapeMapHasher>& ContextFaces, bool ExtentContext, const NCollection_DataMap<TopoDS_Shape, BRepOffset_Offset, TopTools_ShapeMapHasher>& MapSF, const BRepOffset_Analyse& A, NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& MES, NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& Build, NCollection_List<TopoDS_Shape>& Failed, const Message_ProgressRange& theRange, bool bIsPlanar = false);
  void ContextIntByArc(const NCollection_IndexedMap<TopoDS_Shape, TopTools_ShapeMapHasher>& ContextFaces, bool ExtentContext, const BRepOffset_Analyse& Analyse, const BRepAlgo_Image& InitOffsetFace, BRepAlgo_Image& InitOffsetEdge, const Message_ProgressRange& theRange);
  void SetDone(const TopoDS_Face& F1, const TopoDS_Face& F2);
  bool IsDone(const TopoDS_Face& F1, const TopoDS_Face& F2) const;
  NCollection_IndexedMap<TopoDS_Shape, TopTools_ShapeMapHasher>& TouchedFaces();
  opencascade::handle<BRepAlgo_AsDes> AsDes() const;
  NCollection_IndexedMap<TopoDS_Shape, TopTools_ShapeMapHasher>& NewEdges();
};

class BRepOffset_MakeLoops {
public:
  BRepOffset_MakeLoops();
  void Build(const NCollection_List<TopoDS_Shape>& LF, const opencascade::handle<BRepAlgo_AsDes>& AsDes, BRepAlgo_Image& Image, BRepAlgo_Image& theImageVV, const Message_ProgressRange& theRange);
  void BuildOnContext(const NCollection_List<TopoDS_Shape>& LContext, const BRepOffset_Analyse& Analyse, const opencascade::handle<BRepAlgo_AsDes>& AsDes, BRepAlgo_Image& Image, bool InSide, const Message_ProgressRange& theRange);
  void BuildFaces(const NCollection_List<TopoDS_Shape>& LF, const opencascade::handle<BRepAlgo_AsDes>& AsDes, BRepAlgo_Image& Image, const Message_ProgressRange& theRange);
};

class BRepOffset_MakeOffset {
public:
  BRepOffset_MakeOffset();
  BRepOffset_MakeOffset(const TopoDS_Shape& S, double Offset, double Tol, BRepOffset_Mode Mode = BRepOffset_Skin, bool Intersection = false, bool SelfInter = false, GeomAbs_JoinType Join = GeomAbs_Arc, bool Thickening = false, bool RemoveIntEdges = false);
  void Initialize(const TopoDS_Shape& S, double Offset, double Tol, BRepOffset_Mode Mode = BRepOffset_Skin, bool Intersection = false, bool SelfInter = false, GeomAbs_JoinType Join = GeomAbs_Arc, bool Thickening = false, bool RemoveIntEdges = false);
  void Clear();
  void AllowLinearization(bool theIsAllowed);
  void AddFace(const TopoDS_Face& F);
  void SetOffsetOnFace(const TopoDS_Face& F, double Off);
  void MakeOffsetShape();
  void MakeThickSolid();
  bool IsDone() const;
  const TopoDS_Shape& Shape() const;
  const TopoDS_Shape& InitShape() const;
  BRepOffset_Error Error() const;
  const BRepAlgo_Image& OffsetFacesFromShapes() const;
  GeomAbs_JoinType GetJoinType() const;
  const BRepAlgo_Image& OffsetEdgesFromShapes() const;
  const NCollection_IndexedMap<TopoDS_Shape, TopTools_ShapeMapHasher>& ClosingFaces() const;
  bool CheckInputData(const Message_ProgressRange& theRange);
  const TopoDS_Shape& GetBadShape() const;
  const NCollection_List<TopoDS_Shape>& Generated(const TopoDS_Shape& theS);
  const NCollection_List<TopoDS_Shape>& Modified(const TopoDS_Shape& theS);
  bool IsDeleted(const TopoDS_Shape& S);
};

class BRepOffset_MakeSimpleOffset {
public:
  BRepOffset_MakeSimpleOffset();
  BRepOffset_MakeSimpleOffset(const TopoDS_Shape& theInputShape, double theOffsetValue);
  void Initialize(const TopoDS_Shape& theInputShape, double theOffsetValue);
  void Perform();
  TCollection_AsciiString GetErrorMessage() const;
  BRepOffsetSimple_Status GetError() const;
  bool GetBuildSolidFlag() const;
  void SetBuildSolidFlag(bool theBuildFlag);
  double GetOffsetValue() const;
  void SetOffsetValue(double theOffsetValue);
  double GetTolerance() const;
  void SetTolerance(double theValue);
  bool IsDone() const;
  const TopoDS_Shape& GetResultShape() const;
  TopoDS_Shape Generated(const TopoDS_Shape& theShape) const;
  TopoDS_Shape Modified(const TopoDS_Shape& theShape) const;
};

class BRepOffset_SimpleOffset : public BRepTools_Modification {
public:
  BRepOffset_SimpleOffset(const TopoDS_Shape& theInputShape, double theOffsetValue, double theTolerance);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
  bool NewSurface(const TopoDS_Face& F, opencascade::handle<Geom_Surface>& S, TopLoc_Location& L, double& Tol, bool& RevWires, bool& RevFace);
  bool NewCurve(const TopoDS_Edge& E, opencascade::handle<Geom_Curve>& C, TopLoc_Location& L, double& Tol);
  bool NewPoint(const TopoDS_Vertex& V, gp_Pnt& P, double& Tol);
  bool NewCurve2d(const TopoDS_Edge& E, const TopoDS_Face& F, const TopoDS_Edge& NewE, const TopoDS_Face& NewF, opencascade::handle<Geom2d_Curve>& C, double& Tol);
  bool NewParameter(const TopoDS_Vertex& V, const TopoDS_Edge& E, double& P, double& Tol);
  GeomAbs_Shape Continuity(const TopoDS_Edge& E, const TopoDS_Face& F1, const TopoDS_Face& F2, const TopoDS_Edge& NewE, const TopoDS_Face& NewF1, const TopoDS_Face& NewF2);
};

class BRepOffset_Tool {
public:
  BRepOffset_Tool();
  static void EdgeVertices(const TopoDS_Edge& E, TopoDS_Vertex& V1, TopoDS_Vertex& V2);
  static void OrientSection(const TopoDS_Edge& E, const TopoDS_Face& F1, const TopoDS_Face& F2, TopAbs_Orientation& O1, TopAbs_Orientation& O2);
  static bool FindCommonShapes(const TopoDS_Face& theF1, const TopoDS_Face& theF2, NCollection_List<TopoDS_Shape>& theLE, NCollection_List<TopoDS_Shape>& theLV);
  static bool FindCommonShapes(const TopoDS_Shape& theS1, const TopoDS_Shape& theS2, TopAbs_ShapeEnum theType, NCollection_List<TopoDS_Shape>& theLSC);
  static void Inter3D(const TopoDS_Face& F1, const TopoDS_Face& F2, NCollection_List<TopoDS_Shape>& LInt1, NCollection_List<TopoDS_Shape>& LInt2, TopAbs_State Side, const TopoDS_Edge& RefEdge, const TopoDS_Face& RefFace1, const TopoDS_Face& RefFace2);
  static bool TryProject(const TopoDS_Face& F1, const TopoDS_Face& F2, const NCollection_List<TopoDS_Shape>& Edges, NCollection_List<TopoDS_Shape>& LInt1, NCollection_List<TopoDS_Shape>& LInt2, TopAbs_State Side, double TolConf);
  static void PipeInter(const TopoDS_Face& F1, const TopoDS_Face& F2, NCollection_List<TopoDS_Shape>& LInt1, NCollection_List<TopoDS_Shape>& LInt2, TopAbs_State Side);
  static void Inter2d(const TopoDS_Face& F, const TopoDS_Edge& E1, const TopoDS_Edge& E2, NCollection_List<TopoDS_Shape>& LV, double Tol);
  static void InterOrExtent(const TopoDS_Face& F1, const TopoDS_Face& F2, NCollection_List<TopoDS_Shape>& LInt1, NCollection_List<TopoDS_Shape>& LInt2, TopAbs_State Side);
  static void CheckBounds(const TopoDS_Face& F, const BRepOffset_Analyse& Analyse, bool& enlargeU, bool& enlargeVfirst, bool& enlargeVlast);
  static bool EnLargeFace(const TopoDS_Face& F, TopoDS_Face& NF, bool ChangeGeom, bool UpDatePCurve = false, bool enlargeU = true, bool enlargeVfirst = true, bool enlargeVlast = true, int theExtensionMode = 1, double theLenBeforeUfirst = -1., double theLenAfterUlast = -1., double theLenBeforeVfirst = -1., double theLenAfterVlast = -1.);
  static void ExtentFace(const TopoDS_Face& F, NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& ConstShapes, NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& ToBuild, TopAbs_State Side, double TolConf, TopoDS_Face& NF);
  static void BuildNeighbour(const TopoDS_Wire& W, const TopoDS_Face& F, NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& NOnV1, NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& NOnV2);
  static void MapVertexEdges(const TopoDS_Shape& S, NCollection_DataMap<TopoDS_Shape, NCollection_List<TopoDS_Shape>, TopTools_ShapeMapHasher>& MVE);
  static TopoDS_Shape Deboucle3D(const TopoDS_Shape& S, const NCollection_Map<TopoDS_Shape, TopTools_ShapeMapHasher>& Boundary);
  static void CorrectOrientation(const TopoDS_Shape& SI, const NCollection_IndexedMap<TopoDS_Shape, TopTools_ShapeMapHasher>& NewEdges, const opencascade::handle<BRepAlgo_AsDes>& AsDes, BRepAlgo_Image& InitOffset, double Offset);
  static double Gabarit(const opencascade::handle<Geom_Curve>& aCurve);
  static bool CheckPlanesNormals(const TopoDS_Face& theFace1, const TopoDS_Face& theFace2, double theTolAng = 1.e-8);
};
