// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* BRepMAT2d: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module BRepMAT2dModule

%include "NetOcc.i"

%{
#include <BRepMAT2d_module.hxx>
%}

%import "GeomAbs.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "gp.i"
%import "TColgp.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "IntRes2d.i"
%import "math.i"
%import "Bisector.i"
%import "MAT.i"
%import "TColGeom2d.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "TopAbs.i"
%import "TopLoc.i"
%import "TopoDS.i"
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.IntRes2d; using OCC.Core.math; using OCC.Core.Bisector; using OCC.Core.MAT; using OCC.Core.TColGeom2d; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.TopAbs; using OCC.Core.TopLoc; using OCC.Core.TopoDS;)

%occt_valueclass(BRepMAT2d_BisectingLocus)
%occt_valueclass(BRepMAT2d_Explorer)
%occt_valueclass(BRepMAT2d_LinkTopoBilo)

class BRepMAT2d_BisectingLocus {
public:
  BRepMAT2d_BisectingLocus();
  void Compute(BRepMAT2d_Explorer& anExplo, int LineIndex = 1, MAT_Side aSide = MAT_Left, GeomAbs_JoinType aJoinType = GeomAbs_Arc, bool IsOpenResult = false);
  bool IsDone() const;
  opencascade::handle<MAT_Graph> Graph() const;
  int NumberOfContours() const;
  int NumberOfElts(int IndLine) const;
  int NumberOfSections(int IndLine, int Index) const;
  opencascade::handle<MAT_BasicElt> BasicElt(int IndLine, int Index) const;
  opencascade::handle<Geom2d_Geometry> GeomElt(const opencascade::handle<MAT_BasicElt>& aBasicElt) const;
  gp_Pnt2d GeomElt(const opencascade::handle<MAT_Node>& aNode) const;
  Bisector_Bisec GeomBis(const opencascade::handle<MAT_Arc>& anArc, bool& Reverse) const;
};

class BRepMAT2d_Explorer {
public:
  BRepMAT2d_Explorer();
  BRepMAT2d_Explorer(const TopoDS_Face& aFace);
  void Clear();
  void Perform(const TopoDS_Face& aFace);
  int NumberOfContours() const;
  int NumberOfCurves(int IndexContour) const;
  void Init(int IndexContour);
  bool More() const;
  void Next();
  opencascade::handle<Geom2d_Curve> Value() const;
  TopoDS_Shape Shape() const;
  const NCollection_Sequence<opencascade::handle<Geom2d_Curve>>& Contour(int IndexContour) const;
  bool IsModified(const TopoDS_Shape& aShape) const;
  TopoDS_Shape ModifiedShape(const TopoDS_Shape& aShape) const;
  const NCollection_Sequence<bool>& GetIsClosed() const;
};

class BRepMAT2d_LinkTopoBilo {
public:
  BRepMAT2d_LinkTopoBilo();
  BRepMAT2d_LinkTopoBilo(const BRepMAT2d_Explorer& Explo, const BRepMAT2d_BisectingLocus& BiLo);
  void Perform(const BRepMAT2d_Explorer& Explo, const BRepMAT2d_BisectingLocus& BiLo);
  void Init(const TopoDS_Shape& S);
  bool More();
  void Next();
  opencascade::handle<MAT_BasicElt> Value() const;
  TopoDS_Shape GeneratingShape(const opencascade::handle<MAT_BasicElt>& aBE) const;
};
