// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* DsgPrs: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module DsgPrsModule

%include "NetOcc.i"

%{
#include <DsgPrs_module.hxx>
%}

%import "GeomAbs.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "gp.i"
%import "TColgp.i"
%import "GeomEval.i"
%import "Geom.i"
%import "Quantity.i"
%import "Image.i"
%import "Aspect.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "TopAbs.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "OSD.i"
%import "Message.i"
%import "TopLoc.i"
%import "TopoDS.i"
%import "BRepAdaptor.i"
%import "BVH.i"
%import "Bnd.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "IntCurvesFace.i"
%import "TopTools.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "Font.i"
%import "Media.i"
%import "Graphic3d.i"
%import "TShort.i"
%import "Poly.i"
%import "Prs3d.i"
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.Quantity; using OCC.Core.Image; using OCC.Core.Aspect; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.TopAbs; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.TopLoc; using OCC.Core.TopoDS; using OCC.Core.BRepAdaptor; using OCC.Core.BVH; using OCC.Core.Bnd; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.IntCurvesFace; using OCC.Core.TopTools; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.Font; using OCC.Core.Media; using OCC.Core.Graphic3d; using OCC.Core.TShort; using OCC.Core.Poly; using OCC.Core.Prs3d;)

%occt_valueclass(DsgPrs)
%occt_valueclass(DsgPrs_AnglePresentation)
%occt_valueclass(DsgPrs_Chamf2dPresentation)
%occt_valueclass(DsgPrs_ConcentricPresentation)
%occt_valueclass(DsgPrs_DatumPrs)
%occt_valueclass(DsgPrs_DiameterPresentation)
%occt_valueclass(DsgPrs_EllipseRadiusPresentation)
%occt_valueclass(DsgPrs_EqualDistancePresentation)
%occt_valueclass(DsgPrs_EqualRadiusPresentation)
%occt_valueclass(DsgPrs_FilletRadiusPresentation)
%occt_valueclass(DsgPrs_FixPresentation)
%occt_valueclass(DsgPrs_IdenticPresentation)
%occt_valueclass(DsgPrs_LengthPresentation)
%occt_valueclass(DsgPrs_MidPointPresentation)
%occt_valueclass(DsgPrs_OffsetPresentation)
%occt_valueclass(DsgPrs_ParalPresentation)
%occt_valueclass(DsgPrs_PerpenPresentation)
%occt_valueclass(DsgPrs_RadiusPresentation)
%occt_valueclass(DsgPrs_ShadedPlanePresentation)
%occt_valueclass(DsgPrs_ShapeDirPresentation)
%occt_valueclass(DsgPrs_SymbPresentation)
%occt_valueclass(DsgPrs_SymmetricPresentation)
%occt_valueclass(DsgPrs_TangentPresentation)
%occt_valueclass(DsgPrs_XYZAxisPresentation)
%occt_valueclass(DsgPrs_XYZPlanePresentation)

enum DsgPrs_ArrowSide {
  DsgPrs_AS_NONE = 0,
  DsgPrs_AS_FIRSTAR = 1,
  DsgPrs_AS_LASTAR = 2,
  DsgPrs_AS_BOTHAR = 3,
  DsgPrs_AS_FIRSTPT = 4,
  DsgPrs_AS_LASTPT = 5,
  DsgPrs_AS_BOTHPT = 6,
  DsgPrs_AS_FIRSTAR_LASTPT = 7,
  DsgPrs_AS_FIRSTPT_LASTAR = 8,
};

class DsgPrs {
public:
  DsgPrs();
  static void ComputeSymbol(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_DimensionAspect>& anAspect, const gp_Pnt& pt1, const gp_Pnt& pt2, const gp_Dir& dir1, const gp_Dir& dir2, DsgPrs_ArrowSide ArrowSide, bool drawFromCenter = true);
  static void ComputePlanarFacesLengthPresentation(double FirstArrowLength, double SecondArrowLength, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& DirAttach, const gp_Pnt& OffsetPoint, const gp_Pln& PlaneOfFaces, gp_Pnt& EndOfArrow1, gp_Pnt& EndOfArrow2, gp_Dir& DirOfArrow1);
  static void ComputeCurvilinearFacesLengthPresentation(double FirstArrowLength, double SecondArrowLength, const opencascade::handle<Geom_Surface>& SecondSurf, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& DirAttach, gp_Pnt& EndOfArrow2, gp_Dir& DirOfArrow1, opencascade::handle<Geom_Curve>& VCurve, opencascade::handle<Geom_Curve>& UCurve, double& FirstU, double& deltaU, double& FirstV, double& deltaV);
  static void ComputeFacesAnglePresentation(double ArrowLength, double Value, const gp_Pnt& CenterPoint, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& dir1, const gp_Dir& dir2, const gp_Dir& axisdir, bool isPlane, const gp_Ax1& AxisOfSurf, const gp_Pnt& OffsetPoint, gp_Circ& AngleCirc, double& FirstParAngleCirc, double& LastParAngleCirc, gp_Pnt& EndOfArrow1, gp_Pnt& EndOfArrow2, gp_Dir& DirOfArrow1, gp_Dir& DirOfArrow2, gp_Pnt& ProjAttachPoint2, gp_Circ& AttachCirc, double& FirstParAttachCirc, double& LastParAttachCirc);
  static void ComputeRadiusLine(const gp_Pnt& aCenter, const gp_Pnt& anEndOfArrow, const gp_Pnt& aPosition, bool drawFromCenter, gp_Pnt& aRadLineOrign, gp_Pnt& aRadLineEnd);
  static void ComputeFilletRadiusPresentation(double ArrowLength, double Value, const gp_Pnt& Position, const gp_Dir& NormalDir, const gp_Pnt& FirstPoint, const gp_Pnt& SecondPoint, const gp_Pnt& Center, const gp_Pnt& BasePnt, bool drawRevers, bool& SpecCase, gp_Circ& FilletCirc, double& FirstParCirc, double& LastParCirc, gp_Pnt& EndOfArrow, gp_Dir& DirOfArrow, gp_Pnt& DrawPosition);
  static double DistanceFromApex(const gp_Elips& elips, const gp_Pnt& Apex, double par);
};

class DsgPrs_AnglePresentation {
public:
  DsgPrs_AnglePresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double aVal, const TCollection_ExtendedString& aText, const gp_Circ& aCircle, const gp_Pnt& aPosition, const gp_Pnt& Apex, const gp_Circ& VminCircle, const gp_Circ& VmaxCircle, double aArrowSize);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double theval, const gp_Pnt& CenterPoint, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& dir1, const gp_Dir& dir2, const gp_Pnt& OffsetPoint);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double theval, const TCollection_ExtendedString& thevalstring, const gp_Pnt& CenterPoint, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& dir1, const gp_Dir& dir2, const gp_Pnt& OffsetPoint);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double theval, const TCollection_ExtendedString& thevalstring, const gp_Pnt& CenterPoint, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& dir1, const gp_Dir& dir2, const gp_Pnt& OffsetPoint, DsgPrs_ArrowSide ArrowSide);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double theval, const TCollection_ExtendedString& thevalstring, const gp_Pnt& CenterPoint, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& dir1, const gp_Dir& dir2, const gp_Dir& axisdir, const gp_Pnt& OffsetPoint);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double theval, const TCollection_ExtendedString& thevalstring, const gp_Pnt& CenterPoint, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& dir1, const gp_Dir& dir2, const gp_Dir& axisdir, bool isPlane, const gp_Ax1& AxisOfSurf, const gp_Pnt& OffsetPoint, DsgPrs_ArrowSide ArrowSide);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double theval, const gp_Pnt& theCenter, const gp_Pnt& AttachmentPoint1, const gp_Ax1& theAxe, DsgPrs_ArrowSide ArrowSide);
};

class DsgPrs_Chamf2dPresentation {
public:
  DsgPrs_Chamf2dPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& aPntAttach, const gp_Pnt& aPntEnd, const TCollection_ExtendedString& aText);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& aPntAttach, const gp_Pnt& aPntEnd, const TCollection_ExtendedString& aText, DsgPrs_ArrowSide ArrowSide);
};

class DsgPrs_ConcentricPresentation {
public:
  DsgPrs_ConcentricPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& aCenter, double aRadius, const gp_Dir& aNorm, const gp_Pnt& aPoint);
};

class DsgPrs_DatumPrs : public Prs3d_Root {
public:
  DsgPrs_DatumPrs();
  static void Add(const opencascade::handle<Graphic3d_Structure>& thePresentation, const gp_Ax2& theDatum, const opencascade::handle<Prs3d_Drawer>& theDrawer);
};

class DsgPrs_DiameterPresentation {
public:
  DsgPrs_DiameterPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint, const gp_Circ& aCircle, DsgPrs_ArrowSide ArrowSide, bool IsDiamSymbol);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint, const gp_Circ& aCircle, double uFirst, double uLast, DsgPrs_ArrowSide ArrowSide, bool IsDiamSymbol);
};

class DsgPrs_EllipseRadiusPresentation {
public:
  DsgPrs_EllipseRadiusPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double theval, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint, const gp_Pnt& anEndOfArrow, const gp_Pnt& aCenter, bool IsMaxRadius, DsgPrs_ArrowSide ArrowSide);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double theval, const TCollection_ExtendedString& aText, const gp_Elips& anEllipse, const gp_Pnt& AttachmentPoint, const gp_Pnt& anEndOfArrow, const gp_Pnt& aCenter, double uFirst, bool IsInDomain, bool IsMaxRadius, DsgPrs_ArrowSide ArrowSide);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double theval, const TCollection_ExtendedString& aText, const opencascade::handle<Geom_OffsetCurve>& aCurve, const gp_Pnt& AttachmentPoint, const gp_Pnt& anEndOfArrow, const gp_Pnt& aCenter, double uFirst, bool IsInDomain, bool IsMaxRadius, DsgPrs_ArrowSide ArrowSide);
};

class DsgPrs_EqualDistancePresentation {
public:
  DsgPrs_EqualDistancePresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& Point1, const gp_Pnt& Point2, const gp_Pnt& Point3, const gp_Pnt& Point4, const opencascade::handle<Geom_Plane>& Plane);
  static void AddInterval(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& aPoint1, const gp_Pnt& aPoint2, const gp_Dir& aDir, const gp_Pnt& aPosition, DsgPrs_ArrowSide anArrowSide, gp_Pnt& anExtremePnt1, gp_Pnt& anExtremePnt2);
  static void AddIntervalBetweenTwoArcs(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Circ& aCircle1, const gp_Circ& aCircle2, const gp_Pnt& aPoint1, const gp_Pnt& aPoint2, const gp_Pnt& aPoint3, const gp_Pnt& aPoint4, DsgPrs_ArrowSide anArrowSide);
};

class DsgPrs_EqualRadiusPresentation {
public:
  DsgPrs_EqualRadiusPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& FirstCenter, const gp_Pnt& SecondCenter, const gp_Pnt& FirstPoint, const gp_Pnt& SecondPoint, const opencascade::handle<Geom_Plane>& Plane);
};

class DsgPrs_FilletRadiusPresentation {
public:
  DsgPrs_FilletRadiusPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, double thevalue, const TCollection_ExtendedString& aText, const gp_Pnt& aPosition, const gp_Dir& aNormalDir, const gp_Pnt& aBasePnt, const gp_Pnt& aFirstPoint, const gp_Pnt& aSecondPoint, const gp_Pnt& aCenter, DsgPrs_ArrowSide ArrowPrs, bool drawRevers, gp_Pnt& DrawPosition, gp_Pnt& EndOfArrow, opencascade::handle<Geom_TrimmedCurve>& TrimCurve, bool& HasCircle);
};

class DsgPrs_FixPresentation {
public:
  DsgPrs_FixPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& aPntAttach, const gp_Pnt& aPntEnd, const gp_Dir& aNormPln, double aSymbSize);
};

class DsgPrs_IdenticPresentation {
public:
  DsgPrs_IdenticPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& aPntAttach, const gp_Pnt& aPntOffset);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& aFAttach, const gp_Pnt& aSAttach, const gp_Pnt& aPntOffset);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Ax2& aAx2, const gp_Pnt& aCenter, const gp_Pnt& aFAttach, const gp_Pnt& aSAttach, const gp_Pnt& aPntOffset);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Ax2& aAx2, const gp_Pnt& aCenter, const gp_Pnt& aFAttach, const gp_Pnt& aSAttach, const gp_Pnt& aPntOffset, const gp_Pnt& aPntOnCirc);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Elips& anEllipse, const gp_Pnt& aFAttach, const gp_Pnt& aSAttach, const gp_Pnt& aPntOffset, const gp_Pnt& aPntOnElli);
};

class DsgPrs_LengthPresentation {
public:
  DsgPrs_LengthPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& aDirection, const gp_Pnt& OffsetPoint);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& aDirection, const gp_Pnt& OffsetPoint, DsgPrs_ArrowSide ArrowSide);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Pln& PlaneOfFaces, const gp_Dir& aDirection, const gp_Pnt& OffsetPoint, DsgPrs_ArrowSide ArrowSide);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const opencascade::handle<Geom_Surface>& SecondSurf, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& aDirection, const gp_Pnt& OffsetPoint, DsgPrs_ArrowSide ArrowSide);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& Pt1, const gp_Pnt& Pt2, DsgPrs_ArrowSide ArrowSide);
};

class DsgPrs_MidPointPresentation {
public:
  DsgPrs_MidPointPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Ax2& theAxe, const gp_Pnt& MidPoint, const gp_Pnt& Position, const gp_Pnt& AttachPoint, bool first);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Ax2& theAxe, const gp_Pnt& MidPoint, const gp_Pnt& Position, const gp_Pnt& AttachPoint, const gp_Pnt& Point1, const gp_Pnt& Point2, bool first);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Circ& aCircle, const gp_Pnt& MidPoint, const gp_Pnt& Position, const gp_Pnt& AttachPoint, const gp_Pnt& Point1, const gp_Pnt& Point2, bool first);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Elips& anElips, const gp_Pnt& MidPoint, const gp_Pnt& Position, const gp_Pnt& AttachPoint, const gp_Pnt& Point1, const gp_Pnt& Point2, bool first);
};

class DsgPrs_OffsetPresentation {
public:
  DsgPrs_OffsetPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& aDirection, const gp_Dir& aDirection2, const gp_Pnt& OffsetPoint);
  static void AddAxes(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& aDirection, const gp_Dir& aDirection2, const gp_Pnt& OffsetPoint);
};

class DsgPrs_ParalPresentation {
public:
  DsgPrs_ParalPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& aDirection, const gp_Pnt& OffsetPoint);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& aDirection, const gp_Pnt& OffsetPoint, DsgPrs_ArrowSide ArrowSide);
};

class DsgPrs_PerpenPresentation {
public:
  DsgPrs_PerpenPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& pAx1, const gp_Pnt& pAx2, const gp_Pnt& pnt1, const gp_Pnt& pnt2, const gp_Pnt& OffsetPoint, bool intOut1, bool intOut2);
};

class DsgPrs_RadiusPresentation {
public:
  DsgPrs_RadiusPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint, const gp_Circ& aCircle, double firstparam, double lastparam, bool drawFromCenter = true, bool reverseArrow = false);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& AttachmentPoint, const gp_Pnt& Center, const gp_Pnt& EndOfArrow, DsgPrs_ArrowSide ArrowSide, bool drawFromCenter = true, bool reverseArrow = false);
};

class DsgPrs_ShadedPlanePresentation {
public:
  DsgPrs_ShadedPlanePresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& aPt1, const gp_Pnt& aPt2, const gp_Pnt& aPt3);
};

class DsgPrs_ShapeDirPresentation {
public:
  DsgPrs_ShapeDirPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& prs, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TopoDS_Shape& shape, int mode);
};

class DsgPrs_SymbPresentation {
public:
  DsgPrs_SymbPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const TCollection_ExtendedString& aText, const gp_Pnt& OffsetPoint);
};

class DsgPrs_SymmetricPresentation {
public:
  DsgPrs_SymmetricPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Dir& aDirection1, const gp_Lin& aAxis, const gp_Pnt& OffsetPoint);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Circ& aCircle1, const gp_Lin& aAxis, const gp_Pnt& OffsetPoint);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& AttachmentPoint1, const gp_Pnt& AttachmentPoint2, const gp_Lin& aAxis, const gp_Pnt& OffsetPoint);
};

class DsgPrs_TangentPresentation {
public:
  DsgPrs_TangentPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& OffsetPoint, const gp_Dir& aDirection, double aLength);
};

class DsgPrs_XYZAxisPresentation {
public:
  DsgPrs_XYZAxisPresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_LineAspect>& anLineAspect, const gp_Dir& aDir, double aVal, const char* aText, const gp_Pnt& aPfirst, const gp_Pnt& aPlast);
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_LineAspect>& aLineAspect, const opencascade::handle<Prs3d_ArrowAspect>& anArrowAspect, const opencascade::handle<Prs3d_TextAspect>& aTextAspect, const gp_Dir& aDir, double aVal, const char* aText, const gp_Pnt& aPfirst, const gp_Pnt& aPlast);
};

class DsgPrs_XYZPlanePresentation {
public:
  DsgPrs_XYZPlanePresentation();
  static void Add(const opencascade::handle<Graphic3d_Structure>& aPresentation, const opencascade::handle<Prs3d_Drawer>& aDrawer, const gp_Pnt& aPt1, const gp_Pnt& aPt2, const gp_Pnt& aPt3);
};
