// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* FlexLexer: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module FlexLexerModule

%include "NetOcc.i"

%{
#include <FlexLexer_module.hxx>
%}

%netocc_csimports()
