// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* GeomLib: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module GeomLibModule

%include "NetOcc.i"

%{
#include <GeomLib_module.hxx>
%}

%import "GeomAbs.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "gp.i"
%import "TColgp.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "GeomEval.i"
%import "Geom.i"
%import "TopAbs.i"
%import "math.i"
%import "Adaptor3d.i"
%import "PLib.i"
%import "AdvApprox.i"
%import "Geom2dAdaptor.i"
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.TopAbs; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.PLib; using OCC.Core.AdvApprox; using OCC.Core.Geom2dAdaptor;)

%occt_valueclass(GeomLib)
%occt_valueclass(GeomLib_Check2dBSplineCurve)
%nodefaultctor GeomLib_Check2dBSplineCurve;
%feature("valuewrapper") GeomLib_Check2dBSplineCurve;
%occt_valueclass(GeomLib_CheckBSplineCurve)
%nodefaultctor GeomLib_CheckBSplineCurve;
%feature("valuewrapper") GeomLib_CheckBSplineCurve;
%occt_valueclass(GeomLib_CheckCurveOnSurface)
%occt_valueclass(GeomLib_DenominatorMultiplier)
%nodefaultctor GeomLib_DenominatorMultiplier;
%feature("valuewrapper") GeomLib_DenominatorMultiplier;
%occt_valueclass(GeomLib_Interpolate)
%nodefaultctor GeomLib_Interpolate;
%feature("valuewrapper") GeomLib_Interpolate;
%occt_valueclass(GeomLib_IsPlanarSurface)
%nodefaultctor GeomLib_IsPlanarSurface;
%feature("valuewrapper") GeomLib_IsPlanarSurface;
%occt_valueclass(GeomLib_LogSample)
%nodefaultctor GeomLib_LogSample;
%feature("valuewrapper") GeomLib_LogSample;
%occt_valueclass(GeomLib_MakeCurvefromApprox)
%nodefaultctor GeomLib_MakeCurvefromApprox;
%feature("valuewrapper") GeomLib_MakeCurvefromApprox;
%occt_valueclass(GeomLib_PolyFunc)
%nodefaultctor GeomLib_PolyFunc;
%feature("valuewrapper") GeomLib_PolyFunc;
%occt_valueclass(GeomLib_Tool)

enum GeomLib_InterpolationErrors {
  GeomLib_NoError = 0,
  GeomLib_NotEnoughtPoints = 1,
  GeomLib_DegreeSmallerThan3 = 2,
  GeomLib_InversionProblem = 3,
};

class GeomLib {
public:
  GeomLib();
  static opencascade::handle<Geom_Curve> To3d(const gp_Ax2& Position, const opencascade::handle<Geom2d_Curve>& Curve2d);
  static opencascade::handle<Geom2d_Curve> GTransform(const opencascade::handle<Geom2d_Curve>& Curve, const gp_GTrsf2d& GTrsf);
  static void SameRange(double Tolerance, const opencascade::handle<Geom2d_Curve>& Curve2dPtr, double First, double Last, double RequestedFirst, double RequestedLast, opencascade::handle<Geom2d_Curve>& NewCurve2dPtr);
  static void BuildCurve3d(double Tolerance, Adaptor3d_CurveOnSurface& CurvePtr, double FirstParameter, double LastParameter, opencascade::handle<Geom_Curve>& NewCurvePtr, double& MaxDeviation, double& AverageDeviation, GeomAbs_Shape Continuity = GeomAbs_C1, int MaxDegree = 14, int MaxSegment = 30);
  static void AdjustExtremity(opencascade::handle<Geom_BoundedCurve>& Curve, const gp_Pnt& P1, const gp_Pnt& P2, const gp_Vec& T1, const gp_Vec& T2);
  static void ExtendCurveToPoint(opencascade::handle<Geom_BoundedCurve>& Curve, const gp_Pnt& Point, int Cont, bool After);
  static void ExtendSurfByLength(opencascade::handle<Geom_BoundedSurface>& Surf, double Length, int Cont, bool InU, bool After);
  static void AxeOfInertia(const NCollection_Array1<gp_Pnt>& Points, gp_Ax2& Axe, bool& IsSingular, double Tol = 1.0e-7);
  static void Inertia(const NCollection_Array1<gp_Pnt>& Points, gp_Pnt& Bary, gp_Dir& XDir, gp_Dir& YDir, double& Xgap, double& YGap, double& ZGap);
  static void RemovePointsFromArray(int NumPoints, const NCollection_Array1<double>& InParameters, opencascade::handle<NCollection_HArray1<double>>& OutParameters);
  static void DensifyArray1OfReal(int MinNumPoints, const NCollection_Array1<double>& InParameters, opencascade::handle<NCollection_HArray1<double>>& OutParameters);
  static void FuseIntervals(const NCollection_Array1<double>& Interval1, const NCollection_Array1<double>& Interval2, NCollection_Sequence<double>& Fusion, double Confusion = 1.0e-9, bool IsAdjustToFirstInterval = false);
  static void EvalMaxParametricDistance(const Adaptor3d_Curve& Curve, const Adaptor3d_Curve& AReferenceCurve, double Tolerance, const NCollection_Array1<double>& Parameters, double& MaxDistance);
  static void EvalMaxDistanceAlongParameter(const Adaptor3d_Curve& Curve, const Adaptor3d_Curve& AReferenceCurve, double Tolerance, const NCollection_Array1<double>& Parameters, double& MaxDistance);
  static void CancelDenominatorDerivative(opencascade::handle<Geom_BSplineSurface>& BSurf, bool UDirection, bool VDirection);
  static int NormEstim(const opencascade::handle<Geom_Surface>& theSurf, const gp_Pnt2d& theUV, double theTol, gp_Dir& theNorm);
  static void IsClosed(const opencascade::handle<Geom_Surface>& S, double Tol, bool& isUClosed, bool& isVClosed);
  static bool IsBSplUClosed(const opencascade::handle<Geom_BSplineSurface>& S, double U1, double U2, double Tol);
  static bool IsBSplVClosed(const opencascade::handle<Geom_BSplineSurface>& S, double V1, double V2, double Tol);
  static bool IsBzUClosed(const opencascade::handle<Geom_BezierSurface>& S, double U1, double U2, double Tol);
  static bool IsBzVClosed(const opencascade::handle<Geom_BezierSurface>& S, double V1, double V2, double Tol);
  static bool isIsoLine(const opencascade::handle<Adaptor2d_Curve2d>& theC2D, bool& theIsU, double& theParam, bool& theIsForward);
  static opencascade::handle<Geom_Curve> buildC3dOnIsoLine(const opencascade::handle<Adaptor2d_Curve2d>& theC2D, const opencascade::handle<Adaptor3d_Surface>& theSurf, double theFirst, double theLast, double theTolerance, bool theIsU, double theParam, bool theIsForward);
};

class GeomLib_Check2dBSplineCurve {
public:
  GeomLib_Check2dBSplineCurve(const opencascade::handle<Geom2d_BSplineCurve>& Curve, double Tolerance, double AngularTolerance);
  bool IsDone() const;
  void NeedTangentFix(bool& FirstFlag, bool& SecondFlag) const;
  void FixTangent(bool FirstFlag, bool LastFlag);
  opencascade::handle<Geom2d_BSplineCurve> FixedTangent(bool FirstFlag, bool LastFlag);
};

class GeomLib_CheckBSplineCurve {
public:
  GeomLib_CheckBSplineCurve(const opencascade::handle<Geom_BSplineCurve>& Curve, double Tolerance, double AngularTolerance);
  bool IsDone() const;
  void NeedTangentFix(bool& FirstFlag, bool& SecondFlag) const;
  void FixTangent(bool FirstFlag, bool LastFlag);
  opencascade::handle<Geom_BSplineCurve> FixedTangent(bool FirstFlag, bool LastFlag);
};

class GeomLib_CheckCurveOnSurface {
public:
  GeomLib_CheckCurveOnSurface();
  GeomLib_CheckCurveOnSurface(const opencascade::handle<Adaptor3d_Curve>& theCurve, double theTolRange = Precision::PConfusion());
  void Init(const opencascade::handle<Adaptor3d_Curve>& theCurve, double theTolRange = Precision::PConfusion());
  void Init();
  void Perform(const opencascade::handle<Adaptor3d_CurveOnSurface>& theCurveOnSurface);
  void SetParallel(bool theIsParallel);
  bool IsParallel();
  bool IsDone() const;
  int ErrorStatus() const;
  double MaxDistance() const;
  double MaxParameter() const;
};

class GeomLib_DenominatorMultiplier {
public:
  GeomLib_DenominatorMultiplier(const opencascade::handle<Geom_BSplineSurface>& Surface, const NCollection_Array1<double>& KnotVector);
  double Value(double UParameter, double VParameter) const;
};

class GeomLib_Interpolate {
public:
  GeomLib_Interpolate(int Degree, int NumPoints, const NCollection_Array1<gp_Pnt>& Points, const NCollection_Array1<double>& Parameters);
  bool IsDone() const;
  GeomLib_InterpolationErrors Error() const;
  opencascade::handle<Geom_BSplineCurve> Curve() const;
};

class GeomLib_IsPlanarSurface {
public:
  GeomLib_IsPlanarSurface(const opencascade::handle<Geom_Surface>& S, double Tol = 1.0e-7);
  bool IsPlanar() const;
  const gp_Pln& Plan() const;
};

class GeomLib_LogSample : public math_FunctionSample {
public:
  GeomLib_LogSample(double A, double B, int N);
  double GetParameter(int Index) const;
};

class GeomLib_MakeCurvefromApprox {
public:
  GeomLib_MakeCurvefromApprox(const AdvApprox_ApproxAFunction& Approx);
  bool IsDone() const;
  int Nb1DSpaces() const;
  int Nb2DSpaces() const;
  int Nb3DSpaces() const;
  opencascade::handle<Geom2d_BSplineCurve> Curve2d(int Index2d) const;
  opencascade::handle<Geom2d_BSplineCurve> Curve2dFromTwo1d(int Index1d, int Index2d) const;
  opencascade::handle<Geom2d_BSplineCurve> Curve2d(int Index1d, int Index2d) const;
  opencascade::handle<Geom_BSplineCurve> Curve(int Index3d) const;
  opencascade::handle<Geom_BSplineCurve> Curve(int Index1D, int Index3D) const;
};

class GeomLib_PolyFunc : public math_FunctionWithDerivative {
public:
  GeomLib_PolyFunc(const math_VectorBase<double>& Coeffs);
  bool Value(double X, double& F);
  bool Derivative(double X, double& D);
  bool Values(double X, double& F, double& D);
};

class GeomLib_Tool {
public:
  GeomLib_Tool();
  static bool Parameter(const opencascade::handle<Geom_Curve>& Curve, const gp_Pnt& Point, double MaxDist, double& U);
  static bool Parameters(const opencascade::handle<Geom_Surface>& Surface, const gp_Pnt& Point, double MaxDist, double& U, double& V);
  static bool Parameter(const opencascade::handle<Geom2d_Curve>& Curve, const gp_Pnt2d& Point, double MaxDist, double& U);
  static double ComputeDeviation(const Geom2dAdaptor_Curve& theCurve, double theFPar, double theLPar, double theStartParameter, int theNbIters = 100, double* thePrmOnCurve = nullptr, gp_Pnt2d* thePtOnCurve = nullptr, gp_Vec2d* theVecCurvLine = nullptr, gp_Lin2d* theLine = nullptr);
  static double ComputeDeviation(const Geom2dAdaptor_Curve& theCurve, double theFPar, double theLPar, int theNbSubIntervals, int theNbIters = 10, double* thePrmOnCurve = nullptr);
};
