// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* IntAna2d: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module IntAna2dModule

%include "NetOcc.i"

%{
#include <IntAna2d_module.hxx>
%}

%import "Standard.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "gp.i"
%netocc_csimports(using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.gp;)

%occt_valueclass(IntAna2d_IntPoint)
%occt_valueclass(IntAna2d_AnaIntersection)
%occt_valueclass(IntAna2d_Conic)
%nodefaultctor IntAna2d_Conic;
%feature("valuewrapper") IntAna2d_Conic;
%occt_valueclass(MyDirectPolynomialRoots)
%nodefaultctor MyDirectPolynomialRoots;
%feature("valuewrapper") MyDirectPolynomialRoots;

class IntAna2d_IntPoint {
public:
  IntAna2d_IntPoint(double X, double Y, double U1, double U2);
  IntAna2d_IntPoint(double X, double Y, double U1);
  IntAna2d_IntPoint();
  void SetValue(double X, double Y, double U1, double U2);
  void SetValue(double X, double Y, double U1);
  const gp_Pnt2d& Value() const;
  bool SecondIsImplicit() const;
  double ParamOnFirst() const;
  double ParamOnSecond() const;
};

class IntAna2d_AnaIntersection {
public:
  IntAna2d_AnaIntersection();
  IntAna2d_AnaIntersection(const gp_Lin2d& L1, const gp_Lin2d& L2);
  IntAna2d_AnaIntersection(const gp_Circ2d& C1, const gp_Circ2d& C2);
  IntAna2d_AnaIntersection(const gp_Lin2d& L, const gp_Circ2d& C);
  IntAna2d_AnaIntersection(const gp_Lin2d& L, const IntAna2d_Conic& C);
  IntAna2d_AnaIntersection(const gp_Circ2d& C, const IntAna2d_Conic& Co);
  IntAna2d_AnaIntersection(const gp_Elips2d& E, const IntAna2d_Conic& C);
  IntAna2d_AnaIntersection(const gp_Parab2d& P, const IntAna2d_Conic& C);
  IntAna2d_AnaIntersection(const gp_Hypr2d& H, const IntAna2d_Conic& C);
  void Perform(const gp_Lin2d& L1, const gp_Lin2d& L2);
  void Perform(const gp_Circ2d& C1, const gp_Circ2d& C2);
  void Perform(const gp_Lin2d& L, const gp_Circ2d& C);
  void Perform(const gp_Lin2d& L, const IntAna2d_Conic& C);
  void Perform(const gp_Circ2d& C, const IntAna2d_Conic& Co);
  void Perform(const gp_Elips2d& E, const IntAna2d_Conic& C);
  void Perform(const gp_Parab2d& P, const IntAna2d_Conic& C);
  void Perform(const gp_Hypr2d& H, const IntAna2d_Conic& C);
  bool IsDone() const;
  bool IsEmpty() const;
  bool IdenticalElements() const;
  bool ParallelElements() const;
  int NbPoints() const;
  const IntAna2d_IntPoint& Point(int N) const;
};

class IntAna2d_Conic {
public:
  IntAna2d_Conic(const gp_Circ2d& C);
  IntAna2d_Conic(const gp_Lin2d& C);
  IntAna2d_Conic(const gp_Parab2d& C);
  IntAna2d_Conic(const gp_Hypr2d& C);
  IntAna2d_Conic(const gp_Elips2d& C);
  double Value(double X, double Y) const;
  gp_XY Grad(double X, double Y) const;
  void ValAndGrad(double X, double Y, double& Val, gp_XY& Grd) const;
  void Coefficients(double& A, double& B, double& C, double& D, double& E, double& F) const;
  void NewCoefficients(double& A, double& B, double& C, double& D, double& E, double& F, const gp_Ax2d& Axis) const;
};

class MyDirectPolynomialRoots {
public:
  int NbSolutions() const;
  double Value(int i) const;
  double IsDone() const;
  bool InfiniteRoots() const;
};
