// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* IntCurvesFace: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module IntCurvesFaceModule

%include "NetOcc.i"

%{
#include <IntCurvesFace_module.hxx>
%}

%import "GeomAbs.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "gp.i"
%import "TColgp.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "GeomEval.i"
%import "Geom.i"
%import "TopAbs.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "TopLoc.i"
%import "TopoDS.i"
%import "BRepAdaptor.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "TopTools.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "BVH.i"
%import "Bnd.i"
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.TopAbs; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.TopLoc; using OCC.Core.TopoDS; using OCC.Core.BRepAdaptor; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.TopTools; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.BVH; using OCC.Core.Bnd;)

%occt_transient(IntCurvesFace_Intersector)
%nodefaultctor IntCurvesFace_Intersector;
%feature("valuewrapper") IntCurvesFace_Intersector;
%occt_valueclass(IntCurvesFace_ShapeIntersector)

class IntCurvesFace_Intersector : public Standard_Transient {
public:
  IntCurvesFace_Intersector(const TopoDS_Face& F, double aTol, bool aRestr = true, bool UseBToler = true);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
  void Perform(const gp_Lin& L, double PInf, double PSup);
  void Perform(const opencascade::handle<Adaptor3d_Curve>& HCu, double PInf, double PSup);
  GeomAbs_SurfaceType SurfaceType() const;
  bool IsDone() const;
  int NbPnt() const;
  double UParameter(int I) const;
  double VParameter(int I) const;
  double WParameter(int I) const;
  const gp_Pnt& Pnt(int I) const;
  IntCurveSurface_TransitionOnCurve Transition(int I) const;
  TopAbs_State State(int I) const;
  bool IsParallel() const;
  const TopoDS_Face& Face() const;
  TopAbs_State ClassifyUVPoint(const gp_Pnt2d& Puv) const;
  Bnd_Box Bounding() const;
  void SetUseBoundToler(bool UseBToler);
  bool GetUseBoundToler() const;
};

class IntCurvesFace_ShapeIntersector {
public:
  IntCurvesFace_ShapeIntersector();
  void Load(const TopoDS_Shape& Sh, double Tol);
  void Perform(const gp_Lin& L, double PInf, double PSup);
  void PerformNearest(const gp_Lin& L, double PInf, double PSup);
  void Perform(const opencascade::handle<Adaptor3d_Curve>& HCu, double PInf, double PSup);
  bool IsDone() const;
  int NbPnt() const;
  double UParameter(int I) const;
  double VParameter(int I) const;
  double WParameter(int I) const;
  const gp_Pnt& Pnt(int I) const;
  IntCurveSurface_TransitionOnCurve Transition(int I) const;
  TopAbs_State State(int I) const;
  const TopoDS_Face& Face(int I) const;
  void SortResult();
};
