// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* IntImpParGen: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module IntImpParGenModule

%include "NetOcc.i"

%{
#include <IntImpParGen_module.hxx>
%}

%import "Standard.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "gp.i"
%import "IntRes2d.i"
%netocc_csimports(using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.gp; using OCC.Core.IntRes2d;)

%occt_valueclass(IntImpParGen)
%occt_valueclass(IntImpParGen_ImpTool)

class IntImpParGen {
public:
  IntImpParGen();
  static void DetermineTransition(IntRes2d_Position Pos1, gp_Vec2d& Tan1, const gp_Vec2d& Norm1, IntRes2d_Transition& Trans1, IntRes2d_Position Pos2, gp_Vec2d& Tan2, const gp_Vec2d& Norm2, IntRes2d_Transition& Trans2, double Tol);
  static bool DetermineTransition(IntRes2d_Position Pos1, gp_Vec2d& Tan1, IntRes2d_Transition& Trans1, IntRes2d_Position Pos2, gp_Vec2d& Tan2, IntRes2d_Transition& Trans2, double Tol);
  static void DeterminePosition(IntRes2d_Position& Pos1, const IntRes2d_Domain& Dom1, const gp_Pnt2d& P1, double Tol);
  static double NormalizeOnDomain(double& Par1, const IntRes2d_Domain& Dom1);
};

class IntImpParGen_ImpTool {
public:
  IntImpParGen_ImpTool();
};
