// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* math: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module mathModule

%include "NetOcc.i"

%{
#include <math_module.hxx>
%}

%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%netocc_csimports(using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard;)

%occt_valueclass(math_DoubleTab)
%nodefaultctor math_DoubleTab;
%feature("valuewrapper") math_DoubleTab;
%occt_valueclass(math_Matrix)
%nodefaultctor math_Matrix;
%feature("valuewrapper") math_Matrix;
%occt_valueclass(math_NotSquare)
%occt_valueclass(math)
%occt_valueclass(math_BFGS)
%nodefaultctor math_BFGS;
%feature("valuewrapper") math_BFGS;
%occt_valueclass(math_BissecNewton)
%nodefaultctor math_BissecNewton;
%feature("valuewrapper") math_BissecNewton;
%occt_valueclass(math_BracketMinimum)
%nodefaultctor math_BracketMinimum;
%feature("valuewrapper") math_BracketMinimum;
%occt_valueclass(math_BracketedRoot)
%nodefaultctor math_BracketedRoot;
%feature("valuewrapper") math_BracketedRoot;
%occt_valueclass(math_BrentMinimum)
%nodefaultctor math_BrentMinimum;
%feature("valuewrapper") math_BrentMinimum;
%occt_valueclass(math_BullardGenerator)
%occt_valueclass(math_ComputeGaussPointsAndWeights)
%nodefaultctor math_ComputeGaussPointsAndWeights;
%feature("valuewrapper") math_ComputeGaussPointsAndWeights;
%occt_valueclass(math_ComputeKronrodPointsAndWeights)
%nodefaultctor math_ComputeKronrodPointsAndWeights;
%feature("valuewrapper") math_ComputeKronrodPointsAndWeights;
%occt_valueclass(math_Crout)
%nodefaultctor math_Crout;
%feature("valuewrapper") math_Crout;
%occt_valueclass(math_DirectPolynomialRoots)
%nodefaultctor math_DirectPolynomialRoots;
%feature("valuewrapper") math_DirectPolynomialRoots;
%occt_valueclass(math_EigenValuesSearcher)
%nodefaultctor math_EigenValuesSearcher;
%feature("valuewrapper") math_EigenValuesSearcher;
%occt_valueclass(math_FRPR)
%nodefaultctor math_FRPR;
%feature("valuewrapper") math_FRPR;
%nodefaultctor math_Function;
%occt_valueclass(math_FunctionAllRoots)
%nodefaultctor math_FunctionAllRoots;
%feature("valuewrapper") math_FunctionAllRoots;
%occt_valueclass(math_FunctionRoot)
%nodefaultctor math_FunctionRoot;
%feature("valuewrapper") math_FunctionRoot;
%occt_valueclass(math_FunctionRoots)
%nodefaultctor math_FunctionRoots;
%feature("valuewrapper") math_FunctionRoots;
%occt_valueclass(math_FunctionSample)
%nodefaultctor math_FunctionSample;
%feature("valuewrapper") math_FunctionSample;
%nodefaultctor math_FunctionSet;
%occt_valueclass(math_FunctionSetRoot)
%nodefaultctor math_FunctionSetRoot;
%feature("valuewrapper") math_FunctionSetRoot;
%nodefaultctor math_FunctionSetWithDerivatives;
%nodefaultctor math_FunctionWithDerivative;
%occt_valueclass(math_Gauss)
%nodefaultctor math_Gauss;
%feature("valuewrapper") math_Gauss;
%occt_valueclass(math_GaussLeastSquare)
%nodefaultctor math_GaussLeastSquare;
%feature("valuewrapper") math_GaussLeastSquare;
%occt_valueclass(math_GaussMultipleIntegration)
%nodefaultctor math_GaussMultipleIntegration;
%feature("valuewrapper") math_GaussMultipleIntegration;
%occt_valueclass(math_GaussSetIntegration)
%nodefaultctor math_GaussSetIntegration;
%feature("valuewrapper") math_GaussSetIntegration;
%occt_valueclass(math_GaussSingleIntegration)
%nodefaultctor math_MultipleVarFunction;
%occt_valueclass(math_GlobOptMin)
%nodefaultctor math_GlobOptMin;
%feature("valuewrapper") math_GlobOptMin;
%occt_valueclass(math_Householder)
%nodefaultctor math_Householder;
%feature("valuewrapper") math_Householder;
%occt_valueclass(math_Jacobi)
%nodefaultctor math_Jacobi;
%feature("valuewrapper") math_Jacobi;
%occt_valueclass(math_KronrodSingleIntegration)
%nodefaultctor math_MultipleVarFunctionWithGradient;
%nodefaultctor math_MultipleVarFunctionWithHessian;
%occt_valueclass(math_NewtonFunctionRoot)
%nodefaultctor math_NewtonFunctionRoot;
%feature("valuewrapper") math_NewtonFunctionRoot;
%occt_valueclass(math_NewtonFunctionSetRoot)
%nodefaultctor math_NewtonFunctionSetRoot;
%feature("valuewrapper") math_NewtonFunctionSetRoot;
%occt_valueclass(math_NewtonMinimum)
%nodefaultctor math_NewtonMinimum;
%feature("valuewrapper") math_NewtonMinimum;
%occt_valueclass(math_PSO)
%nodefaultctor math_PSO;
%feature("valuewrapper") math_PSO;
%occt_valueclass(PSO_Particle)
%occt_valueclass(math_PSOParticlesPool)
%nodefaultctor math_PSOParticlesPool;
%feature("valuewrapper") math_PSOParticlesPool;
%occt_valueclass(math_Powell)
%nodefaultctor math_Powell;
%feature("valuewrapper") math_Powell;
%occt_valueclass(math_SVD)
%nodefaultctor math_SVD;
%feature("valuewrapper") math_SVD;
%occt_valueclass(math_SingularMatrix)
%occt_valueclass(math_TrigonometricEquationFunction)
%nodefaultctor math_TrigonometricEquationFunction;
%feature("valuewrapper") math_TrigonometricEquationFunction;
%occt_valueclass(math_TrigonometricFunctionRoots)
%nodefaultctor math_TrigonometricFunctionRoots;
%feature("valuewrapper") math_TrigonometricFunctionRoots;
%occt_valueclass(math_Uzawa)
%nodefaultctor math_Uzawa;
%feature("valuewrapper") math_Uzawa;
%occt_valueclass(math_ValueAndWeight)
%netocc_keep_construct(math_GlobOptMin)
%netocc_keep_construct(math_PSO)

enum math_Status {
  math_OK = 0,
  math_TooManyIterations = 1,
  math_FunctionError = 2,
  math_DirectionSearchError = 3,
  math_NotBracketed = 4,
};

%include "extras/math.i"

%occt_math_vector(math_IntegerVector, int, int)
%occt_math_vector(math_Vector, double, double)

class math_DoubleTab {
public:
  math_DoubleTab(int theLowerRow, int theUpperRow, int theLowerCol, int theUpperCol);
  math_DoubleTab(void* theTab, int theLowerRow, int theUpperRow, int theLowerCol, int theUpperCol);
  void Init(double theInitValue);
  void Copy(math_DoubleTab& theOther) const;
  bool IsDeletable() const;
  void SetLowerRow(int theLowerRow);
  void SetLowerCol(int theLowerCol);
  int LowerRow() const;
  int UpperRow() const;
  int LowerCol() const;
  int UpperCol() const;
  int NbRows() const;
  int NbColumns() const;
  double& Value(int theRowIndex, int theColIndex);
};

class math_Matrix {
public:
  math_Matrix(int LowerRow, int UpperRow, int LowerCol, int UpperCol);
  math_Matrix(int LowerRow, int UpperRow, int LowerCol, int UpperCol, double InitialValue);
  math_Matrix(void* Tab, int LowerRow, int UpperRow, int LowerCol, int UpperCol);
  void Init(double InitialValue);
  int RowNumber() const;
  int ColNumber() const;
  int LowerRow() const;
  int UpperRow() const;
  int LowerCol() const;
  int UpperCol() const;
  double Determinant() const;
  void Transpose();
  void Invert();
  void Multiply(double Right);
  math_Matrix Multiplied(double Right) const;
  math_Matrix TMultiplied(double Right) const;
  void Divide(double Right);
  math_Matrix Divided(double Right) const;
  void Add(const math_Matrix& Right);
  math_Matrix Added(const math_Matrix& Right) const;
  void Add(const math_Matrix& Left, const math_Matrix& Right);
  void Subtract(const math_Matrix& Right);
  math_Matrix Subtracted(const math_Matrix& Right) const;
  void Set(int I1, int I2, int J1, int J2, const math_Matrix& M);
  void SetRow(int Row, const math_VectorBase<double>& V);
  void SetCol(int Col, const math_VectorBase<double>& V);
  void SetDiag(double Value);
  math_VectorBase<double> Row(int Row) const;
  math_VectorBase<double> Col(int Col) const;
  void SwapRow(int Row1, int Row2);
  void SwapCol(int Col1, int Col2);
  math_Matrix Transposed() const;
  math_Matrix Inverse() const;
  math_Matrix TMultiply(const math_Matrix& Right) const;
  void Multiply(const math_VectorBase<double>& Left, const math_VectorBase<double>& Right);
  void Multiply(const math_Matrix& Left, const math_Matrix& Right);
  void TMultiply(const math_Matrix& TLeft, const math_Matrix& Right);
  void Subtract(const math_Matrix& Left, const math_Matrix& Right);
  double& Value(int Row, int Col);
  void Initialized(const math_Matrix& Other);
  void Multiply(const math_Matrix& Right);
  math_Matrix Multiplied(const math_Matrix& Right) const;
  math_VectorBase<double> Multiplied(const math_VectorBase<double>& Right) const;
  math_Matrix Opposite() const;
  void Dump(std::ostream& o) const;
};

class math_NotSquare : public Standard_DimensionError {
public:
  math_NotSquare(const char* theMessage = "");
  math_NotSquare(const char* theMessage, const char* theStackTrace);
  const char* ExceptionType() const;
};

class math {
public:
  math();
  static int GaussPointsMax();
  static void GaussPoints(int Index, math_VectorBase<double>& Points);
  static void GaussWeights(int Index, math_VectorBase<double>& Weights);
  static int KronrodPointsMax();
  static bool OrderedGaussPointsAndWeights(int Index, math_VectorBase<double>& Points, math_VectorBase<double>& Weights);
  static bool KronrodPointsAndWeights(int Index, math_VectorBase<double>& Points, math_VectorBase<double>& Weights);
};

class math_BFGS {
public:
  math_BFGS(int NbVariables, double Tolerance = 1.0e-8, int NbIterations = 200, double ZEPS = 1.0e-12);
  void SetBoundary(const math_VectorBase<double>& theLeftBorder, const math_VectorBase<double>& theRightBorder);
  void Perform(math_MultipleVarFunctionWithGradient& F, const math_VectorBase<double>& StartingPoint);
  bool IsSolutionReached(math_MultipleVarFunctionWithGradient& F) const;
  bool IsDone() const;
  const math_VectorBase<double>& Location() const;
  void Location(math_VectorBase<double>& Loc) const;
  double Minimum() const;
  const math_VectorBase<double>& Gradient() const;
  void Gradient(math_VectorBase<double>& Grad) const;
  int NbIterations() const;
  void Dump(std::ostream& o) const;
};

class math_BissecNewton {
public:
  math_BissecNewton(double theXTolerance);
  void Perform(math_FunctionWithDerivative& F, double Bound1, double Bound2, int NbIterations = 100);
  bool IsSolutionReached(math_FunctionWithDerivative& theFunction);
  bool IsDone() const;
  double Root() const;
  double Derivative() const;
  double Value() const;
  void Dump(std::ostream& o) const;
};

class math_BracketMinimum {
public:
  math_BracketMinimum(double A, double B);
  math_BracketMinimum(math_Function& F, double A, double B);
  math_BracketMinimum(math_Function& F, double A, double B, double FA);
  math_BracketMinimum(math_Function& F, double A, double B, double FA, double FB);
  void SetLimits(double theLeft, double theRight);
  void SetFA(double theValue);
  void SetFB(double theValue);
  void Perform(math_Function& F);
  bool IsDone() const;
  void Values(double& A, double& B, double& C) const;
  void FunctionValues(double& FA, double& FB, double& FC) const;
  void Dump(std::ostream& o) const;
};

class math_BracketedRoot {
public:
  math_BracketedRoot(math_Function& F, double Bound1, double Bound2, double Tolerance, int NbIterations = 100, double ZEPS = 1.0e-12);
  bool IsDone() const;
  double Root() const;
  double Value() const;
  int NbIterations() const;
  void Dump(std::ostream& o) const;
};

class math_BrentMinimum {
public:
  math_BrentMinimum(double TolX, int NbIterations = 100, double ZEPS = 1.0e-12);
  math_BrentMinimum(double TolX, double Fbx, int NbIterations = 100, double ZEPS = 1.0e-12);
  void Perform(math_Function& F, double Ax, double Bx, double Cx);
  bool IsSolutionReached(math_Function& theFunction);
  bool IsDone() const;
  double Location() const;
  double Minimum() const;
  int NbIterations() const;
  void Dump(std::ostream& o) const;
};

class math_BullardGenerator {
public:
  math_BullardGenerator(unsigned int theSeed = 1);
  void SetSeed(unsigned int theSeed = 1);
  unsigned int NextInt();
  double NextReal();
};

class math_ComputeGaussPointsAndWeights {
public:
  math_ComputeGaussPointsAndWeights(int Number);
  bool IsDone() const;
  math_VectorBase<double> Points() const;
  math_VectorBase<double> Weights() const;
};

class math_ComputeKronrodPointsAndWeights {
public:
  math_ComputeKronrodPointsAndWeights(int Number);
  bool IsDone() const;
  math_VectorBase<double> Points() const;
  math_VectorBase<double> Weights() const;
};

class math_Crout {
public:
  math_Crout(const math_Matrix& A, double MinPivot = 1.0e-20);
  bool IsDone() const;
  void Solve(const math_VectorBase<double>& B, math_VectorBase<double>& X) const;
  const math_Matrix& Inverse() const;
  void Invert(math_Matrix& Inv) const;
  double Determinant() const;
  void Dump(std::ostream& o) const;
};

class math_DirectPolynomialRoots {
public:
  math_DirectPolynomialRoots(double theA, double theB, double theC, double theD, double theE);
  math_DirectPolynomialRoots(double theA, double theB, double theC, double theD);
  math_DirectPolynomialRoots(double theA, double theB, double theC);
  math_DirectPolynomialRoots(double theA, double theB);
  bool IsDone() const;
  bool InfiniteRoots() const;
  int NbSolutions() const;
  double Value(int theIndex) const;
  void Dump(std::ostream& theStream) const;
};

class math_EigenValuesSearcher {
public:
  math_EigenValuesSearcher(const NCollection_Array1<double>& theDiagonal, const NCollection_Array1<double>& theSubdiagonal);
  bool IsDone() const;
  int Dimension() const;
  double EigenValue(int theIndex) const;
  math_VectorBase<double> EigenVector(int theIndex) const;
};

class math_FRPR {
public:
  math_FRPR(const math_MultipleVarFunctionWithGradient& theFunction, double theTolerance, int theNbIterations = 200, double theZEPS = 1.0e-12);
  void Perform(math_MultipleVarFunctionWithGradient& theFunction, const math_VectorBase<double>& theStartingPoint);
  bool IsSolutionReached(math_MultipleVarFunctionWithGradient& theFunction);
  bool IsDone() const;
  const math_VectorBase<double>& Location() const;
  void Location(math_VectorBase<double>& Loc) const;
  double Minimum() const;
  const math_VectorBase<double>& Gradient() const;
  void Gradient(math_VectorBase<double>& Grad) const;
  int NbIterations() const;
  void Dump(std::ostream& o) const;
};

class math_Function {
public:
  bool Value(double X, double& F);
  int GetStateNumber();
};

class math_FunctionAllRoots {
public:
  math_FunctionAllRoots(math_FunctionWithDerivative& F, const math_FunctionSample& S, double EpsX, double EpsF, double EpsNul);
  bool IsDone() const;
  int NbIntervals() const;
  void GetInterval(int Index, double& A, double& B) const;
  void GetIntervalState(int Index, int& IFirst, int& ILast) const;
  int NbPoints() const;
  double GetPoint(int Index) const;
  int GetPointState(int Index) const;
  void Dump(std::ostream& o) const;
};

class math_FunctionRoot {
public:
  math_FunctionRoot(math_FunctionWithDerivative& F, double Guess, double Tolerance, int NbIterations = 100);
  math_FunctionRoot(math_FunctionWithDerivative& F, double Guess, double Tolerance, double A, double B, int NbIterations = 100);
  bool IsDone() const;
  double Root() const;
  double Derivative() const;
  double Value() const;
  int NbIterations() const;
  void Dump(std::ostream& o) const;
};

class math_FunctionRoots {
public:
  math_FunctionRoots(math_FunctionWithDerivative& F, double A, double B, int NbSample, double EpsX = 0.0, double EpsF = 0.0, double EpsNull = 0.0, double K = 0.0);
  bool IsDone() const;
  bool IsAllNull() const;
  int NbSolutions() const;
  double Value(int Nieme) const;
  int StateNumber(int Nieme) const;
  void Dump(std::ostream& o) const;
};

class math_FunctionSample {
public:
  math_FunctionSample(double A, double B, int N);
  void Bounds(double& A, double& B) const;
  int NbPoints() const;
  double GetParameter(int Index) const;
};

class math_FunctionSet {
public:
  int NbVariables() const;
  int NbEquations() const;
  bool Value(const math_VectorBase<double>& X, math_VectorBase<double>& F);
  int GetStateNumber();
};

class math_FunctionSetRoot {
public:
  math_FunctionSetRoot(math_FunctionSetWithDerivatives& F, const math_VectorBase<double>& Tolerance, int NbIterations = 100);
  math_FunctionSetRoot(math_FunctionSetWithDerivatives& F, int NbIterations = 100);
  void SetTolerance(const math_VectorBase<double>& Tolerance);
  bool IsSolutionReached(math_FunctionSetWithDerivatives& arg0);
  void Perform(math_FunctionSetWithDerivatives& theFunction, const math_VectorBase<double>& theStartingPoint, bool theStopOnDivergent = false);
  void Perform(math_FunctionSetWithDerivatives& theFunction, const math_VectorBase<double>& theStartingPoint, const math_VectorBase<double>& theInfBound, const math_VectorBase<double>& theSupBound, bool theStopOnDivergent = false);
  bool IsDone() const;
  int NbIterations() const;
  int StateNumber() const;
  const math_VectorBase<double>& Root() const;
  void Root(math_VectorBase<double>& Root) const;
  const math_Matrix& Derivative() const;
  void Derivative(math_Matrix& Der) const;
  const math_VectorBase<double>& FunctionSetErrors() const;
  void FunctionSetErrors(math_VectorBase<double>& Err) const;
  void Dump(std::ostream& o) const;
  bool IsDivergent() const;
};

class math_FunctionSetWithDerivatives : public math_FunctionSet {
public:
  int NbVariables() const;
  int NbEquations() const;
  bool Value(const math_VectorBase<double>& X, math_VectorBase<double>& F);
  bool Derivatives(const math_VectorBase<double>& X, math_Matrix& D);
  bool Values(const math_VectorBase<double>& X, math_VectorBase<double>& F, math_Matrix& D);
};

class math_FunctionWithDerivative : public math_Function {
public:
  bool Value(double X, double& F);
  bool Derivative(double X, double& D);
  bool Values(double X, double& F, double& D);
};

class math_Gauss {
public:
  math_Gauss(const math_Matrix& A, double MinPivot = 1.0e-20);
  bool IsDone() const;
  void Solve(const math_VectorBase<double>& B, math_VectorBase<double>& X) const;
  void Solve(math_VectorBase<double>& B) const;
  double Determinant() const;
  void Invert(math_Matrix& Inv) const;
  void Dump(std::ostream& o) const;
};

class math_GaussLeastSquare {
public:
  math_GaussLeastSquare(const math_Matrix& A, double MinPivot = 1.0e-20);
  bool IsDone() const;
  void Solve(const math_VectorBase<double>& B, math_VectorBase<double>& X) const;
  void Dump(std::ostream& o) const;
};

class math_GaussMultipleIntegration {
public:
  math_GaussMultipleIntegration(math_MultipleVarFunction& F, const math_VectorBase<double>& Lower, const math_VectorBase<double>& Upper, const math_VectorBase<int>& Order);
  bool IsDone() const;
  double Value() const;
  void Dump(std::ostream& o) const;
};

class math_GaussSetIntegration {
public:
  math_GaussSetIntegration(math_FunctionSet& F, const math_VectorBase<double>& Lower, const math_VectorBase<double>& Upper, const math_VectorBase<int>& Order);
  bool IsDone() const;
  const math_VectorBase<double>& Value() const;
  void Dump(std::ostream& o) const;
};

class math_GaussSingleIntegration {
public:
  math_GaussSingleIntegration();
  math_GaussSingleIntegration(math_Function& F, double Lower, double Upper, int Order);
  math_GaussSingleIntegration(math_Function& F, double Lower, double Upper, int Order, double Tol);
  bool IsDone() const;
  double Value() const;
  void Dump(std::ostream& o) const;
};

class math_MultipleVarFunction {
public:
  int NbVariables() const;
  bool Value(const math_VectorBase<double>& X, double& F);
  int GetStateNumber();
};

class math_GlobOptMin {
public:
  %apply SWIGTYPE * NETOCC_KEEP { math_MultipleVarFunction* theFunc };
  math_GlobOptMin(math_MultipleVarFunction* theFunc, const math_VectorBase<double>& theLowerBorder, const math_VectorBase<double>& theUpperBorder, double theC = 9, double theDiscretizationTol = 1.0e-2, double theSameTol = 1.0e-7);
  %clear math_MultipleVarFunction* theFunc;
  %netocc_keep_argument(SetGlobalParams.0, math_MultipleVarFunction* theFunc)
  void SetGlobalParams(math_MultipleVarFunction* theFunc, const math_VectorBase<double>& theLowerBorder, const math_VectorBase<double>& theUpperBorder, double theC = 9, double theDiscretizationTol = 1.0e-2, double theSameTol = 1.0e-7);
  %clear math_MultipleVarFunction* theFunc;
  void SetLocalParams(const math_VectorBase<double>& theLocalA, const math_VectorBase<double>& theLocalB);
  void SetTol(double theDiscretizationTol, double theSameTol);
  void GetTol(double& theDiscretizationTol, double& theSameTol);
  void Perform(bool isFindSingleSolution = false);
  void Points(int theIndex, math_VectorBase<double>& theSol);
  void SetContinuity(int theCont);
  int GetContinuity() const;
  void SetFunctionalMinimalValue(double theMinimalValue);
  double GetFunctionalMinimalValue() const;
  void SetLipConstState(bool theFlag);
  bool GetLipConstState() const;
  bool isDone() const;
  double GetF() const;
  int NbExtrema() const;
};

class math_Householder {
public:
  math_Householder(const math_Matrix& A, const math_Matrix& B, double EPS = 1.0e-20);
  math_Householder(const math_Matrix& A, const math_Matrix& B, int lowerArow, int upperArow, int lowerAcol, int upperAcol, double EPS = 1.0e-20);
  math_Householder(const math_Matrix& A, const math_VectorBase<double>& B, double EPS = 1.0e-20);
  bool IsDone() const;
  void Value(math_VectorBase<double>& sol, int Index = 1) const;
  const math_Matrix& AllValues() const;
  void Dump(std::ostream& o) const;
};

class math_Jacobi {
public:
  math_Jacobi(const math_Matrix& A);
  bool IsDone() const;
  const math_VectorBase<double>& Values() const;
  double Value(int Num) const;
  const math_Matrix& Vectors() const;
  void Vector(int Num, math_VectorBase<double>& V) const;
  void Dump(std::ostream& o) const;
};

class math_KronrodSingleIntegration {
public:
  math_KronrodSingleIntegration();
  math_KronrodSingleIntegration(math_Function& theFunction, double theLower, double theUpper, int theNbPnts);
  math_KronrodSingleIntegration(math_Function& theFunction, double theLower, double theUpper, int theNbPnts, double theTolerance, int theMaxNbIter);
  void Perform(math_Function& theFunction, double theLower, double theUpper, int theNbPnts);
  void Perform(math_Function& theFunction, double theLower, double theUpper, int theNbPnts, double theTolerance, int theMaxNbIter);
  bool IsDone() const;
  double Value() const;
  double ErrorReached() const;
  double AbsolutError() const;
  int OrderReached() const;
  int NbIterReached() const;
  static bool GKRule(math_Function& theFunction, double theLower, double theUpper, const math_VectorBase<double>& theGaussP, const math_VectorBase<double>& theGaussW, const math_VectorBase<double>& theKronrodP, const math_VectorBase<double>& theKronrodW, double& theValue, double& theError);
};

class math_MultipleVarFunctionWithGradient : public math_MultipleVarFunction {
public:
  int NbVariables() const;
  bool Value(const math_VectorBase<double>& X, double& F);
  bool Gradient(const math_VectorBase<double>& X, math_VectorBase<double>& G);
  bool Values(const math_VectorBase<double>& X, double& F, math_VectorBase<double>& G);
};

class math_MultipleVarFunctionWithHessian : public math_MultipleVarFunctionWithGradient {
public:
  int NbVariables() const;
  bool Value(const math_VectorBase<double>& X, double& F);
  bool Gradient(const math_VectorBase<double>& X, math_VectorBase<double>& G);
  bool Values(const math_VectorBase<double>& X, double& F, math_VectorBase<double>& G);
  bool Values(const math_VectorBase<double>& X, double& F, math_VectorBase<double>& G, math_Matrix& H);
};

class math_NewtonFunctionRoot {
public:
  math_NewtonFunctionRoot(math_FunctionWithDerivative& F, double Guess, double EpsX, double EpsF, int NbIterations = 100);
  math_NewtonFunctionRoot(math_FunctionWithDerivative& F, double Guess, double EpsX, double EpsF, double A, double B, int NbIterations = 100);
  math_NewtonFunctionRoot(double A, double B, double EpsX, double EpsF, int NbIterations = 100);
  void Perform(math_FunctionWithDerivative& F, double Guess);
  bool IsDone() const;
  double Root() const;
  double Derivative() const;
  double Value() const;
  int NbIterations() const;
  void Dump(std::ostream& o) const;
};

class math_NewtonFunctionSetRoot {
public:
  math_NewtonFunctionSetRoot(math_FunctionSetWithDerivatives& theFunction, const math_VectorBase<double>& theXTolerance, double theFTolerance, int theNbIterations = 100);
  math_NewtonFunctionSetRoot(math_FunctionSetWithDerivatives& theFunction, double theFTolerance, int theNbIterations = 100);
  void SetTolerance(const math_VectorBase<double>& XTol);
  void Perform(math_FunctionSetWithDerivatives& theFunction, const math_VectorBase<double>& theStartingPoint);
  void Perform(math_FunctionSetWithDerivatives& theFunction, const math_VectorBase<double>& theStartingPoint, const math_VectorBase<double>& theInfBound, const math_VectorBase<double>& theSupBound);
  bool IsSolutionReached(math_FunctionSetWithDerivatives& F);
  bool IsDone() const;
  const math_VectorBase<double>& Root() const;
  void Root(math_VectorBase<double>& Root) const;
  const math_Matrix& Derivative() const;
  void Derivative(math_Matrix& Der) const;
  const math_VectorBase<double>& FunctionSetErrors() const;
  void FunctionSetErrors(math_VectorBase<double>& Err) const;
  int NbIterations() const;
  void Dump(std::ostream& o) const;
};

class math_NewtonMinimum {
public:
  math_NewtonMinimum(const math_MultipleVarFunctionWithHessian& theFunction, double theTolerance = Precision::Confusion(), int theNbIterations = 40, double theConvexity = 1.0e-6, bool theWithSingularity = true);
  void Perform(math_MultipleVarFunctionWithHessian& theFunction, const math_VectorBase<double>& theStartingPoint);
  bool IsConverged() const;
  bool IsDone() const;
  const math_VectorBase<double>& Location() const;
  void Location(math_VectorBase<double>& Loc) const;
  void SetBoundary(const math_VectorBase<double>& theLeftBorder, const math_VectorBase<double>& theRightBorder);
  double Minimum() const;
  const math_VectorBase<double>& Gradient() const;
  void Gradient(math_VectorBase<double>& Grad) const;
  int NbIterations() const;
  math_Status GetStatus() const;
  void Dump(std::ostream& o) const;
};

class math_PSO {
public:
  %apply SWIGTYPE * NETOCC_KEEP { math_MultipleVarFunction* theFunc };
  math_PSO(math_MultipleVarFunction* theFunc, const math_VectorBase<double>& theLowBorder, const math_VectorBase<double>& theUppBorder, const math_VectorBase<double>& theSteps, int theNbParticles = 32, int theNbIter = 100);
  %clear math_MultipleVarFunction* theFunc;
  void Perform(const math_VectorBase<double>& theSteps, double& theValue, math_VectorBase<double>& theOutPnt, int theNbIter = 100);
  void Perform(math_PSOParticlesPool& theParticles, int theNbParticles, double& theValue, math_VectorBase<double>& theOutPnt, int theNbIter = 100);
};

class PSO_Particle {
public:
  PSO_Particle();
};

class math_PSOParticlesPool {
public:
  math_PSOParticlesPool(int theParticlesCount, int theDimensionCount);
  PSO_Particle* GetParticle(int theIdx);
  PSO_Particle* GetBestParticle();
  PSO_Particle* GetWorstParticle();
};

class math_Powell {
public:
  math_Powell(const math_MultipleVarFunction& theFunction, double theTolerance, int theNbIterations = 200, double theZEPS = 1.0e-12);
  void Perform(math_MultipleVarFunction& theFunction, const math_VectorBase<double>& theStartingPoint, const math_Matrix& theStartingDirections);
  bool IsSolutionReached(math_MultipleVarFunction& theFunction);
  bool IsDone() const;
  const math_VectorBase<double>& Location() const;
  void Location(math_VectorBase<double>& Loc) const;
  double Minimum() const;
  int NbIterations() const;
  void Dump(std::ostream& o) const;
};

class math_SVD {
public:
  math_SVD(const math_Matrix& A);
  bool IsDone() const;
  void Solve(const math_VectorBase<double>& B, math_VectorBase<double>& X, double Eps = 1.0e-6);
  void PseudoInverse(math_Matrix& Inv, double Eps = 1.0e-6);
  void Dump(std::ostream& o) const;
};

class math_SingularMatrix : public Standard_Failure {
public:
  math_SingularMatrix(const char* theMessage = "");
  math_SingularMatrix(const char* theMessage, const char* theStackTrace);
  const char* ExceptionType() const;
};

class math_TrigonometricEquationFunction : public math_FunctionWithDerivative {
public:
  math_TrigonometricEquationFunction(double A, double B, double C, double D, double E);
  bool Value(double X, double& F);
  bool Derivative(double X, double& D);
  bool Values(double X, double& F, double& D);
};

class math_TrigonometricFunctionRoots {
public:
  math_TrigonometricFunctionRoots(double A, double B, double C, double D, double E, double InfBound, double SupBound);
  math_TrigonometricFunctionRoots(double D, double E, double InfBound, double SupBound);
  math_TrigonometricFunctionRoots(double C, double D, double E, double InfBound, double SupBound);
  bool IsDone() const;
  bool InfiniteRoots() const;
  double Value(int Index) const;
  int NbSolutions() const;
  void Dump(std::ostream& o) const;
};

class math_Uzawa {
public:
  math_Uzawa(const math_Matrix& Cont, const math_VectorBase<double>& Secont, const math_VectorBase<double>& StartingPoint, double EpsLix = 1.0e-06, double EpsLic = 1.0e-06, int NbIterations = 500);
  math_Uzawa(const math_Matrix& Cont, const math_VectorBase<double>& Secont, const math_VectorBase<double>& StartingPoint, int Nci, int Nce, double EpsLix = 1.0e-06, double EpsLic = 1.0e-06, int NbIterations = 500);
  bool IsDone() const;
  const math_VectorBase<double>& Value() const;
  const math_VectorBase<double>& InitialError() const;
  void Duale(math_VectorBase<double>& V) const;
  const math_VectorBase<double>& Error() const;
  int NbIterations() const;
  const math_Matrix& InverseCont() const;
  void Dump(std::ostream& o) const;
};

class math_ValueAndWeight {
public:
  math_ValueAndWeight();
  math_ValueAndWeight(double theValue, double theWeight);
  double Value() const;
  double Weight() const;
};
