// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* NCollection: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module NCollectionModule

%include "NetOcc.i"

%{
#include <NCollection_module.hxx>
%}

%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%netocc_csimports(using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard;)

%occt_transient(NCollection_BaseAllocator)
%nodefaultctor NCollection_BaseAllocator;
%feature("valuewrapper") NCollection_BaseAllocator;
%nodefaultdtor NCollection_ListNode;
%nodefaultctor NCollection_ListNode;
%feature("valuewrapper") NCollection_ListNode;
%nodefaultdtor NCollection_BaseMap;
%nodefaultctor NCollection_BaseMap;
%feature("valuewrapper") NCollection_BaseMap;
%occt_valueclass(NCollection_BaseMap_Iterator)
%nodefaultctor NCollection_BaseMap_Iterator;
%feature("valuewrapper") NCollection_BaseMap_Iterator;
%nodefaultdtor NCollection_SeqNode;
%nodefaultctor NCollection_SeqNode;
%nodefaultdtor NCollection_BaseSequence;
%nodefaultctor NCollection_BaseSequence;
%feature("valuewrapper") NCollection_BaseSequence;
%occt_valueclass(NCollection_BaseSequence_Iterator)
%occt_transient(NCollection_AccAllocator)
%occt_transient(NCollection_AlignedAllocator)
%nodefaultctor NCollection_AlignedAllocator;
%feature("valuewrapper") NCollection_AlignedAllocator;
%occt_valueclass(NCollection_BaseList)
%nodefaultctor NCollection_BaseList;
%feature("valuewrapper") NCollection_BaseList;
%occt_valueclass(NCollection_BaseList_Iterator)
%occt_transient(NCollection_Buffer)
%nodefaultctor NCollection_Buffer;
%feature("valuewrapper") NCollection_Buffer;
%occt_transient(NCollection_IncAllocator)
%nodefaultctor NCollection_IncAllocator_IBlock;
%feature("valuewrapper") NCollection_IncAllocator_IBlock;
%occt_valueclass(NCollection_ForwardRangeSentinel)
%occt_transient(NCollection_HeapAllocator)
%nodefaultctor NCollection_HeapAllocator;
%feature("valuewrapper") NCollection_HeapAllocator;
%nodefaultdtor NCollection_SparseArrayBase;
%nodefaultctor NCollection_SparseArrayBase;
%feature("valuewrapper") NCollection_SparseArrayBase;
%occt_valueclass(NCollection_SparseArrayBase_Iterator)
%nodefaultctor NCollection_SparseArrayBase_Iterator;
%feature("valuewrapper") NCollection_SparseArrayBase_Iterator;
%occt_transient(NCollection_WinHeapAllocator)
%occt_valueclass(BVH_Vec3f)
%occt_valueclass(BVH_Vec4f)
%occt_valueclass(BVH_Vec2f)
%occt_valueclass(TColStd_PackedMapOfInteger)
%occt_valueclass(BVH_Vec2d)
%occt_valueclass(BVH_Vec3d)
%feature("valuewrapper") NCollection_LocalArray_double_1024;
%occt_valueclass(TColStd_ListIteratorOfListOfInteger)
%occt_valueclass(BVH_Vec2i)
%occt_valueclass(BVH_Mat4d)
%occt_valueclass(NCollection_Vec3_bool)
%occt_valueclass(BVH_Vec4d)
%occt_valueclass(NCollection_Mat3_double)
%occt_valueclass(NCollection_Vec2_bool)
%occt_valueclass(Graphic3d_Vec4ub)
%occt_valueclass(BVH_Vec3i)
%occt_valueclass(BVH_Vec4i)
%occt_valueclass(NCollection_Mat3_float)
%occt_valueclass(BVH_Mat4f)
%occt_valueclass(NCollection_String)
%occt_valueclass(Graphic3d_Vec2ub)
%occt_valueclass(Graphic3d_Vec3ub)
%occt_valueclass(NCollection_UtfIterator_char)
%nodefaultctor NCollection_UtfIterator_char;
%feature("valuewrapper") NCollection_UtfIterator_char;
%occt_valueclass(NCollection_UtfString_char16_t)
%occt_valueclass(NCollection_UtfString_char32_t)
%occt_valueclass(NCollection_UtfIterator_char16_t)
%nodefaultctor NCollection_UtfIterator_char16_t;
%feature("valuewrapper") NCollection_UtfIterator_char16_t;
%occt_valueclass(NCollection_UtfIterator_char32_t)
%nodefaultctor NCollection_UtfIterator_char32_t;
%feature("valuewrapper") NCollection_UtfIterator_char32_t;
%nodefaultctor NCollection_SparseArray_int;
%feature("valuewrapper") NCollection_SparseArray_int;
%netocc_address(%arg(bool*))
%netocc_address(%arg(char*))
%netocc_address(%arg(char16_t*))
%netocc_address(%arg(char32_t*))
%netocc_address(%arg(const bool*))
%netocc_address(%arg(const char32_t*))
%netocc_address(%arg(const double*))
%netocc_address(%arg(const float*))
%netocc_address(%arg(const int*))
%netocc_address(%arg(const uint8_t*))
%netocc_address(%arg(const unsigned char*))
%netocc_address(%arg(double*))
%netocc_address(%arg(float*))
%netocc_address(%arg(int*))
%netocc_address(%arg(uint8_t*))
%netocc_address(%arg(unsigned char*))

%typemap(csbase) NCollection_IncAllocator_IBlockSizeLevel "ushort"
enum class NCollection_IncAllocator_IBlockSizeLevel {
  Min = 0,
  Small = 1,
  Medium = 2,
  Large = 3,
  Max = 4,
};

enum NCollection_CellFilter_Action {
  CellFilter_Keep = 0,
  CellFilter_Purge = 1,
};

%occt_dynamicarray(NCollection_DynamicArray_float, float, float)
%occt_dynamicarray(NCollection_DynamicArray_int, int, int)

class NCollection_BaseAllocator : public Standard_Transient {
public:
  void* Allocate(size_t theSize);
  void* AllocateOptimal(size_t theSize);
  void Free(void* theAddress);
  static const opencascade::handle<NCollection_BaseAllocator>& CommonBaseAllocator();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class NCollection_ListNode {
public:
  NCollection_ListNode*& Next();
};

class NCollection_BaseMap {
public:
  size_t NbBuckets() const;
  int Extent() const;
  int Length() const;
  size_t Size() const;
  bool IsEmpty() const;
  const opencascade::handle<NCollection_BaseAllocator>& Allocator() const;
};

class NCollection_BaseMap_Iterator {
public:
  void Initialize(const NCollection_BaseMap& theMap);
  void Reset();
  bool IsEqual(const NCollection_BaseMap_Iterator& theOther) const;
};

class NCollection_SeqNode {
public:
  NCollection_SeqNode* Next() const;
  NCollection_SeqNode* Previous() const;
  %netocc_keep_argument(SetNext.0, NCollection_SeqNode* theNext)
  void SetNext(NCollection_SeqNode* theNext);
  %clear NCollection_SeqNode* theNext;
  %netocc_keep_argument(SetPrevious.0, NCollection_SeqNode* thePrev)
  void SetPrevious(NCollection_SeqNode* thePrev);
  %clear NCollection_SeqNode* thePrev;
};

class NCollection_BaseSequence {
public:
  bool IsEmpty() const;
  int Length() const;
  size_t Size() const;
  const opencascade::handle<NCollection_BaseAllocator>& Allocator() const;
};

class NCollection_BaseSequence_Iterator {
public:
  NCollection_BaseSequence_Iterator();
  NCollection_BaseSequence_Iterator(const NCollection_BaseSequence& theSeq, bool isStart);
  void Init(const NCollection_BaseSequence& theSeq, bool isStart = true);
  void Previous();
};

class NCollection_AccAllocator : public NCollection_BaseAllocator {
public:
  NCollection_AccAllocator(size_t theBlockSize = DefaultBlockSize);
  void* Allocate(size_t theSize);
  void* AllocateOptimal(size_t theSize);
  void Free(void* theAddress);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class NCollection_AlignedAllocator : public NCollection_BaseAllocator {
public:
  NCollection_AlignedAllocator(size_t theAlignment);
  void* Allocate(size_t theSize);
  void* AllocateOptimal(size_t theSize);
  void Free(void* thePtr);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class NCollection_BaseList {
public:
  int Extent() const;
  int Length() const;
  size_t Size() const;
  bool IsEmpty() const;
  const opencascade::handle<NCollection_BaseAllocator>& Allocator() const;
};

class NCollection_BaseList_Iterator {
public:
  NCollection_BaseList_Iterator();
  NCollection_BaseList_Iterator(const NCollection_BaseList& theList);
  void Init(const NCollection_BaseList& theList);
  void Initialize(const NCollection_BaseList& theList);
  bool More() const;
  bool IsEqual(const NCollection_BaseList_Iterator& theOther) const;
};

class NCollection_Buffer : public Standard_Transient {
public:
  NCollection_Buffer(const opencascade::handle<NCollection_BaseAllocator>& theAlloc, size_t theSize = 0, NetOcc_Address< uint8_t* > theData = nullptr);
  NetOcc_Address< const uint8_t* > Data() const;
  NetOcc_Address< uint8_t* > ChangeData();
  bool IsEmpty() const;
  size_t Size() const;
  const opencascade::handle<NCollection_BaseAllocator>& Allocator() const;
  void SetAllocator(const opencascade::handle<NCollection_BaseAllocator>& theAlloc);
  bool Allocate(size_t theSize);
  void Free();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class NCollection_IncAllocator : public NCollection_BaseAllocator {
public:
  NCollection_IncAllocator(size_t theBlockSize = THE_DEFAULT_BLOCK_SIZE);
  void SetThreadSafe(bool theIsThreadSafe = true);
  void* Allocate(size_t size);
  void* AllocateOptimal(size_t size);
  void Free(void* arg0);
  void Reset(bool theReleaseMemory = false);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class NCollection_IncAllocator_IBlock {
public:
};

class NCollection_ForwardRangeSentinel {
public:
  NCollection_ForwardRangeSentinel();
};

class NCollection_HeapAllocator : public NCollection_BaseAllocator {
public:
  void* Allocate(size_t theSize);
  void* AllocateOptimal(size_t theSize);
  void Free(void* anAddress);
  static const opencascade::handle<NCollection_HeapAllocator>& GlobalHeapAllocator();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class NCollection_SparseArrayBase {
public:
  size_t Size() const;
  bool HasValue(size_t theIndex) const;
};

class NCollection_SparseArrayBase_Iterator {
public:
  void Restart();
  bool More() const;
  void Next();
  size_t Index() const;
};

class NCollection_WinHeapAllocator : public NCollection_BaseAllocator {
public:
  NCollection_WinHeapAllocator(size_t theInitSizeBytes = 0x80000);
  void* Allocate(size_t theSize);
  void* AllocateOptimal(size_t theSize);
  void Free(void* theAddress);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class BVH_Vec3f {
public:
  BVH_Vec3f();
  BVH_Vec3f(float theValue);
  BVH_Vec3f(float theX, float theY, float theZ);
  BVH_Vec3f(const BVH_Vec2f& theVec2, float theZ = Element_t(0));
  static int Length();
  void SetValues(float theX, float theY, float theZ);
  void SetValues(const BVH_Vec2f& theVec2, float theZ);
  BVH_Vec2f xy() const;
  BVH_Vec2f yx() const;
  BVH_Vec2f xz() const;
  BVH_Vec2f zx() const;
  BVH_Vec2f yz() const;
  BVH_Vec2f zy() const;
  BVH_Vec3f xyz() const;
  BVH_Vec3f xzy() const;
  BVH_Vec3f yxz() const;
  BVH_Vec3f yzx() const;
  BVH_Vec3f zyx() const;
  BVH_Vec3f zxy() const;
  float& x();
  float& r();
  float& y();
  float& g();
  float& z();
  float& b();
  bool IsEqual(const BVH_Vec3f& theOther) const;
  NetOcc_Address< const float* > GetData() const;
  NetOcc_Address< float* > ChangeData();
  void Multiply(float theFactor);
  BVH_Vec3f Multiplied(float theFactor) const;
  BVH_Vec3f cwiseMin(const BVH_Vec3f& theVec) const;
  BVH_Vec3f cwiseMax(const BVH_Vec3f& theVec) const;
  BVH_Vec3f cwiseAbs() const;
  float maxComp() const;
  float minComp() const;
  float Dot(const BVH_Vec3f& theOther) const;
  float Modulus() const;
  float SquareModulus() const;
  void Normalize();
  BVH_Vec3f Normalized() const;
  static BVH_Vec3f Cross(const BVH_Vec3f& theVec1, const BVH_Vec3f& theVec2);
  static BVH_Vec3f GetLERP(const BVH_Vec3f& theFrom, const BVH_Vec3f& theTo, float theT);
  static BVH_Vec3f DX();
  static BVH_Vec3f DY();
  static BVH_Vec3f DZ();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class BVH_Vec4f {
public:
  BVH_Vec4f();
  BVH_Vec4f(float theValue);
  BVH_Vec4f(float theX, float theY, float theZ, float theW);
  BVH_Vec4f(const BVH_Vec2f& theVec2);
  BVH_Vec4f(const BVH_Vec3f& theVec3, float theW = Element_t(0));
  static int Length();
  void SetValues(float theX, float theY, float theZ, float theW);
  void SetValues(const BVH_Vec3f& theVec3, float theW);
  BVH_Vec2f xy() const;
  BVH_Vec2f yx() const;
  BVH_Vec2f xz() const;
  BVH_Vec2f zx() const;
  BVH_Vec2f xw() const;
  BVH_Vec2f wx() const;
  BVH_Vec2f yz() const;
  BVH_Vec2f zy() const;
  BVH_Vec2f yw() const;
  BVH_Vec2f wy() const;
  BVH_Vec2f zw() const;
  BVH_Vec2f wz() const;
  BVH_Vec3f xyz() const;
  BVH_Vec3f xzy() const;
  BVH_Vec3f yxz() const;
  BVH_Vec3f yzx() const;
  BVH_Vec3f zyx() const;
  BVH_Vec3f zxy() const;
  BVH_Vec3f xyw() const;
  BVH_Vec3f xwy() const;
  BVH_Vec3f yxw() const;
  BVH_Vec3f ywx() const;
  BVH_Vec3f wyx() const;
  BVH_Vec3f wxy() const;
  BVH_Vec3f xzw() const;
  BVH_Vec3f xwz() const;
  BVH_Vec3f zxw() const;
  BVH_Vec3f zwx() const;
  BVH_Vec3f wzx() const;
  BVH_Vec3f wxz() const;
  BVH_Vec3f yzw() const;
  BVH_Vec3f ywz() const;
  BVH_Vec3f zyw() const;
  BVH_Vec3f zwy() const;
  BVH_Vec3f wzy() const;
  BVH_Vec3f wyz() const;
  BVH_Vec3f rgb() const;
  BVH_Vec3f rbg() const;
  BVH_Vec3f grb() const;
  BVH_Vec3f gbr() const;
  BVH_Vec3f bgr() const;
  BVH_Vec3f brg() const;
  float& x();
  float& r();
  float& y();
  float& g();
  float& z();
  float& b();
  float& w();
  float& a();
  bool IsEqual(const BVH_Vec4f& theOther) const;
  NetOcc_Address< const float* > GetData() const;
  NetOcc_Address< float* > ChangeData();
  void Multiply(float theFactor);
  BVH_Vec4f Multiplied(float theFactor) const;
  BVH_Vec4f cwiseMin(const BVH_Vec4f& theVec) const;
  BVH_Vec4f cwiseMax(const BVH_Vec4f& theVec) const;
  BVH_Vec4f cwiseAbs() const;
  float maxComp() const;
  float minComp() const;
  float Dot(const BVH_Vec4f& theOther) const;
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class BVH_Vec2f {
public:
  BVH_Vec2f();
  BVH_Vec2f(float theXY);
  BVH_Vec2f(float theX, float theY);
  static int Length();
  void SetValues(float theX, float theY);
  BVH_Vec2f xy() const;
  BVH_Vec2f yx() const;
  float& x();
  float& y();
  bool IsEqual(const BVH_Vec2f& theOther) const;
  NetOcc_Address< const float* > GetData() const;
  NetOcc_Address< float* > ChangeData();
  void Multiply(float theFactor);
  BVH_Vec2f Multiplied(float theFactor) const;
  BVH_Vec2f cwiseMin(const BVH_Vec2f& theVec) const;
  BVH_Vec2f cwiseMax(const BVH_Vec2f& theVec) const;
  BVH_Vec2f cwiseAbs() const;
  float maxComp() const;
  float minComp() const;
  float Dot(const BVH_Vec2f& theOther) const;
  float Modulus() const;
  float SquareModulus() const;
  static BVH_Vec2f DX();
  static BVH_Vec2f DY();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class TColStd_PackedMapOfInteger {
public:
  TColStd_PackedMapOfInteger(size_t theNbBuckets = 1);
  TColStd_PackedMapOfInteger(int theNbBuckets);
  void Assign(const TColStd_PackedMapOfInteger& theOther);
  void ReSize(size_t theNbBuckets);
  void ReSize(int theNbBuckets);
  void Clear();
  bool Add(int theKey);
  bool Contains(int theKey) const;
  bool Remove(int theKey);
  size_t NbBuckets() const;
  int Extent() const;
  int Length() const;
  size_t Size() const;
  bool IsEmpty() const;
  int GetMinimalMapped() const;
  int GetMaximalMapped() const;
  %csattributes Union(const TColStd_PackedMapOfInteger& theLeft, const TColStd_PackedMapOfInteger& theRight) "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  void Union(const TColStd_PackedMapOfInteger& theLeft, const TColStd_PackedMapOfInteger& theRight);
  %csattributes Unite(const TColStd_PackedMapOfInteger& theOther) "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  bool Unite(const TColStd_PackedMapOfInteger& theOther);
  %csattributes Intersection(const TColStd_PackedMapOfInteger& theLeft, const TColStd_PackedMapOfInteger& theRight) "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  void Intersection(const TColStd_PackedMapOfInteger& theLeft, const TColStd_PackedMapOfInteger& theRight);
  %csattributes Intersect(const TColStd_PackedMapOfInteger& theOther) "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  bool Intersect(const TColStd_PackedMapOfInteger& theOther);
  %csattributes Subtraction(const TColStd_PackedMapOfInteger& theLeft, const TColStd_PackedMapOfInteger& theRight) "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  void Subtraction(const TColStd_PackedMapOfInteger& theLeft, const TColStd_PackedMapOfInteger& theRight);
  %csattributes Subtract(const TColStd_PackedMapOfInteger& theOther) "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  bool Subtract(const TColStd_PackedMapOfInteger& theOther);
  %csattributes Difference(const TColStd_PackedMapOfInteger& theLeft, const TColStd_PackedMapOfInteger& theRight) "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  void Difference(const TColStd_PackedMapOfInteger& theLeft, const TColStd_PackedMapOfInteger& theRight);
  %csattributes Differ(const TColStd_PackedMapOfInteger& theOther) "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  bool Differ(const TColStd_PackedMapOfInteger& theOther);
  %csattributes IsEqual(const TColStd_PackedMapOfInteger& theOther) const "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  bool IsEqual(const TColStd_PackedMapOfInteger& theOther) const;
  %csattributes IsSubset(const TColStd_PackedMapOfInteger& theOther) const "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  bool IsSubset(const TColStd_PackedMapOfInteger& theOther) const;
  %csattributes HasIntersection(const TColStd_PackedMapOfInteger& theOther) const "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  bool HasIntersection(const TColStd_PackedMapOfInteger& theOther) const;
  %csattributes Contains(const TColStd_PackedMapOfInteger& theOther) const "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  bool Contains(const TColStd_PackedMapOfInteger& theOther) const;
};

class BVH_Vec2d {
public:
  BVH_Vec2d();
  BVH_Vec2d(double theXY);
  BVH_Vec2d(double theX, double theY);
  static int Length();
  void SetValues(double theX, double theY);
  BVH_Vec2d xy() const;
  BVH_Vec2d yx() const;
  double& x();
  double& y();
  bool IsEqual(const BVH_Vec2d& theOther) const;
  NetOcc_Address< const double* > GetData() const;
  NetOcc_Address< double* > ChangeData();
  void Multiply(double theFactor);
  BVH_Vec2d Multiplied(double theFactor) const;
  BVH_Vec2d cwiseMin(const BVH_Vec2d& theVec) const;
  BVH_Vec2d cwiseMax(const BVH_Vec2d& theVec) const;
  BVH_Vec2d cwiseAbs() const;
  double maxComp() const;
  double minComp() const;
  double Dot(const BVH_Vec2d& theOther) const;
  double Modulus() const;
  double SquareModulus() const;
  static BVH_Vec2d DX();
  static BVH_Vec2d DY();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class BVH_Vec3d {
public:
  BVH_Vec3d();
  BVH_Vec3d(double theValue);
  BVH_Vec3d(double theX, double theY, double theZ);
  BVH_Vec3d(const BVH_Vec2d& theVec2, double theZ = Element_t(0));
  static int Length();
  void SetValues(double theX, double theY, double theZ);
  void SetValues(const BVH_Vec2d& theVec2, double theZ);
  BVH_Vec2d xy() const;
  BVH_Vec2d yx() const;
  BVH_Vec2d xz() const;
  BVH_Vec2d zx() const;
  BVH_Vec2d yz() const;
  BVH_Vec2d zy() const;
  BVH_Vec3d xyz() const;
  BVH_Vec3d xzy() const;
  BVH_Vec3d yxz() const;
  BVH_Vec3d yzx() const;
  BVH_Vec3d zyx() const;
  BVH_Vec3d zxy() const;
  double& x();
  double& r();
  double& y();
  double& g();
  double& z();
  double& b();
  bool IsEqual(const BVH_Vec3d& theOther) const;
  NetOcc_Address< const double* > GetData() const;
  NetOcc_Address< double* > ChangeData();
  void Multiply(double theFactor);
  BVH_Vec3d Multiplied(double theFactor) const;
  BVH_Vec3d cwiseMin(const BVH_Vec3d& theVec) const;
  BVH_Vec3d cwiseMax(const BVH_Vec3d& theVec) const;
  BVH_Vec3d cwiseAbs() const;
  double maxComp() const;
  double minComp() const;
  double Dot(const BVH_Vec3d& theOther) const;
  double Modulus() const;
  double SquareModulus() const;
  void Normalize();
  BVH_Vec3d Normalized() const;
  static BVH_Vec3d Cross(const BVH_Vec3d& theVec1, const BVH_Vec3d& theVec2);
  static BVH_Vec3d GetLERP(const BVH_Vec3d& theFrom, const BVH_Vec3d& theTo, double theT);
  static BVH_Vec3d DX();
  static BVH_Vec3d DY();
  static BVH_Vec3d DZ();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class NCollection_LocalArray_double_1024 {
public:
  NCollection_LocalArray_double_1024(size_t theSize);
  NCollection_LocalArray_double_1024();
  void Allocate(size_t theSize);
  void Reallocate(size_t theNewSize, bool theToCopy = true);
  size_t Size() const;
  NCollection_Array1<double> ToArray1() const;
};

class TColStd_ListIteratorOfListOfInteger : public NCollection_BaseList_Iterator {
public:
  TColStd_ListIteratorOfListOfInteger();
  TColStd_ListIteratorOfListOfInteger(const NCollection_BaseList& theList);
  bool More() const;
  void Next();
  int& Value();
  int& ChangeValue() const;
};

class BVH_Vec2i {
public:
  BVH_Vec2i();
  BVH_Vec2i(int theXY);
  BVH_Vec2i(int theX, int theY);
  static int Length();
  void SetValues(int theX, int theY);
  BVH_Vec2i xy() const;
  BVH_Vec2i yx() const;
  int& x();
  int& y();
  bool IsEqual(const BVH_Vec2i& theOther) const;
  NetOcc_Address< const int* > GetData() const;
  NetOcc_Address< int* > ChangeData();
  void Multiply(int theFactor);
  BVH_Vec2i Multiplied(int theFactor) const;
  BVH_Vec2i cwiseMin(const BVH_Vec2i& theVec) const;
  BVH_Vec2i cwiseMax(const BVH_Vec2i& theVec) const;
  BVH_Vec2i cwiseAbs() const;
  int maxComp() const;
  int minComp() const;
  int Dot(const BVH_Vec2i& theOther) const;
  int Modulus() const;
  int SquareModulus() const;
  static BVH_Vec2i DX();
  static BVH_Vec2i DY();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class BVH_Mat4d {
public:
  BVH_Mat4d();
  static size_t Rows();
  static size_t Cols();
  static BVH_Mat4d Identity();
  static BVH_Mat4d Zero();
  double GetValue(size_t theRow, size_t theCol) const;
  double& ChangeValue(size_t theRow, size_t theCol);
  void SetValue(size_t theRow, size_t theCol, double theValue);
  BVH_Vec4d GetRow(size_t theRow) const;
  void SetRow(size_t theRow, const BVH_Vec3d& theVec);
  void SetRow(size_t theRow, const BVH_Vec4d& theVec);
  BVH_Vec4d GetColumn(size_t theCol) const;
  void SetColumn(size_t theCol, const BVH_Vec3d& theVec);
  void SetColumn(size_t theCol, const BVH_Vec4d& theVec);
  BVH_Vec4d GetDiagonal() const;
  void SetDiagonal(const BVH_Vec3d& theVec);
  void SetDiagonal(const BVH_Vec4d& theVec);
  NCollection_Mat3_double GetMat3() const;
  void InitZero();
  bool IsZero() const;
  void InitIdentity();
  bool IsIdentity() const;
  bool IsEqual(const BVH_Mat4d& theOther) const;
  NetOcc_Address< const double* > GetData() const;
  NetOcc_Address< double* > ChangeData();
  static BVH_Mat4d Multiply(const BVH_Mat4d& theMatA, const BVH_Mat4d& theMatB);
  BVH_Mat4d Multiplied(const BVH_Mat4d& theMat) const;
  void Multiply(double theFactor);
  BVH_Mat4d Multiplied(double theFactor) const;
  void Divide(double theFactor);
  BVH_Mat4d Divided(double theScalar) const;
  void Add(const BVH_Mat4d& theMat);
  void Subtract(const BVH_Mat4d& theMat);
  BVH_Mat4d Added(const BVH_Mat4d& theMat) const;
  BVH_Mat4d Subtracted(const BVH_Mat4d& theMat) const;
  BVH_Mat4d Negated() const;
  void Translate(const BVH_Vec3d& theVec);
  BVH_Mat4d Transposed() const;
  void Transpose();
  bool Inverted(BVH_Mat4d& theOutMx, double& theDet) const;
  bool Inverted(BVH_Mat4d& theOutMx) const;
  BVH_Mat4d Inverted() const;
  double DeterminantMat3() const;
  BVH_Mat4d Adjoint() const;
  static const BVH_Mat4d& Map(const double* theData);
  void DumpJson(std::ostream& theOStream, int arg1) const;
};

class NCollection_Vec3_bool {
public:
  NCollection_Vec3_bool();
  NCollection_Vec3_bool(bool theValue);
  NCollection_Vec3_bool(bool theX, bool theY, bool theZ);
  NCollection_Vec3_bool(const NCollection_Vec2_bool& theVec2, bool theZ = Element_t(0));
  static int Length();
  void SetValues(bool theX, bool theY, bool theZ);
  void SetValues(const NCollection_Vec2_bool& theVec2, bool theZ);
  NCollection_Vec2_bool xy() const;
  NCollection_Vec2_bool yx() const;
  NCollection_Vec2_bool xz() const;
  NCollection_Vec2_bool zx() const;
  NCollection_Vec2_bool yz() const;
  NCollection_Vec2_bool zy() const;
  NCollection_Vec3_bool xyz() const;
  NCollection_Vec3_bool xzy() const;
  NCollection_Vec3_bool yxz() const;
  NCollection_Vec3_bool yzx() const;
  NCollection_Vec3_bool zyx() const;
  NCollection_Vec3_bool zxy() const;
  bool& x();
  bool& r();
  bool& y();
  bool& g();
  bool& z();
  bool& b();
  bool IsEqual(const NCollection_Vec3_bool& theOther) const;
  NetOcc_Address< const bool* > GetData() const;
  NetOcc_Address< bool* > ChangeData();
  void Multiply(bool theFactor);
  NCollection_Vec3_bool Multiplied(bool theFactor) const;
  NCollection_Vec3_bool cwiseMin(const NCollection_Vec3_bool& theVec) const;
  NCollection_Vec3_bool cwiseMax(const NCollection_Vec3_bool& theVec) const;
  NCollection_Vec3_bool cwiseAbs() const;
  bool maxComp() const;
  bool minComp() const;
  bool Dot(const NCollection_Vec3_bool& theOther) const;
  bool Modulus() const;
  bool SquareModulus() const;
  void Normalize();
  NCollection_Vec3_bool Normalized() const;
  static NCollection_Vec3_bool Cross(const NCollection_Vec3_bool& theVec1, const NCollection_Vec3_bool& theVec2);
  static NCollection_Vec3_bool GetLERP(const NCollection_Vec3_bool& theFrom, const NCollection_Vec3_bool& theTo, bool theT);
  static NCollection_Vec3_bool DX();
  static NCollection_Vec3_bool DY();
  static NCollection_Vec3_bool DZ();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class BVH_Vec4d {
public:
  BVH_Vec4d();
  BVH_Vec4d(double theValue);
  BVH_Vec4d(double theX, double theY, double theZ, double theW);
  BVH_Vec4d(const BVH_Vec2d& theVec2);
  BVH_Vec4d(const BVH_Vec3d& theVec3, double theW = Element_t(0));
  static int Length();
  void SetValues(double theX, double theY, double theZ, double theW);
  void SetValues(const BVH_Vec3d& theVec3, double theW);
  BVH_Vec2d xy() const;
  BVH_Vec2d yx() const;
  BVH_Vec2d xz() const;
  BVH_Vec2d zx() const;
  BVH_Vec2d xw() const;
  BVH_Vec2d wx() const;
  BVH_Vec2d yz() const;
  BVH_Vec2d zy() const;
  BVH_Vec2d yw() const;
  BVH_Vec2d wy() const;
  BVH_Vec2d zw() const;
  BVH_Vec2d wz() const;
  BVH_Vec3d xyz() const;
  BVH_Vec3d xzy() const;
  BVH_Vec3d yxz() const;
  BVH_Vec3d yzx() const;
  BVH_Vec3d zyx() const;
  BVH_Vec3d zxy() const;
  BVH_Vec3d xyw() const;
  BVH_Vec3d xwy() const;
  BVH_Vec3d yxw() const;
  BVH_Vec3d ywx() const;
  BVH_Vec3d wyx() const;
  BVH_Vec3d wxy() const;
  BVH_Vec3d xzw() const;
  BVH_Vec3d xwz() const;
  BVH_Vec3d zxw() const;
  BVH_Vec3d zwx() const;
  BVH_Vec3d wzx() const;
  BVH_Vec3d wxz() const;
  BVH_Vec3d yzw() const;
  BVH_Vec3d ywz() const;
  BVH_Vec3d zyw() const;
  BVH_Vec3d zwy() const;
  BVH_Vec3d wzy() const;
  BVH_Vec3d wyz() const;
  BVH_Vec3d rgb() const;
  BVH_Vec3d rbg() const;
  BVH_Vec3d grb() const;
  BVH_Vec3d gbr() const;
  BVH_Vec3d bgr() const;
  BVH_Vec3d brg() const;
  double& x();
  double& r();
  double& y();
  double& g();
  double& z();
  double& b();
  double& w();
  double& a();
  bool IsEqual(const BVH_Vec4d& theOther) const;
  NetOcc_Address< const double* > GetData() const;
  NetOcc_Address< double* > ChangeData();
  void Multiply(double theFactor);
  BVH_Vec4d Multiplied(double theFactor) const;
  BVH_Vec4d cwiseMin(const BVH_Vec4d& theVec) const;
  BVH_Vec4d cwiseMax(const BVH_Vec4d& theVec) const;
  BVH_Vec4d cwiseAbs() const;
  double maxComp() const;
  double minComp() const;
  double Dot(const BVH_Vec4d& theOther) const;
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class NCollection_Mat3_double {
public:
  NCollection_Mat3_double();
  static NCollection_Mat3_double Identity();
  static NCollection_Mat3_double Zero();
  double GetValue(size_t theRow, size_t theCol) const;
  double& ChangeValue(size_t theRow, size_t theCol);
  void SetValue(size_t theRow, size_t theCol, double theValue);
  BVH_Vec3d GetRow(size_t theRow) const;
  void SetRow(size_t theRow, const BVH_Vec3d& theVec);
  BVH_Vec3d GetColumn(size_t theCol) const;
  void SetColumn(size_t theCol, const BVH_Vec3d& theVec);
  BVH_Vec3d GetDiagonal() const;
  void SetDiagonal(const BVH_Vec3d& theVec);
  void InitZero();
  bool IsZero() const;
  void InitIdentity();
  bool IsIdentity() const;
  bool IsEqual(const NCollection_Mat3_double& theOther) const;
  NetOcc_Address< const double* > GetData() const;
  NetOcc_Address< double* > ChangeData();
  static NCollection_Mat3_double Multiply(const NCollection_Mat3_double& theMatA, const NCollection_Mat3_double& theMatB);
  NCollection_Mat3_double Multiplied(const NCollection_Mat3_double& theMat) const;
  void Multiply(double theFactor);
  NCollection_Mat3_double Multiplied(double theFactor) const;
  void Divide(double theFactor);
  NCollection_Mat3_double Divided(double theScalar) const;
  void Add(const NCollection_Mat3_double& theMat);
  void Subtract(const NCollection_Mat3_double& theMat);
  NCollection_Mat3_double Added(const NCollection_Mat3_double& theMat) const;
  NCollection_Mat3_double Subtracted(const NCollection_Mat3_double& theMat) const;
  NCollection_Mat3_double Negated() const;
  NCollection_Mat3_double Transposed() const;
  void Transpose();
  double Determinant() const;
  NCollection_Mat3_double Adjoint() const;
  bool Inverted(NCollection_Mat3_double& theInv, double& theDet) const;
  bool Inverted(NCollection_Mat3_double& theInv) const;
  NCollection_Mat3_double Inverted() const;
  static const NCollection_Mat3_double& Map(const double* theData);
  void DumpJson(std::ostream& theOStream, int arg1) const;
};

class NCollection_Vec2_bool {
public:
  NCollection_Vec2_bool();
  NCollection_Vec2_bool(bool theXY);
  NCollection_Vec2_bool(bool theX, bool theY);
  static int Length();
  void SetValues(bool theX, bool theY);
  NCollection_Vec2_bool xy() const;
  NCollection_Vec2_bool yx() const;
  bool& x();
  bool& y();
  bool IsEqual(const NCollection_Vec2_bool& theOther) const;
  NetOcc_Address< const bool* > GetData() const;
  NetOcc_Address< bool* > ChangeData();
  void Multiply(bool theFactor);
  NCollection_Vec2_bool Multiplied(bool theFactor) const;
  NCollection_Vec2_bool cwiseMin(const NCollection_Vec2_bool& theVec) const;
  NCollection_Vec2_bool cwiseMax(const NCollection_Vec2_bool& theVec) const;
  NCollection_Vec2_bool cwiseAbs() const;
  bool maxComp() const;
  bool minComp() const;
  bool Dot(const NCollection_Vec2_bool& theOther) const;
  bool Modulus() const;
  bool SquareModulus() const;
  static NCollection_Vec2_bool DX();
  static NCollection_Vec2_bool DY();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class Graphic3d_Vec4ub {
public:
  Graphic3d_Vec4ub();
  Graphic3d_Vec4ub(unsigned char theValue);
  Graphic3d_Vec4ub(unsigned char theX, unsigned char theY, unsigned char theZ, unsigned char theW);
  Graphic3d_Vec4ub(const Graphic3d_Vec2ub& theVec2);
  Graphic3d_Vec4ub(const Graphic3d_Vec3ub& theVec3, unsigned char theW = Element_t(0));
  static int Length();
  void SetValues(unsigned char theX, unsigned char theY, unsigned char theZ, unsigned char theW);
  void SetValues(const Graphic3d_Vec3ub& theVec3, unsigned char theW);
  Graphic3d_Vec2ub xy() const;
  Graphic3d_Vec2ub yx() const;
  Graphic3d_Vec2ub xz() const;
  Graphic3d_Vec2ub zx() const;
  Graphic3d_Vec2ub xw() const;
  Graphic3d_Vec2ub wx() const;
  Graphic3d_Vec2ub yz() const;
  Graphic3d_Vec2ub zy() const;
  Graphic3d_Vec2ub yw() const;
  Graphic3d_Vec2ub wy() const;
  Graphic3d_Vec2ub zw() const;
  Graphic3d_Vec2ub wz() const;
  Graphic3d_Vec3ub xyz() const;
  Graphic3d_Vec3ub xzy() const;
  Graphic3d_Vec3ub yxz() const;
  Graphic3d_Vec3ub yzx() const;
  Graphic3d_Vec3ub zyx() const;
  Graphic3d_Vec3ub zxy() const;
  Graphic3d_Vec3ub xyw() const;
  Graphic3d_Vec3ub xwy() const;
  Graphic3d_Vec3ub yxw() const;
  Graphic3d_Vec3ub ywx() const;
  Graphic3d_Vec3ub wyx() const;
  Graphic3d_Vec3ub wxy() const;
  Graphic3d_Vec3ub xzw() const;
  Graphic3d_Vec3ub xwz() const;
  Graphic3d_Vec3ub zxw() const;
  Graphic3d_Vec3ub zwx() const;
  Graphic3d_Vec3ub wzx() const;
  Graphic3d_Vec3ub wxz() const;
  Graphic3d_Vec3ub yzw() const;
  Graphic3d_Vec3ub ywz() const;
  Graphic3d_Vec3ub zyw() const;
  Graphic3d_Vec3ub zwy() const;
  Graphic3d_Vec3ub wzy() const;
  Graphic3d_Vec3ub wyz() const;
  Graphic3d_Vec3ub rgb() const;
  Graphic3d_Vec3ub rbg() const;
  Graphic3d_Vec3ub grb() const;
  Graphic3d_Vec3ub gbr() const;
  Graphic3d_Vec3ub bgr() const;
  Graphic3d_Vec3ub brg() const;
  unsigned char& x();
  unsigned char& r();
  unsigned char& y();
  unsigned char& g();
  unsigned char& z();
  unsigned char& b();
  unsigned char& w();
  unsigned char& a();
  bool IsEqual(const Graphic3d_Vec4ub& theOther) const;
  NetOcc_Address< const unsigned char* > GetData() const;
  NetOcc_Address< unsigned char* > ChangeData();
  void Multiply(unsigned char theFactor);
  Graphic3d_Vec4ub Multiplied(unsigned char theFactor) const;
  Graphic3d_Vec4ub cwiseMin(const Graphic3d_Vec4ub& theVec) const;
  Graphic3d_Vec4ub cwiseMax(const Graphic3d_Vec4ub& theVec) const;
  Graphic3d_Vec4ub cwiseAbs() const;
  unsigned char maxComp() const;
  unsigned char minComp() const;
  unsigned char Dot(const Graphic3d_Vec4ub& theOther) const;
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class BVH_Vec3i {
public:
  BVH_Vec3i();
  BVH_Vec3i(int theValue);
  BVH_Vec3i(int theX, int theY, int theZ);
  BVH_Vec3i(const BVH_Vec2i& theVec2, int theZ = Element_t(0));
  static int Length();
  void SetValues(int theX, int theY, int theZ);
  void SetValues(const BVH_Vec2i& theVec2, int theZ);
  BVH_Vec2i xy() const;
  BVH_Vec2i yx() const;
  BVH_Vec2i xz() const;
  BVH_Vec2i zx() const;
  BVH_Vec2i yz() const;
  BVH_Vec2i zy() const;
  BVH_Vec3i xyz() const;
  BVH_Vec3i xzy() const;
  BVH_Vec3i yxz() const;
  BVH_Vec3i yzx() const;
  BVH_Vec3i zyx() const;
  BVH_Vec3i zxy() const;
  int& x();
  int& r();
  int& y();
  int& g();
  int& z();
  int& b();
  bool IsEqual(const BVH_Vec3i& theOther) const;
  NetOcc_Address< const int* > GetData() const;
  NetOcc_Address< int* > ChangeData();
  void Multiply(int theFactor);
  BVH_Vec3i Multiplied(int theFactor) const;
  BVH_Vec3i cwiseMin(const BVH_Vec3i& theVec) const;
  BVH_Vec3i cwiseMax(const BVH_Vec3i& theVec) const;
  BVH_Vec3i cwiseAbs() const;
  int maxComp() const;
  int minComp() const;
  int Dot(const BVH_Vec3i& theOther) const;
  int Modulus() const;
  int SquareModulus() const;
  void Normalize();
  BVH_Vec3i Normalized() const;
  static BVH_Vec3i Cross(const BVH_Vec3i& theVec1, const BVH_Vec3i& theVec2);
  static BVH_Vec3i GetLERP(const BVH_Vec3i& theFrom, const BVH_Vec3i& theTo, int theT);
  static BVH_Vec3i DX();
  static BVH_Vec3i DY();
  static BVH_Vec3i DZ();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class BVH_Vec4i {
public:
  BVH_Vec4i();
  BVH_Vec4i(int theValue);
  BVH_Vec4i(int theX, int theY, int theZ, int theW);
  BVH_Vec4i(const BVH_Vec2i& theVec2);
  BVH_Vec4i(const BVH_Vec3i& theVec3, int theW = Element_t(0));
  static int Length();
  void SetValues(int theX, int theY, int theZ, int theW);
  void SetValues(const BVH_Vec3i& theVec3, int theW);
  BVH_Vec2i xy() const;
  BVH_Vec2i yx() const;
  BVH_Vec2i xz() const;
  BVH_Vec2i zx() const;
  BVH_Vec2i xw() const;
  BVH_Vec2i wx() const;
  BVH_Vec2i yz() const;
  BVH_Vec2i zy() const;
  BVH_Vec2i yw() const;
  BVH_Vec2i wy() const;
  BVH_Vec2i zw() const;
  BVH_Vec2i wz() const;
  BVH_Vec3i xyz() const;
  BVH_Vec3i xzy() const;
  BVH_Vec3i yxz() const;
  BVH_Vec3i yzx() const;
  BVH_Vec3i zyx() const;
  BVH_Vec3i zxy() const;
  BVH_Vec3i xyw() const;
  BVH_Vec3i xwy() const;
  BVH_Vec3i yxw() const;
  BVH_Vec3i ywx() const;
  BVH_Vec3i wyx() const;
  BVH_Vec3i wxy() const;
  BVH_Vec3i xzw() const;
  BVH_Vec3i xwz() const;
  BVH_Vec3i zxw() const;
  BVH_Vec3i zwx() const;
  BVH_Vec3i wzx() const;
  BVH_Vec3i wxz() const;
  BVH_Vec3i yzw() const;
  BVH_Vec3i ywz() const;
  BVH_Vec3i zyw() const;
  BVH_Vec3i zwy() const;
  BVH_Vec3i wzy() const;
  BVH_Vec3i wyz() const;
  BVH_Vec3i rgb() const;
  BVH_Vec3i rbg() const;
  BVH_Vec3i grb() const;
  BVH_Vec3i gbr() const;
  BVH_Vec3i bgr() const;
  BVH_Vec3i brg() const;
  int& x();
  int& r();
  int& y();
  int& g();
  int& z();
  int& b();
  int& w();
  int& a();
  bool IsEqual(const BVH_Vec4i& theOther) const;
  NetOcc_Address< const int* > GetData() const;
  NetOcc_Address< int* > ChangeData();
  void Multiply(int theFactor);
  BVH_Vec4i Multiplied(int theFactor) const;
  BVH_Vec4i cwiseMin(const BVH_Vec4i& theVec) const;
  BVH_Vec4i cwiseMax(const BVH_Vec4i& theVec) const;
  BVH_Vec4i cwiseAbs() const;
  int maxComp() const;
  int minComp() const;
  int Dot(const BVH_Vec4i& theOther) const;
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class NCollection_Mat3_float {
public:
  NCollection_Mat3_float();
  static NCollection_Mat3_float Identity();
  static NCollection_Mat3_float Zero();
  float GetValue(size_t theRow, size_t theCol) const;
  float& ChangeValue(size_t theRow, size_t theCol);
  void SetValue(size_t theRow, size_t theCol, float theValue);
  BVH_Vec3f GetRow(size_t theRow) const;
  void SetRow(size_t theRow, const BVH_Vec3f& theVec);
  BVH_Vec3f GetColumn(size_t theCol) const;
  void SetColumn(size_t theCol, const BVH_Vec3f& theVec);
  BVH_Vec3f GetDiagonal() const;
  void SetDiagonal(const BVH_Vec3f& theVec);
  void InitZero();
  bool IsZero() const;
  void InitIdentity();
  bool IsIdentity() const;
  bool IsEqual(const NCollection_Mat3_float& theOther) const;
  NetOcc_Address< const float* > GetData() const;
  NetOcc_Address< float* > ChangeData();
  static NCollection_Mat3_float Multiply(const NCollection_Mat3_float& theMatA, const NCollection_Mat3_float& theMatB);
  NCollection_Mat3_float Multiplied(const NCollection_Mat3_float& theMat) const;
  void Multiply(float theFactor);
  NCollection_Mat3_float Multiplied(float theFactor) const;
  void Divide(float theFactor);
  NCollection_Mat3_float Divided(float theScalar) const;
  void Add(const NCollection_Mat3_float& theMat);
  void Subtract(const NCollection_Mat3_float& theMat);
  NCollection_Mat3_float Added(const NCollection_Mat3_float& theMat) const;
  NCollection_Mat3_float Subtracted(const NCollection_Mat3_float& theMat) const;
  NCollection_Mat3_float Negated() const;
  NCollection_Mat3_float Transposed() const;
  void Transpose();
  float Determinant() const;
  NCollection_Mat3_float Adjoint() const;
  bool Inverted(NCollection_Mat3_float& theInv, float& theDet) const;
  bool Inverted(NCollection_Mat3_float& theInv) const;
  NCollection_Mat3_float Inverted() const;
  static const NCollection_Mat3_float& Map(const float* theData);
  void DumpJson(std::ostream& theOStream, int arg1) const;
};

class BVH_Mat4f {
public:
  BVH_Mat4f();
  static size_t Rows();
  static size_t Cols();
  static BVH_Mat4f Identity();
  static BVH_Mat4f Zero();
  float GetValue(size_t theRow, size_t theCol) const;
  float& ChangeValue(size_t theRow, size_t theCol);
  void SetValue(size_t theRow, size_t theCol, float theValue);
  BVH_Vec4f GetRow(size_t theRow) const;
  void SetRow(size_t theRow, const BVH_Vec3f& theVec);
  void SetRow(size_t theRow, const BVH_Vec4f& theVec);
  BVH_Vec4f GetColumn(size_t theCol) const;
  void SetColumn(size_t theCol, const BVH_Vec3f& theVec);
  void SetColumn(size_t theCol, const BVH_Vec4f& theVec);
  BVH_Vec4f GetDiagonal() const;
  void SetDiagonal(const BVH_Vec3f& theVec);
  void SetDiagonal(const BVH_Vec4f& theVec);
  NCollection_Mat3_float GetMat3() const;
  void InitZero();
  bool IsZero() const;
  void InitIdentity();
  bool IsIdentity() const;
  bool IsEqual(const BVH_Mat4f& theOther) const;
  NetOcc_Address< const float* > GetData() const;
  NetOcc_Address< float* > ChangeData();
  static BVH_Mat4f Multiply(const BVH_Mat4f& theMatA, const BVH_Mat4f& theMatB);
  BVH_Mat4f Multiplied(const BVH_Mat4f& theMat) const;
  void Multiply(float theFactor);
  BVH_Mat4f Multiplied(float theFactor) const;
  void Divide(float theFactor);
  BVH_Mat4f Divided(float theScalar) const;
  void Add(const BVH_Mat4f& theMat);
  void Subtract(const BVH_Mat4f& theMat);
  BVH_Mat4f Added(const BVH_Mat4f& theMat) const;
  BVH_Mat4f Subtracted(const BVH_Mat4f& theMat) const;
  BVH_Mat4f Negated() const;
  void Translate(const BVH_Vec3f& theVec);
  BVH_Mat4f Transposed() const;
  void Transpose();
  bool Inverted(BVH_Mat4f& theOutMx, float& theDet) const;
  bool Inverted(BVH_Mat4f& theOutMx) const;
  BVH_Mat4f Inverted() const;
  float DeterminantMat3() const;
  BVH_Mat4f Adjoint() const;
  static const BVH_Mat4f& Map(const float* theData);
  void DumpJson(std::ostream& theOStream, int arg1) const;
};

class NCollection_String {
public:
  NCollection_String();
  NCollection_String(const char16_t* theCopyUtf16, int theLength = -1);
  NCollection_String(NetOcc_Address< const char32_t* > theCopyUtf32, int theLength = -1);
  NCollection_UtfIterator_char Iterator() const;
  int Size() const;
  int Length() const;
  char32_t GetChar(int theCharIndex) const;
  const char* GetCharBuffer(int theCharIndex) const;
  void FromLocale(const char* theString, int theLength = -1);
  bool IsEqual(const NCollection_String& theCompare) const;
  NCollection_String SubString(int theStart, int theEnd) const;
  const char* ToCString() const;
  NCollection_String ToUtf8() const;
  NCollection_UtfString_char16_t ToUtf16() const;
  NCollection_UtfString_char32_t ToUtf32() const;
  bool ToLocale(char* theBuffer, int theSizeBytes) const;
  bool IsEmpty() const;
  void Clear();
  const NCollection_String& Assign(const NCollection_String& theOther);
  void Swap(NCollection_String& theOther);
};

class Graphic3d_Vec2ub {
public:
  Graphic3d_Vec2ub();
  Graphic3d_Vec2ub(unsigned char theXY);
  Graphic3d_Vec2ub(unsigned char theX, unsigned char theY);
  static int Length();
  void SetValues(unsigned char theX, unsigned char theY);
  Graphic3d_Vec2ub xy() const;
  Graphic3d_Vec2ub yx() const;
  unsigned char& x();
  unsigned char& y();
  bool IsEqual(const Graphic3d_Vec2ub& theOther) const;
  NetOcc_Address< const unsigned char* > GetData() const;
  NetOcc_Address< unsigned char* > ChangeData();
  void Multiply(unsigned char theFactor);
  Graphic3d_Vec2ub Multiplied(unsigned char theFactor) const;
  Graphic3d_Vec2ub cwiseMin(const Graphic3d_Vec2ub& theVec) const;
  Graphic3d_Vec2ub cwiseMax(const Graphic3d_Vec2ub& theVec) const;
  Graphic3d_Vec2ub cwiseAbs() const;
  unsigned char maxComp() const;
  unsigned char minComp() const;
  unsigned char Dot(const Graphic3d_Vec2ub& theOther) const;
  unsigned char Modulus() const;
  unsigned char SquareModulus() const;
  static Graphic3d_Vec2ub DX();
  static Graphic3d_Vec2ub DY();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class Graphic3d_Vec3ub {
public:
  Graphic3d_Vec3ub();
  Graphic3d_Vec3ub(unsigned char theValue);
  Graphic3d_Vec3ub(unsigned char theX, unsigned char theY, unsigned char theZ);
  Graphic3d_Vec3ub(const Graphic3d_Vec2ub& theVec2, unsigned char theZ = Element_t(0));
  static int Length();
  void SetValues(unsigned char theX, unsigned char theY, unsigned char theZ);
  void SetValues(const Graphic3d_Vec2ub& theVec2, unsigned char theZ);
  Graphic3d_Vec2ub xy() const;
  Graphic3d_Vec2ub yx() const;
  Graphic3d_Vec2ub xz() const;
  Graphic3d_Vec2ub zx() const;
  Graphic3d_Vec2ub yz() const;
  Graphic3d_Vec2ub zy() const;
  Graphic3d_Vec3ub xyz() const;
  Graphic3d_Vec3ub xzy() const;
  Graphic3d_Vec3ub yxz() const;
  Graphic3d_Vec3ub yzx() const;
  Graphic3d_Vec3ub zyx() const;
  Graphic3d_Vec3ub zxy() const;
  unsigned char& x();
  unsigned char& r();
  unsigned char& y();
  unsigned char& g();
  unsigned char& z();
  unsigned char& b();
  bool IsEqual(const Graphic3d_Vec3ub& theOther) const;
  NetOcc_Address< const unsigned char* > GetData() const;
  NetOcc_Address< unsigned char* > ChangeData();
  void Multiply(unsigned char theFactor);
  Graphic3d_Vec3ub Multiplied(unsigned char theFactor) const;
  Graphic3d_Vec3ub cwiseMin(const Graphic3d_Vec3ub& theVec) const;
  Graphic3d_Vec3ub cwiseMax(const Graphic3d_Vec3ub& theVec) const;
  Graphic3d_Vec3ub cwiseAbs() const;
  unsigned char maxComp() const;
  unsigned char minComp() const;
  unsigned char Dot(const Graphic3d_Vec3ub& theOther) const;
  unsigned char Modulus() const;
  unsigned char SquareModulus() const;
  void Normalize();
  Graphic3d_Vec3ub Normalized() const;
  static Graphic3d_Vec3ub Cross(const Graphic3d_Vec3ub& theVec1, const Graphic3d_Vec3ub& theVec2);
  static Graphic3d_Vec3ub GetLERP(const Graphic3d_Vec3ub& theFrom, const Graphic3d_Vec3ub& theTo, unsigned char theT);
  static Graphic3d_Vec3ub DX();
  static Graphic3d_Vec3ub DY();
  static Graphic3d_Vec3ub DZ();
  void DumpJson(std::ostream& theOStream, int theDepth = -1) const;
};

class NCollection_UtfIterator_char {
public:
  NCollection_UtfIterator_char(const char* theString);
  void Init(const char* theString);
  bool IsValid() const;
  const char* BufferHere() const;
  NetOcc_Address< char* > ChangeBufferHere();
  const char* BufferNext() const;
  int Index() const;
  int AdvanceBytesUtf8() const;
  int AdvanceBytesUtf16() const;
  int AdvanceCodeUnitsUtf16() const;
  int AdvanceBytesUtf32() const;
  NetOcc_Address< char* > GetUtf8(char* theBuffer) const;
  NetOcc_Address< char16_t* > GetUtf16(char16_t* theBuffer) const;
  NetOcc_Address< char32_t* > GetUtf32(NetOcc_Address< char32_t* > theBuffer) const;
};

class NCollection_UtfString_char16_t {
public:
  NCollection_UtfString_char16_t();
  NCollection_UtfString_char16_t(const char16_t* theCopyUtf16, int theLength = -1);
  NCollection_UtfString_char16_t(NetOcc_Address< const char32_t* > theCopyUtf32, int theLength = -1);
  NCollection_UtfIterator_char16_t Iterator() const;
  int Size() const;
  int Length() const;
  char32_t GetChar(int theCharIndex) const;
  const char16_t* GetCharBuffer(int theCharIndex) const;
  void FromLocale(const char* theString, int theLength = -1);
  bool IsEqual(const NCollection_UtfString_char16_t& theCompare) const;
  NCollection_UtfString_char16_t SubString(int theStart, int theEnd) const;
  const char16_t* ToCString() const;
  NCollection_String ToUtf8() const;
  NCollection_UtfString_char16_t ToUtf16() const;
  NCollection_UtfString_char32_t ToUtf32() const;
  bool ToLocale(char* theBuffer, int theSizeBytes) const;
  bool IsEmpty() const;
  void Clear();
  const NCollection_UtfString_char16_t& Assign(const NCollection_UtfString_char16_t& theOther);
  void Swap(NCollection_UtfString_char16_t& theOther);
};

class NCollection_UtfString_char32_t {
public:
  NCollection_UtfString_char32_t();
  NCollection_UtfString_char32_t(const char16_t* theCopyUtf16, int theLength = -1);
  NCollection_UtfString_char32_t(NetOcc_Address< const char32_t* > theCopyUtf32, int theLength = -1);
  NCollection_UtfIterator_char32_t Iterator() const;
  int Size() const;
  int Length() const;
  char32_t GetChar(int theCharIndex) const;
  NetOcc_Address< const char32_t* > GetCharBuffer(int theCharIndex) const;
  void FromLocale(const char* theString, int theLength = -1);
  bool IsEqual(const NCollection_UtfString_char32_t& theCompare) const;
  NCollection_UtfString_char32_t SubString(int theStart, int theEnd) const;
  NetOcc_Address< const char32_t* > ToCString() const;
  NCollection_String ToUtf8() const;
  NCollection_UtfString_char16_t ToUtf16() const;
  NCollection_UtfString_char32_t ToUtf32() const;
  bool ToLocale(char* theBuffer, int theSizeBytes) const;
  bool IsEmpty() const;
  void Clear();
  const NCollection_UtfString_char32_t& Assign(const NCollection_UtfString_char32_t& theOther);
  void Swap(NCollection_UtfString_char32_t& theOther);
};

class NCollection_UtfIterator_char16_t {
public:
  NCollection_UtfIterator_char16_t(const char16_t* theString);
  void Init(const char16_t* theString);
  bool IsValid() const;
  const char16_t* BufferHere() const;
  NetOcc_Address< char16_t* > ChangeBufferHere();
  const char16_t* BufferNext() const;
  int Index() const;
  int AdvanceBytesUtf8() const;
  int AdvanceBytesUtf16() const;
  int AdvanceCodeUnitsUtf16() const;
  int AdvanceBytesUtf32() const;
  NetOcc_Address< char* > GetUtf8(char* theBuffer) const;
  NetOcc_Address< char16_t* > GetUtf16(char16_t* theBuffer) const;
  NetOcc_Address< char32_t* > GetUtf32(NetOcc_Address< char32_t* > theBuffer) const;
};

class NCollection_UtfIterator_char32_t {
public:
  NCollection_UtfIterator_char32_t(NetOcc_Address< const char32_t* > theString);
  void Init(NetOcc_Address< const char32_t* > theString);
  bool IsValid() const;
  NetOcc_Address< const char32_t* > BufferHere() const;
  NetOcc_Address< char32_t* > ChangeBufferHere();
  NetOcc_Address< const char32_t* > BufferNext() const;
  int Index() const;
  int AdvanceBytesUtf8() const;
  int AdvanceBytesUtf16() const;
  int AdvanceCodeUnitsUtf16() const;
  int AdvanceBytesUtf32() const;
  NetOcc_Address< char* > GetUtf8(char* theBuffer) const;
  NetOcc_Address< char16_t* > GetUtf16(char16_t* theBuffer) const;
  NetOcc_Address< char32_t* > GetUtf32(NetOcc_Address< char32_t* > theBuffer) const;
};

class NCollection_SparseArray_int : public NCollection_SparseArrayBase {
public:
  NCollection_SparseArray_int(size_t theIncrement);
  void Assign(const NCollection_SparseArray_int& theOther);
  void Exchange(NCollection_SparseArray_int& theOther);
  void Clear();
  const int& Value(size_t theIndex) const;
  int& ChangeValue(size_t theIndex);
  int& SetValue(size_t theIndex, const int& theValue);
  bool UnsetValue(size_t theIndex);
  size_t Extent() const;
  bool IsEmpty() const;
  const int& Find(size_t theIndex) const;
  int& ChangeFind(size_t theIndex);
  int& Bind(size_t theIndex, const int& theValue);
  bool IsBound(size_t theIndex) const;
  bool UnBind(size_t theIndex);
};

// namespace NCollection_Primes: static class NCollection_Primes
%rename(NCollection_Primes) NCollection_Primes::NetOcc_NCollection_Primes;
%inline %{
namespace NCollection_Primes {
struct NetOcc_NCollection_Primes {
  static size_t NextPrimeForMap(size_t theN) { return NCollection_Primes::NextPrimeForMap(theN); }
};
}
%}
