// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* RWHeaderSection: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module RWHeaderSectionModule

%include "NetOcc.i"

%{
#include <RWHeaderSection_module.hxx>
%}

%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "NCollection.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "GeomAbs.i"
%import "gp.i"
%import "TColgp.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "GeomEval.i"
%import "Geom.i"
%import "TopAbs.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "TopLoc.i"
%import "TopoDS.i"
%import "BRepAdaptor.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "IntCurvesFace.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "BVH.i"
%import "Bnd.i"
%import "TopTools.i"
%import "Resource.i"
%import "CDM.i"
%import "LDOM.i"
%import "Storage.i"
%import "PCDM.i"
%import "CDF.i"
%import "TDF.i"
%import "TDocStd.i"
%import "DE.i"
%import "IFGraph.i"
%import "IFSelect.i"
%import "TColGeom.i"
%import "ShapeExtend.i"
%import "TShort.i"
%import "Poly.i"
%import "BRep.i"
%import "BRepTools.i"
%import "ShapeBuild.i"
%import "ShapeProcess.i"
%import "XSAlgo.i"
%import "Transfer.i"
%import "XSControl.i"
%import "MoniTool.i"
%import "Interface.i"
%import "StepData.i"
%import "HeaderSection.i"
%netocc_csimports(using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.GeomAbs; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.TopAbs; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.TopLoc; using OCC.Core.TopoDS; using OCC.Core.BRepAdaptor; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.IntCurvesFace; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.BVH; using OCC.Core.Bnd; using OCC.Core.TopTools; using OCC.Core.Resource; using OCC.Core.CDM; using OCC.Core.LDOM; using OCC.Core.Storage; using OCC.Core.PCDM; using OCC.Core.CDF; using OCC.Core.TDF; using OCC.Core.TDocStd; using OCC.Core.DE; using OCC.Core.IFGraph; using OCC.Core.IFSelect; using OCC.Core.TColGeom; using OCC.Core.ShapeExtend; using OCC.Core.TShort; using OCC.Core.Poly; using OCC.Core.BRep; using OCC.Core.BRepTools; using OCC.Core.ShapeBuild; using OCC.Core.ShapeProcess; using OCC.Core.XSAlgo; using OCC.Core.Transfer; using OCC.Core.XSControl; using OCC.Core.MoniTool; using OCC.Core.Interface; using OCC.Core.StepData; using OCC.Core.HeaderSection;)

%occt_valueclass(RWHeaderSection)
%occt_transient(RWHeaderSection_GeneralModule)
%occt_valueclass(RWHeaderSection_RWFileDescription)
%occt_valueclass(RWHeaderSection_RWFileName)
%occt_valueclass(RWHeaderSection_RWFileSchema)
%occt_transient(RWHeaderSection_ReadWriteModule)

class RWHeaderSection {
public:
  RWHeaderSection();
  static void Init();
};

class RWHeaderSection_GeneralModule : public StepData_GeneralModule {
public:
  RWHeaderSection_GeneralModule();
  void FillSharedCase(int CN, const opencascade::handle<Standard_Transient>& ent, Interface_EntityIterator& iter) const;
  void CheckCase(int CN, const opencascade::handle<Standard_Transient>& ent, const Interface_ShareTool& shares, opencascade::handle<Interface_Check>& ach) const;
  void CopyCase(int CN, const opencascade::handle<Standard_Transient>& entfrom, const opencascade::handle<Standard_Transient>& entto, Interface_CopyTool& TC) const;
  bool NewVoid(int CN, opencascade::handle<Standard_Transient>& ent) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class RWHeaderSection_RWFileDescription {
public:
  RWHeaderSection_RWFileDescription();
  void ReadStep(const opencascade::handle<StepData_StepReaderData>& data, int num, opencascade::handle<Interface_Check>& ach, const opencascade::handle<HeaderSection_FileDescription>& ent) const;
  void WriteStep(StepData_StepWriter& SW, const opencascade::handle<HeaderSection_FileDescription>& ent) const;
};

class RWHeaderSection_RWFileName {
public:
  RWHeaderSection_RWFileName();
  void ReadStep(const opencascade::handle<StepData_StepReaderData>& data, int num, opencascade::handle<Interface_Check>& ach, const opencascade::handle<HeaderSection_FileName>& ent) const;
  void WriteStep(StepData_StepWriter& SW, const opencascade::handle<HeaderSection_FileName>& ent) const;
};

class RWHeaderSection_RWFileSchema {
public:
  RWHeaderSection_RWFileSchema();
  void ReadStep(const opencascade::handle<StepData_StepReaderData>& data, int num, opencascade::handle<Interface_Check>& ach, const opencascade::handle<HeaderSection_FileSchema>& ent) const;
  void WriteStep(StepData_StepWriter& SW, const opencascade::handle<HeaderSection_FileSchema>& ent) const;
};

class RWHeaderSection_ReadWriteModule : public StepData_ReadWriteModule {
public:
  RWHeaderSection_ReadWriteModule();
  int CaseStep(const TCollection_AsciiString& atype) const;
  int CaseStep(const NCollection_Sequence<TCollection_AsciiString>& types) const;
  bool IsComplex(int CN) const;
  const std::string_view& StepType(int CN) const;
  void ReadStep(int CN, const opencascade::handle<StepData_StepReaderData>& data, int num, opencascade::handle<Interface_Check>& ach, const opencascade::handle<Standard_Transient>& ent) const;
  void WriteStep(int CN, StepData_StepWriter& SW, const opencascade::handle<Standard_Transient>& ent) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};
