// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* RWStepRepr: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module RWStepReprModule

%include "NetOcc.i"

%{
#include <RWStepRepr_module.hxx>
%}

%netocc_csimports()
