// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* ShapeUpgrade: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module ShapeUpgradeModule

%include "NetOcc.i"

%{
#include <ShapeUpgrade_module.hxx>
%}

%import "GeomAbs.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "gp.i"
%import "TColgp.i"
%import "GeomEval.i"
%import "Geom.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "TopAbs.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "TopLoc.i"
%import "TopoDS.i"
%import "BRepAdaptor.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "IntCurvesFace.i"
%import "TopTools.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "BVH.i"
%import "Bnd.i"
%import "TShort.i"
%import "Poly.i"
%import "BRep.i"
%import "BRepTools.i"
%import "TColGeom.i"
%import "ShapeExtend.i"
%import "ShapeAnalysis.i"
%import "ShapeBuild.i"
%import "TColGeom2d.i"
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.TopAbs; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.TopLoc; using OCC.Core.TopoDS; using OCC.Core.BRepAdaptor; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.IntCurvesFace; using OCC.Core.TopTools; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.BVH; using OCC.Core.Bnd; using OCC.Core.TShort; using OCC.Core.Poly; using OCC.Core.BRep; using OCC.Core.BRepTools; using OCC.Core.TColGeom; using OCC.Core.ShapeExtend; using OCC.Core.ShapeAnalysis; using OCC.Core.ShapeBuild; using OCC.Core.TColGeom2d;)

%occt_valueclass(ShapeUpgrade)
%occt_transient(ShapeUpgrade_Tool)
%occt_transient(ShapeUpgrade_EdgeDivide)
%occt_transient(ShapeUpgrade_ClosedEdgeDivide)
%occt_transient(ShapeUpgrade_FaceDivide)
%occt_transient(ShapeUpgrade_ClosedFaceDivide)
%occt_transient(ShapeUpgrade_SplitCurve)
%occt_transient(ShapeUpgrade_SplitCurve2d)
%occt_transient(ShapeUpgrade_ConvertCurve2dToBezier)
%occt_transient(ShapeUpgrade_SplitCurve3d)
%occt_transient(ShapeUpgrade_ConvertCurve3dToBezier)
%occt_transient(ShapeUpgrade_SplitSurface)
%occt_transient(ShapeUpgrade_ConvertSurfaceToBezierBasis)
%occt_transient(ShapeUpgrade_FaceDivideArea)
%occt_transient(ShapeUpgrade_FixSmallCurves)
%occt_transient(ShapeUpgrade_FixSmallBezierCurves)
%occt_transient(ShapeUpgrade_RemoveInternalWires)
%occt_transient(ShapeUpgrade_RemoveLocations)
%occt_valueclass(ShapeUpgrade_ShapeDivide)
%occt_valueclass(ShapeUpgrade_ShapeConvertToBezier)
%occt_valueclass(ShapeUpgrade_ShapeDivideAngle)
%nodefaultctor ShapeUpgrade_ShapeDivideAngle;
%feature("valuewrapper") ShapeUpgrade_ShapeDivideAngle;
%occt_valueclass(ShapeUpgrade_ShapeDivideArea)
%occt_valueclass(ShapeUpgrade_ShapeDivideClosed)
%nodefaultctor ShapeUpgrade_ShapeDivideClosed;
%feature("valuewrapper") ShapeUpgrade_ShapeDivideClosed;
%occt_valueclass(ShapeUpgrade_ShapeDivideClosedEdges)
%nodefaultctor ShapeUpgrade_ShapeDivideClosedEdges;
%feature("valuewrapper") ShapeUpgrade_ShapeDivideClosedEdges;
%occt_valueclass(ShapeUpgrade_ShapeDivideContinuity)
%occt_valueclass(ShapeUpgrade_ShellSewing)
%occt_transient(ShapeUpgrade_SplitCurve2dContinuity)
%occt_transient(ShapeUpgrade_SplitCurve3dContinuity)
%occt_transient(ShapeUpgrade_SplitSurfaceAngle)
%nodefaultctor ShapeUpgrade_SplitSurfaceAngle;
%feature("valuewrapper") ShapeUpgrade_SplitSurfaceAngle;
%occt_transient(ShapeUpgrade_SplitSurfaceArea)
%occt_transient(ShapeUpgrade_SplitSurfaceContinuity)
%occt_transient(ShapeUpgrade_UnifySameDomain)
%occt_transient(ShapeUpgrade_WireDivide)

class ShapeUpgrade {
public:
  ShapeUpgrade();
  static bool C0BSplineToSequenceOfC1BSplineCurve(const opencascade::handle<Geom_BSplineCurve>& BS, opencascade::handle<NCollection_HSequence<opencascade::handle<Geom_BoundedCurve>>>& seqBS);
  static bool C0BSplineToSequenceOfC1BSplineCurve(const opencascade::handle<Geom2d_BSplineCurve>& BS, opencascade::handle<NCollection_HSequence<opencascade::handle<Geom2d_BoundedCurve>>>& seqBS);
};

class ShapeUpgrade_Tool : public Standard_Transient {
public:
  ShapeUpgrade_Tool();
  void Set(const opencascade::handle<ShapeUpgrade_Tool>& tool);
  void SetContext(const opencascade::handle<ShapeBuild_ReShape>& context);
  opencascade::handle<ShapeBuild_ReShape> Context() const;
  void SetPrecision(double preci);
  double Precision() const;
  void SetMinTolerance(double mintol);
  double MinTolerance() const;
  void SetMaxTolerance(double maxtol);
  double MaxTolerance() const;
  double LimitTolerance(double toler) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_EdgeDivide : public ShapeUpgrade_Tool {
public:
  ShapeUpgrade_EdgeDivide();
  void Clear();
  void SetFace(const TopoDS_Face& F);
  bool Compute(const TopoDS_Edge& E);
  bool HasCurve2d() const;
  bool HasCurve3d() const;
  opencascade::handle<NCollection_HSequence<double>> Knots2d() const;
  opencascade::handle<NCollection_HSequence<double>> Knots3d() const;
  void SetSplitCurve2dTool(const opencascade::handle<ShapeUpgrade_SplitCurve2d>& splitCurve2dTool);
  void SetSplitCurve3dTool(const opencascade::handle<ShapeUpgrade_SplitCurve3d>& splitCurve3dTool);
  opencascade::handle<ShapeUpgrade_SplitCurve2d> GetSplitCurve2dTool() const;
  opencascade::handle<ShapeUpgrade_SplitCurve3d> GetSplitCurve3dTool() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_ClosedEdgeDivide : public ShapeUpgrade_EdgeDivide {
public:
  ShapeUpgrade_ClosedEdgeDivide();
  bool Compute(const TopoDS_Edge& anEdge);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_FaceDivide : public ShapeUpgrade_Tool {
public:
  ShapeUpgrade_FaceDivide();
  ShapeUpgrade_FaceDivide(const TopoDS_Face& F);
  void Init(const TopoDS_Face& F);
  void SetSurfaceSegmentMode(bool Segment);
  bool Perform(double theArea = 0.);
  bool SplitSurface(double theArea = 0.);
  bool SplitCurves();
  TopoDS_Shape Result() const;
  bool Status(ShapeExtend_Status status) const;
  void SetSplitSurfaceTool(const opencascade::handle<ShapeUpgrade_SplitSurface>& splitSurfaceTool);
  void SetWireDivideTool(const opencascade::handle<ShapeUpgrade_WireDivide>& wireDivideTool);
  opencascade::handle<ShapeUpgrade_SplitSurface> GetSplitSurfaceTool() const;
  opencascade::handle<ShapeUpgrade_WireDivide> GetWireDivideTool() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_ClosedFaceDivide : public ShapeUpgrade_FaceDivide {
public:
  ShapeUpgrade_ClosedFaceDivide();
  ShapeUpgrade_ClosedFaceDivide(const TopoDS_Face& F);
  bool SplitSurface(double theArea = 0.);
  void SetNbSplitPoints(int num);
  int GetNbSplitPoints() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_SplitCurve : public Standard_Transient {
public:
  ShapeUpgrade_SplitCurve();
  void Init(double First, double Last);
  void SetSplitValues(const opencascade::handle<NCollection_HSequence<double>>& SplitValues);
  void Build(bool Segment);
  const opencascade::handle<NCollection_HSequence<double>>& SplitValues() const;
  void Compute();
  void Perform(bool Segment = true);
  bool Status(ShapeExtend_Status status) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_SplitCurve2d : public ShapeUpgrade_SplitCurve {
public:
  ShapeUpgrade_SplitCurve2d();
  void Init(const opencascade::handle<Geom2d_Curve>& C);
  void Init(const opencascade::handle<Geom2d_Curve>& C, double First, double Last);
  void Build(bool Segment);
  const opencascade::handle<NCollection_HArray1<opencascade::handle<Geom2d_Curve>>>& GetCurves() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_ConvertCurve2dToBezier : public ShapeUpgrade_SplitCurve2d {
public:
  ShapeUpgrade_ConvertCurve2dToBezier();
  void Compute();
  void Build(bool Segment);
  opencascade::handle<NCollection_HSequence<double>> SplitParams() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_SplitCurve3d : public ShapeUpgrade_SplitCurve {
public:
  ShapeUpgrade_SplitCurve3d();
  void Init(const opencascade::handle<Geom_Curve>& C);
  void Init(const opencascade::handle<Geom_Curve>& C, double First, double Last);
  void Build(bool Segment);
  const opencascade::handle<NCollection_HArray1<opencascade::handle<Geom_Curve>>>& GetCurves() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_ConvertCurve3dToBezier : public ShapeUpgrade_SplitCurve3d {
public:
  ShapeUpgrade_ConvertCurve3dToBezier();
  void SetLineMode(bool mode);
  bool GetLineMode() const;
  void SetCircleMode(bool mode);
  bool GetCircleMode() const;
  void SetConicMode(bool mode);
  bool GetConicMode() const;
  void Compute();
  void Build(bool Segment);
  opencascade::handle<NCollection_HSequence<double>> SplitParams() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_SplitSurface : public Standard_Transient {
public:
  ShapeUpgrade_SplitSurface();
  void Init(const opencascade::handle<Geom_Surface>& S);
  void Init(const opencascade::handle<Geom_Surface>& S, double UFirst, double ULast, double VFirst, double VLast, double theArea = 0.);
  void SetUSplitValues(const opencascade::handle<NCollection_HSequence<double>>& UValues);
  void SetVSplitValues(const opencascade::handle<NCollection_HSequence<double>>& VValues);
  void Build(bool Segment);
  void Compute(bool Segment = true);
  void Perform(bool Segment = true);
  const opencascade::handle<NCollection_HSequence<double>>& USplitValues() const;
  const opencascade::handle<NCollection_HSequence<double>>& VSplitValues() const;
  bool Status(ShapeExtend_Status status) const;
  const opencascade::handle<ShapeExtend_CompositeSurface>& ResSurfaces() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_ConvertSurfaceToBezierBasis : public ShapeUpgrade_SplitSurface {
public:
  ShapeUpgrade_ConvertSurfaceToBezierBasis();
  void Build(bool Segment);
  void Compute(bool Segment);
  opencascade::handle<ShapeExtend_CompositeSurface> Segments() const;
  void SetPlaneMode(bool mode);
  bool GetPlaneMode() const;
  void SetRevolutionMode(bool mode);
  bool GetRevolutionMode() const;
  void SetExtrusionMode(bool mode);
  bool GetExtrusionMode() const;
  void SetBSplineMode(bool mode);
  bool GetBSplineMode() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_FaceDivideArea : public ShapeUpgrade_FaceDivide {
public:
  ShapeUpgrade_FaceDivideArea();
  ShapeUpgrade_FaceDivideArea(const TopoDS_Face& F);
  bool Perform(double theArea = 0.);
  double& MaxArea();
  int& NbParts();
  void SetNumbersUVSplits(int theNbUsplits, int theNbVsplits);
  void SetSplittingByNumber(bool theIsSplittingByNumber);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_FixSmallCurves : public ShapeUpgrade_Tool {
public:
  ShapeUpgrade_FixSmallCurves();
  void Init(const TopoDS_Edge& theEdge, const TopoDS_Face& theFace);
  bool Approx(opencascade::handle<Geom_Curve>& Curve3d, opencascade::handle<Geom2d_Curve>& Curve2d, opencascade::handle<Geom2d_Curve>& Curve2dR, double& First, double& Last);
  void SetSplitCurve3dTool(const opencascade::handle<ShapeUpgrade_SplitCurve3d>& splitCurve3dTool);
  void SetSplitCurve2dTool(const opencascade::handle<ShapeUpgrade_SplitCurve2d>& splitCurve2dTool);
  bool Status(ShapeExtend_Status status) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_FixSmallBezierCurves : public ShapeUpgrade_FixSmallCurves {
public:
  ShapeUpgrade_FixSmallBezierCurves();
  bool Approx(opencascade::handle<Geom_Curve>& Curve3d, opencascade::handle<Geom2d_Curve>& Curve2d, opencascade::handle<Geom2d_Curve>& Curve2dR, double& First, double& Last);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_RemoveInternalWires : public ShapeUpgrade_Tool {
public:
  ShapeUpgrade_RemoveInternalWires();
  ShapeUpgrade_RemoveInternalWires(const TopoDS_Shape& theShape);
  void Init(const TopoDS_Shape& theShape);
  bool Perform();
  bool Perform(const NCollection_Sequence<TopoDS_Shape>& theSeqShapes);
  TopoDS_Shape GetResult() const;
  double& MinArea();
  bool& RemoveFaceMode();
  const NCollection_Sequence<TopoDS_Shape>& RemovedFaces() const;
  const NCollection_Sequence<TopoDS_Shape>& RemovedWires() const;
  bool Status(ShapeExtend_Status theStatus) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_RemoveLocations : public Standard_Transient {
public:
  ShapeUpgrade_RemoveLocations();
  bool Remove(const TopoDS_Shape& theShape);
  TopoDS_Shape GetResult() const;
  void SetRemoveLevel(TopAbs_ShapeEnum theLevel);
  TopAbs_ShapeEnum RemoveLevel() const;
  TopoDS_Shape ModifiedShape(const TopoDS_Shape& theInitShape) const;
  const NCollection_DataMap<TopoDS_Shape, TopoDS_Shape, TopTools_ShapeMapHasher>& GetModifiedShapesMap() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_ShapeDivide {
public:
  ShapeUpgrade_ShapeDivide();
  ShapeUpgrade_ShapeDivide(const TopoDS_Shape& S);
  void Init(const TopoDS_Shape& S);
  void SetPrecision(double Prec);
  void SetMaxTolerance(double maxtol);
  void SetMinTolerance(double mintol);
  void SetSurfaceSegmentMode(bool Segment);
  bool Perform(bool newContext = true);
  TopoDS_Shape Result() const;
  opencascade::handle<ShapeBuild_ReShape> GetContext() const;
  void SetContext(const opencascade::handle<ShapeBuild_ReShape>& context);
  void SetMsgRegistrator(const opencascade::handle<ShapeExtend_BasicMsgRegistrator>& msgreg);
  opencascade::handle<ShapeExtend_BasicMsgRegistrator> MsgRegistrator() const;
  void SendMsg(const TopoDS_Shape& shape, const Message_Msg& message, Message_Gravity gravity = Message_Info) const;
  bool Status(ShapeExtend_Status status) const;
  void SetSplitFaceTool(const opencascade::handle<ShapeUpgrade_FaceDivide>& splitFaceTool);
  void SetEdgeMode(int aEdgeMode);
};

class ShapeUpgrade_ShapeConvertToBezier : public ShapeUpgrade_ShapeDivide {
public:
  ShapeUpgrade_ShapeConvertToBezier();
  ShapeUpgrade_ShapeConvertToBezier(const TopoDS_Shape& S);
  void Set2dConversion(bool mode);
  bool Get2dConversion() const;
  void Set3dConversion(bool mode);
  bool Get3dConversion() const;
  void SetSurfaceConversion(bool mode);
  bool GetSurfaceConversion() const;
  void Set3dLineConversion(bool mode);
  bool Get3dLineConversion() const;
  void Set3dCircleConversion(bool mode);
  bool Get3dCircleConversion() const;
  void Set3dConicConversion(bool mode);
  bool Get3dConicConversion() const;
  void SetPlaneMode(bool mode);
  bool GetPlaneMode() const;
  void SetRevolutionMode(bool mode);
  bool GetRevolutionMode() const;
  void SetExtrusionMode(bool mode);
  bool GetExtrusionMode() const;
  void SetBSplineMode(bool mode);
  bool GetBSplineMode() const;
  bool Perform(bool newContext = true);
};

class ShapeUpgrade_ShapeDivideAngle : public ShapeUpgrade_ShapeDivide {
public:
  ShapeUpgrade_ShapeDivideAngle(double MaxAngle);
  ShapeUpgrade_ShapeDivideAngle(double MaxAngle, const TopoDS_Shape& S);
  void InitTool(double MaxAngle);
  void SetMaxAngle(double MaxAngle);
  double MaxAngle() const;
};

class ShapeUpgrade_ShapeDivideArea : public ShapeUpgrade_ShapeDivide {
public:
  ShapeUpgrade_ShapeDivideArea();
  ShapeUpgrade_ShapeDivideArea(const TopoDS_Shape& S);
  double& MaxArea();
  int& NbParts();
  void SetNumbersUVSplits(int theNbUsplits, int theNbVsplits);
  void SetSplittingByNumber(bool theIsSplittingByNumber);
};

class ShapeUpgrade_ShapeDivideClosed : public ShapeUpgrade_ShapeDivide {
public:
  ShapeUpgrade_ShapeDivideClosed(const TopoDS_Shape& S);
  void SetNbSplitPoints(int num);
};

class ShapeUpgrade_ShapeDivideClosedEdges : public ShapeUpgrade_ShapeDivide {
public:
  ShapeUpgrade_ShapeDivideClosedEdges(const TopoDS_Shape& S);
  void SetNbSplitPoints(int num);
};

class ShapeUpgrade_ShapeDivideContinuity : public ShapeUpgrade_ShapeDivide {
public:
  ShapeUpgrade_ShapeDivideContinuity();
  ShapeUpgrade_ShapeDivideContinuity(const TopoDS_Shape& S);
  void SetTolerance(double Tol);
  void SetTolerance2d(double Tol);
  void SetBoundaryCriterion(GeomAbs_Shape Criterion = GeomAbs_C1);
  void SetPCurveCriterion(GeomAbs_Shape Criterion = GeomAbs_C1);
  void SetSurfaceCriterion(GeomAbs_Shape Criterion = GeomAbs_C1);
};

class ShapeUpgrade_ShellSewing {
public:
  ShapeUpgrade_ShellSewing();
  TopoDS_Shape ApplySewing(const TopoDS_Shape& shape, double tol = 0.0);
};

class ShapeUpgrade_SplitCurve2dContinuity : public ShapeUpgrade_SplitCurve2d {
public:
  ShapeUpgrade_SplitCurve2dContinuity();
  void SetCriterion(GeomAbs_Shape Criterion);
  void SetTolerance(double Tol);
  void Compute();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_SplitCurve3dContinuity : public ShapeUpgrade_SplitCurve3d {
public:
  ShapeUpgrade_SplitCurve3dContinuity();
  void SetCriterion(GeomAbs_Shape Criterion);
  void SetTolerance(double Tol);
  void Compute();
  const opencascade::handle<Geom_Curve>& GetCurve() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_SplitSurfaceAngle : public ShapeUpgrade_SplitSurface {
public:
  ShapeUpgrade_SplitSurfaceAngle(double MaxAngle);
  void SetMaxAngle(double MaxAngle);
  double MaxAngle() const;
  void Compute(bool Segment);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_SplitSurfaceArea : public ShapeUpgrade_SplitSurface {
public:
  ShapeUpgrade_SplitSurfaceArea();
  int& NbParts();
  void SetSplittingIntoSquares(bool theIsSplittingIntoSquares);
  void SetNumbersUVSplits(int theNbUsplits, int theNbVsplits);
  void Compute(bool Segment = true);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_SplitSurfaceContinuity : public ShapeUpgrade_SplitSurface {
public:
  ShapeUpgrade_SplitSurfaceContinuity();
  void SetCriterion(GeomAbs_Shape Criterion);
  void SetTolerance(double Tol);
  void Compute(bool Segment);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_UnifySameDomain : public Standard_Transient {
public:
  ShapeUpgrade_UnifySameDomain();
  ShapeUpgrade_UnifySameDomain(const TopoDS_Shape& aShape, bool UnifyEdges = true, bool UnifyFaces = true, bool ConcatBSplines = false);
  void Initialize(const TopoDS_Shape& aShape, bool UnifyEdges = true, bool UnifyFaces = true, bool ConcatBSplines = false);
  void AllowInternalEdges(bool theValue);
  void KeepShape(const TopoDS_Shape& theShape);
  void KeepShapes(const NCollection_Map<TopoDS_Shape, TopTools_ShapeMapHasher>& theShapes);
  void SetSafeInputMode(bool theValue);
  void SetLinearTolerance(double theValue);
  void SetAngularTolerance(double theValue);
  void Build();
  const TopoDS_Shape& Shape() const;
  const opencascade::handle<BRepTools_History>& History() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class ShapeUpgrade_WireDivide : public ShapeUpgrade_Tool {
public:
  ShapeUpgrade_WireDivide();
  void Init(const TopoDS_Wire& W, const TopoDS_Face& F);
  void Init(const TopoDS_Wire& W, const opencascade::handle<Geom_Surface>& S);
  void Load(const TopoDS_Wire& W);
  void Load(const TopoDS_Edge& E);
  void SetFace(const TopoDS_Face& F);
  void SetSurface(const opencascade::handle<Geom_Surface>& S);
  void SetSurface(const opencascade::handle<Geom_Surface>& S, const TopLoc_Location& L);
  void Perform();
  const TopoDS_Wire& Wire() const;
  bool Status(ShapeExtend_Status status) const;
  void SetSplitCurve3dTool(const opencascade::handle<ShapeUpgrade_SplitCurve3d>& splitCurve3dTool);
  void SetSplitCurve2dTool(const opencascade::handle<ShapeUpgrade_SplitCurve2d>& splitCurve2dTool);
  void SetTransferParamTool(const opencascade::handle<ShapeAnalysis_TransferParameters>& TransferParam);
  void SetEdgeDivideTool(const opencascade::handle<ShapeUpgrade_EdgeDivide>& edgeDivideTool);
  opencascade::handle<ShapeUpgrade_EdgeDivide> GetEdgeDivideTool() const;
  opencascade::handle<ShapeAnalysis_TransferParameters> GetTransferParamTool();
  void SetEdgeMode(int EdgeMode);
  void SetFixSmallCurveTool(const opencascade::handle<ShapeUpgrade_FixSmallCurves>& FixSmallCurvesTool);
  opencascade::handle<ShapeUpgrade_FixSmallCurves> GetFixSmallCurveTool() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};
