// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* StdPersistent: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module StdPersistentModule

%include "NetOcc.i"

%{
#include <StdPersistent_module.hxx>
%}

%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "Storage.i"
%import "TDF.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "Resource.i"
%import "CDM.i"
%import "LDOM.i"
%import "PCDM.i"
%import "CDF.i"
%import "TDocStd.i"
%import "StdObjMgt.i"
%import "TDataStd.i"
%import "TFunction.i"
%import "StdLPersistent.i"
%import "gp.i"
%import "TopLoc.i"
%import "TopAbs.i"
%import "TopoDS.i"
%import "StdObject.i"
%import "GeomAbs.i"
%import "TColgp.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "GeomEval.i"
%import "Geom.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "BRepAdaptor.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "IntCurvesFace.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "BVH.i"
%import "Bnd.i"
%import "TopTools.i"
%import "TNaming.i"
%netocc_csimports(using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.Storage; using OCC.Core.TDF; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.Resource; using OCC.Core.CDM; using OCC.Core.LDOM; using OCC.Core.PCDM; using OCC.Core.CDF; using OCC.Core.TDocStd; using OCC.Core.StdObjMgt; using OCC.Core.TDataStd; using OCC.Core.TFunction; using OCC.Core.StdLPersistent; using OCC.Core.gp; using OCC.Core.TopLoc; using OCC.Core.TopAbs; using OCC.Core.TopoDS; using OCC.Core.StdObject; using OCC.Core.GeomAbs; using OCC.Core.TColgp; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.BRepAdaptor; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.IntCurvesFace; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.BVH; using OCC.Core.Bnd; using OCC.Core.TopTools; using OCC.Core.TNaming;)

%occt_valueclass(StdPersistent)
%occt_valueclass(StdPersistent_DataXtd)
%occt_transient(StdPersistent_DataXtd_Geometry)
%occt_transient(StdPersistent_DataXtd_Position)
%occt_transient(StdPersistent_DataXtd_Constraint)
%occt_transient(StdPersistent_DataXtd_PatternStd)
%occt_valueclass(StdPersistent_TopoDS)
%occt_valueclass(StdPersistent_HArray1)
%occt_valueclass(StdPersistent_Naming)
%occt_transient(StdPersistent_Naming_NamedShape)
%occt_transient(StdPersistent_Naming_Name)
%occt_transient(StdPersistent_Naming_Name_1)
%occt_transient(StdPersistent_Naming_Name_2)
%occt_transient(StdPersistent_Naming_Naming)
%occt_transient(StdPersistent_Naming_Naming_1)
%occt_valueclass(StdPersistent_PPrsStd)
%occt_transient(StdPersistent_PPrsStd_AISPresentation)
%occt_transient(StdPersistent_PPrsStd_AISPresentation_1)
%occt_valueclass(StdPersistent_TopLoc)
%occt_transient(StdPersistent_TopLoc_Datum3D)
%occt_transient(StdPersistent_TopLoc_ItemLocation)

class StdPersistent {
public:
  StdPersistent();
  static void BindTypes(StdObjMgt_MapOfInstantiators& theMap);
};

class StdPersistent_DataXtd {
public:
  StdPersistent_DataXtd();
};

class StdPersistent_DataXtd_Geometry : public StdObjMgt_Persistent {
public:
  StdPersistent_DataXtd_Geometry();
  void ImportAttribute();
};

class StdPersistent_DataXtd_Position : public StdObjMgt_Persistent {
public:
  StdPersistent_DataXtd_Position();
  void ImportAttribute();
};

class StdPersistent_DataXtd_Constraint : public Standard_Transient {
public:
  StdPersistent_DataXtd_Constraint();
  void Read(StdObjMgt_ReadData& theReadData);
  void Write(StdObjMgt_WriteData& theWriteData) const;
  void PChildren(NCollection_Sequence<opencascade::handle<StdObjMgt_Persistent>>& theChildren) const;
  const char* PName() const;
};

class StdPersistent_DataXtd_PatternStd : public Standard_Transient {
public:
  StdPersistent_DataXtd_PatternStd();
  void Read(StdObjMgt_ReadData& theReadData);
  void Write(StdObjMgt_WriteData& theWriteData);
  void PChildren(NCollection_Sequence<opencascade::handle<StdObjMgt_Persistent>>& theChildren) const;
  const char* PName() const;
};

class StdPersistent_TopoDS {
public:
  StdPersistent_TopoDS();
};

class StdPersistent_HArray1 {
public:
  StdPersistent_HArray1();
};

class StdPersistent_Naming {
public:
  StdPersistent_Naming();
};

class StdPersistent_Naming_NamedShape : public Standard_Transient {
public:
  StdPersistent_Naming_NamedShape();
  void Read(StdObjMgt_ReadData& theReadData);
  void Write(StdObjMgt_WriteData& theWriteData) const;
  void PChildren(NCollection_Sequence<opencascade::handle<StdObjMgt_Persistent>>& theChildren) const;
  const char* PName() const;
};

class StdPersistent_Naming_Name : public StdObjMgt_Persistent {
public:
  StdPersistent_Naming_Name();
  void Read(StdObjMgt_ReadData& theReadData);
  void Write(StdObjMgt_WriteData& theWriteData) const;
  void PChildren(NCollection_Sequence<opencascade::handle<StdObjMgt_Persistent>>& theChildren) const;
  const char* PName() const;
  void Import(TNaming_Name& theName, const opencascade::handle<TDF_Data>& theDF) const;
};

class StdPersistent_Naming_Name_1 : public StdPersistent_Naming_Name {
public:
  StdPersistent_Naming_Name_1();
  void Read(StdObjMgt_ReadData& theReadData);
  void Write(StdObjMgt_WriteData& theWriteData) const;
  void PChildren(NCollection_Sequence<opencascade::handle<StdObjMgt_Persistent>>& theChildren) const;
  const char* PName() const;
  void Import(TNaming_Name& theName, const opencascade::handle<TDF_Data>& theDF) const;
};

class StdPersistent_Naming_Name_2 : public StdPersistent_Naming_Name_1 {
public:
  StdPersistent_Naming_Name_2();
  void Read(StdObjMgt_ReadData& theReadData);
  void Write(StdObjMgt_WriteData& theWriteData) const;
  void PChildren(NCollection_Sequence<opencascade::handle<StdObjMgt_Persistent>>& theChildren) const;
  const char* PName() const;
  void Import(TNaming_Name& theName, const opencascade::handle<TDF_Data>& theDF) const;
};

class StdPersistent_Naming_Naming : public StdObjMgt_Persistent {
public:
  StdPersistent_Naming_Naming();
  void ImportAttribute();
};

class StdPersistent_Naming_Naming_1 : public StdPersistent_Naming_Naming {
public:
  StdPersistent_Naming_Naming_1();
  void ImportAttribute();
};

class StdPersistent_PPrsStd {
public:
  StdPersistent_PPrsStd();
};

class StdPersistent_PPrsStd_AISPresentation : public Standard_Transient {
public:
  StdPersistent_PPrsStd_AISPresentation();
  void Read(StdObjMgt_ReadData& theReadData);
  void Write(StdObjMgt_WriteData& theWriteData) const;
  void PChildren(NCollection_Sequence<opencascade::handle<StdObjMgt_Persistent>>& theChildren) const;
  const char* PName() const;
};

class StdPersistent_PPrsStd_AISPresentation_1 : public StdPersistent_PPrsStd_AISPresentation {
public:
  StdPersistent_PPrsStd_AISPresentation_1();
  void Read(StdObjMgt_ReadData& theReadData);
  void Write(StdObjMgt_WriteData& theWriteData);
  const char* PName() const;
};

class StdPersistent_TopLoc {
public:
  StdPersistent_TopLoc();
  static opencascade::handle<StdPersistent_TopLoc_ItemLocation> Translate(const TopLoc_Location& theLoc, NCollection_DataMap<opencascade::handle<Standard_Transient>, opencascade::handle<StdObjMgt_Persistent>, NCollection_DefaultHasher<opencascade::handle<Standard_Transient>>>& theMap);
  static opencascade::handle<StdPersistent_TopLoc_Datum3D> Translate(const opencascade::handle<TopLoc_Datum3D>& theDatum, NCollection_DataMap<opencascade::handle<Standard_Transient>, opencascade::handle<StdObjMgt_Persistent>, NCollection_DefaultHasher<opencascade::handle<Standard_Transient>>>& theMap);
};

class StdPersistent_TopLoc_Datum3D : public StdObjMgt_Persistent {
public:
  void PChildren(NCollection_Sequence<opencascade::handle<StdObjMgt_Persistent>>& arg0) const;
  const char* PName() const;
};

class StdPersistent_TopLoc_ItemLocation : public StdObjMgt_Persistent {
public:
  StdPersistent_TopLoc_ItemLocation();
  void Read(StdObjMgt_ReadData& theReadData);
  void Write(StdObjMgt_WriteData& theWriteData) const;
  void PChildren(NCollection_Sequence<opencascade::handle<StdObjMgt_Persistent>>& theChildren) const;
  const char* PName() const;
  TopLoc_Location Import() const;
};
