// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* StepRepr: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module StepReprModule

%include "NetOcc.i"

%{
#include <StepRepr_module.hxx>
%}

%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "GeomAbs.i"
%import "gp.i"
%import "TColgp.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "GeomEval.i"
%import "Geom.i"
%import "TopAbs.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "TopLoc.i"
%import "TopoDS.i"
%import "BRepAdaptor.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "IntCurvesFace.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "BVH.i"
%import "Bnd.i"
%import "TopTools.i"
%import "Resource.i"
%import "CDM.i"
%import "LDOM.i"
%import "Storage.i"
%import "PCDM.i"
%import "CDF.i"
%import "TDF.i"
%import "TDocStd.i"
%import "DE.i"
%import "IFGraph.i"
%import "IFSelect.i"
%import "TColGeom.i"
%import "ShapeExtend.i"
%import "TShort.i"
%import "Poly.i"
%import "BRep.i"
%import "BRepTools.i"
%import "ShapeBuild.i"
%import "ShapeProcess.i"
%import "XSAlgo.i"
%import "Transfer.i"
%import "XSControl.i"
%import "MoniTool.i"
%import "Interface.i"
%import "StepData.i"
%import "StepBasic.i"
%import "StepGeom.i"
%import "StepShape.i"
%netocc_csimports(using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.GeomAbs; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.TopAbs; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.TopLoc; using OCC.Core.TopoDS; using OCC.Core.BRepAdaptor; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.IntCurvesFace; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.BVH; using OCC.Core.Bnd; using OCC.Core.TopTools; using OCC.Core.Resource; using OCC.Core.CDM; using OCC.Core.LDOM; using OCC.Core.Storage; using OCC.Core.PCDM; using OCC.Core.CDF; using OCC.Core.TDF; using OCC.Core.TDocStd; using OCC.Core.DE; using OCC.Core.IFGraph; using OCC.Core.IFSelect; using OCC.Core.TColGeom; using OCC.Core.ShapeExtend; using OCC.Core.TShort; using OCC.Core.Poly; using OCC.Core.BRep; using OCC.Core.BRepTools; using OCC.Core.ShapeBuild; using OCC.Core.ShapeProcess; using OCC.Core.XSAlgo; using OCC.Core.Transfer; using OCC.Core.XSControl; using OCC.Core.MoniTool; using OCC.Core.Interface; using OCC.Core.StepData; using OCC.Core.StepBasic; using OCC.Core.StepGeom; using OCC.Core.StepShape;)

%occt_transient(StepRepr_ShapeAspect)
%occt_transient(StepRepr_CompositeShapeAspect)
%occt_transient(StepRepr_ContinuosShapeAspect)
%occt_transient(StepRepr_AllAroundShapeAspect)
%occt_transient(StepRepr_DerivedShapeAspect)
%occt_transient(StepRepr_Apex)
%occt_transient(StepRepr_ProductDefinitionUsage)
%occt_transient(StepRepr_AssemblyComponentUsage)
%occt_transient(StepRepr_AssemblyComponentUsageSubstitute)
%occt_transient(StepRepr_BetweenShapeAspect)
%occt_transient(StepRepr_RepresentationItem)
%occt_transient(StepRepr_BooleanRepresentationItem)
%occt_transient(StepRepr_CentreOfSymmetry)
%occt_valueclass(StepRepr_CharacterizedDefinition)
%occt_transient(StepRepr_Representation)
%occt_transient(StepRepr_CharacterizedRepresentation)
%occt_transient(StepRepr_CompShAspAndDatumFeatAndShAsp)
%occt_transient(StepRepr_CompGroupShAspAndCompShAspAndDatumFeatAndShAsp)
%occt_transient(StepRepr_CompositeGroupShapeAspect)
%occt_transient(StepRepr_CompoundRepresentationItem)
%occt_valueclass(StepRepr_ConfigurationDesignItem)
%occt_transient(StepRepr_ConfigurationDesign)
%occt_transient(StepRepr_ConfigurationEffectivity)
%occt_transient(StepRepr_ConfigurationItem)
%occt_transient(StepRepr_ConstructiveGeometryRepresentation)
%occt_transient(StepRepr_RepresentationRelationship)
%occt_transient(StepRepr_ConstructiveGeometryRepresentationRelationship)
%occt_valueclass(StepRepr_RepresentedDefinition)
%occt_transient(StepRepr_PropertyDefinitionRepresentation)
%occt_transient(StepRepr_DataEnvironment)
%occt_transient(StepRepr_DefinitionalRepresentation)
%occt_transient(StepRepr_DescriptiveRepresentationItem)
%occt_transient(StepRepr_Extension)
%occt_transient(StepRepr_ExternallyDefinedRepresentation)
%occt_transient(StepRepr_ShapeAspectRelationship)
%occt_transient(StepRepr_FeatureForDatumTargetRelationship)
%occt_transient(StepRepr_FunctionallyDefinedTransformation)
%occt_transient(StepRepr_GeometricAlignment)
%occt_transient(StepRepr_RepresentationContext)
%occt_transient(StepRepr_GlobalUncertaintyAssignedContext)
%occt_transient(StepRepr_GlobalUnitAssignedContext)
%occt_transient(StepRepr_IntegerRepresentationItem)
%occt_transient(StepRepr_ItemDefinedTransformation)
%occt_transient(StepRepr_MakeFromUsageOption)
%occt_transient(StepRepr_MappedItem)
%occt_transient(StepRepr_MaterialDesignation)
%occt_transient(StepRepr_PropertyDefinition)
%occt_transient(StepRepr_MaterialProperty)
%occt_transient(StepRepr_MaterialPropertyRepresentation)
%occt_transient(StepRepr_MeasureRepresentationItem)
%occt_transient(StepRepr_MechanicalDesignAndDraughtingRelationship)
%occt_transient(StepRepr_NextAssemblyUsageOccurrence)
%occt_transient(StepRepr_ParallelOffset)
%occt_transient(StepRepr_ParametricRepresentationContext)
%occt_transient(StepRepr_PerpendicularTo)
%occt_transient(StepRepr_ProductConcept)
%occt_transient(StepRepr_ProductDefinitionShape)
%occt_transient(StepRepr_PromissoryUsageOccurrence)
%occt_transient(StepRepr_PropertyDefinitionRelationship)
%occt_transient(StepRepr_QuantifiedAssemblyComponentUsage)
%occt_transient(StepRepr_RealRepresentationItem)
%occt_transient(StepRepr_ReprItemAndMeasureWithUnit)
%occt_transient(StepRepr_ReprItemAndLengthMeasureWithUnit)
%occt_transient(StepRepr_ReprItemAndMeasureWithUnitAndQRI)
%occt_transient(StepRepr_ReprItemAndLengthMeasureWithUnitAndQRI)
%occt_transient(StepRepr_ReprItemAndPlaneAngleMeasureWithUnit)
%occt_transient(StepRepr_ReprItemAndPlaneAngleMeasureWithUnitAndQRI)
%occt_transient(StepRepr_RepresentationContextReference)
%occt_transient(StepRepr_RepresentationMap)
%occt_valueclass(StepRepr_RepresentationOrRepresentationReference)
%occt_transient(StepRepr_RepresentationReference)
%occt_valueclass(StepRepr_Transformation)
%occt_transient(StepRepr_ShapeRepresentationRelationship)
%occt_transient(StepRepr_RepresentationRelationshipWithTransformation)
%occt_transient(StepRepr_ShapeAspectDerivingRelationship)
%occt_transient(StepRepr_ShapeAspectTransition)
%occt_valueclass(StepRepr_ShapeDefinition)
%occt_transient(StepRepr_ShapeRepresentationRelationshipWithTransformation)
%occt_transient(StepRepr_SpecifiedHigherUsageOccurrence)
%occt_transient(StepRepr_StructuralResponseProperty)
%occt_transient(StepRepr_StructuralResponsePropertyDefinitionRepresentation)
%occt_transient(StepRepr_SuppliedPartRelationship)
%occt_transient(StepRepr_Tangent)
%occt_transient(StepRepr_ValueRange)
%occt_transient(StepRepr_ValueRepresentationItem)

%occt_array1(StepRepr_Array1OfMaterialPropertyRepresentation, opencascade::handle<StepRepr_MaterialPropertyRepresentation>, StepRepr_MaterialPropertyRepresentation)
%occt_array1(StepRepr_Array1OfPropertyDefinitionRepresentation, opencascade::handle<StepRepr_PropertyDefinitionRepresentation>, StepRepr_PropertyDefinitionRepresentation)
%occt_array1(StepRepr_Array1OfRepresentationItem, opencascade::handle<StepRepr_RepresentationItem>, StepRepr_RepresentationItem)
%occt_array1(StepRepr_Array1OfShapeAspect, opencascade::handle<StepRepr_ShapeAspect>, StepRepr_ShapeAspect)
%occt_harray1(StepRepr_HArray1OfMaterialPropertyRepresentation, opencascade::handle<StepRepr_MaterialPropertyRepresentation>, StepRepr_MaterialPropertyRepresentation)
%occt_harray1(StepRepr_HArray1OfPropertyDefinitionRepresentation, opencascade::handle<StepRepr_PropertyDefinitionRepresentation>, StepRepr_PropertyDefinitionRepresentation)
%occt_harray1(StepRepr_HArray1OfRepresentationItem, opencascade::handle<StepRepr_RepresentationItem>, StepRepr_RepresentationItem)
%occt_harray1(StepRepr_HArray1OfShapeAspect, opencascade::handle<StepRepr_ShapeAspect>, StepRepr_ShapeAspect)

class StepRepr_ShapeAspect : public Standard_Transient {
public:
  StepRepr_ShapeAspect();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<TCollection_HAsciiString>& aDescription, const opencascade::handle<StepRepr_ProductDefinitionShape>& aOfShape, StepData_Logical aProductDefinitional);
  void SetName(const opencascade::handle<TCollection_HAsciiString>& aName);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& aDescription);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  void SetOfShape(const opencascade::handle<StepRepr_ProductDefinitionShape>& aOfShape);
  opencascade::handle<StepRepr_ProductDefinitionShape> OfShape() const;
  void SetProductDefinitional(StepData_Logical aProductDefinitional);
  StepData_Logical ProductDefinitional() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_CompositeShapeAspect : public StepRepr_ShapeAspect {
public:
  StepRepr_CompositeShapeAspect();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ContinuosShapeAspect : public StepRepr_CompositeShapeAspect {
public:
  StepRepr_ContinuosShapeAspect();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_AllAroundShapeAspect : public StepRepr_ContinuosShapeAspect {
public:
  StepRepr_AllAroundShapeAspect();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_DerivedShapeAspect : public StepRepr_ShapeAspect {
public:
  StepRepr_DerivedShapeAspect();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_Apex : public StepRepr_DerivedShapeAspect {
public:
  StepRepr_Apex();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ProductDefinitionUsage : public StepBasic_ProductDefinitionRelationship {
public:
  StepRepr_ProductDefinitionUsage();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_AssemblyComponentUsage : public StepRepr_ProductDefinitionUsage {
public:
  StepRepr_AssemblyComponentUsage();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Id, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Name, bool hasProductDefinitionRelationship_Description, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Description, const opencascade::handle<StepBasic_ProductDefinition>& aProductDefinitionRelationship_RelatingProductDefinition, const opencascade::handle<StepBasic_ProductDefinition>& aProductDefinitionRelationship_RelatedProductDefinition, bool hasReferenceDesignator, const opencascade::handle<TCollection_HAsciiString>& aReferenceDesignator);
  void Init(const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Id, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Name, bool hasProductDefinitionRelationship_Description, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Description, const StepBasic_ProductDefinitionOrReference& aProductDefinitionRelationship_RelatingProductDefinition, const StepBasic_ProductDefinitionOrReference& aProductDefinitionRelationship_RelatedProductDefinition, bool hasReferenceDesignator, const opencascade::handle<TCollection_HAsciiString>& aReferenceDesignator);
  opencascade::handle<TCollection_HAsciiString> ReferenceDesignator() const;
  void SetReferenceDesignator(const opencascade::handle<TCollection_HAsciiString>& ReferenceDesignator);
  bool HasReferenceDesignator() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_AssemblyComponentUsageSubstitute : public Standard_Transient {
public:
  StepRepr_AssemblyComponentUsageSubstitute();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<TCollection_HAsciiString>& aDef, const opencascade::handle<StepRepr_AssemblyComponentUsage>& aBase, const opencascade::handle<StepRepr_AssemblyComponentUsage>& aSubs);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetName(const opencascade::handle<TCollection_HAsciiString>& aName);
  opencascade::handle<TCollection_HAsciiString> Definition() const;
  void SetDefinition(const opencascade::handle<TCollection_HAsciiString>& aDef);
  opencascade::handle<StepRepr_AssemblyComponentUsage> Base() const;
  void SetBase(const opencascade::handle<StepRepr_AssemblyComponentUsage>& aBase);
  opencascade::handle<StepRepr_AssemblyComponentUsage> Substitute() const;
  void SetSubstitute(const opencascade::handle<StepRepr_AssemblyComponentUsage>& aSubstitute);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_BetweenShapeAspect : public StepRepr_ContinuosShapeAspect {
public:
  StepRepr_BetweenShapeAspect();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_RepresentationItem : public Standard_Transient {
public:
  StepRepr_RepresentationItem();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName);
  void SetName(const opencascade::handle<TCollection_HAsciiString>& aName);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_BooleanRepresentationItem : public StepRepr_RepresentationItem {
public:
  StepRepr_BooleanRepresentationItem();
  void Init(const opencascade::handle<TCollection_HAsciiString>& theName, bool theValue);
  void SetValue(bool theValue);
  bool Value() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_CentreOfSymmetry : public StepRepr_DerivedShapeAspect {
public:
  StepRepr_CentreOfSymmetry();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_CharacterizedDefinition : public StepData_SelectType {
public:
  StepRepr_CharacterizedDefinition();
  int CaseNum(const opencascade::handle<Standard_Transient>& ent) const;
  opencascade::handle<StepBasic_CharacterizedObject> CharacterizedObject() const;
  opencascade::handle<StepBasic_ProductDefinition> ProductDefinition() const;
  opencascade::handle<StepBasic_ProductDefinitionRelationship> ProductDefinitionRelationship() const;
  opencascade::handle<StepRepr_ProductDefinitionShape> ProductDefinitionShape() const;
  opencascade::handle<StepRepr_ShapeAspect> ShapeAspect() const;
  opencascade::handle<StepRepr_ShapeAspectRelationship> ShapeAspectRelationship() const;
  opencascade::handle<StepBasic_DocumentFile> DocumentFile() const;
};

class StepRepr_Representation : public Standard_Transient {
public:
  StepRepr_Representation();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<NCollection_HArray1<opencascade::handle<StepRepr_RepresentationItem>>>& aItems, const opencascade::handle<StepRepr_RepresentationContext>& aContextOfItems);
  void SetName(const opencascade::handle<TCollection_HAsciiString>& aName);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetItems(const opencascade::handle<NCollection_HArray1<opencascade::handle<StepRepr_RepresentationItem>>>& aItems);
  opencascade::handle<NCollection_HArray1<opencascade::handle<StepRepr_RepresentationItem>>> Items() const;
  opencascade::handle<StepRepr_RepresentationItem> ItemsValue(int num) const;
  int NbItems() const;
  void SetContextOfItems(const opencascade::handle<StepRepr_RepresentationContext>& aContextOfItems);
  opencascade::handle<StepRepr_RepresentationContext> ContextOfItems() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_CharacterizedRepresentation : public StepRepr_Representation {
public:
  StepRepr_CharacterizedRepresentation();
  void Init(const opencascade::handle<TCollection_HAsciiString>& theName, const opencascade::handle<TCollection_HAsciiString>& theDescription, const opencascade::handle<NCollection_HArray1<opencascade::handle<StepRepr_RepresentationItem>>>& theItems, const opencascade::handle<StepRepr_RepresentationContext>& theContextOfItems);
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& theDescription);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_CompShAspAndDatumFeatAndShAsp : public StepRepr_ShapeAspect {
public:
  StepRepr_CompShAspAndDatumFeatAndShAsp();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_CompGroupShAspAndCompShAspAndDatumFeatAndShAsp : public StepRepr_CompShAspAndDatumFeatAndShAsp {
public:
  StepRepr_CompGroupShAspAndCompShAspAndDatumFeatAndShAsp();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_CompositeGroupShapeAspect : public StepRepr_CompositeShapeAspect {
public:
  StepRepr_CompositeGroupShapeAspect();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_CompoundRepresentationItem : public StepRepr_RepresentationItem {
public:
  StepRepr_CompoundRepresentationItem();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<NCollection_HArray1<opencascade::handle<StepRepr_RepresentationItem>>>& item_element);
  opencascade::handle<NCollection_HArray1<opencascade::handle<StepRepr_RepresentationItem>>> ItemElement() const;
  int NbItemElement() const;
  void SetItemElement(const opencascade::handle<NCollection_HArray1<opencascade::handle<StepRepr_RepresentationItem>>>& item_element);
  opencascade::handle<StepRepr_RepresentationItem> ItemElementValue(int num) const;
  void SetItemElementValue(int num, const opencascade::handle<StepRepr_RepresentationItem>& anelement);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ConfigurationDesignItem : public StepData_SelectType {
public:
  StepRepr_ConfigurationDesignItem();
  int CaseNum(const opencascade::handle<Standard_Transient>& ent) const;
  opencascade::handle<StepBasic_ProductDefinition> ProductDefinition() const;
  opencascade::handle<StepBasic_ProductDefinitionFormation> ProductDefinitionFormation() const;
};

class StepRepr_ConfigurationDesign : public Standard_Transient {
public:
  StepRepr_ConfigurationDesign();
  void Init(const opencascade::handle<StepRepr_ConfigurationItem>& aConfiguration, const StepRepr_ConfigurationDesignItem& aDesign);
  opencascade::handle<StepRepr_ConfigurationItem> Configuration() const;
  void SetConfiguration(const opencascade::handle<StepRepr_ConfigurationItem>& Configuration);
  StepRepr_ConfigurationDesignItem Design() const;
  void SetDesign(const StepRepr_ConfigurationDesignItem& Design);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ConfigurationEffectivity : public StepBasic_ProductDefinitionEffectivity {
public:
  StepRepr_ConfigurationEffectivity();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aEffectivity_Id, const opencascade::handle<StepBasic_ProductDefinitionRelationship>& aProductDefinitionEffectivity_Usage, const opencascade::handle<StepRepr_ConfigurationDesign>& aConfiguration);
  opencascade::handle<StepRepr_ConfigurationDesign> Configuration() const;
  void SetConfiguration(const opencascade::handle<StepRepr_ConfigurationDesign>& Configuration);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ConfigurationItem : public Standard_Transient {
public:
  StepRepr_ConfigurationItem();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aId, const opencascade::handle<TCollection_HAsciiString>& aName, bool hasDescription, const opencascade::handle<TCollection_HAsciiString>& aDescription, const opencascade::handle<StepRepr_ProductConcept>& aItemConcept, bool hasPurpose, const opencascade::handle<TCollection_HAsciiString>& aPurpose);
  opencascade::handle<TCollection_HAsciiString> Id() const;
  void SetId(const opencascade::handle<TCollection_HAsciiString>& Id);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetName(const opencascade::handle<TCollection_HAsciiString>& Name);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& Description);
  bool HasDescription() const;
  opencascade::handle<StepRepr_ProductConcept> ItemConcept() const;
  void SetItemConcept(const opencascade::handle<StepRepr_ProductConcept>& ItemConcept);
  opencascade::handle<TCollection_HAsciiString> Purpose() const;
  void SetPurpose(const opencascade::handle<TCollection_HAsciiString>& Purpose);
  bool HasPurpose() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ConstructiveGeometryRepresentation : public StepRepr_Representation {
public:
  StepRepr_ConstructiveGeometryRepresentation();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_RepresentationRelationship : public Standard_Transient {
public:
  StepRepr_RepresentationRelationship();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<TCollection_HAsciiString>& aDescription, const opencascade::handle<StepRepr_Representation>& aRep1, const opencascade::handle<StepRepr_Representation>& aRep2);
  void SetName(const opencascade::handle<TCollection_HAsciiString>& aName);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  bool HasDescription();
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& aDescription);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  void SetRep1(const opencascade::handle<StepRepr_Representation>& aRep1);
  opencascade::handle<StepRepr_Representation> Rep1() const;
  void SetRep2(const opencascade::handle<StepRepr_Representation>& aRep2);
  opencascade::handle<StepRepr_Representation> Rep2() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ConstructiveGeometryRepresentationRelationship : public StepRepr_RepresentationRelationship {
public:
  StepRepr_ConstructiveGeometryRepresentationRelationship();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_RepresentedDefinition : public StepData_SelectType {
public:
  StepRepr_RepresentedDefinition();
  int CaseNum(const opencascade::handle<Standard_Transient>& ent) const;
  opencascade::handle<StepBasic_GeneralProperty> GeneralProperty() const;
  opencascade::handle<StepRepr_PropertyDefinition> PropertyDefinition() const;
  opencascade::handle<StepRepr_PropertyDefinitionRelationship> PropertyDefinitionRelationship() const;
  opencascade::handle<StepRepr_ShapeAspect> ShapeAspect() const;
  opencascade::handle<StepRepr_ShapeAspectRelationship> ShapeAspectRelationship() const;
};

class StepRepr_PropertyDefinitionRepresentation : public Standard_Transient {
public:
  StepRepr_PropertyDefinitionRepresentation();
  void Init(const StepRepr_RepresentedDefinition& aDefinition, const opencascade::handle<StepRepr_Representation>& aUsedRepresentation);
  StepRepr_RepresentedDefinition Definition() const;
  void SetDefinition(const StepRepr_RepresentedDefinition& Definition);
  opencascade::handle<StepRepr_Representation> UsedRepresentation() const;
  void SetUsedRepresentation(const opencascade::handle<StepRepr_Representation>& UsedRepresentation);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_DataEnvironment : public Standard_Transient {
public:
  StepRepr_DataEnvironment();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<TCollection_HAsciiString>& aDescription, const opencascade::handle<NCollection_HArray1<opencascade::handle<StepRepr_PropertyDefinitionRepresentation>>>& aElements);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetName(const opencascade::handle<TCollection_HAsciiString>& Name);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& Description);
  opencascade::handle<NCollection_HArray1<opencascade::handle<StepRepr_PropertyDefinitionRepresentation>>> Elements() const;
  void SetElements(const opencascade::handle<NCollection_HArray1<opencascade::handle<StepRepr_PropertyDefinitionRepresentation>>>& Elements);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_DefinitionalRepresentation : public StepRepr_Representation {
public:
  StepRepr_DefinitionalRepresentation();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_DescriptiveRepresentationItem : public StepRepr_RepresentationItem {
public:
  StepRepr_DescriptiveRepresentationItem();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<TCollection_HAsciiString>& aDescription);
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& aDescription);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_Extension : public StepRepr_DerivedShapeAspect {
public:
  StepRepr_Extension();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ExternallyDefinedRepresentation : public StepRepr_Representation {
public:
  StepRepr_ExternallyDefinedRepresentation();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ShapeAspectRelationship : public Standard_Transient {
public:
  StepRepr_ShapeAspectRelationship();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, bool hasDescription, const opencascade::handle<TCollection_HAsciiString>& aDescription, const opencascade::handle<StepRepr_ShapeAspect>& aRelatingShapeAspect, const opencascade::handle<StepRepr_ShapeAspect>& aRelatedShapeAspect);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetName(const opencascade::handle<TCollection_HAsciiString>& Name);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& Description);
  bool HasDescription() const;
  opencascade::handle<StepRepr_ShapeAspect> RelatingShapeAspect() const;
  void SetRelatingShapeAspect(const opencascade::handle<StepRepr_ShapeAspect>& RelatingShapeAspect);
  opencascade::handle<StepRepr_ShapeAspect> RelatedShapeAspect() const;
  void SetRelatedShapeAspect(const opencascade::handle<StepRepr_ShapeAspect>& RelatedShapeAspect);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_FeatureForDatumTargetRelationship : public StepRepr_ShapeAspectRelationship {
public:
  StepRepr_FeatureForDatumTargetRelationship();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_FunctionallyDefinedTransformation : public Standard_Transient {
public:
  StepRepr_FunctionallyDefinedTransformation();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<TCollection_HAsciiString>& aDescription);
  void SetName(const opencascade::handle<TCollection_HAsciiString>& aName);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& aDescription);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_GeometricAlignment : public StepRepr_DerivedShapeAspect {
public:
  StepRepr_GeometricAlignment();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_RepresentationContext : public Standard_Transient {
public:
  StepRepr_RepresentationContext();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aContextIdentifier, const opencascade::handle<TCollection_HAsciiString>& aContextType);
  void SetContextIdentifier(const opencascade::handle<TCollection_HAsciiString>& aContextIdentifier);
  opencascade::handle<TCollection_HAsciiString> ContextIdentifier() const;
  void SetContextType(const opencascade::handle<TCollection_HAsciiString>& aContextType);
  opencascade::handle<TCollection_HAsciiString> ContextType() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_GlobalUncertaintyAssignedContext : public StepRepr_RepresentationContext {
public:
  StepRepr_GlobalUncertaintyAssignedContext();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aContextIdentifier, const opencascade::handle<TCollection_HAsciiString>& aContextType, const opencascade::handle<NCollection_HArray1<opencascade::handle<StepBasic_UncertaintyMeasureWithUnit>>>& aUncertainty);
  void SetUncertainty(const opencascade::handle<NCollection_HArray1<opencascade::handle<StepBasic_UncertaintyMeasureWithUnit>>>& aUncertainty);
  opencascade::handle<NCollection_HArray1<opencascade::handle<StepBasic_UncertaintyMeasureWithUnit>>> Uncertainty() const;
  opencascade::handle<StepBasic_UncertaintyMeasureWithUnit> UncertaintyValue(int num) const;
  int NbUncertainty() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_GlobalUnitAssignedContext : public StepRepr_RepresentationContext {
public:
  StepRepr_GlobalUnitAssignedContext();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aContextIdentifier, const opencascade::handle<TCollection_HAsciiString>& aContextType, const opencascade::handle<NCollection_HArray1<opencascade::handle<StepBasic_NamedUnit>>>& aUnits);
  void SetUnits(const opencascade::handle<NCollection_HArray1<opencascade::handle<StepBasic_NamedUnit>>>& aUnits);
  opencascade::handle<NCollection_HArray1<opencascade::handle<StepBasic_NamedUnit>>> Units() const;
  opencascade::handle<StepBasic_NamedUnit> UnitsValue(int num) const;
  int NbUnits() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_IntegerRepresentationItem : public StepRepr_RepresentationItem {
public:
  StepRepr_IntegerRepresentationItem();
  void Init(const opencascade::handle<TCollection_HAsciiString>& theName, int theValue);
  void SetValue(int theValue);
  int Value() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ItemDefinedTransformation : public Standard_Transient {
public:
  StepRepr_ItemDefinedTransformation();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<TCollection_HAsciiString>& aDescription, const opencascade::handle<StepRepr_RepresentationItem>& aTransformItem1, const opencascade::handle<StepRepr_RepresentationItem>& aTransformItem2);
  void SetName(const opencascade::handle<TCollection_HAsciiString>& aName);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  bool HasDescription() const;
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& aDescription);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  void SetTransformItem1(const opencascade::handle<StepRepr_RepresentationItem>& aItem);
  opencascade::handle<StepRepr_RepresentationItem> TransformItem1() const;
  void SetTransformItem2(const opencascade::handle<StepRepr_RepresentationItem>& aItem);
  opencascade::handle<StepRepr_RepresentationItem> TransformItem2() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_MakeFromUsageOption : public StepRepr_ProductDefinitionUsage {
public:
  StepRepr_MakeFromUsageOption();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Id, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Name, bool hasProductDefinitionRelationship_Description, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Description, const opencascade::handle<StepBasic_ProductDefinition>& aProductDefinitionRelationship_RelatingProductDefinition, const opencascade::handle<StepBasic_ProductDefinition>& aProductDefinitionRelationship_RelatedProductDefinition, int aRanking, const opencascade::handle<TCollection_HAsciiString>& aRankingRationale, const opencascade::handle<Standard_Transient>& aQuantity);
  void Init(const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Id, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Name, bool hasProductDefinitionRelationship_Description, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Description, const StepBasic_ProductDefinitionOrReference& aProductDefinitionRelationship_RelatingProductDefinition, const StepBasic_ProductDefinitionOrReference& aProductDefinitionRelationship_RelatedProductDefinition, int aRanking, const opencascade::handle<TCollection_HAsciiString>& aRankingRationale, const opencascade::handle<Standard_Transient>& aQuantity);
  int Ranking() const;
  void SetRanking(int Ranking);
  opencascade::handle<TCollection_HAsciiString> RankingRationale() const;
  void SetRankingRationale(const opencascade::handle<TCollection_HAsciiString>& RankingRationale);
  opencascade::handle<Standard_Transient> Quantity() const;
  void SetQuantity(const opencascade::handle<Standard_Transient>& Quantity);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_MappedItem : public StepRepr_RepresentationItem {
public:
  StepRepr_MappedItem();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<StepRepr_RepresentationMap>& aMappingSource, const opencascade::handle<StepRepr_RepresentationItem>& aMappingTarget);
  void SetMappingSource(const opencascade::handle<StepRepr_RepresentationMap>& aMappingSource);
  opencascade::handle<StepRepr_RepresentationMap> MappingSource() const;
  void SetMappingTarget(const opencascade::handle<StepRepr_RepresentationItem>& aMappingTarget);
  opencascade::handle<StepRepr_RepresentationItem> MappingTarget() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_MaterialDesignation : public Standard_Transient {
public:
  StepRepr_MaterialDesignation();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const StepRepr_CharacterizedDefinition& aOfDefinition);
  void SetName(const opencascade::handle<TCollection_HAsciiString>& aName);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetOfDefinition(const StepRepr_CharacterizedDefinition& aOfDefinition);
  StepRepr_CharacterizedDefinition OfDefinition() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_PropertyDefinition : public Standard_Transient {
public:
  StepRepr_PropertyDefinition();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, bool hasDescription, const opencascade::handle<TCollection_HAsciiString>& aDescription, const StepRepr_CharacterizedDefinition& aDefinition);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetName(const opencascade::handle<TCollection_HAsciiString>& Name);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& Description);
  bool HasDescription() const;
  StepRepr_CharacterizedDefinition Definition() const;
  void SetDefinition(const StepRepr_CharacterizedDefinition& Definition);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_MaterialProperty : public StepRepr_PropertyDefinition {
public:
  StepRepr_MaterialProperty();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_MaterialPropertyRepresentation : public StepRepr_PropertyDefinitionRepresentation {
public:
  StepRepr_MaterialPropertyRepresentation();
  void Init(const StepRepr_RepresentedDefinition& aPropertyDefinitionRepresentation_Definition, const opencascade::handle<StepRepr_Representation>& aPropertyDefinitionRepresentation_UsedRepresentation, const opencascade::handle<StepRepr_DataEnvironment>& aDependentEnvironment);
  opencascade::handle<StepRepr_DataEnvironment> DependentEnvironment() const;
  void SetDependentEnvironment(const opencascade::handle<StepRepr_DataEnvironment>& DependentEnvironment);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_MeasureRepresentationItem : public StepRepr_RepresentationItem {
public:
  StepRepr_MeasureRepresentationItem();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<StepBasic_MeasureValueMember>& aValueComponent, const StepBasic_Unit& aUnitComponent);
  void SetMeasure(const opencascade::handle<StepBasic_MeasureWithUnit>& Measure);
  opencascade::handle<StepBasic_MeasureWithUnit> Measure() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_MechanicalDesignAndDraughtingRelationship : public StepRepr_RepresentationRelationship {
public:
  StepRepr_MechanicalDesignAndDraughtingRelationship();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_NextAssemblyUsageOccurrence : public StepRepr_AssemblyComponentUsage {
public:
  StepRepr_NextAssemblyUsageOccurrence();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ParallelOffset : public StepRepr_DerivedShapeAspect {
public:
  StepRepr_ParallelOffset();
  void Init(const opencascade::handle<TCollection_HAsciiString>& theName, const opencascade::handle<TCollection_HAsciiString>& theDescription, const opencascade::handle<StepRepr_ProductDefinitionShape>& theOfShape, StepData_Logical theProductDefinitional, const opencascade::handle<Standard_Transient>& theOffset);
  opencascade::handle<Standard_Transient> Offset() const;
  void SetOffset(const opencascade::handle<Standard_Transient>& theOffset);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ParametricRepresentationContext : public StepRepr_RepresentationContext {
public:
  StepRepr_ParametricRepresentationContext();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_PerpendicularTo : public StepRepr_DerivedShapeAspect {
public:
  StepRepr_PerpendicularTo();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ProductConcept : public Standard_Transient {
public:
  StepRepr_ProductConcept();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aId, const opencascade::handle<TCollection_HAsciiString>& aName, bool hasDescription, const opencascade::handle<TCollection_HAsciiString>& aDescription, const opencascade::handle<StepBasic_ProductConceptContext>& aMarketContext);
  opencascade::handle<TCollection_HAsciiString> Id() const;
  void SetId(const opencascade::handle<TCollection_HAsciiString>& Id);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetName(const opencascade::handle<TCollection_HAsciiString>& Name);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& Description);
  bool HasDescription() const;
  opencascade::handle<StepBasic_ProductConceptContext> MarketContext() const;
  void SetMarketContext(const opencascade::handle<StepBasic_ProductConceptContext>& MarketContext);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ProductDefinitionShape : public StepRepr_PropertyDefinition {
public:
  StepRepr_ProductDefinitionShape();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_PromissoryUsageOccurrence : public StepRepr_AssemblyComponentUsage {
public:
  StepRepr_PromissoryUsageOccurrence();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_PropertyDefinitionRelationship : public Standard_Transient {
public:
  StepRepr_PropertyDefinitionRelationship();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<TCollection_HAsciiString>& aDescription, const opencascade::handle<StepRepr_PropertyDefinition>& aRelatingPropertyDefinition, const opencascade::handle<StepRepr_PropertyDefinition>& aRelatedPropertyDefinition);
  opencascade::handle<TCollection_HAsciiString> Name() const;
  void SetName(const opencascade::handle<TCollection_HAsciiString>& Name);
  opencascade::handle<TCollection_HAsciiString> Description() const;
  void SetDescription(const opencascade::handle<TCollection_HAsciiString>& Description);
  opencascade::handle<StepRepr_PropertyDefinition> RelatingPropertyDefinition() const;
  void SetRelatingPropertyDefinition(const opencascade::handle<StepRepr_PropertyDefinition>& RelatingPropertyDefinition);
  opencascade::handle<StepRepr_PropertyDefinition> RelatedPropertyDefinition() const;
  void SetRelatedPropertyDefinition(const opencascade::handle<StepRepr_PropertyDefinition>& RelatedPropertyDefinition);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_QuantifiedAssemblyComponentUsage : public StepRepr_AssemblyComponentUsage {
public:
  StepRepr_QuantifiedAssemblyComponentUsage();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Id, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Name, bool hasProductDefinitionRelationship_Description, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Description, const opencascade::handle<StepBasic_ProductDefinition>& aProductDefinitionRelationship_RelatingProductDefinition, const opencascade::handle<StepBasic_ProductDefinition>& aProductDefinitionRelationship_RelatedProductDefinition, bool hasAssemblyComponentUsage_ReferenceDesignator, const opencascade::handle<TCollection_HAsciiString>& aAssemblyComponentUsage_ReferenceDesignator, const opencascade::handle<Standard_Transient>& aQuantity);
  void Init(const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Id, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Name, bool hasProductDefinitionRelationship_Description, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Description, const StepBasic_ProductDefinitionOrReference& aProductDefinitionRelationship_RelatingProductDefinition, const StepBasic_ProductDefinitionOrReference& aProductDefinitionRelationship_RelatedProductDefinition, bool hasAssemblyComponentUsage_ReferenceDesignator, const opencascade::handle<TCollection_HAsciiString>& aAssemblyComponentUsage_ReferenceDesignator, const opencascade::handle<Standard_Transient>& aQuantity);
  opencascade::handle<Standard_Transient> Quantity() const;
  void SetQuantity(const opencascade::handle<Standard_Transient>& Quantity);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_RealRepresentationItem : public StepRepr_RepresentationItem {
public:
  StepRepr_RealRepresentationItem();
  void Init(const opencascade::handle<TCollection_HAsciiString>& theName, double theValue);
  void SetValue(double theValue);
  double Value() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ReprItemAndMeasureWithUnit : public StepRepr_RepresentationItem {
public:
  StepRepr_ReprItemAndMeasureWithUnit();
  void Init(const opencascade::handle<StepBasic_MeasureWithUnit>& aMWU, const opencascade::handle<StepRepr_RepresentationItem>& aRI);
  opencascade::handle<StepRepr_MeasureRepresentationItem> GetMeasureRepresentationItem() const;
  void SetMeasureWithUnit(const opencascade::handle<StepBasic_MeasureWithUnit>& aMWU);
  opencascade::handle<StepBasic_MeasureWithUnit> GetMeasureWithUnit() const;
  opencascade::handle<StepRepr_RepresentationItem> GetRepresentationItem() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ReprItemAndLengthMeasureWithUnit : public StepRepr_ReprItemAndMeasureWithUnit {
public:
  StepRepr_ReprItemAndLengthMeasureWithUnit();
  void SetLengthMeasureWithUnit(const opencascade::handle<StepBasic_LengthMeasureWithUnit>& aLMWU);
  opencascade::handle<StepBasic_LengthMeasureWithUnit> GetLengthMeasureWithUnit() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ReprItemAndMeasureWithUnitAndQRI : public StepRepr_ReprItemAndMeasureWithUnit {
public:
  StepRepr_ReprItemAndMeasureWithUnitAndQRI();
  void Init(const opencascade::handle<StepBasic_MeasureWithUnit>& aMWU, const opencascade::handle<StepRepr_RepresentationItem>& aRI, const opencascade::handle<StepShape_QualifiedRepresentationItem>& aQRI);
  void SetQualifiedRepresentationItem(const opencascade::handle<StepShape_QualifiedRepresentationItem>& aQRI);
  opencascade::handle<StepShape_QualifiedRepresentationItem> GetQualifiedRepresentationItem() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ReprItemAndLengthMeasureWithUnitAndQRI : public StepRepr_ReprItemAndMeasureWithUnitAndQRI {
public:
  StepRepr_ReprItemAndLengthMeasureWithUnitAndQRI();
  void SetLengthMeasureWithUnit(const opencascade::handle<StepBasic_LengthMeasureWithUnit>& aLMWU);
  opencascade::handle<StepBasic_LengthMeasureWithUnit> GetLengthMeasureWithUnit() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ReprItemAndPlaneAngleMeasureWithUnit : public StepRepr_ReprItemAndMeasureWithUnit {
public:
  StepRepr_ReprItemAndPlaneAngleMeasureWithUnit();
  void SetPlaneAngleMeasureWithUnit(const opencascade::handle<StepBasic_PlaneAngleMeasureWithUnit>& aLMWU);
  opencascade::handle<StepBasic_PlaneAngleMeasureWithUnit> GetPlaneAngleMeasureWithUnit() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ReprItemAndPlaneAngleMeasureWithUnitAndQRI : public StepRepr_ReprItemAndMeasureWithUnitAndQRI {
public:
  StepRepr_ReprItemAndPlaneAngleMeasureWithUnitAndQRI();
  void SetPlaneAngleMeasureWithUnit(const opencascade::handle<StepBasic_PlaneAngleMeasureWithUnit>& aLMWU);
  opencascade::handle<StepBasic_PlaneAngleMeasureWithUnit> GetPlaneAngleMeasureWithUnit() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_RepresentationContextReference : public Standard_Transient {
public:
  StepRepr_RepresentationContextReference();
  void Init(const opencascade::handle<TCollection_HAsciiString>& theContextIdentifier);
  opencascade::handle<TCollection_HAsciiString> ContextIdentifier() const;
  void SetContextIdentifier(const opencascade::handle<TCollection_HAsciiString>& theContextIdentifier);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_RepresentationMap : public Standard_Transient {
public:
  StepRepr_RepresentationMap();
  void Init(const opencascade::handle<StepRepr_RepresentationItem>& aMappingOrigin, const opencascade::handle<StepRepr_Representation>& aMappedRepresentation);
  void SetMappingOrigin(const opencascade::handle<StepRepr_RepresentationItem>& aMappingOrigin);
  opencascade::handle<StepRepr_RepresentationItem> MappingOrigin() const;
  void SetMappedRepresentation(const opencascade::handle<StepRepr_Representation>& aMappedRepresentation);
  opencascade::handle<StepRepr_Representation> MappedRepresentation() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_RepresentationOrRepresentationReference : public StepData_SelectType {
public:
  StepRepr_RepresentationOrRepresentationReference();
  int CaseNum(const opencascade::handle<Standard_Transient>& ent) const;
  opencascade::handle<StepRepr_Representation> Representation() const;
  opencascade::handle<StepRepr_RepresentationReference> RepresentationReference() const;
};

class StepRepr_RepresentationReference : public Standard_Transient {
public:
  StepRepr_RepresentationReference();
  void Init(const opencascade::handle<TCollection_HAsciiString>& theId, const opencascade::handle<StepRepr_RepresentationContextReference>& theContextOfItems);
  opencascade::handle<TCollection_HAsciiString> Id() const;
  void SetId(const opencascade::handle<TCollection_HAsciiString>& theId);
  opencascade::handle<StepRepr_RepresentationContextReference> ContextOfItems() const;
  void SetContextOfItems(const opencascade::handle<StepRepr_RepresentationContextReference>& theContextOfItems);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_Transformation : public StepData_SelectType {
public:
  StepRepr_Transformation();
  int CaseNum(const opencascade::handle<Standard_Transient>& ent) const;
  opencascade::handle<StepRepr_ItemDefinedTransformation> ItemDefinedTransformation() const;
  opencascade::handle<StepRepr_FunctionallyDefinedTransformation> FunctionallyDefinedTransformation() const;
};

class StepRepr_ShapeRepresentationRelationship : public StepRepr_RepresentationRelationship {
public:
  StepRepr_ShapeRepresentationRelationship();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_RepresentationRelationshipWithTransformation : public StepRepr_ShapeRepresentationRelationship {
public:
  StepRepr_RepresentationRelationshipWithTransformation();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aName, const opencascade::handle<TCollection_HAsciiString>& aDescription, const opencascade::handle<StepRepr_Representation>& aRep1, const opencascade::handle<StepRepr_Representation>& aRep2, const StepRepr_Transformation& aTransf);
  StepRepr_Transformation TransformationOperator() const;
  void SetTransformationOperator(const StepRepr_Transformation& aTrans);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ShapeAspectDerivingRelationship : public StepRepr_ShapeAspectRelationship {
public:
  StepRepr_ShapeAspectDerivingRelationship();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ShapeAspectTransition : public StepRepr_ShapeAspectRelationship {
public:
  StepRepr_ShapeAspectTransition();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ShapeDefinition : public StepData_SelectType {
public:
  StepRepr_ShapeDefinition();
  int CaseNum(const opencascade::handle<Standard_Transient>& ent) const;
  opencascade::handle<StepRepr_ProductDefinitionShape> ProductDefinitionShape() const;
  opencascade::handle<StepRepr_ShapeAspect> ShapeAspect() const;
  opencascade::handle<StepRepr_ShapeAspectRelationship> ShapeAspectRelationship() const;
};

class StepRepr_ShapeRepresentationRelationshipWithTransformation : public StepRepr_RepresentationRelationshipWithTransformation {
public:
  StepRepr_ShapeRepresentationRelationshipWithTransformation();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_SpecifiedHigherUsageOccurrence : public StepRepr_AssemblyComponentUsage {
public:
  StepRepr_SpecifiedHigherUsageOccurrence();
  void Init(const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Id, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Name, bool hasProductDefinitionRelationship_Description, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Description, const opencascade::handle<StepBasic_ProductDefinition>& aProductDefinitionRelationship_RelatingProductDefinition, const opencascade::handle<StepBasic_ProductDefinition>& aProductDefinitionRelationship_RelatedProductDefinition, bool hasAssemblyComponentUsage_ReferenceDesignator, const opencascade::handle<TCollection_HAsciiString>& aAssemblyComponentUsage_ReferenceDesignator, const opencascade::handle<StepRepr_AssemblyComponentUsage>& aUpperUsage, const opencascade::handle<StepRepr_NextAssemblyUsageOccurrence>& aNextUsage);
  void Init(const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Id, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Name, bool hasProductDefinitionRelationship_Description, const opencascade::handle<TCollection_HAsciiString>& aProductDefinitionRelationship_Description, const StepBasic_ProductDefinitionOrReference& aProductDefinitionRelationship_RelatingProductDefinition, const StepBasic_ProductDefinitionOrReference& aProductDefinitionRelationship_RelatedProductDefinition, bool hasAssemblyComponentUsage_ReferenceDesignator, const opencascade::handle<TCollection_HAsciiString>& aAssemblyComponentUsage_ReferenceDesignator, const opencascade::handle<StepRepr_AssemblyComponentUsage>& aUpperUsage, const opencascade::handle<StepRepr_NextAssemblyUsageOccurrence>& aNextUsage);
  opencascade::handle<StepRepr_AssemblyComponentUsage> UpperUsage() const;
  void SetUpperUsage(const opencascade::handle<StepRepr_AssemblyComponentUsage>& UpperUsage);
  opencascade::handle<StepRepr_NextAssemblyUsageOccurrence> NextUsage() const;
  void SetNextUsage(const opencascade::handle<StepRepr_NextAssemblyUsageOccurrence>& NextUsage);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_StructuralResponseProperty : public StepRepr_PropertyDefinition {
public:
  StepRepr_StructuralResponseProperty();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_StructuralResponsePropertyDefinitionRepresentation : public StepRepr_PropertyDefinitionRepresentation {
public:
  StepRepr_StructuralResponsePropertyDefinitionRepresentation();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_SuppliedPartRelationship : public StepBasic_ProductDefinitionRelationship {
public:
  StepRepr_SuppliedPartRelationship();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_Tangent : public StepRepr_DerivedShapeAspect {
public:
  StepRepr_Tangent();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ValueRange : public StepRepr_CompoundRepresentationItem {
public:
  StepRepr_ValueRange();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class StepRepr_ValueRepresentationItem : public StepRepr_RepresentationItem {
public:
  StepRepr_ValueRepresentationItem();
  void Init(const opencascade::handle<TCollection_HAsciiString>& theName, const opencascade::handle<StepBasic_MeasureValueMember>& theValueComponentMember);
  void SetValueComponentMember(const opencascade::handle<StepBasic_MeasureValueMember>& theValueComponentMember);
  opencascade::handle<StepBasic_MeasureValueMember> ValueComponentMember() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};
