// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* TopoDSToStep: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module TopoDSToStepModule

%include "NetOcc.i"

%{
#include <TopoDSToStep_module.hxx>
%}

%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "NCollection.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "GeomAbs.i"
%import "gp.i"
%import "TColgp.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "GeomEval.i"
%import "Geom.i"
%import "TopAbs.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "TopLoc.i"
%import "TopoDS.i"
%import "BRepAdaptor.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "IntCurvesFace.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "BVH.i"
%import "Bnd.i"
%import "TopTools.i"
%import "Resource.i"
%import "CDM.i"
%import "LDOM.i"
%import "Storage.i"
%import "PCDM.i"
%import "CDF.i"
%import "TDF.i"
%import "TDocStd.i"
%import "DE.i"
%import "Interface.i"
%import "IFGraph.i"
%import "IFSelect.i"
%import "TColGeom.i"
%import "ShapeExtend.i"
%import "TShort.i"
%import "Poly.i"
%import "BRep.i"
%import "BRepTools.i"
%import "ShapeBuild.i"
%import "ShapeProcess.i"
%import "XSAlgo.i"
%import "Transfer.i"
%import "XSControl.i"
%import "MoniTool.i"
%import "StepData.i"
%import "StepRepr.i"
%import "StepBasic.i"
%import "StepGeom.i"
%import "StepShape.i"
%import "StepVisual.i"
%netocc_csimports(using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.GeomAbs; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.TopAbs; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.TopLoc; using OCC.Core.TopoDS; using OCC.Core.BRepAdaptor; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.IntCurvesFace; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.BVH; using OCC.Core.Bnd; using OCC.Core.TopTools; using OCC.Core.Resource; using OCC.Core.CDM; using OCC.Core.LDOM; using OCC.Core.Storage; using OCC.Core.PCDM; using OCC.Core.CDF; using OCC.Core.TDF; using OCC.Core.TDocStd; using OCC.Core.DE; using OCC.Core.Interface; using OCC.Core.IFGraph; using OCC.Core.IFSelect; using OCC.Core.TColGeom; using OCC.Core.ShapeExtend; using OCC.Core.TShort; using OCC.Core.Poly; using OCC.Core.BRep; using OCC.Core.BRepTools; using OCC.Core.ShapeBuild; using OCC.Core.ShapeProcess; using OCC.Core.XSAlgo; using OCC.Core.Transfer; using OCC.Core.XSControl; using OCC.Core.MoniTool; using OCC.Core.StepData; using OCC.Core.StepRepr; using OCC.Core.StepBasic; using OCC.Core.StepGeom; using OCC.Core.StepShape; using OCC.Core.StepVisual;)

%occt_valueclass(TopoDSToStep)
%occt_valueclass(TopoDSToStep_Root)
%nodefaultctor TopoDSToStep_Root;
%feature("valuewrapper") TopoDSToStep_Root;
%occt_valueclass(TopoDSToStep_Builder)
%occt_valueclass(TopoDSToStep_FacetedTool)
%occt_valueclass(TopoDSToStep_MakeBrepWithVoids)
%nodefaultctor TopoDSToStep_MakeBrepWithVoids;
%feature("valuewrapper") TopoDSToStep_MakeBrepWithVoids;
%occt_valueclass(TopoDSToStep_MakeFacetedBrep)
%nodefaultctor TopoDSToStep_MakeFacetedBrep;
%feature("valuewrapper") TopoDSToStep_MakeFacetedBrep;
%occt_valueclass(TopoDSToStep_MakeFacetedBrepAndBrepWithVoids)
%nodefaultctor TopoDSToStep_MakeFacetedBrepAndBrepWithVoids;
%feature("valuewrapper") TopoDSToStep_MakeFacetedBrepAndBrepWithVoids;
%occt_valueclass(TopoDSToStep_MakeGeometricCurveSet)
%nodefaultctor TopoDSToStep_MakeGeometricCurveSet;
%feature("valuewrapper") TopoDSToStep_MakeGeometricCurveSet;
%occt_valueclass(TopoDSToStep_MakeManifoldSolidBrep)
%nodefaultctor TopoDSToStep_MakeManifoldSolidBrep;
%feature("valuewrapper") TopoDSToStep_MakeManifoldSolidBrep;
%occt_valueclass(TopoDSToStep_MakeShellBasedSurfaceModel)
%nodefaultctor TopoDSToStep_MakeShellBasedSurfaceModel;
%feature("valuewrapper") TopoDSToStep_MakeShellBasedSurfaceModel;
%occt_valueclass(TopoDSToStep_MakeStepEdge)
%occt_valueclass(TopoDSToStep_MakeStepFace)
%occt_valueclass(TopoDSToStep_MakeStepVertex)
%occt_valueclass(TopoDSToStep_MakeStepWire)
%occt_valueclass(TopoDSToStep_MakeTessellatedItem)
%occt_valueclass(TopoDSToStep_Tool)
%nodefaultctor TopoDSToStep_Tool;
%feature("valuewrapper") TopoDSToStep_Tool;
%occt_valueclass(TopoDSToStep_WireframeBuilder)

enum TopoDSToStep_BuilderError {
  TopoDSToStep_BuilderDone = 0,
  TopoDSToStep_NoFaceMapped = 1,
  TopoDSToStep_BuilderOther = 2,
};

enum TopoDSToStep_MakeFaceError {
  TopoDSToStep_FaceDone = 0,
  TopoDSToStep_InfiniteFace = 1,
  TopoDSToStep_NonManifoldFace = 2,
  TopoDSToStep_NoWireMapped = 3,
  TopoDSToStep_FaceOther = 4,
};

enum TopoDSToStep_MakeWireError {
  TopoDSToStep_WireDone = 0,
  TopoDSToStep_NonManifoldWire = 1,
  TopoDSToStep_WireOther = 2,
};

enum TopoDSToStep_MakeEdgeError {
  TopoDSToStep_EdgeDone = 0,
  TopoDSToStep_NonManifoldEdge = 1,
  TopoDSToStep_EdgeOther = 2,
};

enum TopoDSToStep_MakeVertexError {
  TopoDSToStep_VertexDone = 0,
  TopoDSToStep_VertexOther = 1,
};

enum TopoDSToStep_FacetedError {
  TopoDSToStep_FacetedDone = 0,
  TopoDSToStep_SurfaceNotPlane = 1,
  TopoDSToStep_PCurveNotLinear = 2,
};

class TopoDSToStep {
public:
  TopoDSToStep();
  static opencascade::handle<TCollection_HAsciiString> DecodeBuilderError(TopoDSToStep_BuilderError E);
  static opencascade::handle<TCollection_HAsciiString> DecodeFaceError(TopoDSToStep_MakeFaceError E);
  static opencascade::handle<TCollection_HAsciiString> DecodeWireError(TopoDSToStep_MakeWireError E);
  static opencascade::handle<TCollection_HAsciiString> DecodeEdgeError(TopoDSToStep_MakeEdgeError E);
  static opencascade::handle<TCollection_HAsciiString> DecodeVertexError(TopoDSToStep_MakeVertexError E);
  static void AddResult(const opencascade::handle<Transfer_FinderProcess>& FP, const TopoDS_Shape& Shape, const opencascade::handle<Standard_Transient>& entity);
  static void AddResult(const opencascade::handle<Transfer_FinderProcess>& FP, const TopoDSToStep_Tool& Tool);
};

class TopoDSToStep_Root {
public:
  double& Tolerance();
  bool IsDone() const;
};

class TopoDSToStep_Builder : public TopoDSToStep_Root {
public:
  TopoDSToStep_Builder();
  TopoDSToStep_Builder(const TopoDS_Shape& S, TopoDSToStep_Tool& T, const opencascade::handle<Transfer_FinderProcess>& FP, int theTessellatedGeomParam, const StepData_Factors& theLocalFactors = StepData_Factors());
  void Init(const TopoDS_Shape& S, TopoDSToStep_Tool& T, const opencascade::handle<Transfer_FinderProcess>& FP, int theTessellatedGeomParam, const StepData_Factors& theLocalFactors = StepData_Factors());
  TopoDSToStep_BuilderError Error() const;
  const opencascade::handle<StepShape_TopologicalRepresentationItem>& Value() const;
  const opencascade::handle<StepVisual_TessellatedItem>& TessellatedValue() const;
};

class TopoDSToStep_FacetedTool {
public:
  TopoDSToStep_FacetedTool();
  static TopoDSToStep_FacetedError CheckTopoDSShape(const TopoDS_Shape& SH);
};

class TopoDSToStep_MakeBrepWithVoids : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeBrepWithVoids(const TopoDS_Solid& S, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  const opencascade::handle<StepShape_BrepWithVoids>& Value() const;
  const opencascade::handle<StepVisual_TessellatedItem>& TessellatedValue() const;
};

class TopoDSToStep_MakeFacetedBrep : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeFacetedBrep(const TopoDS_Shell& S, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  TopoDSToStep_MakeFacetedBrep(const TopoDS_Solid& S, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  const opencascade::handle<StepShape_FacetedBrep>& Value() const;
  const opencascade::handle<StepVisual_TessellatedItem>& TessellatedValue() const;
};

class TopoDSToStep_MakeFacetedBrepAndBrepWithVoids : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeFacetedBrepAndBrepWithVoids(const TopoDS_Solid& S, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  const opencascade::handle<StepShape_FacetedBrepAndBrepWithVoids>& Value() const;
  const opencascade::handle<StepVisual_TessellatedItem>& TessellatedValue() const;
};

class TopoDSToStep_MakeGeometricCurveSet : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeGeometricCurveSet(const TopoDS_Shape& SH, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  const opencascade::handle<StepShape_GeometricCurveSet>& Value() const;
};

class TopoDSToStep_MakeManifoldSolidBrep : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeManifoldSolidBrep(const TopoDS_Shell& S, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  TopoDSToStep_MakeManifoldSolidBrep(const TopoDS_Solid& S, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  const opencascade::handle<StepShape_ManifoldSolidBrep>& Value() const;
  const opencascade::handle<StepVisual_TessellatedItem>& TessellatedValue() const;
};

class TopoDSToStep_MakeShellBasedSurfaceModel : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeShellBasedSurfaceModel(const TopoDS_Face& F, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  TopoDSToStep_MakeShellBasedSurfaceModel(const TopoDS_Shell& S, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  TopoDSToStep_MakeShellBasedSurfaceModel(const TopoDS_Solid& S, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  const opencascade::handle<StepShape_ShellBasedSurfaceModel>& Value() const;
  const opencascade::handle<StepVisual_TessellatedItem>& TessellatedValue() const;
};

class TopoDSToStep_MakeStepEdge : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeStepEdge();
  TopoDSToStep_MakeStepEdge(const TopoDS_Edge& E, TopoDSToStep_Tool& T, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  void Init(const TopoDS_Edge& E, TopoDSToStep_Tool& T, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  const opencascade::handle<StepShape_TopologicalRepresentationItem>& Value() const;
  TopoDSToStep_MakeEdgeError Error() const;
};

class TopoDSToStep_MakeStepFace : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeStepFace();
  TopoDSToStep_MakeStepFace(const TopoDS_Face& F, TopoDSToStep_Tool& T, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  void Init(const TopoDS_Face& F, TopoDSToStep_Tool& T, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  const opencascade::handle<StepShape_TopologicalRepresentationItem>& Value() const;
  TopoDSToStep_MakeFaceError Error() const;
};

class TopoDSToStep_MakeStepVertex : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeStepVertex();
  TopoDSToStep_MakeStepVertex(const TopoDS_Vertex& V, TopoDSToStep_Tool& T, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  void Init(const TopoDS_Vertex& V, TopoDSToStep_Tool& T, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  const opencascade::handle<StepShape_TopologicalRepresentationItem>& Value() const;
  TopoDSToStep_MakeVertexError Error() const;
};

class TopoDSToStep_MakeStepWire : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeStepWire();
  TopoDSToStep_MakeStepWire(const TopoDS_Wire& W, TopoDSToStep_Tool& T, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  void Init(const TopoDS_Wire& W, TopoDSToStep_Tool& T, const opencascade::handle<Transfer_FinderProcess>& FP, const StepData_Factors& theLocalFactors = StepData_Factors());
  const opencascade::handle<StepShape_TopologicalRepresentationItem>& Value() const;
  TopoDSToStep_MakeWireError Error() const;
};

class TopoDSToStep_MakeTessellatedItem : public TopoDSToStep_Root {
public:
  TopoDSToStep_MakeTessellatedItem();
  TopoDSToStep_MakeTessellatedItem(const TopoDS_Face& theFace, TopoDSToStep_Tool& theTool, const opencascade::handle<Transfer_FinderProcess>& theFP, bool theToPreferSurfaceSet, const StepData_Factors& theLocalFactors);
  TopoDSToStep_MakeTessellatedItem(const TopoDS_Shell& theShell, TopoDSToStep_Tool& theTool, const opencascade::handle<Transfer_FinderProcess>& theFP, const StepData_Factors& theLocalFactors);
  void Init(const TopoDS_Face& theFace, TopoDSToStep_Tool& theTool, const opencascade::handle<Transfer_FinderProcess>& theFP, bool theToPreferSurfaceSet, const StepData_Factors& theLocalFactors);
  void Init(const TopoDS_Shell& theShell, TopoDSToStep_Tool& theTool, const opencascade::handle<Transfer_FinderProcess>& theFP, const StepData_Factors& theLocalFactors);
  const opencascade::handle<StepVisual_TessellatedItem>& Value() const;
};

class TopoDSToStep_Tool {
public:
  TopoDSToStep_Tool(const opencascade::handle<StepData_StepModel>& theModel);
  TopoDSToStep_Tool(const NCollection_DataMap<TopoDS_Shape, opencascade::handle<Standard_Transient>, TopTools_ShapeMapHasher>& M, bool FacetedContext, int theSurfCurveMode);
  void Init(const NCollection_DataMap<TopoDS_Shape, opencascade::handle<Standard_Transient>, TopTools_ShapeMapHasher>& M, bool FacetedContext, int theSurfCurveMode);
  bool IsBound(const TopoDS_Shape& S);
  void Bind(const TopoDS_Shape& S, const opencascade::handle<StepShape_TopologicalRepresentationItem>& T);
  opencascade::handle<StepShape_TopologicalRepresentationItem> Find(const TopoDS_Shape& S);
  bool Faceted() const;
  void SetCurrentShell(const TopoDS_Shell& S);
  const TopoDS_Shell& CurrentShell() const;
  void SetCurrentFace(const TopoDS_Face& F);
  const TopoDS_Face& CurrentFace() const;
  void SetCurrentWire(const TopoDS_Wire& W);
  const TopoDS_Wire& CurrentWire() const;
  void SetCurrentEdge(const TopoDS_Edge& E);
  const TopoDS_Edge& CurrentEdge() const;
  void SetCurrentVertex(const TopoDS_Vertex& V);
  const TopoDS_Vertex& CurrentVertex() const;
  double Lowest3DTolerance() const;
  void SetSurfaceReversed(bool B);
  bool SurfaceReversed() const;
  const NCollection_DataMap<TopoDS_Shape, opencascade::handle<Standard_Transient>, TopTools_ShapeMapHasher>& Map() const;
  int PCurveMode() const;
};

class TopoDSToStep_WireframeBuilder : public TopoDSToStep_Root {
public:
  TopoDSToStep_WireframeBuilder();
  TopoDSToStep_WireframeBuilder(const TopoDS_Shape& S, TopoDSToStep_Tool& T, const StepData_Factors& theLocalFactors = StepData_Factors());
  void Init(const TopoDS_Shape& S, TopoDSToStep_Tool& T, const StepData_Factors& theLocalFactors = StepData_Factors());
  TopoDSToStep_BuilderError Error() const;
  const opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>>& Value() const;
  bool GetTrimmedCurveFromEdge(const TopoDS_Edge& E, const TopoDS_Face& F, NCollection_DataMap<TopoDS_Shape, opencascade::handle<Standard_Transient>, TopTools_ShapeMapHasher>& M, opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>>& L, const StepData_Factors& theLocalFactors = StepData_Factors()) const;
  bool GetTrimmedCurveFromFace(const TopoDS_Face& F, NCollection_DataMap<TopoDS_Shape, opencascade::handle<Standard_Transient>, TopTools_ShapeMapHasher>& M, opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>>& L, const StepData_Factors& theLocalFactors = StepData_Factors()) const;
  bool GetTrimmedCurveFromShape(const TopoDS_Shape& S, NCollection_DataMap<TopoDS_Shape, opencascade::handle<Standard_Transient>, TopTools_ShapeMapHasher>& M, opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>>& L, const StepData_Factors& theLocalFactors = StepData_Factors()) const;
};
