// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* TopOpeBRepDS: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module TopOpeBRepDSModule

%include "NetOcc.i"

%{
#include <TopOpeBRepDS_module.hxx>
%}

%import "GeomAbs.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "gp.i"
%import "TColgp.i"
%import "GeomEval.i"
%import "Geom.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "TopAbs.i"
%import "Adaptor2d.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "TopLoc.i"
%import "TopoDS.i"
%import "BRepAdaptor.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "IntCurvesFace.i"
%import "TopTools.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "BVH.i"
%import "Bnd.i"
%import "TopExp.i"
%import "TopOpeBRepTool.i"
%import "TopOpeBRep.i"
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.TopAbs; using OCC.Core.Adaptor2d; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.TopLoc; using OCC.Core.TopoDS; using OCC.Core.BRepAdaptor; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.IntCurvesFace; using OCC.Core.TopTools; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.BVH; using OCC.Core.Bnd; using OCC.Core.TopExp; using OCC.Core.TopOpeBRepTool; using OCC.Core.TopOpeBRep;)

%occt_valueclass(TopOpeBRepDS)
%occt_valueclass(TopOpeBRepDS_Transition)
%occt_transient(TopOpeBRepDS_Interference)
%occt_transient(TopOpeBRepDS_Association)
%occt_valueclass(TopOpeBRepDS_BuildTool)
%occt_transient(TopOpeBRepDS_Check)
%occt_valueclass(TopOpeBRepDS_Curve)
%occt_valueclass(TopOpeBRepDS_GeometryData)
%occt_valueclass(TopOpeBRepDS_CurveData)
%occt_valueclass(TopOpeBRepDS_CurveExplorer)
%occt_valueclass(TopOpeBRepDS_InterferenceIterator)
%occt_valueclass(TopOpeBRepDS_CurveIterator)
%nodefaultctor TopOpeBRepDS_CurveIterator;
%feature("valuewrapper") TopOpeBRepDS_CurveIterator;
%occt_transient(TopOpeBRepDS_CurvePointInterference)
%nodefaultctor TopOpeBRepDS_CurvePointInterference;
%feature("valuewrapper") TopOpeBRepDS_CurvePointInterference;
%occt_valueclass(TopOpeBRepDS_Surface)
%occt_valueclass(TopOpeBRepDS_SurfaceData)
%occt_valueclass(TopOpeBRepDS_Point)
%occt_valueclass(TopOpeBRepDS_PointData)
%occt_valueclass(TopOpeBRepDS_ShapeData)
%occt_valueclass(TopOpeBRepDS_ShapeWithState)
%occt_valueclass(TopOpeBRepDS_DataStructure)
%occt_valueclass(TopOpeBRepDS_Dumper)
%nodefaultctor TopOpeBRepDS_Dumper;
%feature("valuewrapper") TopOpeBRepDS_Dumper;
%occt_valueclass(TopOpeBRepDS_EIR)
%nodefaultctor TopOpeBRepDS_EIR;
%feature("valuewrapper") TopOpeBRepDS_EIR;
%occt_transient(TopOpeBRepDS_ShapeShapeInterference)
%nodefaultctor TopOpeBRepDS_ShapeShapeInterference;
%feature("valuewrapper") TopOpeBRepDS_ShapeShapeInterference;
%occt_transient(TopOpeBRepDS_EdgeVertexInterference)
%nodefaultctor TopOpeBRepDS_EdgeVertexInterference;
%feature("valuewrapper") TopOpeBRepDS_EdgeVertexInterference;
%occt_transient(TopOpeBRepDS_FaceEdgeInterference)
%nodefaultctor TopOpeBRepDS_FaceEdgeInterference;
%feature("valuewrapper") TopOpeBRepDS_FaceEdgeInterference;
%occt_transient(TopOpeBRepDS_HDataStructure)
%occt_valueclass(TopOpeBRepDS_ListOfShapeOn1State)
%occt_valueclass(TopOpeBRepDS_Edge3dInterferenceTool)
%occt_valueclass(TopOpeBRepDS_EdgeInterferenceTool)
%occt_valueclass(TopOpeBRepDS_Explorer)
%occt_valueclass(TopOpeBRepDS_FIR)
%nodefaultctor TopOpeBRepDS_FIR;
%feature("valuewrapper") TopOpeBRepDS_FIR;
%occt_valueclass(TopOpeBRepDS_FaceInterferenceTool)
%nodefaultctor TopOpeBRepDS_FaceInterferenceTool;
%feature("valuewrapper") TopOpeBRepDS_FaceInterferenceTool;
%occt_valueclass(TopOpeBRepDS_Filter)
%nodefaultctor TopOpeBRepDS_Filter;
%feature("valuewrapper") TopOpeBRepDS_Filter;
%occt_valueclass(TopOpeBRepDS_GapFiller)
%nodefaultctor TopOpeBRepDS_GapFiller;
%feature("valuewrapper") TopOpeBRepDS_GapFiller;
%occt_transient(TopOpeBRepDS_GapTool)
%occt_valueclass(TopOpeBRepDS_InterferenceTool)
%occt_transient(TopOpeBRepDS_Marker)
%occt_valueclass(TopOpeBRepDS_PointExplorer)
%occt_valueclass(TopOpeBRepDS_PointIterator)
%nodefaultctor TopOpeBRepDS_PointIterator;
%feature("valuewrapper") TopOpeBRepDS_PointIterator;
%occt_valueclass(TopOpeBRepDS_Reducer)
%nodefaultctor TopOpeBRepDS_Reducer;
%feature("valuewrapper") TopOpeBRepDS_Reducer;
%occt_transient(TopOpeBRepDS_SolidSurfaceInterference)
%nodefaultctor TopOpeBRepDS_SolidSurfaceInterference;
%feature("valuewrapper") TopOpeBRepDS_SolidSurfaceInterference;
%occt_transient(TopOpeBRepDS_SurfaceCurveInterference)
%occt_valueclass(TopOpeBRepDS_SurfaceExplorer)
%occt_valueclass(TopOpeBRepDS_SurfaceIterator)
%nodefaultctor TopOpeBRepDS_SurfaceIterator;
%feature("valuewrapper") TopOpeBRepDS_SurfaceIterator;
%occt_valueclass(TopOpeBRepDS_TKI)
%occt_valueclass(TopOpeBRepDS_TOOL)
%occt_valueclass(TopTools_ListIteratorOfListOfShape)

enum TopOpeBRepDS_Kind {
  TopOpeBRepDS_POINT = 0,
  TopOpeBRepDS_CURVE = 1,
  TopOpeBRepDS_SURFACE = 2,
  TopOpeBRepDS_VERTEX = 3,
  TopOpeBRepDS_EDGE = 4,
  TopOpeBRepDS_WIRE = 5,
  TopOpeBRepDS_FACE = 6,
  TopOpeBRepDS_SHELL = 7,
  TopOpeBRepDS_SOLID = 8,
  TopOpeBRepDS_COMPSOLID = 9,
  TopOpeBRepDS_COMPOUND = 10,
  TopOpeBRepDS_UNKNOWN = 11,
};

enum TopOpeBRepDS_Config {
  TopOpeBRepDS_UNSHGEOMETRY = 0,
  TopOpeBRepDS_SAMEORIENTED = 1,
  TopOpeBRepDS_DIFFORIENTED = 2,
};

enum TopOpeBRepDS_CheckStatus {
  TopOpeBRepDS_OK = 0,
  TopOpeBRepDS_NOK = 1,
};

%occt_datamap(TopOpeBRepDS_DataMapOfShapeListOfShapeOn1State, TopoDS_Shape, TopOpeBRepDS_ListOfShapeOn1State, TopTools_ShapeMapHasher, TopoDS_Shape, TopOpeBRepDS_ListOfShapeOn1State)
%occt_datamap(TopOpeBRepDS_DataMapOfShapeState, TopoDS_Shape, TopAbs_State, TopTools_ShapeMapHasher, TopoDS_Shape, TopAbs_State)
%occt_indexeddatamap(TopOpeBRepDS_IndexedDataMapOfShapeWithState, TopoDS_Shape, TopOpeBRepDS_ShapeWithState, TopTools_ShapeMapHasher, TopoDS_Shape, TopOpeBRepDS_ShapeWithState)
%occt_list(TopOpeBRepDS_ListOfInterference, opencascade::handle<TopOpeBRepDS_Interference>, TopOpeBRepDS_Interference)
%occt_indexeddatamap(TopOpeBRepDS_MapOfShapeData, TopoDS_Shape, TopOpeBRepDS_ShapeData, TopTools_ShapeMapHasher, TopoDS_Shape, TopOpeBRepDS_ShapeData)

class TopOpeBRepDS {
public:
  TopOpeBRepDS();
  static TCollection_AsciiString SPrint(TopAbs_State S);
  static void Print(TopAbs_State S, std::ostream& OS);
  static TCollection_AsciiString SPrint(TopOpeBRepDS_Kind K);
  static TCollection_AsciiString SPrint(TopOpeBRepDS_Kind K, int I, const TCollection_AsciiString& B = "", const TCollection_AsciiString& A = "");
  static void Print(TopOpeBRepDS_Kind K, std::ostream& S);
  static void Print(TopOpeBRepDS_Kind K, int I, std::ostream& S, const TCollection_AsciiString& B = "", const TCollection_AsciiString& A = "");
  static TCollection_AsciiString SPrint(TopAbs_ShapeEnum T);
  static TCollection_AsciiString SPrint(TopAbs_ShapeEnum T, int I);
  static void Print(TopAbs_ShapeEnum T, int I, std::ostream& S);
  static TCollection_AsciiString SPrint(TopAbs_Orientation O);
  static TCollection_AsciiString SPrint(TopOpeBRepDS_Config C);
  static void Print(TopOpeBRepDS_Config C, std::ostream& S);
  static bool IsGeometry(TopOpeBRepDS_Kind K);
  static bool IsTopology(TopOpeBRepDS_Kind K);
  static TopAbs_ShapeEnum KindToShape(TopOpeBRepDS_Kind K);
  static TopOpeBRepDS_Kind ShapeToKind(TopAbs_ShapeEnum S);
};

class TopOpeBRepDS_Transition {
public:
  TopOpeBRepDS_Transition();
  TopOpeBRepDS_Transition(TopAbs_State StateBefore, TopAbs_State StateAfter, TopAbs_ShapeEnum ShapeBefore = TopAbs_FACE, TopAbs_ShapeEnum ShapeAfter = TopAbs_FACE);
  TopOpeBRepDS_Transition(TopAbs_Orientation O);
  void Set(TopAbs_State StateBefore, TopAbs_State StateAfter, TopAbs_ShapeEnum ShapeBefore = TopAbs_FACE, TopAbs_ShapeEnum ShapeAfter = TopAbs_FACE);
  void StateBefore(TopAbs_State S);
  void StateAfter(TopAbs_State S);
  void ShapeBefore(TopAbs_ShapeEnum SE);
  void ShapeAfter(TopAbs_ShapeEnum SE);
  void Before(TopAbs_State S, TopAbs_ShapeEnum ShapeBefore = TopAbs_FACE);
  void After(TopAbs_State S, TopAbs_ShapeEnum ShapeAfter = TopAbs_FACE);
  void Index(int I);
  void IndexBefore(int I);
  void IndexAfter(int I);
  TopAbs_State Before() const;
  TopAbs_ShapeEnum ONBefore() const;
  TopAbs_State After() const;
  TopAbs_ShapeEnum ONAfter() const;
  TopAbs_ShapeEnum ShapeBefore() const;
  TopAbs_ShapeEnum ShapeAfter() const;
  int Index() const;
  int IndexBefore() const;
  int IndexAfter() const;
  void Set(TopAbs_Orientation O);
  TopAbs_Orientation Orientation(TopAbs_State S, TopAbs_ShapeEnum T = TopAbs_FACE) const;
  TopOpeBRepDS_Transition Complement() const;
  bool IsUnknown() const;
};

class TopOpeBRepDS_Interference : public Standard_Transient {
public:
  TopOpeBRepDS_Interference();
  TopOpeBRepDS_Interference(const TopOpeBRepDS_Transition& Transition, TopOpeBRepDS_Kind SupportType, int Support, TopOpeBRepDS_Kind GeometryType, int Geometry);
  TopOpeBRepDS_Interference(const opencascade::handle<TopOpeBRepDS_Interference>& I);
  const TopOpeBRepDS_Transition& Transition() const;
  TopOpeBRepDS_Transition& ChangeTransition();
  void Transition(const TopOpeBRepDS_Transition& T);
  void GKGSKS(TopOpeBRepDS_Kind& GK, int& G, TopOpeBRepDS_Kind& SK, int& S) const;
  TopOpeBRepDS_Kind SupportType() const;
  int Support() const;
  TopOpeBRepDS_Kind GeometryType() const;
  int Geometry() const;
  void SetGeometry(int GI);
  void SupportType(TopOpeBRepDS_Kind ST);
  void Support(int S);
  void GeometryType(TopOpeBRepDS_Kind GT);
  void Geometry(int G);
  bool HasSameSupport(const opencascade::handle<TopOpeBRepDS_Interference>& Other) const;
  bool HasSameGeometry(const opencascade::handle<TopOpeBRepDS_Interference>& Other) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_Association : public Standard_Transient {
public:
  TopOpeBRepDS_Association();
  void Associate(const opencascade::handle<TopOpeBRepDS_Interference>& I, const opencascade::handle<TopOpeBRepDS_Interference>& K);
  void Associate(const opencascade::handle<TopOpeBRepDS_Interference>& I, const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI);
  bool HasAssociation(const opencascade::handle<TopOpeBRepDS_Interference>& I) const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& Associated(const opencascade::handle<TopOpeBRepDS_Interference>& I);
  bool AreAssociated(const opencascade::handle<TopOpeBRepDS_Interference>& I, const opencascade::handle<TopOpeBRepDS_Interference>& K) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_BuildTool {
public:
  TopOpeBRepDS_BuildTool();
  TopOpeBRepDS_BuildTool(TopOpeBRepTool_OutCurveType OutCurveType);
  TopOpeBRepDS_BuildTool(const TopOpeBRepTool_GeomTool& GT);
  const TopOpeBRepTool_GeomTool& GetGeomTool() const;
  TopOpeBRepTool_GeomTool& ChangeGeomTool();
  void MakeVertex(TopoDS_Shape& V, const TopOpeBRepDS_Point& P) const;
  void MakeEdge(TopoDS_Shape& E, const TopOpeBRepDS_Curve& C) const;
  void MakeEdge(TopoDS_Shape& E, const TopOpeBRepDS_Curve& C, const TopOpeBRepDS_DataStructure& DS) const;
  void MakeEdge(TopoDS_Shape& E, const opencascade::handle<Geom_Curve>& C, double Tol) const;
  void MakeEdge(TopoDS_Shape& E) const;
  void MakeWire(TopoDS_Shape& W) const;
  void MakeFace(TopoDS_Shape& F, const TopOpeBRepDS_Surface& S) const;
  void MakeShell(TopoDS_Shape& Sh) const;
  void MakeSolid(TopoDS_Shape& S) const;
  void CopyEdge(const TopoDS_Shape& Ein, TopoDS_Shape& Eou) const;
  void GetOrientedEdgeVertices(TopoDS_Edge& E, TopoDS_Vertex& Vmin, TopoDS_Vertex& Vmax, double& Parmin, double& Parmax) const;
  void UpdateEdgeCurveTol(const TopoDS_Face& F1, const TopoDS_Face& F2, TopoDS_Edge& E, const opencascade::handle<Geom_Curve>& C3Dnew, double tol3d, double tol2d1, double tol2d2, double& newtol, double& newparmin, double& newparmax) const;
  void ApproxCurves(const TopOpeBRepDS_Curve& C, TopoDS_Edge& E, int& inewC, const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS) const;
  void ComputePCurves(const TopOpeBRepDS_Curve& C, TopoDS_Edge& E, TopOpeBRepDS_Curve& newC, bool CompPC1, bool CompPC2, bool CompC3D) const;
  void PutPCurves(const TopOpeBRepDS_Curve& newC, TopoDS_Edge& E, bool CompPC1, bool CompPC2) const;
  void RecomputeCurves(const TopOpeBRepDS_Curve& C, const TopoDS_Edge& oldE, TopoDS_Edge& E, int& inewC, const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS) const;
  void CopyFace(const TopoDS_Shape& Fin, TopoDS_Shape& Fou) const;
  void AddEdgeVertex(const TopoDS_Shape& Ein, TopoDS_Shape& Eou, const TopoDS_Shape& V) const;
  void AddEdgeVertex(TopoDS_Shape& E, const TopoDS_Shape& V) const;
  void AddWireEdge(TopoDS_Shape& W, const TopoDS_Shape& E) const;
  void AddFaceWire(TopoDS_Shape& F, const TopoDS_Shape& W) const;
  void AddShellFace(TopoDS_Shape& Sh, const TopoDS_Shape& F) const;
  void AddSolidShell(TopoDS_Shape& S, const TopoDS_Shape& Sh) const;
  void Parameter(const TopoDS_Shape& E, const TopoDS_Shape& V, double P) const;
  void Range(const TopoDS_Shape& E, double first, double last) const;
  void UpdateEdge(const TopoDS_Shape& Ein, TopoDS_Shape& Eou) const;
  void Parameter(const TopOpeBRepDS_Curve& C, TopoDS_Shape& E, TopoDS_Shape& V) const;
  void Curve3D(TopoDS_Shape& E, const opencascade::handle<Geom_Curve>& C, double Tol) const;
  void PCurve(TopoDS_Shape& F, TopoDS_Shape& E, const opencascade::handle<Geom2d_Curve>& C) const;
  void PCurve(TopoDS_Shape& F, TopoDS_Shape& E, const TopOpeBRepDS_Curve& CDS, const opencascade::handle<Geom2d_Curve>& C) const;
  void Orientation(TopoDS_Shape& S, TopAbs_Orientation O) const;
  TopAbs_Orientation Orientation(const TopoDS_Shape& S) const;
  void Closed(TopoDS_Shape& S, bool B) const;
  bool Approximation() const;
  void UpdateSurface(const TopoDS_Shape& F, const opencascade::handle<Geom_Surface>& SU) const;
  void UpdateSurface(const TopoDS_Shape& E, const TopoDS_Shape& oldF, const TopoDS_Shape& newF) const;
  bool OverWrite() const;
  void OverWrite(bool O);
  bool Translate() const;
  void Translate(bool T);
};

class TopOpeBRepDS_Check : public Standard_Transient {
public:
  TopOpeBRepDS_Check();
  TopOpeBRepDS_Check(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS);
  bool ChkIntg();
  bool ChkIntgInterf(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI);
  bool CheckDS(int i, TopOpeBRepDS_Kind K);
  bool ChkIntgSamDom();
  bool CheckShapes(const NCollection_List<TopoDS_Shape>& LS) const;
  bool OneVertexOnPnt();
  const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS() const;
  opencascade::handle<TopOpeBRepDS_HDataStructure>& ChangeHDS();
  void PrintIntg(std::ostream& S);
  void Print(TopOpeBRepDS_CheckStatus stat, std::ostream& S);
  void PrintShape(TopAbs_ShapeEnum SE, std::ostream& S);
  void PrintShape(int index, std::ostream& S);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_Curve {
public:
  TopOpeBRepDS_Curve();
  TopOpeBRepDS_Curve(const opencascade::handle<Geom_Curve>& P, double T, bool IsWalk = false);
  void DefineCurve(const opencascade::handle<Geom_Curve>& P, double T, bool IsWalk);
  void Tolerance(double tol);
  void SetSCI(const opencascade::handle<TopOpeBRepDS_Interference>& I1, const opencascade::handle<TopOpeBRepDS_Interference>& I2);
  const opencascade::handle<TopOpeBRepDS_Interference>& GetSCI1() const;
  const opencascade::handle<TopOpeBRepDS_Interference>& GetSCI2() const;
  %csattributes GetSCI(opencascade::handle<TopOpeBRepDS_Interference>& theI1, opencascade::handle<TopOpeBRepDS_Interference>& theI2) const "[global::System.Obsolete(\"Deprecated in OCCT.\")]";
  void GetSCI(opencascade::handle<TopOpeBRepDS_Interference>& theI1, opencascade::handle<TopOpeBRepDS_Interference>& theI2) const;
  void SetShapes(const TopoDS_Shape& S1, const TopoDS_Shape& S2);
  void GetShapes(TopoDS_Shape& S1, TopoDS_Shape& S2) const;
  const TopoDS_Shape& Shape1() const;
  TopoDS_Shape& ChangeShape1();
  const TopoDS_Shape& Shape2() const;
  TopoDS_Shape& ChangeShape2();
  const opencascade::handle<Geom_Curve>& Curve() const;
  void SetRange(double First, double Last);
  bool Range(double& First, double& Last) const;
  double Tolerance() const;
  opencascade::handle<Geom_Curve>& ChangeCurve();
  void Curve(const opencascade::handle<Geom_Curve>& C3D, double Tol);
  const opencascade::handle<Geom2d_Curve>& Curve1() const;
  void Curve1(const opencascade::handle<Geom2d_Curve>& PC1);
  const opencascade::handle<Geom2d_Curve>& Curve2() const;
  void Curve2(const opencascade::handle<Geom2d_Curve>& PC2);
  bool IsWalk() const;
  void ChangeIsWalk(bool B);
  bool Keep() const;
  void ChangeKeep(bool B);
  int Mother() const;
  void ChangeMother(int I);
  int DSIndex() const;
  void ChangeDSIndex(int I);
};

class TopOpeBRepDS_GeometryData {
public:
  TopOpeBRepDS_GeometryData();
  void Assign(const TopOpeBRepDS_GeometryData& Other);
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& Interferences() const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ChangeInterferences();
  void AddInterference(const opencascade::handle<TopOpeBRepDS_Interference>& I);
};

class TopOpeBRepDS_CurveData : public TopOpeBRepDS_GeometryData {
public:
  TopOpeBRepDS_CurveData();
  TopOpeBRepDS_CurveData(const TopOpeBRepDS_Curve& C);
};

class TopOpeBRepDS_CurveExplorer {
public:
  TopOpeBRepDS_CurveExplorer();
  TopOpeBRepDS_CurveExplorer(const TopOpeBRepDS_DataStructure& DS, bool FindOnlyKeep = true);
  void Init(const TopOpeBRepDS_DataStructure& DS, bool FindOnlyKeep = true);
  bool More() const;
  void Next();
  const TopOpeBRepDS_Curve& Curve() const;
  bool IsCurve(int I) const;
  bool IsCurveKeep(int I) const;
  const TopOpeBRepDS_Curve& Curve(int I) const;
  int NbCurve();
  int Index() const;
};

class TopOpeBRepDS_InterferenceIterator {
public:
  TopOpeBRepDS_InterferenceIterator();
  TopOpeBRepDS_InterferenceIterator(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L);
  void Init(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L);
  void GeometryKind(TopOpeBRepDS_Kind GK);
  void Geometry(int G);
  void SupportKind(TopOpeBRepDS_Kind ST);
  void Support(int S);
  void Match();
  bool MatchInterference(const opencascade::handle<TopOpeBRepDS_Interference>& I) const;
  bool More() const;
  void Next();
  const opencascade::handle<TopOpeBRepDS_Interference>& Value() const;
  TopOpeBRepDS_ListIteratorOfListOfInterference& ChangeIterator();
};

class TopOpeBRepDS_CurveIterator : public TopOpeBRepDS_InterferenceIterator {
public:
  TopOpeBRepDS_CurveIterator(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L);
  bool MatchInterference(const opencascade::handle<TopOpeBRepDS_Interference>& I) const;
  int Current() const;
  TopAbs_Orientation Orientation(TopAbs_State S) const;
  const opencascade::handle<Geom2d_Curve>& PCurve() const;
};

class TopOpeBRepDS_CurvePointInterference : public TopOpeBRepDS_Interference {
public:
  TopOpeBRepDS_CurvePointInterference(const TopOpeBRepDS_Transition& T, TopOpeBRepDS_Kind ST, int S, TopOpeBRepDS_Kind GT, int G, double P);
  double Parameter() const;
  void Parameter(double P);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_Surface {
public:
  TopOpeBRepDS_Surface();
  TopOpeBRepDS_Surface(const opencascade::handle<Geom_Surface>& P, double T);
  void Assign(const TopOpeBRepDS_Surface& Other);
  const opencascade::handle<Geom_Surface>& Surface() const;
  double Tolerance() const;
  void Tolerance(double theTol);
  bool Keep() const;
  void ChangeKeep(bool theToKeep);
};

class TopOpeBRepDS_SurfaceData : public TopOpeBRepDS_GeometryData {
public:
  TopOpeBRepDS_SurfaceData();
  TopOpeBRepDS_SurfaceData(const TopOpeBRepDS_Surface& S);
};

class TopOpeBRepDS_Point {
public:
  TopOpeBRepDS_Point();
  TopOpeBRepDS_Point(const gp_Pnt& P, double T);
  TopOpeBRepDS_Point(const TopoDS_Shape& S);
  bool IsEqual(const TopOpeBRepDS_Point& other) const;
  const gp_Pnt& Point() const;
  gp_Pnt& ChangePoint();
  double Tolerance() const;
  void Tolerance(double Tol);
  bool Keep() const;
  void ChangeKeep(bool B);
};

class TopOpeBRepDS_PointData : public TopOpeBRepDS_GeometryData {
public:
  TopOpeBRepDS_PointData();
  TopOpeBRepDS_PointData(const TopOpeBRepDS_Point& P);
  TopOpeBRepDS_PointData(const TopOpeBRepDS_Point& P, int I1, int I2);
  void SetShapes(int I1, int I2);
  void GetShapes(int& I1, int& I2) const;
};

class TopOpeBRepDS_ShapeData {
public:
  TopOpeBRepDS_ShapeData();
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& Interferences() const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ChangeInterferences();
  bool Keep() const;
  void ChangeKeep(bool B);
};

class TopOpeBRepDS_ShapeWithState {
public:
  TopOpeBRepDS_ShapeWithState();
  const NCollection_List<TopoDS_Shape>& Part(TopAbs_State aState) const;
  void AddPart(const TopoDS_Shape& aShape, TopAbs_State aState);
  void AddParts(const NCollection_List<TopoDS_Shape>& aListOfShape, TopAbs_State aState);
  void SetState(TopAbs_State aState);
  TopAbs_State State() const;
  void SetIsSplitted(bool anIsSplitted);
  bool IsSplitted() const;
};

class TopOpeBRepDS_DataStructure {
public:
  TopOpeBRepDS_DataStructure();
  void Init();
  int AddSurface(const TopOpeBRepDS_Surface& S);
  void RemoveSurface(int I);
  bool KeepSurface(int I) const;
  bool KeepSurface(TopOpeBRepDS_Surface& S) const;
  void ChangeKeepSurface(int I, bool FindKeep);
  void ChangeKeepSurface(TopOpeBRepDS_Surface& S, bool FindKeep);
  int AddCurve(const TopOpeBRepDS_Curve& S);
  void RemoveCurve(int I);
  bool KeepCurve(int I) const;
  bool KeepCurve(const TopOpeBRepDS_Curve& C) const;
  void ChangeKeepCurve(int I, bool FindKeep);
  void ChangeKeepCurve(TopOpeBRepDS_Curve& C, bool FindKeep);
  int AddPoint(const TopOpeBRepDS_Point& PDS);
  int AddPointSS(const TopOpeBRepDS_Point& PDS, const TopoDS_Shape& S1, const TopoDS_Shape& S2);
  void RemovePoint(int I);
  bool KeepPoint(int I) const;
  bool KeepPoint(const TopOpeBRepDS_Point& P) const;
  void ChangeKeepPoint(int I, bool FindKeep);
  void ChangeKeepPoint(TopOpeBRepDS_Point& P, bool FindKeep);
  int AddShape(const TopoDS_Shape& S);
  int AddShape(const TopoDS_Shape& S, int I);
  bool KeepShape(int I, bool FindKeep = true) const;
  bool KeepShape(const TopoDS_Shape& S, bool FindKeep = true) const;
  void ChangeKeepShape(int I, bool FindKeep);
  void ChangeKeepShape(const TopoDS_Shape& S, bool FindKeep);
  void InitSectionEdges();
  int AddSectionEdge(const TopoDS_Edge& E);
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& SurfaceInterferences(int I) const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ChangeSurfaceInterferences(int I);
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& CurveInterferences(int I) const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ChangeCurveInterferences(int I);
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& PointInterferences(int I) const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ChangePointInterferences(int I);
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ShapeInterferences(const TopoDS_Shape& S, bool FindKeep = true) const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ChangeShapeInterferences(const TopoDS_Shape& S);
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ShapeInterferences(int I, bool FindKeep = true) const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ChangeShapeInterferences(int I);
  const NCollection_List<TopoDS_Shape>& ShapeSameDomain(const TopoDS_Shape& S) const;
  NCollection_List<TopoDS_Shape>& ChangeShapeSameDomain(const TopoDS_Shape& S);
  const NCollection_List<TopoDS_Shape>& ShapeSameDomain(int I) const;
  NCollection_List<TopoDS_Shape>& ChangeShapeSameDomain(int I);
  NCollection_IndexedDataMap<TopoDS_Shape, TopOpeBRepDS_ShapeData, TopTools_ShapeMapHasher>& ChangeShapes();
  void AddShapeSameDomain(const TopoDS_Shape& S, const TopoDS_Shape& SSD);
  void RemoveShapeSameDomain(const TopoDS_Shape& S, const TopoDS_Shape& SSD);
  int SameDomainRef(int I) const;
  int SameDomainRef(const TopoDS_Shape& S) const;
  void SameDomainRef(int I, int Ref);
  void SameDomainRef(const TopoDS_Shape& S, int Ref);
  TopOpeBRepDS_Config SameDomainOri(int I) const;
  TopOpeBRepDS_Config SameDomainOri(const TopoDS_Shape& S) const;
  void SameDomainOri(int I, TopOpeBRepDS_Config Ori);
  void SameDomainOri(const TopoDS_Shape& S, TopOpeBRepDS_Config Ori);
  int SameDomainInd(int I) const;
  int SameDomainInd(const TopoDS_Shape& S) const;
  void SameDomainInd(int I, int Ind);
  void SameDomainInd(const TopoDS_Shape& S, int Ind);
  int AncestorRank(int I) const;
  int AncestorRank(const TopoDS_Shape& S) const;
  void AncestorRank(int I, int Ianc);
  void AncestorRank(const TopoDS_Shape& S, int Ianc);
  void AddShapeInterference(const TopoDS_Shape& S, const opencascade::handle<TopOpeBRepDS_Interference>& I);
  void RemoveShapeInterference(const TopoDS_Shape& S, const opencascade::handle<TopOpeBRepDS_Interference>& I);
  void FillShapesSameDomain(const TopoDS_Shape& S1, const TopoDS_Shape& S2, bool refFirst = true);
  void FillShapesSameDomain(const TopoDS_Shape& S1, const TopoDS_Shape& S2, TopOpeBRepDS_Config c1, TopOpeBRepDS_Config c2, bool refFirst = true);
  void UnfillShapesSameDomain(const TopoDS_Shape& S1, const TopoDS_Shape& S2);
  int NbSurfaces() const;
  int NbCurves() const;
  void ChangeNbCurves(int N);
  int NbPoints() const;
  int NbShapes() const;
  int NbSectionEdges() const;
  const TopOpeBRepDS_Surface& Surface(int I) const;
  TopOpeBRepDS_Surface& ChangeSurface(int I);
  const TopOpeBRepDS_Curve& Curve(int I) const;
  TopOpeBRepDS_Curve& ChangeCurve(int I);
  const TopOpeBRepDS_Point& Point(int I) const;
  TopOpeBRepDS_Point& ChangePoint(int I);
  const TopoDS_Shape& Shape(int I, bool FindKeep = true) const;
  int Shape(const TopoDS_Shape& S, bool FindKeep = true) const;
  const TopoDS_Edge& SectionEdge(int I, bool FindKeep = true) const;
  int SectionEdge(const TopoDS_Edge& E, bool FindKeep = true) const;
  bool IsSectionEdge(const TopoDS_Edge& E, bool FindKeep = true) const;
  bool HasGeometry(const TopoDS_Shape& S) const;
  bool HasShape(const TopoDS_Shape& S, bool FindKeep = true) const;
  void SetNewSurface(const TopoDS_Shape& F, const opencascade::handle<Geom_Surface>& S);
  bool HasNewSurface(const TopoDS_Shape& F) const;
  const opencascade::handle<Geom_Surface>& NewSurface(const TopoDS_Shape& F) const;
  void Isfafa(bool isfafa);
  bool Isfafa() const;
  NCollection_IndexedDataMap<TopoDS_Shape, TopOpeBRepDS_ShapeWithState, TopTools_ShapeMapHasher>& ChangeMapOfShapeWithStateObj();
  NCollection_IndexedDataMap<TopoDS_Shape, TopOpeBRepDS_ShapeWithState, TopTools_ShapeMapHasher>& ChangeMapOfShapeWithStateTool();
  NCollection_IndexedDataMap<TopoDS_Shape, TopOpeBRepDS_ShapeWithState, TopTools_ShapeMapHasher>& ChangeMapOfShapeWithState(const TopoDS_Shape& aShape, bool& aFlag);
  const TopOpeBRepDS_ShapeWithState& GetShapeWithState(const TopoDS_Shape& aShape) const;
  NCollection_IndexedMap<TopoDS_Shape, TopTools_ShapeMapHasher>& ChangeMapOfRejectedShapesObj();
  NCollection_IndexedMap<TopoDS_Shape, TopTools_ShapeMapHasher>& ChangeMapOfRejectedShapesTool();
};

class TopOpeBRepDS_Dumper {
public:
  TopOpeBRepDS_Dumper(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS);
  TCollection_AsciiString SDumpRefOri(TopOpeBRepDS_Kind K, int I) const;
  TCollection_AsciiString SDumpRefOri(const TopoDS_Shape& S) const;
  TCollection_AsciiString SPrintShape(int I) const;
  TCollection_AsciiString SPrintShape(const TopoDS_Shape& S) const;
  TCollection_AsciiString SPrintShapeRefOri(const TopoDS_Shape& S, const TCollection_AsciiString& B = "") const;
  TCollection_AsciiString SPrintShapeRefOri(const NCollection_List<TopoDS_Shape>& L, const TCollection_AsciiString& B = "") const;
};

class TopOpeBRepDS_EIR {
public:
  TopOpeBRepDS_EIR(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS);
  void ProcessEdgeInterferences();
  void ProcessEdgeInterferences(int I);
};

class TopOpeBRepDS_ShapeShapeInterference : public TopOpeBRepDS_Interference {
public:
  TopOpeBRepDS_ShapeShapeInterference(const TopOpeBRepDS_Transition& T, TopOpeBRepDS_Kind ST, int S, TopOpeBRepDS_Kind GT, int G, bool GBound, TopOpeBRepDS_Config C);
  TopOpeBRepDS_Config Config() const;
  bool GBound() const;
  void SetGBound(bool b);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_EdgeVertexInterference : public TopOpeBRepDS_ShapeShapeInterference {
public:
  TopOpeBRepDS_EdgeVertexInterference(const TopOpeBRepDS_Transition& T, TopOpeBRepDS_Kind ST, int S, int G, bool GIsBound, TopOpeBRepDS_Config C, double P);
  TopOpeBRepDS_EdgeVertexInterference(const TopOpeBRepDS_Transition& T, int S, int G, bool GIsBound, TopOpeBRepDS_Config C, double P);
  double Parameter() const;
  void Parameter(double P);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_FaceEdgeInterference : public TopOpeBRepDS_ShapeShapeInterference {
public:
  TopOpeBRepDS_FaceEdgeInterference(const TopOpeBRepDS_Transition& T, int S, int G, bool GIsBound, TopOpeBRepDS_Config C);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_HDataStructure : public Standard_Transient {
public:
  TopOpeBRepDS_HDataStructure();
  void AddAncestors(const TopoDS_Shape& S);
  void AddAncestors(const TopoDS_Shape& S, TopAbs_ShapeEnum T1, TopAbs_ShapeEnum T2);
  void ChkIntg();
  const TopOpeBRepDS_DataStructure& DS() const;
  TopOpeBRepDS_DataStructure& ChangeDS();
  int NbSurfaces() const;
  int NbCurves() const;
  int NbPoints() const;
  const TopOpeBRepDS_Surface& Surface(int I) const;
  TopOpeBRepDS_CurveIterator SurfaceCurves(int I) const;
  const TopOpeBRepDS_Curve& Curve(int I) const;
  TopOpeBRepDS_Curve& ChangeCurve(int I);
  TopOpeBRepDS_PointIterator CurvePoints(int I) const;
  const TopOpeBRepDS_Point& Point(int I) const;
  int NbShapes() const;
  const TopoDS_Shape& Shape(int I, bool FindKeep = true) const;
  int Shape(const TopoDS_Shape& S, bool FindKeep = true) const;
  bool HasGeometry(const TopoDS_Shape& S) const;
  bool HasShape(const TopoDS_Shape& S, bool FindKeep = true) const;
  bool HasSameDomain(const TopoDS_Shape& S, bool FindKeep = true) const;
  TopTools_ListIteratorOfListOfShape SameDomain(const TopoDS_Shape& S) const;
  TopOpeBRepDS_Config SameDomainOrientation(const TopoDS_Shape& S) const;
  int SameDomainReference(const TopoDS_Shape& S) const;
  TopOpeBRepDS_SurfaceIterator SolidSurfaces(const TopoDS_Shape& S) const;
  TopOpeBRepDS_SurfaceIterator SolidSurfaces(int I) const;
  TopOpeBRepDS_CurveIterator FaceCurves(const TopoDS_Shape& F) const;
  TopOpeBRepDS_CurveIterator FaceCurves(int I) const;
  TopOpeBRepDS_PointIterator EdgePoints(const TopoDS_Shape& E) const;
  int MakeCurve(const TopOpeBRepDS_Curve& C1, TopOpeBRepDS_Curve& C2);
  void RemoveCurve(int iC);
  int NbGeometry(TopOpeBRepDS_Kind K) const;
  int NbTopology(TopOpeBRepDS_Kind K) const;
  int NbTopology() const;
  bool EdgesSameParameter() const;
  void SortOnParameter(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L1, NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L2) const;
  void SortOnParameter(NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L) const;
  void MinMaxOnParameter(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L, double& Min, double& Max) const;
  bool ScanInterfList(TopOpeBRepDS_ListIteratorOfListOfInterference& IT, const TopOpeBRepDS_Point& PDS) const;
  bool GetGeometry(TopOpeBRepDS_ListIteratorOfListOfInterference& IT, const TopOpeBRepDS_Point& PDS, int& G, TopOpeBRepDS_Kind& K) const;
  void StoreInterference(const opencascade::handle<TopOpeBRepDS_Interference>& I, NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI, const TCollection_AsciiString& str = "");
  void StoreInterference(const opencascade::handle<TopOpeBRepDS_Interference>& I, const TopoDS_Shape& S, const TCollection_AsciiString& str = "");
  void StoreInterference(const opencascade::handle<TopOpeBRepDS_Interference>& I, int IS, const TCollection_AsciiString& str = "");
  void StoreInterferences(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI, const TopoDS_Shape& S, const TCollection_AsciiString& str = "");
  void StoreInterferences(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI, int IS, const TCollection_AsciiString& str = "");
  void ClearStoreInterferences(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI, const TopoDS_Shape& S, const TCollection_AsciiString& str = "");
  void ClearStoreInterferences(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI, int IS, const TCollection_AsciiString& str = "");
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_ListOfShapeOn1State {
public:
  TopOpeBRepDS_ListOfShapeOn1State();
  const NCollection_List<TopoDS_Shape>& ListOnState() const;
  NCollection_List<TopoDS_Shape>& ChangeListOnState();
  bool IsSplit() const;
  void Split(bool B = true);
  void Clear();
};

class TopOpeBRepDS_Edge3dInterferenceTool {
public:
  TopOpeBRepDS_Edge3dInterferenceTool();
  void InitPointVertex(int IsVertex, const TopoDS_Shape& VonOO);
  void Init(const TopoDS_Shape& Eref, const TopoDS_Shape& E, const TopoDS_Shape& F, const opencascade::handle<TopOpeBRepDS_Interference>& I);
  void Add(const TopoDS_Shape& Eref, const TopoDS_Shape& E, const TopoDS_Shape& F, const opencascade::handle<TopOpeBRepDS_Interference>& I);
  void Transition(const opencascade::handle<TopOpeBRepDS_Interference>& I) const;
};

class TopOpeBRepDS_EdgeInterferenceTool {
public:
  TopOpeBRepDS_EdgeInterferenceTool();
  void Init(const TopoDS_Shape& E, const opencascade::handle<TopOpeBRepDS_Interference>& I);
  void Add(const TopoDS_Shape& E, const TopoDS_Shape& V, const opencascade::handle<TopOpeBRepDS_Interference>& I);
  void Add(const TopoDS_Shape& E, const TopOpeBRepDS_Point& P, const opencascade::handle<TopOpeBRepDS_Interference>& I);
  void Transition(const opencascade::handle<TopOpeBRepDS_Interference>& I) const;
};

class TopOpeBRepDS_Explorer {
public:
  TopOpeBRepDS_Explorer();
  TopOpeBRepDS_Explorer(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS, TopAbs_ShapeEnum T = TopAbs_SHAPE, bool findkeep = true);
  void Init(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS, TopAbs_ShapeEnum T = TopAbs_SHAPE, bool findkeep = true);
  TopAbs_ShapeEnum Type() const;
  bool More() const;
  void Next();
  const TopoDS_Shape& Current() const;
  int Index() const;
  const TopoDS_Face& Face() const;
  const TopoDS_Edge& Edge() const;
  const TopoDS_Vertex& Vertex() const;
};

class TopOpeBRepDS_FIR {
public:
  TopOpeBRepDS_FIR(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS);
  void ProcessFaceInterferences(const NCollection_DataMap<TopoDS_Shape, TopOpeBRepDS_ListOfShapeOn1State, TopTools_ShapeMapHasher>& M);
  void ProcessFaceInterferences(int I, const NCollection_DataMap<TopoDS_Shape, TopOpeBRepDS_ListOfShapeOn1State, TopTools_ShapeMapHasher>& M);
};

class TopOpeBRepDS_FaceInterferenceTool {
public:
  TopOpeBRepDS_FaceInterferenceTool(TopOpeBRepDS_DataStructure* P);
  void Init(const TopoDS_Shape& FI, const TopoDS_Shape& E, bool Eisnew, const opencascade::handle<TopOpeBRepDS_Interference>& I);
  void Add(const TopoDS_Shape& FI, const TopoDS_Shape& F, const TopoDS_Shape& E, bool Eisnew, const opencascade::handle<TopOpeBRepDS_Interference>& I);
  void Add(const TopoDS_Shape& E, const TopOpeBRepDS_Curve& C, const opencascade::handle<TopOpeBRepDS_Interference>& I);
  void SetEdgePntPar(const gp_Pnt& P, double par);
  void GetEdgePntPar(gp_Pnt& P, double& par) const;
  bool IsEdgePntParDef() const;
  void Transition(const opencascade::handle<TopOpeBRepDS_Interference>& I) const;
};

class TopOpeBRepDS_Filter {
public:
  TopOpeBRepDS_Filter(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS, TopOpeBRepTool_ShapeClassifier* pClassif = nullptr);
  void ProcessInterferences();
  void ProcessFaceInterferences(const NCollection_DataMap<TopoDS_Shape, TopOpeBRepDS_ListOfShapeOn1State, TopTools_ShapeMapHasher>& MEsp);
  void ProcessFaceInterferences(int I, const NCollection_DataMap<TopoDS_Shape, TopOpeBRepDS_ListOfShapeOn1State, TopTools_ShapeMapHasher>& MEsp);
  void ProcessEdgeInterferences();
  void ProcessEdgeInterferences(int I);
  void ProcessCurveInterferences();
  void ProcessCurveInterferences(int I);
};

class TopOpeBRepDS_GapFiller {
public:
  TopOpeBRepDS_GapFiller(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS);
  void Perform();
  void FindAssociatedPoints(const opencascade::handle<TopOpeBRepDS_Interference>& I, NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI);
  bool CheckConnexity(NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI);
  void AddPointsOnShape(const TopoDS_Shape& S, NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI);
  void AddPointsOnConnexShape(const TopoDS_Shape& F, const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI);
  void FilterByFace(const TopoDS_Face& F, NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI);
  void FilterByEdge(const TopoDS_Edge& E, NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI);
  void FilterByIncidentDistance(const TopoDS_Face& F, const opencascade::handle<TopOpeBRepDS_Interference>& I, NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& LI);
  bool IsOnFace(const opencascade::handle<TopOpeBRepDS_Interference>& I, const TopoDS_Face& F) const;
  bool IsOnEdge(const opencascade::handle<TopOpeBRepDS_Interference>& I, const TopoDS_Edge& E) const;
  void BuildNewGeometries();
  void ReBuildGeom(const opencascade::handle<TopOpeBRepDS_Interference>& I1, NCollection_Map<int, NCollection_DefaultHasher<int>>& Done);
};

class TopOpeBRepDS_GapTool : public Standard_Transient {
public:
  TopOpeBRepDS_GapTool();
  TopOpeBRepDS_GapTool(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS);
  void Init(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS);
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& Interferences(int IndexPoint) const;
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& SameInterferences(const opencascade::handle<TopOpeBRepDS_Interference>& I) const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ChangeSameInterferences(const opencascade::handle<TopOpeBRepDS_Interference>& I);
  bool Curve(const opencascade::handle<TopOpeBRepDS_Interference>& I, TopOpeBRepDS_Curve& C) const;
  bool EdgeSupport(const opencascade::handle<TopOpeBRepDS_Interference>& I, TopoDS_Shape& E) const;
  bool FacesSupport(const opencascade::handle<TopOpeBRepDS_Interference>& I, TopoDS_Shape& F1, TopoDS_Shape& F2) const;
  bool ParameterOnEdge(const opencascade::handle<TopOpeBRepDS_Interference>& I, const TopoDS_Shape& E, double& U) const;
  void SetPoint(const opencascade::handle<TopOpeBRepDS_Interference>& I, int IndexPoint);
  void SetParameterOnEdge(const opencascade::handle<TopOpeBRepDS_Interference>& I, const TopoDS_Shape& E, double U);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_InterferenceTool {
public:
  TopOpeBRepDS_InterferenceTool();
  static opencascade::handle<TopOpeBRepDS_Interference> MakeEdgeInterference(const TopOpeBRepDS_Transition& T, TopOpeBRepDS_Kind SK, int SI, TopOpeBRepDS_Kind GK, int GI, double P);
  static opencascade::handle<TopOpeBRepDS_Interference> MakeCurveInterference(const TopOpeBRepDS_Transition& T, TopOpeBRepDS_Kind SK, int SI, TopOpeBRepDS_Kind GK, int GI, double P);
  static opencascade::handle<TopOpeBRepDS_Interference> DuplicateCurvePointInterference(const opencascade::handle<TopOpeBRepDS_Interference>& I);
  static opencascade::handle<TopOpeBRepDS_Interference> MakeFaceCurveInterference(const TopOpeBRepDS_Transition& Transition, int FaceI, int CurveI, const opencascade::handle<Geom2d_Curve>& PC);
  static opencascade::handle<TopOpeBRepDS_Interference> MakeSolidSurfaceInterference(const TopOpeBRepDS_Transition& Transition, int SolidI, int SurfaceI);
  static opencascade::handle<TopOpeBRepDS_Interference> MakeEdgeVertexInterference(const TopOpeBRepDS_Transition& Transition, int EdgeI, int VertexI, bool VertexIsBound, TopOpeBRepDS_Config Config, double param);
  static opencascade::handle<TopOpeBRepDS_Interference> MakeFaceEdgeInterference(const TopOpeBRepDS_Transition& Transition, int FaceI, int EdgeI, bool EdgeIsBound, TopOpeBRepDS_Config Config);
  static double Parameter(const opencascade::handle<TopOpeBRepDS_Interference>& CPI);
  static void Parameter(const opencascade::handle<TopOpeBRepDS_Interference>& CPI, double Par);
};

class TopOpeBRepDS_Marker : public Standard_Transient {
public:
  TopOpeBRepDS_Marker();
  void Reset();
  void Set(int i, bool b);
  void Set(bool b, int n, void* a);
  bool GetI(int i) const;
  void Allocate(int n);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_PointExplorer {
public:
  TopOpeBRepDS_PointExplorer();
  TopOpeBRepDS_PointExplorer(const TopOpeBRepDS_DataStructure& DS, bool FindOnlyKeep = true);
  void Init(const TopOpeBRepDS_DataStructure& DS, bool FindOnlyKeep = true);
  bool More() const;
  void Next();
  const TopOpeBRepDS_Point& Point() const;
  bool IsPoint(int I) const;
  bool IsPointKeep(int I) const;
  const TopOpeBRepDS_Point& Point(int I) const;
  int NbPoint();
  int Index() const;
};

class TopOpeBRepDS_PointIterator : public TopOpeBRepDS_InterferenceIterator {
public:
  TopOpeBRepDS_PointIterator(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L);
  bool MatchInterference(const opencascade::handle<TopOpeBRepDS_Interference>& I) const;
  int Current() const;
  TopAbs_Orientation Orientation(TopAbs_State S) const;
  double Parameter() const;
  bool IsVertex() const;
  bool IsPoint() const;
  bool DiffOriented() const;
  bool SameOriented() const;
  int Support() const;
};

class TopOpeBRepDS_Reducer {
public:
  TopOpeBRepDS_Reducer(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS);
  void ProcessFaceInterferences(const NCollection_DataMap<TopoDS_Shape, TopOpeBRepDS_ListOfShapeOn1State, TopTools_ShapeMapHasher>& M);
  void ProcessEdgeInterferences();
};

class TopOpeBRepDS_SolidSurfaceInterference : public TopOpeBRepDS_Interference {
public:
  TopOpeBRepDS_SolidSurfaceInterference(const TopOpeBRepDS_Transition& Transition, TopOpeBRepDS_Kind SupportType, int Support, TopOpeBRepDS_Kind GeometryType, int Geometry);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_SurfaceCurveInterference : public TopOpeBRepDS_Interference {
public:
  TopOpeBRepDS_SurfaceCurveInterference();
  TopOpeBRepDS_SurfaceCurveInterference(const TopOpeBRepDS_Transition& Transition, TopOpeBRepDS_Kind SupportType, int Support, TopOpeBRepDS_Kind GeometryType, int Geometry, const opencascade::handle<Geom2d_Curve>& PC);
  TopOpeBRepDS_SurfaceCurveInterference(const opencascade::handle<TopOpeBRepDS_Interference>& I);
  const opencascade::handle<Geom2d_Curve>& PCurve() const;
  void PCurve(const opencascade::handle<Geom2d_Curve>& PC);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class TopOpeBRepDS_SurfaceExplorer {
public:
  TopOpeBRepDS_SurfaceExplorer();
  TopOpeBRepDS_SurfaceExplorer(const TopOpeBRepDS_DataStructure& DS, bool FindOnlyKeep = true);
  void Init(const TopOpeBRepDS_DataStructure& DS, bool FindOnlyKeep = true);
  bool More() const;
  void Next();
  const TopOpeBRepDS_Surface& Surface() const;
  bool IsSurface(int I) const;
  bool IsSurfaceKeep(int I) const;
  const TopOpeBRepDS_Surface& Surface(int I) const;
  int NbSurface();
  int Index() const;
};

class TopOpeBRepDS_SurfaceIterator : public TopOpeBRepDS_InterferenceIterator {
public:
  TopOpeBRepDS_SurfaceIterator(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L);
  int Current() const;
  TopAbs_Orientation Orientation(TopAbs_State S) const;
};

class TopOpeBRepDS_TKI {
public:
  TopOpeBRepDS_TKI();
  void Clear();
  void FillOnGeometry(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L);
  void FillOnSupport(const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& L);
  bool IsBound(TopOpeBRepDS_Kind K, int G) const;
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& Interferences(TopOpeBRepDS_Kind K, int G) const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ChangeInterferences(TopOpeBRepDS_Kind K, int G);
  bool HasInterferences(TopOpeBRepDS_Kind K, int G) const;
  void Add(TopOpeBRepDS_Kind K, int G);
  void Add(TopOpeBRepDS_Kind K, int G, const opencascade::handle<TopOpeBRepDS_Interference>& HI);
  void DumpTKIIterator(const TCollection_AsciiString& s1 = "", const TCollection_AsciiString& s2 = "");
  void Init();
  bool More() const;
  void Next();
  const NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& Value(TopOpeBRepDS_Kind& K, int& G) const;
  NCollection_List<opencascade::handle<TopOpeBRepDS_Interference>>& ChangeValue(TopOpeBRepDS_Kind& K, int& G);
};

class TopOpeBRepDS_TOOL {
public:
  TopOpeBRepDS_TOOL();
  static int EShareG(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS, const TopoDS_Edge& E, NCollection_List<TopoDS_Shape>& lEsd);
  static bool ShareG(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS, int is1, int is2);
  static bool GetEsd(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS, const TopoDS_Shape& S, int ie, int& iesd);
  static bool ShareSplitON(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS, const NCollection_DataMap<TopoDS_Shape, TopOpeBRepDS_ListOfShapeOn1State, TopTools_ShapeMapHasher>& MspON, int i1, int i2, TopoDS_Shape& spON);
  static bool GetConfig(const opencascade::handle<TopOpeBRepDS_HDataStructure>& HDS, const NCollection_DataMap<TopoDS_Shape, TopOpeBRepDS_ListOfShapeOn1State, TopTools_ShapeMapHasher>& MEspON, int ie, int iesd, int& conf);
};

class TopTools_ListIteratorOfListOfShape : public NCollection_BaseList_Iterator {
public:
  TopTools_ListIteratorOfListOfShape();
  TopTools_ListIteratorOfListOfShape(const NCollection_BaseList& theList);
  bool More() const;
  void Next();
  const TopoDS_Shape& Value() const;
  TopoDS_Shape& ChangeValue() const;
};
