// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* TopTrans: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module TopTransModule

%include "NetOcc.i"

%{
#include <TopTrans_module.hxx>
%}

%import "TopAbs.i"
%import "Standard.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "gp.i"
%netocc_csimports(using OCC.Core.TopAbs; using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.gp;)

%occt_valueclass(TopTrans_CurveTransition)
%occt_valueclass(TopTrans_SurfaceTransition)

class TopTrans_CurveTransition {
public:
  TopTrans_CurveTransition();
  void Reset(const gp_Dir& Tgt, const gp_Dir& Norm, double Curv);
  void Reset(const gp_Dir& Tgt);
  void Compare(double Tole, const gp_Dir& Tang, const gp_Dir& Norm, double Curv, TopAbs_Orientation S, TopAbs_Orientation Or);
  TopAbs_State StateBefore() const;
  TopAbs_State StateAfter() const;
};

class TopTrans_SurfaceTransition {
public:
  TopTrans_SurfaceTransition();
  void Reset(const gp_Dir& Tgt, const gp_Dir& Norm, const gp_Dir& MaxD, const gp_Dir& MinD, double MaxCurv, double MinCurv);
  void Reset(const gp_Dir& Tgt, const gp_Dir& Norm);
  void Compare(double Tole, const gp_Dir& Norm, const gp_Dir& MaxD, const gp_Dir& MinD, double MaxCurv, double MinCurv, TopAbs_Orientation S, TopAbs_Orientation O);
  void Compare(double Tole, const gp_Dir& Norm, TopAbs_Orientation S, TopAbs_Orientation O);
  TopAbs_State StateBefore() const;
  TopAbs_State StateAfter() const;
  static TopAbs_State GetBefore(TopAbs_Orientation Tran);
  static TopAbs_State GetAfter(TopAbs_Orientation Tran);
};
