// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* Transfer: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module TransferModule

%include "NetOcc.i"

%{
#include <Transfer_module.hxx>
%}

%import "TCollection.i"
%import "TColStd.i"
%import "Standard.i"
%import "NCollection.i"
%import "Resource.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "CDM.i"
%import "LDOM.i"
%import "Storage.i"
%import "PCDM.i"
%import "CDF.i"
%import "TDF.i"
%import "TDocStd.i"
%import "TopAbs.i"
%import "gp.i"
%import "TopLoc.i"
%import "TopoDS.i"
%import "GeomAbs.i"
%import "TColgp.i"
%import "GeomEval.i"
%import "Geom.i"
%import "Geom2dEval.i"
%import "Geom2d.i"
%import "Adaptor2d.i"
%import "math.i"
%import "Adaptor3d.i"
%import "Geom2dAdaptor.i"
%import "GeomAdaptor.i"
%import "BRepAdaptor.i"
%import "IntSurf.i"
%import "Intf.i"
%import "IntCurveSurface.i"
%import "IntCurvesFace.i"
%import "BRepClass3d.i"
%import "IntRes2d.i"
%import "IntCurve.i"
%import "Geom2dInt.i"
%import "HatchGen.i"
%import "Geom2dHatch.i"
%import "AppParCurves.i"
%import "AppCont.i"
%import "Approx.i"
%import "Extrema.i"
%import "GeomAPI.i"
%import "IntAna.i"
%import "IntPatch.i"
%import "ApproxInt.i"
%import "IntImp.i"
%import "GeomInt.i"
%import "IntTools.i"
%import "BOPTools.i"
%import "BVH.i"
%import "Bnd.i"
%import "TopTools.i"
%import "MoniTool.i"
%import "Interface.i"
%import "IFGraph.i"
%import "IFSelect.i"
%import "TColGeom.i"
%import "ShapeExtend.i"
%import "TShort.i"
%import "Poly.i"
%import "BRep.i"
%import "BRepTools.i"
%import "ShapeBuild.i"
%import "ShapeProcess.i"
%import "XSAlgo.i"
%import "XSControl.i"
%import "DE.i"
%netocc_csimports(using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.Resource; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.CDM; using OCC.Core.LDOM; using OCC.Core.Storage; using OCC.Core.PCDM; using OCC.Core.CDF; using OCC.Core.TDF; using OCC.Core.TDocStd; using OCC.Core.TopAbs; using OCC.Core.gp; using OCC.Core.TopLoc; using OCC.Core.TopoDS; using OCC.Core.GeomAbs; using OCC.Core.TColgp; using OCC.Core.GeomEval; using OCC.Core.Geom; using OCC.Core.Geom2dEval; using OCC.Core.Geom2d; using OCC.Core.Adaptor2d; using OCC.Core.math; using OCC.Core.Adaptor3d; using OCC.Core.Geom2dAdaptor; using OCC.Core.GeomAdaptor; using OCC.Core.BRepAdaptor; using OCC.Core.IntSurf; using OCC.Core.Intf; using OCC.Core.IntCurveSurface; using OCC.Core.IntCurvesFace; using OCC.Core.BRepClass3d; using OCC.Core.IntRes2d; using OCC.Core.IntCurve; using OCC.Core.Geom2dInt; using OCC.Core.HatchGen; using OCC.Core.Geom2dHatch; using OCC.Core.AppParCurves; using OCC.Core.AppCont; using OCC.Core.Approx; using OCC.Core.Extrema; using OCC.Core.GeomAPI; using OCC.Core.IntAna; using OCC.Core.IntPatch; using OCC.Core.ApproxInt; using OCC.Core.IntImp; using OCC.Core.GeomInt; using OCC.Core.IntTools; using OCC.Core.BOPTools; using OCC.Core.BVH; using OCC.Core.Bnd; using OCC.Core.TopTools; using OCC.Core.MoniTool; using OCC.Core.Interface; using OCC.Core.IFGraph; using OCC.Core.IFSelect; using OCC.Core.TColGeom; using OCC.Core.ShapeExtend; using OCC.Core.TShort; using OCC.Core.Poly; using OCC.Core.BRep; using OCC.Core.BRepTools; using OCC.Core.ShapeBuild; using OCC.Core.ShapeProcess; using OCC.Core.XSAlgo; using OCC.Core.XSControl; using OCC.Core.DE;)

%occt_valueclass(Transfer_TransferDispatch)
%nodefaultctor Transfer_TransferDispatch;
%feature("valuewrapper") Transfer_TransferDispatch;
%occt_transient(Transfer_Binder)
%nodefaultctor Transfer_Binder;
%feature("valuewrapper") Transfer_Binder;
%occt_transient(Transfer_ActorOfProcessForTransient)
%occt_transient(Transfer_ActorOfTransientProcess)
%occt_transient(Transfer_ActorDispatch)
%nodefaultctor Transfer_ActorDispatch;
%feature("valuewrapper") Transfer_ActorDispatch;
%occt_transient(Transfer_Finder)
%nodefaultctor Transfer_Finder;
%occt_valueclass(Transfer_FindHasher)
%occt_transient(Transfer_ActorOfProcessForFinder)
%occt_transient(Transfer_ActorOfFinderProcess)
%occt_transient(Transfer_SimpleBinderOfTransient)
%occt_transient(Transfer_BinderOfTransientInteger)
%occt_valueclass(Transfer_DataInfo)
%occt_transient(Transfer_DispatchControl)
%nodefaultctor Transfer_DispatchControl;
%feature("valuewrapper") Transfer_DispatchControl;
%occt_transient(Transfer_ProcessForFinder)
%occt_transient(Transfer_FinderProcess)
%occt_valueclass(Transfer_TransferIterator)
%occt_valueclass(Transfer_IteratorOfProcessForFinder)
%nodefaultctor Transfer_IteratorOfProcessForFinder;
%feature("valuewrapper") Transfer_IteratorOfProcessForFinder;
%occt_valueclass(Transfer_IteratorOfProcessForTransient)
%nodefaultctor Transfer_IteratorOfProcessForTransient;
%feature("valuewrapper") Transfer_IteratorOfProcessForTransient;
%occt_transient(Transfer_MapContainer)
%occt_transient(Transfer_MultipleBinder)
%occt_transient(Transfer_ProcessForTransient)
%occt_transient(Transfer_ResultFromModel)
%occt_transient(Transfer_ResultFromTransient)
%occt_valueclass(Transfer_TransferFailure)
%occt_valueclass(Transfer_TransferDeadLoop)
%typemap(csattributes) Transfer_TransferDeadLoop "[global::System.Obsolete(\"Deprecated in OCCT.\")]"
%occt_valueclass(Transfer_TransferInput)
%occt_valueclass(Transfer_TransferOutput)
%nodefaultctor Transfer_TransferOutput;
%feature("valuewrapper") Transfer_TransferOutput;
%occt_transient(Transfer_TransientListBinder)
%occt_transient(Transfer_TransientMapper)
%nodefaultctor Transfer_TransientMapper;
%feature("valuewrapper") Transfer_TransientMapper;
%occt_transient(Transfer_TransientProcess)
%occt_transient(Transfer_VoidBinder)
%netocc_bitset(18)

enum Transfer_StatusResult {
  Transfer_StatusVoid = 0,
  Transfer_StatusDefined = 1,
  Transfer_StatusUsed = 2,
};

enum Transfer_StatusExec {
  Transfer_StatusInitial = 0,
  Transfer_StatusRun = 1,
  Transfer_StatusDone = 2,
  Transfer_StatusError = 3,
  Transfer_StatusLoop = 4,
};

enum Transfer_UndefMode {
  Transfer_UndefIgnore = 0,
  Transfer_UndefFailure = 1,
  Transfer_UndefContent = 2,
  Transfer_UndefUser = 3,
};

%occt_sequence(Transfer_SequenceOfFinder, opencascade::handle<Transfer_Finder>, Transfer_Finder)
%occt_hsequence(Transfer_HSequenceOfFinder, opencascade::handle<Transfer_Finder>, Transfer_Finder)

class Transfer_TransferDispatch : public Interface_CopyTool {
public:
  Transfer_TransferDispatch(const opencascade::handle<Interface_InterfaceModel>& amodel, const Interface_GeneralLib& lib);
  Transfer_TransferDispatch(const opencascade::handle<Interface_InterfaceModel>& amodel, const opencascade::handle<Interface_Protocol>& protocol);
  Transfer_TransferDispatch(const opencascade::handle<Interface_InterfaceModel>& amodel);
  opencascade::handle<Transfer_TransientProcess> TransientProcess() const;
  bool Copy(const opencascade::handle<Standard_Transient>& entfrom, opencascade::handle<Standard_Transient>& entto, bool mapped, bool errstat);
};

class Transfer_Binder : public Standard_Transient {
public:
  void Merge(const opencascade::handle<Transfer_Binder>& other);
  bool IsMultiple() const;
  opencascade::handle<Standard_Type> ResultType() const;
  const char* ResultTypeName() const;
  void AddResult(const opencascade::handle<Transfer_Binder>& next);
  opencascade::handle<Transfer_Binder> NextResult() const;
  bool HasResult() const;
  void SetAlreadyUsed();
  Transfer_StatusResult Status() const;
  Transfer_StatusExec StatusExec() const;
  void SetStatusExec(Transfer_StatusExec stat);
  void AddFail(const char* mess, const char* orig = "");
  void AddWarning(const char* mess, const char* orig = "");
  opencascade::handle<Interface_Check> Check() const;
  opencascade::handle<Interface_Check> CCheck();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_ActorOfProcessForTransient : public Standard_Transient {
public:
  Transfer_ActorOfProcessForTransient();
  bool Recognize(const opencascade::handle<Standard_Transient>& start);
  opencascade::handle<Transfer_Binder> Transferring(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Transfer_ProcessForTransient>& TP);
  opencascade::handle<Transfer_SimpleBinderOfTransient> TransientResult(const opencascade::handle<Standard_Transient>& res) const;
  opencascade::handle<Transfer_Binder> NullResult() const;
  void SetLast(bool mode = true);
  bool IsLast() const;
  void SetNext(const opencascade::handle<Transfer_ActorOfProcessForTransient>& next);
  opencascade::handle<Transfer_ActorOfProcessForTransient> Next() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_ActorOfTransientProcess : public Transfer_ActorOfProcessForTransient {
public:
  Transfer_ActorOfTransientProcess();
  opencascade::handle<Transfer_Binder> Transferring(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Transfer_ProcessForTransient>& TP);
  opencascade::handle<Transfer_Binder> Transfer(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Transfer_TransientProcess>& TP);
  opencascade::handle<Standard_Transient> TransferTransient(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Transfer_TransientProcess>& TP);
  void SetShapeFixParameters(const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString, NCollection_DefaultHasher<TCollection_AsciiString>>& theParameters);
  void SetShapeFixParameters(const DE_ShapeFixParameters& theParameters, const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString, NCollection_DefaultHasher<TCollection_AsciiString>>& theAdditionalParameters = NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString, NCollection_DefaultHasher<TCollection_AsciiString>>());
  const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString, NCollection_DefaultHasher<TCollection_AsciiString>>& GetShapeFixParameters() const;
  void SetProcessingFlags(const std::bitset< 18 >& theFlags);
  const std::pair<std::bitset<18>, bool>& GetProcessingFlags() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_ActorDispatch : public Transfer_ActorOfTransientProcess {
public:
  Transfer_ActorDispatch(const opencascade::handle<Interface_InterfaceModel>& amodel, const Interface_GeneralLib& lib);
  Transfer_ActorDispatch(const opencascade::handle<Interface_InterfaceModel>& amodel, const opencascade::handle<Interface_Protocol>& protocol);
  Transfer_ActorDispatch(const opencascade::handle<Interface_InterfaceModel>& amodel);
  void AddActor(const opencascade::handle<Transfer_ActorOfTransientProcess>& actor);
  Transfer_TransferDispatch& TransferDispatch();
  opencascade::handle<Transfer_Binder> Transfer(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Transfer_TransientProcess>& TP);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_Finder : public Standard_Transient {
public:
  size_t GetHashCode() const;
  bool Equates(const opencascade::handle<Transfer_Finder>& other) const;
  opencascade::handle<Standard_Type> ValueType() const;
  const char* ValueTypeName() const;
  void SetAttribute(const char* name, const opencascade::handle<Standard_Transient>& val);
  bool RemoveAttribute(const char* name);
  bool GetAttribute(const char* name, const opencascade::handle<Standard_Type>& type, opencascade::handle<Standard_Transient>& val) const;
  opencascade::handle<Standard_Transient> Attribute(const char* name) const;
  Interface_ParamType AttributeType(const char* name) const;
  void SetIntegerAttribute(const char* name, int val);
  bool GetIntegerAttribute(const char* name, int& val) const;
  int IntegerAttribute(const char* name) const;
  void SetRealAttribute(const char* name, double val);
  bool GetRealAttribute(const char* name, double& val) const;
  double RealAttribute(const char* name) const;
  void SetStringAttribute(const char* name, const char* val);
  bool GetStringAttribute(const char* name, const char*& val) const;
  const char* StringAttribute(const char* name) const;
  NCollection_DataMap<TCollection_AsciiString, opencascade::handle<Standard_Transient>, NCollection_DefaultHasher<TCollection_AsciiString>>& AttrList();
  void SameAttributes(const opencascade::handle<Transfer_Finder>& other);
  void GetAttributes(const opencascade::handle<Transfer_Finder>& other, const char* fromname = "", bool copied = true);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_FindHasher {
public:
  Transfer_FindHasher();
};

class Transfer_ActorOfProcessForFinder : public Standard_Transient {
public:
  Transfer_ActorOfProcessForFinder();
  bool Recognize(const opencascade::handle<Transfer_Finder>& start);
  opencascade::handle<Transfer_Binder> Transferring(const opencascade::handle<Transfer_Finder>& start, const opencascade::handle<Transfer_ProcessForFinder>& TP);
  opencascade::handle<Transfer_SimpleBinderOfTransient> TransientResult(const opencascade::handle<Standard_Transient>& res) const;
  opencascade::handle<Transfer_Binder> NullResult() const;
  void SetLast(bool mode = true);
  bool IsLast() const;
  void SetNext(const opencascade::handle<Transfer_ActorOfProcessForFinder>& next);
  opencascade::handle<Transfer_ActorOfProcessForFinder> Next() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_ActorOfFinderProcess : public Transfer_ActorOfProcessForFinder {
public:
  Transfer_ActorOfFinderProcess();
  int& ModeTrans();
  opencascade::handle<Transfer_Binder> Transferring(const opencascade::handle<Transfer_Finder>& start, const opencascade::handle<Transfer_ProcessForFinder>& TP);
  opencascade::handle<Transfer_Binder> Transfer(const opencascade::handle<Transfer_Finder>& start, const opencascade::handle<Transfer_FinderProcess>& TP);
  opencascade::handle<Standard_Transient> TransferTransient(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Transfer_FinderProcess>& TP);
  void SetShapeFixParameters(const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString, NCollection_DefaultHasher<TCollection_AsciiString>>& theParameters);
  void SetShapeFixParameters(const DE_ShapeFixParameters& theParameters, const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString, NCollection_DefaultHasher<TCollection_AsciiString>>& theAdditionalParameters = NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString, NCollection_DefaultHasher<TCollection_AsciiString>>());
  const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString, NCollection_DefaultHasher<TCollection_AsciiString>>& GetShapeFixParameters() const;
  void SetShapeProcessFlags(const std::bitset< 18 >& theFlags);
  const std::pair<std::bitset<18>, bool>& GetShapeProcessFlags() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_SimpleBinderOfTransient : public Transfer_Binder {
public:
  Transfer_SimpleBinderOfTransient();
  opencascade::handle<Standard_Type> ResultType() const;
  const char* ResultTypeName() const;
  void SetResult(const opencascade::handle<Standard_Transient>& res);
  const opencascade::handle<Standard_Transient>& Result() const;
  static bool GetTypedResult(const opencascade::handle<Transfer_Binder>& bnd, const opencascade::handle<Standard_Type>& atype, opencascade::handle<Standard_Transient>& res);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_BinderOfTransientInteger : public Transfer_SimpleBinderOfTransient {
public:
  Transfer_BinderOfTransientInteger();
  void SetInteger(int value);
  int Integer() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_DataInfo {
public:
  Transfer_DataInfo();
  static opencascade::handle<Standard_Type> Type(const opencascade::handle<Standard_Transient>& ent);
  static const char* TypeName(const opencascade::handle<Standard_Transient>& ent);
};

class Transfer_DispatchControl : public Interface_CopyControl {
public:
  Transfer_DispatchControl(const opencascade::handle<Interface_InterfaceModel>& model, const opencascade::handle<Transfer_TransientProcess>& TP);
  const opencascade::handle<Transfer_TransientProcess>& TransientProcess() const;
  const opencascade::handle<Interface_InterfaceModel>& StartingModel() const;
  void Clear();
  void Bind(const opencascade::handle<Standard_Transient>& ent, const opencascade::handle<Standard_Transient>& res);
  bool Search(const opencascade::handle<Standard_Transient>& ent, opencascade::handle<Standard_Transient>& res) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_ProcessForFinder : public Standard_Transient {
public:
  Transfer_ProcessForFinder(int nb = 10000);
  Transfer_ProcessForFinder(const opencascade::handle<Message_Messenger>& printer, int nb = 10000);
  void Clear();
  void Clean();
  void Resize(int nb);
  void SetActor(const opencascade::handle<Transfer_ActorOfProcessForFinder>& actor);
  opencascade::handle<Transfer_ActorOfProcessForFinder> Actor() const;
  opencascade::handle<Transfer_Binder> Find(const opencascade::handle<Transfer_Finder>& start) const;
  bool IsBound(const opencascade::handle<Transfer_Finder>& start) const;
  bool IsAlreadyUsed(const opencascade::handle<Transfer_Finder>& start) const;
  void Bind(const opencascade::handle<Transfer_Finder>& start, const opencascade::handle<Transfer_Binder>& binder);
  void Rebind(const opencascade::handle<Transfer_Finder>& start, const opencascade::handle<Transfer_Binder>& binder);
  bool Unbind(const opencascade::handle<Transfer_Finder>& start);
  opencascade::handle<Transfer_Binder> FindElseBind(const opencascade::handle<Transfer_Finder>& start);
  void SetMessenger(const opencascade::handle<Message_Messenger>& messenger);
  opencascade::handle<Message_Messenger> Messenger() const;
  void SetTraceLevel(int tracelev);
  int TraceLevel() const;
  void SendFail(const opencascade::handle<Transfer_Finder>& start, const Message_Msg& amsg);
  void SendWarning(const opencascade::handle<Transfer_Finder>& start, const Message_Msg& amsg);
  void SendMsg(const opencascade::handle<Transfer_Finder>& start, const Message_Msg& amsg);
  void AddFail(const opencascade::handle<Transfer_Finder>& start, const char* mess, const char* orig = "");
  void AddError(const opencascade::handle<Transfer_Finder>& start, const char* mess, const char* orig = "");
  void AddFail(const opencascade::handle<Transfer_Finder>& start, const Message_Msg& amsg);
  void AddWarning(const opencascade::handle<Transfer_Finder>& start, const char* mess, const char* orig = "");
  void AddWarning(const opencascade::handle<Transfer_Finder>& start, const Message_Msg& amsg);
  void Mend(const opencascade::handle<Transfer_Finder>& start, const char* pref = "");
  opencascade::handle<Interface_Check> Check(const opencascade::handle<Transfer_Finder>& start) const;
  void BindTransient(const opencascade::handle<Transfer_Finder>& start, const opencascade::handle<Standard_Transient>& res);
  const opencascade::handle<Standard_Transient>& FindTransient(const opencascade::handle<Transfer_Finder>& start) const;
  void BindMultiple(const opencascade::handle<Transfer_Finder>& start);
  void AddMultiple(const opencascade::handle<Transfer_Finder>& start, const opencascade::handle<Standard_Transient>& res);
  bool FindTypedTransient(const opencascade::handle<Transfer_Finder>& start, const opencascade::handle<Standard_Type>& atype, opencascade::handle<Standard_Transient>& val) const;
  bool GetTypedTransient(const opencascade::handle<Transfer_Binder>& binder, const opencascade::handle<Standard_Type>& atype, opencascade::handle<Standard_Transient>& val) const;
  int NbMapped() const;
  const opencascade::handle<Transfer_Finder>& Mapped(int num) const;
  int MapIndex(const opencascade::handle<Transfer_Finder>& start) const;
  opencascade::handle<Transfer_Binder> MapItem(int num) const;
  void SetRoot(const opencascade::handle<Transfer_Finder>& start);
  void SetRootManagement(bool stat);
  int NbRoots() const;
  const opencascade::handle<Transfer_Finder>& Root(int num) const;
  opencascade::handle<Transfer_Binder> RootItem(int num) const;
  int RootIndex(const opencascade::handle<Transfer_Finder>& start) const;
  int NestingLevel() const;
  void ResetNestingLevel();
  bool Recognize(const opencascade::handle<Transfer_Finder>& start) const;
  opencascade::handle<Transfer_Binder> Transferring(const opencascade::handle<Transfer_Finder>& start);
  bool Transfer(const opencascade::handle<Transfer_Finder>& start);
  void SetErrorHandle(bool err);
  bool ErrorHandle() const;
  void StartTrace(const opencascade::handle<Transfer_Binder>& binder, const opencascade::handle<Transfer_Finder>& start, int level, int mode) const;
  void PrintTrace(const opencascade::handle<Transfer_Finder>& start, std::ostream& S) const;
  bool IsLooping(int alevel) const;
  Transfer_IteratorOfProcessForFinder RootResult(bool withstart = false) const;
  Transfer_IteratorOfProcessForFinder CompleteResult(bool withstart = false) const;
  Transfer_IteratorOfProcessForFinder AbnormalResult() const;
  Interface_CheckIterator CheckList(bool erronly) const;
  Transfer_IteratorOfProcessForFinder ResultOne(const opencascade::handle<Transfer_Finder>& start, int level, bool withstart = false) const;
  Interface_CheckIterator CheckListOne(const opencascade::handle<Transfer_Finder>& start, int level, bool erronly) const;
  bool IsCheckListEmpty(const opencascade::handle<Transfer_Finder>& start, int level, bool erronly) const;
  void RemoveResult(const opencascade::handle<Transfer_Finder>& start, int level, bool compute = true);
  int CheckNum(const opencascade::handle<Transfer_Finder>& start) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_FinderProcess : public Transfer_ProcessForFinder {
public:
  Transfer_FinderProcess(int nb = 10000);
  void SetModel(const opencascade::handle<Interface_InterfaceModel>& model);
  opencascade::handle<Interface_InterfaceModel> Model() const;
  int NextMappedWithAttribute(const char* name, int num0) const;
  opencascade::handle<Transfer_TransientMapper> TransientMapper(const opencascade::handle<Standard_Transient>& obj) const;
  void PrintTrace(const opencascade::handle<Transfer_Finder>& start, std::ostream& S) const;
  void PrintStats(int mode, std::ostream& S) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_TransferIterator {
public:
  Transfer_TransferIterator();
  void AddItem(const opencascade::handle<Transfer_Binder>& atr);
  void SelectBinder(const opencascade::handle<Standard_Type>& atype, bool keep);
  void SelectResult(const opencascade::handle<Standard_Type>& atype, bool keep);
  void SelectUnique(bool keep);
  void SelectItem(int num, bool keep);
  int Number() const;
  void Start();
  bool More();
  void Next();
  const opencascade::handle<Transfer_Binder>& Value() const;
  bool HasResult() const;
  bool HasUniqueResult() const;
  opencascade::handle<Standard_Type> ResultType() const;
  bool HasTransientResult() const;
  const opencascade::handle<Standard_Transient>& TransientResult() const;
  Transfer_StatusExec Status() const;
  bool HasFails() const;
  bool HasWarnings() const;
  opencascade::handle<Interface_Check> Check() const;
};

class Transfer_IteratorOfProcessForFinder : public Transfer_TransferIterator {
public:
  Transfer_IteratorOfProcessForFinder(bool withstarts);
  void Add(const opencascade::handle<Transfer_Binder>& binder);
  void Add(const opencascade::handle<Transfer_Binder>& binder, const opencascade::handle<Transfer_Finder>& start);
  void Filter(const opencascade::handle<NCollection_HSequence<opencascade::handle<Transfer_Finder>>>& list, bool keep = true);
  bool HasStarting() const;
  const opencascade::handle<Transfer_Finder>& Starting() const;
};

class Transfer_IteratorOfProcessForTransient : public Transfer_TransferIterator {
public:
  Transfer_IteratorOfProcessForTransient(bool withstarts);
  void Add(const opencascade::handle<Transfer_Binder>& binder);
  void Add(const opencascade::handle<Transfer_Binder>& binder, const opencascade::handle<Standard_Transient>& start);
  void Filter(const opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>>& list, bool keep = true);
  bool HasStarting() const;
  const opencascade::handle<Standard_Transient>& Starting() const;
};

class Transfer_MapContainer : public Standard_Transient {
public:
  Transfer_MapContainer();
  void SetMapObjects(NCollection_DataMap<opencascade::handle<Standard_Transient>, opencascade::handle<Standard_Transient>, NCollection_DefaultHasher<opencascade::handle<Standard_Transient>>>& theMapObjects);
  NCollection_DataMap<opencascade::handle<Standard_Transient>, opencascade::handle<Standard_Transient>, NCollection_DefaultHasher<opencascade::handle<Standard_Transient>>>& GetMapObjects();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_MultipleBinder : public Transfer_Binder {
public:
  Transfer_MultipleBinder();
  bool IsMultiple() const;
  opencascade::handle<Standard_Type> ResultType() const;
  const char* ResultTypeName() const;
  void AddResult(const opencascade::handle<Standard_Transient>& res);
  int NbResults() const;
  opencascade::handle<Standard_Transient> ResultValue(int num) const;
  opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>> MultipleResult() const;
  void SetMultipleResult(const opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>>& mulres);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_ProcessForTransient : public Standard_Transient {
public:
  Transfer_ProcessForTransient(int nb = 10000);
  Transfer_ProcessForTransient(const opencascade::handle<Message_Messenger>& printer, int nb = 10000);
  void Clear();
  void Clean();
  void Resize(int nb);
  void SetActor(const opencascade::handle<Transfer_ActorOfProcessForTransient>& actor);
  opencascade::handle<Transfer_ActorOfProcessForTransient> Actor() const;
  opencascade::handle<Transfer_Binder> Find(const opencascade::handle<Standard_Transient>& start) const;
  bool IsBound(const opencascade::handle<Standard_Transient>& start) const;
  bool IsAlreadyUsed(const opencascade::handle<Standard_Transient>& start) const;
  void Bind(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Transfer_Binder>& binder);
  void Rebind(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Transfer_Binder>& binder);
  bool Unbind(const opencascade::handle<Standard_Transient>& start);
  opencascade::handle<Transfer_Binder> FindElseBind(const opencascade::handle<Standard_Transient>& start);
  void SetMessenger(const opencascade::handle<Message_Messenger>& messenger);
  opencascade::handle<Message_Messenger> Messenger() const;
  void SetTraceLevel(int tracelev);
  int TraceLevel() const;
  void SendFail(const opencascade::handle<Standard_Transient>& start, const Message_Msg& amsg);
  void SendWarning(const opencascade::handle<Standard_Transient>& start, const Message_Msg& amsg);
  void SendMsg(const opencascade::handle<Standard_Transient>& start, const Message_Msg& amsg);
  void AddFail(const opencascade::handle<Standard_Transient>& start, const char* mess, const char* orig = "");
  void AddError(const opencascade::handle<Standard_Transient>& start, const char* mess, const char* orig = "");
  void AddFail(const opencascade::handle<Standard_Transient>& start, const Message_Msg& amsg);
  void AddWarning(const opencascade::handle<Standard_Transient>& start, const char* mess, const char* orig = "");
  void AddWarning(const opencascade::handle<Standard_Transient>& start, const Message_Msg& amsg);
  void Mend(const opencascade::handle<Standard_Transient>& start, const char* pref = "");
  opencascade::handle<Interface_Check> Check(const opencascade::handle<Standard_Transient>& start) const;
  void BindTransient(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Standard_Transient>& res);
  const opencascade::handle<Standard_Transient>& FindTransient(const opencascade::handle<Standard_Transient>& start) const;
  void BindMultiple(const opencascade::handle<Standard_Transient>& start);
  void AddMultiple(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Standard_Transient>& res);
  bool FindTypedTransient(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Standard_Type>& atype, opencascade::handle<Standard_Transient>& val) const;
  bool GetTypedTransient(const opencascade::handle<Transfer_Binder>& binder, const opencascade::handle<Standard_Type>& atype, opencascade::handle<Standard_Transient>& val) const;
  int NbMapped() const;
  const opencascade::handle<Standard_Transient>& Mapped(int num) const;
  int MapIndex(const opencascade::handle<Standard_Transient>& start) const;
  opencascade::handle<Transfer_Binder> MapItem(int num) const;
  void SetRoot(const opencascade::handle<Standard_Transient>& start);
  void SetRootManagement(bool stat);
  int NbRoots() const;
  const opencascade::handle<Standard_Transient>& Root(int num) const;
  opencascade::handle<Transfer_Binder> RootItem(int num) const;
  int RootIndex(const opencascade::handle<Standard_Transient>& start) const;
  int NestingLevel() const;
  void ResetNestingLevel();
  bool Recognize(const opencascade::handle<Standard_Transient>& start) const;
  opencascade::handle<Transfer_Binder> Transferring(const opencascade::handle<Standard_Transient>& start);
  bool Transfer(const opencascade::handle<Standard_Transient>& start);
  void SetErrorHandle(bool err);
  bool ErrorHandle() const;
  void StartTrace(const opencascade::handle<Transfer_Binder>& binder, const opencascade::handle<Standard_Transient>& start, int level, int mode) const;
  void PrintTrace(const opencascade::handle<Standard_Transient>& start, std::ostream& S) const;
  bool IsLooping(int alevel) const;
  Transfer_IteratorOfProcessForTransient RootResult(bool withstart = false) const;
  Transfer_IteratorOfProcessForTransient CompleteResult(bool withstart = false) const;
  Transfer_IteratorOfProcessForTransient AbnormalResult() const;
  Interface_CheckIterator CheckList(bool erronly) const;
  Transfer_IteratorOfProcessForTransient ResultOne(const opencascade::handle<Standard_Transient>& start, int level, bool withstart = false) const;
  Interface_CheckIterator CheckListOne(const opencascade::handle<Standard_Transient>& start, int level, bool erronly) const;
  bool IsCheckListEmpty(const opencascade::handle<Standard_Transient>& start, int level, bool erronly) const;
  void RemoveResult(const opencascade::handle<Standard_Transient>& start, int level, bool compute = true);
  int CheckNum(const opencascade::handle<Standard_Transient>& start) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_ResultFromModel : public Standard_Transient {
public:
  Transfer_ResultFromModel();
  void SetModel(const opencascade::handle<Interface_InterfaceModel>& model);
  void SetFileName(const char* filename);
  opencascade::handle<Interface_InterfaceModel> Model() const;
  const char* FileName() const;
  bool Fill(const opencascade::handle<Transfer_TransientProcess>& TP, const opencascade::handle<Standard_Transient>& ent);
  void Strip(int mode);
  void FillBack(const opencascade::handle<Transfer_TransientProcess>& TP) const;
  bool HasResult() const;
  opencascade::handle<Transfer_ResultFromTransient> MainResult() const;
  void SetMainResult(const opencascade::handle<Transfer_ResultFromTransient>& amain);
  const char* MainLabel() const;
  int MainNumber() const;
  opencascade::handle<Transfer_ResultFromTransient> ResultFromKey(const opencascade::handle<Standard_Transient>& start) const;
  opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>> Results(int level) const;
  opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>> TransferredList(int level = 2) const;
  opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>> CheckedList(Interface_CheckStatus check, bool result) const;
  Interface_CheckIterator CheckList(bool erronly, int level = 2) const;
  Interface_CheckStatus CheckStatus() const;
  Interface_CheckStatus ComputeCheckStatus(bool enforce);
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_ResultFromTransient : public Standard_Transient {
public:
  Transfer_ResultFromTransient();
  void SetStart(const opencascade::handle<Standard_Transient>& start);
  void SetBinder(const opencascade::handle<Transfer_Binder>& binder);
  opencascade::handle<Standard_Transient> Start() const;
  opencascade::handle<Transfer_Binder> Binder() const;
  bool HasResult() const;
  opencascade::handle<Interface_Check> Check() const;
  Interface_CheckStatus CheckStatus() const;
  void ClearSubs();
  void AddSubResult(const opencascade::handle<Transfer_ResultFromTransient>& sub);
  int NbSubResults() const;
  opencascade::handle<Transfer_ResultFromTransient> SubResult(int num) const;
  opencascade::handle<Transfer_ResultFromTransient> ResultFromKey(const opencascade::handle<Standard_Transient>& key) const;
  void FillMap(NCollection_IndexedMap<opencascade::handle<Standard_Transient>, NCollection_DefaultHasher<opencascade::handle<Standard_Transient>>>& map) const;
  void Fill(const opencascade::handle<Transfer_TransientProcess>& TP);
  void Strip();
  void FillBack(const opencascade::handle<Transfer_TransientProcess>& TP) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_TransferFailure : public Interface_InterfaceError {
public:
  Transfer_TransferFailure(const char* theMessage = "");
  Transfer_TransferFailure(const char* theMessage, const char* theStackTrace);
  const char* ExceptionType() const;
};

class Transfer_TransferDeadLoop : public Transfer_TransferFailure {
public:
  Transfer_TransferDeadLoop(const char* theMessage = "");
  Transfer_TransferDeadLoop(const char* theMessage, const char* theStackTrace);
  const char* ExceptionType() const;
};

class Transfer_TransferInput {
public:
  Transfer_TransferInput();
  Interface_EntityIterator Entities(Transfer_TransferIterator& list) const;
  void FillModel(const opencascade::handle<Transfer_TransientProcess>& proc, const opencascade::handle<Interface_InterfaceModel>& amodel) const;
  void FillModel(const opencascade::handle<Transfer_TransientProcess>& proc, const opencascade::handle<Interface_InterfaceModel>& amodel, const opencascade::handle<Interface_Protocol>& proto, bool roots = true) const;
  void FillModel(const opencascade::handle<Transfer_FinderProcess>& proc, const opencascade::handle<Interface_InterfaceModel>& amodel) const;
  void FillModel(const opencascade::handle<Transfer_FinderProcess>& proc, const opencascade::handle<Interface_InterfaceModel>& amodel, const opencascade::handle<Interface_Protocol>& proto, bool roots = true) const;
};

class Transfer_TransferOutput {
public:
  Transfer_TransferOutput(const opencascade::handle<Transfer_ActorOfTransientProcess>& actor, const opencascade::handle<Interface_InterfaceModel>& amodel);
  Transfer_TransferOutput(const opencascade::handle<Transfer_TransientProcess>& proc, const opencascade::handle<Interface_InterfaceModel>& amodel);
  opencascade::handle<Interface_InterfaceModel> Model() const;
  opencascade::handle<Transfer_TransientProcess> TransientProcess() const;
  void Transfer(const opencascade::handle<Standard_Transient>& obj);
  void TransferRoots(const opencascade::handle<Interface_Protocol>& protocol);
  void TransferRoots(const Interface_Graph& G);
  void TransferRoots();
  Interface_EntityIterator ListForStatus(bool normal, bool roots = true) const;
  opencascade::handle<Interface_InterfaceModel> ModelForStatus(const opencascade::handle<Interface_Protocol>& protocol, bool normal, bool roots = true) const;
};

class Transfer_TransientListBinder : public Transfer_Binder {
public:
  Transfer_TransientListBinder();
  Transfer_TransientListBinder(const opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>>& list);
  bool IsMultiple() const;
  opencascade::handle<Standard_Type> ResultType() const;
  const char* ResultTypeName() const;
  void AddResult(const opencascade::handle<Standard_Transient>& res);
  opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>> Result() const;
  void SetResult(int num, const opencascade::handle<Standard_Transient>& res);
  int NbTransients() const;
  const opencascade::handle<Standard_Transient>& Transient(int num) const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_TransientMapper : public Transfer_Finder {
public:
  Transfer_TransientMapper(const opencascade::handle<Standard_Transient>& akey);
  const opencascade::handle<Standard_Transient>& Value() const;
  bool Equates(const opencascade::handle<Transfer_Finder>& other) const;
  opencascade::handle<Standard_Type> ValueType() const;
  const char* ValueTypeName() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_TransientProcess : public Transfer_ProcessForTransient {
public:
  Transfer_TransientProcess(int nb = 10000);
  void SetModel(const opencascade::handle<Interface_InterfaceModel>& model);
  opencascade::handle<Interface_InterfaceModel> Model() const;
  void SetGraph(const opencascade::handle<Interface_HGraph>& HG);
  bool HasGraph() const;
  opencascade::handle<Interface_HGraph> HGraph() const;
  const Interface_Graph& Graph() const;
  void SetContext(const char* name, const opencascade::handle<Standard_Transient>& ctx);
  bool GetContext(const char* name, const opencascade::handle<Standard_Type>& type, opencascade::handle<Standard_Transient>& ctx) const;
  NCollection_DataMap<TCollection_AsciiString, opencascade::handle<Standard_Transient>, NCollection_DefaultHasher<TCollection_AsciiString>>& Context();
  void PrintTrace(const opencascade::handle<Standard_Transient>& start, std::ostream& S) const;
  int CheckNum(const opencascade::handle<Standard_Transient>& ent) const;
  Interface_EntityIterator TypedSharings(const opencascade::handle<Standard_Transient>& start, const opencascade::handle<Standard_Type>& type) const;
  bool IsDataLoaded(const opencascade::handle<Standard_Transient>& ent) const;
  bool IsDataFail(const opencascade::handle<Standard_Transient>& ent) const;
  void PrintStats(int mode, std::ostream& S) const;
  opencascade::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>> RootsForTransfer();
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class Transfer_VoidBinder : public Transfer_Binder {
public:
  Transfer_VoidBinder();
  opencascade::handle<Standard_Type> ResultType() const;
  const char* ResultTypeName() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};
