// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// BRepGraph_CompSolidId: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into BRepGraph_CompSolidId.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.BRepGraph;

[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct BRepGraph_CompSolidId
{
    [FieldOffset(0)] public uint Index;

    public BRepGraph_CompSolidId()
    {
        this = default;
        BRepGraphModule.NetOcc_BRepGraph_CompSolidId_New_0(ref this);
    }

    public BRepGraph_CompSolidId(uint theIdx)
    {
        this = default;
        BRepGraphModule.NetOcc_BRepGraph_CompSolidId_New_1(ref this, theIdx);
    }

    public BRepGraph_CompSolidId(BRepGraph_NodeId theId)
    {
        this = default;
        BRepGraphModule.NetOcc_BRepGraph_CompSolidId_New_2(ref this, theId);
    }

    public static BRepGraph_CompSolidId Start() => BRepGraphModule.NetOcc_BRepGraph_CompSolidId_Start();
    public static BRepGraph_CompSolidId Invalid() => BRepGraphModule.NetOcc_BRepGraph_CompSolidId_Invalid();
    public readonly bool IsValid() => BRepGraphModule.NetOcc_BRepGraph_CompSolidId_IsValid_0(in this);
    public readonly bool IsValid(uint theMaxCount) => BRepGraphModule.NetOcc_BRepGraph_CompSolidId_IsValid_1(in this, theMaxCount);
    public static BRepGraph_CompSolidId FromNodeId(BRepGraph_NodeId theId) => BRepGraphModule.NetOcc_BRepGraph_CompSolidId_FromNodeId(theId);
    public readonly bool IsRemoved(BRepGraph theGraph) => BRepGraphModule.NetOcc_BRepGraph_CompSolidId_IsRemoved(in this, theGraph);
    public readonly bool IsOwned(BRepGraph theGraph) => BRepGraphModule.NetOcc_BRepGraph_CompSolidId_IsOwned(in this, theGraph);
    public static BRepGraph_CompSolidId operator +(in BRepGraph_CompSolidId theSelf, uint theOffset) => BRepGraphModule.NetOcc_BRepGraph_CompSolidId_op_Addition(in theSelf, theOffset);
    public static BRepGraph_CompSolidId operator -(in BRepGraph_CompSolidId theSelf, uint theOffset) => BRepGraphModule.NetOcc_BRepGraph_CompSolidId_op_Subtraction(in theSelf, theOffset);
}
