// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// BRepGraph_SolidId: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into BRepGraph_SolidId.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.BRepGraph;

[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct BRepGraph_SolidId
{
    [FieldOffset(0)] public uint Index;

    public BRepGraph_SolidId()
    {
        this = default;
        BRepGraphModule.NetOcc_BRepGraph_SolidId_New_0(ref this);
    }

    public BRepGraph_SolidId(uint theIdx)
    {
        this = default;
        BRepGraphModule.NetOcc_BRepGraph_SolidId_New_1(ref this, theIdx);
    }

    public BRepGraph_SolidId(BRepGraph_NodeId theId)
    {
        this = default;
        BRepGraphModule.NetOcc_BRepGraph_SolidId_New_2(ref this, theId);
    }

    public static BRepGraph_SolidId Start() => BRepGraphModule.NetOcc_BRepGraph_SolidId_Start();
    public static BRepGraph_SolidId Invalid() => BRepGraphModule.NetOcc_BRepGraph_SolidId_Invalid();
    public readonly bool IsValid() => BRepGraphModule.NetOcc_BRepGraph_SolidId_IsValid_0(in this);
    public readonly bool IsValid(uint theMaxCount) => BRepGraphModule.NetOcc_BRepGraph_SolidId_IsValid_1(in this, theMaxCount);
    public static BRepGraph_SolidId FromNodeId(BRepGraph_NodeId theId) => BRepGraphModule.NetOcc_BRepGraph_SolidId_FromNodeId(theId);
    public readonly bool IsRemoved(BRepGraph theGraph) => BRepGraphModule.NetOcc_BRepGraph_SolidId_IsRemoved(in this, theGraph);
    public readonly bool IsOwned(BRepGraph theGraph) => BRepGraphModule.NetOcc_BRepGraph_SolidId_IsOwned(in this, theGraph);
    public static BRepGraph_SolidId operator +(in BRepGraph_SolidId theSelf, uint theOffset) => BRepGraphModule.NetOcc_BRepGraph_SolidId_op_Addition(in theSelf, theOffset);
    public static BRepGraph_SolidId operator -(in BRepGraph_SolidId theSelf, uint theOffset) => BRepGraphModule.NetOcc_BRepGraph_SolidId_op_Subtraction(in theSelf, theOffset);
}
