// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// IMeshTools_Parameters: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into IMeshTools_Parameters.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.IMeshTools;

[StructLayout(LayoutKind.Explicit, Size = 64)]
public partial struct IMeshTools_Parameters
{
    [FieldOffset(0)] public IMeshTools_MeshAlgoType MeshAlgo;
    [FieldOffset(8)] public double Angle;
    [FieldOffset(16)] public double Deflection;
    [FieldOffset(24)] public double AngleInterior;
    [FieldOffset(32)] public double DeflectionInterior;
    [FieldOffset(40)] public double MinSize;
    [FieldOffset(48)] public byte InParallel;
    [FieldOffset(49)] public byte Relative;
    [FieldOffset(50)] public byte InternalVerticesMode;
    [FieldOffset(51)] public byte ControlSurfaceDeflection;
    [FieldOffset(52)] public byte EnableControlSurfaceDeflectionAllSurfaces;
    [FieldOffset(53)] public byte CleanModel;
    [FieldOffset(54)] public byte AdjustMinSize;
    [FieldOffset(55)] public byte ForceFaceDeflection;
    [FieldOffset(56)] public byte AllowQualityDecrease;

    public IMeshTools_Parameters()
    {
        this = default;
        IMeshToolsModule.NetOcc_IMeshTools_Parameters_New(ref this);
    }

    public static double RelMinSize() => IMeshToolsModule.NetOcc_IMeshTools_Parameters_RelMinSize();
}
