// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Aggregate header for the NetOcc SWIG module AppStd: generated by netocc-gen, don't edit
#pragma once
#include <Standard_Type.hxx>
#include <TDocStd_Application.hxx>
#include <AppStd_Application.hxx>
