// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Flat names of the nested and namespace types of BOPTools for the NetOcc SWIG modules: generated by netocc-gen, don't edit
#pragma once
#include <BVH_BinaryTree.hxx>
#include <BVH_QuadTree.hxx>
#include <BVH_Tree.hxx>

using BVH_Tree_double_2_BVH_BinaryTree = BVH_Tree<double, 2>;
using BVH_Tree_double_3_BVH_BinaryTree = BVH_Tree<double, 3>;
using BVH_Tree_double_2_BVH_QuadTree = BVH_Tree<double, 2, BVH_QuadTree>;
using BVH_Tree_double_3_BVH_QuadTree = BVH_Tree<double, 3, BVH_QuadTree>;
