// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Flat names of the nested and namespace types of BRepGraph for the NetOcc SWIG modules: generated by netocc-gen, don't edit
#pragma once
#include <BRepGraphInc_Definition.hxx>
#include <BRepGraphInc_Instance.hxx>
#include <BRepGraphInc_Reference.hxx>
#include <BRepGraph_CacheMesh.hxx>
#include <BRepGraph_ChildExplorer.hxx>
#include <BRepGraph_Compact.hxx>
#include <BRepGraph_Copy.hxx>
#include <BRepGraph_CopyRemap.hxx>
#include <BRepGraph_Deduplicate.hxx>
#include <BRepGraph_DefsIterator.hxx>
#include <BRepGraph_EditorView.hxx>
#include <BRepGraph_ItemId.hxx>
#include <BRepGraph_ItemUID.hxx>
#include <BRepGraph_LayerDeferred.hxx>
#include <BRepGraph_LayerHistory.hxx>
#include <BRepGraph_LayerLock.hxx>
#include <BRepGraph_LayerParametric.hxx>
#include <BRepGraph_LayerTopoSupplement.hxx>
#include <BRepGraph_MeshView.hxx>
#include <BRepGraph_MutGuard.hxx>
#include <BRepGraph_NodeId.hxx>
#include <BRepGraph_ParallelPolicy.hxx>
#include <BRepGraph_ParentExplorer.hxx>
#include <BRepGraph_RefId.hxx>
#include <BRepGraph_RefsIterator.hxx>
#include <BRepGraph_RefsView.hxx>
#include <BRepGraph_RelatedIterator.hxx>
#include <BRepGraph_ReverseIterator.hxx>
#include <BRepGraph_ShapesView.hxx>
#include <BRepGraph_Tool.hxx>
#include <BRepGraph_TopoView.hxx>
#include <BRepGraph_UIDsView.hxx>
#include <BRepGraph_UsagePath.hxx>
#include <BRepGraph_Validate.hxx>
#include <BRepGraph_VersionStamp.hxx>

using BRepGraph_NodeId_Kind = BRepGraph_NodeId::Kind;
using BRepGraph_RefId_Kind = BRepGraph_RefId::Kind;
using BRepGraph_ItemId_Domain = BRepGraph_ItemId::Domain;
using BRepGraph_ShapesView_AddStatus = BRepGraph::ShapesView::AddStatus;
using BRepGraph_EditorView_WireOps_CoEdgeOrderStatus = BRepGraph::EditorView::WireOps::CoEdgeOrderStatus;
using BRepGraph_EditorView_WireOps_ReplaceEdgeStatus = BRepGraph::EditorView::WireOps::ReplaceEdgeStatus;
using BRepGraph_ItemUID_Domain = BRepGraph_ItemUID::Domain;
using BRepGraph_CopyRemap_Mode = BRepGraph_CopyRemap::Mode;
using BRepGraph_CopyRemap_MappingKind = BRepGraph_CopyRemap::MappingKind;
using BRepGraph_ChildExplorer_LinkKind = BRepGraph_ChildExplorer::LinkKind;
using BRepGraph_ChildExplorer_TraversalMode = BRepGraph_ChildExplorer::TraversalMode;
using BRepGraph_Compact_Options_CachePolicy = BRepGraph_Compact::Options::CachePolicy;
using BRepGraph_Copy_GeomPolicy = BRepGraph_Copy::GeomPolicy;
using BRepGraph_Copy_MeshPolicy = BRepGraph_Copy::MeshPolicy;
using BRepGraph_Copy_CachePolicy = BRepGraph_Copy::CachePolicy;
using BRepGraph_LayerTopoSupplement_AttachmentKind = BRepGraph_LayerTopoSupplement::AttachmentKind;
using BRepGraph_VersionStamp_Domain = BRepGraph_VersionStamp::Domain;
using BRepGraph_LayerDeferred_RepresentationKind = BRepGraph_LayerDeferred::RepresentationKind;
using BRepGraph_LayerHistory_Kind = BRepGraph_LayerHistory::Kind;
using BRepGraph_LayerParametric_GenerationFlag = BRepGraph_LayerParametric::GenerationFlag;
using BRepGraph_LayerParametric_MeshQuality = BRepGraph_LayerParametric::MeshQuality;
using BRepGraph_ParentExplorer_LinkKind = BRepGraph_ParentExplorer::LinkKind;
using BRepGraph_ParentExplorer_TraversalMode = BRepGraph_ParentExplorer::TraversalMode;
using BRepGraph_RelatedIterator_RelationKind = BRepGraph_RelatedIterator::RelationKind;
using BRepGraph_RelatedIterator_Stage = BRepGraph_RelatedIterator::Stage;
using BRepGraph_Validate_Severity = BRepGraph_Validate::Severity;
using BRepGraph_Validate_Mode = BRepGraph_Validate::Mode;
using BRepGraph_TopoView = BRepGraph::TopoView;
using BRepGraph_TopoView_FaceOps = BRepGraph::TopoView::FaceOps;
using BRepGraph_TopoView_EdgeOps = BRepGraph::TopoView::EdgeOps;
using BRepGraph_TopoView_VertexOps = BRepGraph::TopoView::VertexOps;
using BRepGraph_TopoView_WireOps = BRepGraph::TopoView::WireOps;
using BRepGraph_TopoView_ShellOps = BRepGraph::TopoView::ShellOps;
using BRepGraph_TopoView_SolidOps = BRepGraph::TopoView::SolidOps;
using BRepGraph_TopoView_CoEdgeOps = BRepGraph::TopoView::CoEdgeOps;
using BRepGraph_TopoView_CompoundOps = BRepGraph::TopoView::CompoundOps;
using BRepGraph_TopoView_CompSolidOps = BRepGraph::TopoView::CompSolidOps;
using BRepGraph_TopoView_ProductOps = BRepGraph::TopoView::ProductOps;
using BRepGraph_TopoView_OccurrenceOps = BRepGraph::TopoView::OccurrenceOps;
using BRepGraph_TopoView_GenOps = BRepGraph::TopoView::GenOps;
using BRepGraph_TopoView_GeometryOps = BRepGraph::TopoView::GeometryOps;
using BRepGraph_UIDsView = BRepGraph::UIDsView;
using BRepGraph_RefsView = BRepGraph::RefsView;
using BRepGraph_RefsView_ShellOps = BRepGraph::RefsView::ShellOps;
using BRepGraph_RefsView_FaceOps = BRepGraph::RefsView::FaceOps;
using BRepGraph_RefsView_WireOps = BRepGraph::RefsView::WireOps;
using BRepGraph_RefsView_VertexOps = BRepGraph::RefsView::VertexOps;
using BRepGraph_RefsView_SolidOps = BRepGraph::RefsView::SolidOps;
using BRepGraph_RefsView_ChildOps = BRepGraph::RefsView::ChildOps;
using BRepGraph_RefsView_OccurrenceOps = BRepGraph::RefsView::OccurrenceOps;
using BRepGraph_RefsView_GenOps = BRepGraph::RefsView::GenOps;
using BRepGraph_ShapesView = BRepGraph::ShapesView;
using BRepGraph_ShapesView_Options = BRepGraph::ShapesView::Options;
using BRepGraph_ShapesView_Result = BRepGraph::ShapesView::Result;
using BRepGraph_EditorView = BRepGraph::EditorView;
using BRepGraph_EditorView_VertexOps = BRepGraph::EditorView::VertexOps;
using BRepGraph_EditorView_EdgeOps = BRepGraph::EditorView::EdgeOps;
using BRepGraph_EditorView_CoEdgeOps = BRepGraph::EditorView::CoEdgeOps;
using BRepGraph_EditorView_WireOps = BRepGraph::EditorView::WireOps;
using BRepGraph_EditorView_FaceOps = BRepGraph::EditorView::FaceOps;
using BRepGraph_EditorView_ShellOps = BRepGraph::EditorView::ShellOps;
using BRepGraph_EditorView_SolidOps = BRepGraph::EditorView::SolidOps;
using BRepGraph_EditorView_CompoundOps = BRepGraph::EditorView::CompoundOps;
using BRepGraph_EditorView_CompSolidOps = BRepGraph::EditorView::CompSolidOps;
using BRepGraph_EditorView_ProductOps = BRepGraph::EditorView::ProductOps;
using BRepGraph_EditorView_OccurrenceOps = BRepGraph::EditorView::OccurrenceOps;
using BRepGraph_EditorView_GenOps = BRepGraph::EditorView::GenOps;
using BRepGraph_EditorView_BoundaryIssue = BRepGraph::EditorView::BoundaryIssue;
using BRepGraph_MeshView = BRepGraph::MeshView;
using BRepGraph_MeshView_CacheView = BRepGraph::MeshView::CacheView;
using BRepGraph_MeshView_CacheView_FaceOps = BRepGraph::MeshView::CacheView::FaceOps;
using BRepGraph_MeshView_CacheView_EdgeOps = BRepGraph::MeshView::CacheView::EdgeOps;
using BRepGraph_MeshView_CacheView_CoEdgeOps = BRepGraph::MeshView::CacheView::CoEdgeOps;
using BRepGraph_MeshView_PersistentView = BRepGraph::MeshView::PersistentView;
using BRepGraph_MeshView_PersistentView_FaceOps = BRepGraph::MeshView::PersistentView::FaceOps;
using BRepGraph_MeshView_PersistentView_EdgeOps = BRepGraph::MeshView::PersistentView::EdgeOps;
using BRepGraph_MeshView_PersistentView_CoEdgeOps = BRepGraph::MeshView::PersistentView::CoEdgeOps;
using BRepGraph_MeshView_EffectiveView = BRepGraph::MeshView::EffectiveView;
using BRepGraph_MeshView_EffectiveView_FaceOps = BRepGraph::MeshView::EffectiveView::FaceOps;
using BRepGraph_MeshView_EffectiveView_EdgeOps = BRepGraph::MeshView::EffectiveView::EdgeOps;
using BRepGraph_MeshView_EffectiveView_CoEdgeOps = BRepGraph::MeshView::EffectiveView::CoEdgeOps;
using BRepGraph_MeshView_EditorView = BRepGraph::MeshView::EditorView;
using BRepGraph_MeshView_EditorView_FaceOps = BRepGraph::MeshView::EditorView::FaceOps;
using BRepGraph_MeshView_EditorView_EdgeOps = BRepGraph::MeshView::EditorView::EdgeOps;
using BRepGraph_MeshView_EditorView_CoEdgeOps = BRepGraph::MeshView::EditorView::CoEdgeOps;
using BRepGraph_MeshView_PolyOps = BRepGraph::MeshView::PolyOps;
using BRepGraph_CacheMesh_EntryStamp = BRepGraph_CacheMesh::EntryStamp;
using BRepGraph_CacheMesh_FaceMeshEntry = BRepGraph_CacheMesh::FaceMeshEntry;
using BRepGraph_CacheMesh_CoEdgeMeshEntry = BRepGraph_CacheMesh::CoEdgeMeshEntry;
using BRepGraph_CacheMesh_EdgeMeshEntry = BRepGraph_CacheMesh::EdgeMeshEntry;
using BRepGraph_CacheMesh_DirtySet = BRepGraph_CacheMesh::DirtySet;
using BRepGraph_CacheMesh_SlotState = BRepGraph_CacheMesh::SlotState;
using BRepGraph_CacheMesh_Driver = BRepGraph_CacheMesh::Driver;
using BRepGraph_UsagePath_Step = BRepGraph_UsagePath::Step;
using BRepGraph_ChildExplorer_Config = BRepGraph_ChildExplorer::Config;
using BRepGraph_Compact_Options = BRepGraph_Compact::Options;
using BRepGraph_Compact_Result = BRepGraph_Compact::Result;
using BRepGraph_LayerTopoSupplement_Entry = BRepGraph_LayerTopoSupplement::Entry;
using BRepGraph_Deduplicate_Options = BRepGraph_Deduplicate::Options;
using BRepGraph_Deduplicate_Result = BRepGraph_Deduplicate::Result;
using BRepGraph_DefsIterator_ShellOfSolidTraits = BRepGraph_DefsIterator::ShellOfSolidTraits;
using BRepGraph_DefsIterator_FaceOfShellTraits = BRepGraph_DefsIterator::FaceOfShellTraits;
using BRepGraph_DefsIterator_WireOfFaceTraits = BRepGraph_DefsIterator::WireOfFaceTraits;
using BRepGraph_DefsIterator_CoEdgeOfWireTraits = BRepGraph_DefsIterator::CoEdgeOfWireTraits;
using BRepGraph_DefsIterator_EdgeOfWireTraits = BRepGraph_DefsIterator::EdgeOfWireTraits;
using BRepGraph_DefsIterator_SolidOfCompSolidTraits = BRepGraph_DefsIterator::SolidOfCompSolidTraits;
using BRepGraph_DefsIterator_ChildOfCompoundTraits = BRepGraph_DefsIterator::ChildOfCompoundTraits;
using BRepGraph_DefsIterator_OccurrenceOfProductTraits = BRepGraph_DefsIterator::OccurrenceOfProductTraits;
using BRepGraph_DefsIterator_DefsVertexOfEdge = BRepGraph_DefsIterator::DefsVertexOfEdge;
using BRepGraph_LayerDeferred_Representation = BRepGraph_LayerDeferred::Representation;
using BRepGraph_LayerDeferred_Entry = BRepGraph_LayerDeferred::Entry;
using BRepGraph_LayerDeferred_Entry_RepresentationStorage = BRepGraph_LayerDeferred::Entry::RepresentationStorage;
using BRepGraph_LayerHistory_Event = BRepGraph_LayerHistory::Event;
using BRepGraph_LayerLock_ScopedOwnerEdit = BRepGraph_LayerLock::ScopedOwnerEdit;
using BRepGraph_LayerParametric_AddResult = BRepGraph_LayerParametric::AddResult;
using BRepGraph_ParallelPolicy_Workload = BRepGraph_ParallelPolicy::Workload;
using BRepGraph_ParentExplorer_Config = BRepGraph_ParentExplorer::Config;
using BRepGraph_RefsIterator_ShellOfSolidTraits = BRepGraph_RefsIterator::ShellOfSolidTraits;
using BRepGraph_RefsIterator_FaceOfShellTraits = BRepGraph_RefsIterator::FaceOfShellTraits;
using BRepGraph_RefsIterator_WireOfFaceTraits = BRepGraph_RefsIterator::WireOfFaceTraits;
using BRepGraph_RefsIterator_CoEdgeOfWireTraits = BRepGraph_RefsIterator::CoEdgeOfWireTraits;
using BRepGraph_RefsIterator_SolidOfCompSolidTraits = BRepGraph_RefsIterator::SolidOfCompSolidTraits;
using BRepGraph_RefsIterator_ChildOfCompoundTraits = BRepGraph_RefsIterator::ChildOfCompoundTraits;
using BRepGraph_RefsIterator_OccurrenceOfProductTraits = BRepGraph_RefsIterator::OccurrenceOfProductTraits;
using BRepGraph_RefsIterator_RefsVertexOfEdge = BRepGraph_RefsIterator::RefsVertexOfEdge;
using BRepGraph_ReverseIterator_WireOfCoEdgeUsageTraits = BRepGraph_ReverseIterator::WireOfCoEdgeUsageTraits;
using BRepGraph_ReverseIterator_WireFromEdgeCoEdgeTraits = BRepGraph_ReverseIterator::WireFromEdgeCoEdgeTraits;
using BRepGraph_ReverseIterator_FaceFromEdgeCoEdgeTraits = BRepGraph_ReverseIterator::FaceFromEdgeCoEdgeTraits;
using BRepGraph_ReverseIterator_EdgeOfVertexRefTraits = BRepGraph_ReverseIterator::EdgeOfVertexRefTraits;
using BRepGraph_ReverseIterator_FaceFromWireRefTraits = BRepGraph_ReverseIterator::FaceFromWireRefTraits;
using BRepGraph_ReverseIterator_ShellFromFaceRefTraits = BRepGraph_ReverseIterator::ShellFromFaceRefTraits;
using BRepGraph_ReverseIterator_SolidFromShellRefTraits = BRepGraph_ReverseIterator::SolidFromShellRefTraits;
using BRepGraph_ReverseIterator_CompSolidFromSolidRefTraits = BRepGraph_ReverseIterator::CompSolidFromSolidRefTraits;
using BRepGraph_ReverseIterator_CompoundFromChildRefTraits = BRepGraph_ReverseIterator::CompoundFromChildRefTraits;
using BRepGraph_ReverseIterator_OccurrenceFromOccurrenceRefTraits = BRepGraph_ReverseIterator::OccurrenceFromOccurrenceRefTraits;
using BRepGraph_ReverseIterator_ProductFromOccurrenceRefTraits = BRepGraph_ReverseIterator::ProductFromOccurrenceRefTraits;
using BRepGraph_Tool_Vertex = BRepGraph_Tool::Vertex;
using BRepGraph_Tool_Edge = BRepGraph_Tool::Edge;
using BRepGraph_Tool_CoEdge = BRepGraph_Tool::CoEdge;
using BRepGraph_Tool_Face = BRepGraph_Tool::Face;
using BRepGraph_Tool_Wire = BRepGraph_Tool::Wire;
using BRepGraph_Tool_Shell = BRepGraph_Tool::Shell;
using BRepGraph_Validate_Issue = BRepGraph_Validate::Issue;
using BRepGraph_Validate_Result = BRepGraph_Validate::Result;
using BRepGraph_Validate_Options = BRepGraph_Validate::Options;
using BRepGraph_MutGuard_BRepGraphInc_VertexDef = BRepGraph_MutGuard<BRepGraphInc::VertexDef>;
using BRepGraph_MutGuard_BRepGraphInc_VertexRef = BRepGraph_MutGuard<BRepGraphInc::VertexRef>;
using BRepGraph_MutGuard_BRepGraphInc_EdgeDef = BRepGraph_MutGuard<BRepGraphInc::EdgeDef>;
using BRepGraph_MutGuard_BRepGraphInc_CoEdgeDef = BRepGraph_MutGuard<BRepGraphInc::CoEdgeDef>;
using BRepGraph_MutGuard_BRepGraphInc_WireDef = BRepGraph_MutGuard<BRepGraphInc::WireDef>;
using BRepGraph_MutGuard_BRepGraphInc_WireRef = BRepGraph_MutGuard<BRepGraphInc::WireRef>;
using BRepGraph_MutGuard_BRepGraphInc_FaceDef = BRepGraph_MutGuard<BRepGraphInc::FaceDef>;
using BRepGraph_MutGuard_BRepGraphInc_FaceRef = BRepGraph_MutGuard<BRepGraphInc::FaceRef>;
using BRepGraph_MutGuard_BRepGraphInc_ShellDef = BRepGraph_MutGuard<BRepGraphInc::ShellDef>;
using BRepGraph_MutGuard_BRepGraphInc_ShellRef = BRepGraph_MutGuard<BRepGraphInc::ShellRef>;
using BRepGraph_MutGuard_BRepGraphInc_SolidDef = BRepGraph_MutGuard<BRepGraphInc::SolidDef>;
using BRepGraph_MutGuard_BRepGraphInc_SolidRef = BRepGraph_MutGuard<BRepGraphInc::SolidRef>;
using BRepGraph_MutGuard_BRepGraphInc_CompoundDef = BRepGraph_MutGuard<BRepGraphInc::CompoundDef>;
using BRepGraph_MutGuard_BRepGraphInc_CompSolidDef = BRepGraph_MutGuard<BRepGraphInc::CompSolidDef>;
using BRepGraph_MutGuard_BRepGraphInc_ProductDef = BRepGraph_MutGuard<BRepGraphInc::ProductDef>;
using BRepGraph_MutGuard_BRepGraphInc_OccurrenceDef = BRepGraph_MutGuard<BRepGraphInc::OccurrenceDef>;
using BRepGraph_MutGuard_BRepGraphInc_OccurrenceRef = BRepGraph_MutGuard<BRepGraphInc::OccurrenceRef>;
using BRepGraph_MutGuard_BRepGraphInc_ChildRef = BRepGraph_MutGuard<BRepGraphInc::ChildRef>;
using BRepGraphInc_Instance_BRepGraph_NodeId = BRepGraphInc::Instance<BRepGraph_NodeId>;
using BRepGraph_ReverseIterator_ParentRef_BRepGraph_WireId_BRepGraph_CoEdgeId = BRepGraph_ReverseIterator::ParentRef<BRepGraph_NodeId::Typed<BRepGraph_NodeId::Kind::Wire>, BRepGraph_NodeId::Typed<BRepGraph_NodeId::Kind::CoEdge>>;
using BRepGraph_ReverseIterator_ParentRef_BRepGraph_EdgeId_BRepGraph_VertexRefId = BRepGraph_ReverseIterator::ParentRef<BRepGraph_NodeId::Typed<BRepGraph_NodeId::Kind::Edge>, BRepGraph_RefId::Typed<BRepGraph_RefId::Kind::Vertex>>;
using BRepGraph_Tool_VertexUsage = BRepGraph_Tool::VertexUsage;
using BRepGraph_Tool_CoEdgeUsage = BRepGraph_Tool::CoEdgeUsage;
using BRepGraph_Tool_FaceUsage = BRepGraph_Tool::FaceUsage;
using BRepGraph_Tool_WireUsage = BRepGraph_Tool::WireUsage;
using BRepGraph_Tool_ShellUsage = BRepGraph_Tool::ShellUsage;
