// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Aggregate header for the NetOcc SWIG module DEGLTF: generated by netocc-gen, don't edit
#pragma once
#include <DE_ConfigurationContext.hxx>
#include <DE_ConfigurationNode.hxx>
#include <DE_Provider.hxx>
#include <NCollection_List.hxx>
#include <Standard_Type.hxx>
#include <TDocStd_Document.hxx>
#include <TopoDS_Shape.hxx>
#include <XSControl_WorkSession.hxx>
#include <DEGLTF_ConfigurationNode.hxx>
#include <DEGLTF_Provider.hxx>
#include <DEGLTF_nested.hxx>
