// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Flat names of the nested and namespace types of Geom2dAdaptor for the NetOcc SWIG modules: generated by netocc-gen, don't edit
#pragma once
#include <Geom2dAdaptor_Curve.hxx>

using Geom2dAdaptor_Curve_OffsetData = Geom2dAdaptor_Curve::OffsetData;
using Geom2dAdaptor_Curve_BezierData = Geom2dAdaptor_Curve::BezierData;
using Geom2dAdaptor_Curve_BSplineData = Geom2dAdaptor_Curve::BSplineData;
