// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Flat names of the nested and namespace types of GeomLProp for the NetOcc SWIG modules: generated by netocc-gen, don't edit
#pragma once
#include <GeomLProp_SurfaceUtils.hxx>

using LProp_SurfaceUtils_DirectAccess = LProp_SurfaceUtils::DirectAccess;
