// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Flat names of the nested and namespace types of IntPatch for the NetOcc SWIG modules: generated by netocc-gen, don't edit
#pragma once
#include <IntPatch_BVHTraversal.hxx>
#include <IntPatch_ImpImpIntersection.hxx>
#include <IntPatch_WLine.hxx>

using IntPatch_ImpImpIntersection_IntStatus = IntPatch_ImpImpIntersection::IntStatus;
using IntPatch_WLine_IntPatch_WLType = IntPatch_WLine::IntPatch_WLType;
using IntPatch_BVHTraversal_TrianglePair = IntPatch_BVHTraversal::TrianglePair;
