// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Aggregate header for the NetOcc SWIG module IntWalk: generated by netocc-gen, don't edit
#pragma once
#include <IntSurf_LineOn2S.hxx>
#include <Adaptor3d_Surface.hxx>
#include <IntImp_ConstIsoparametric.hxx>
#include <IntSurf_PntOn2S.hxx>
#include <NCollection_Array1.hxx>
#include <gp_Dir.hxx>
#include <gp_Dir2d.hxx>
#include <gp_Pnt.hxx>
#include <math_FunctionSetRoot.hxx>
#include <math_FunctionSetWithDerivatives.hxx>
#include <math_Matrix.hxx>
#include <math_VectorBase.hxx>
#include <IntWalk_PWalking.hxx>
#include <IntWalk_StatusDeflection.hxx>
#include <IntWalk_TheFunctionOfTheInt2S.hxx>
#include <IntWalk_TheInt2S.hxx>
#include <IntWalk_VectorOfInteger.hxx>
#include <IntWalk_VectorOfWalkingData.hxx>
