// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Aggregate header for the NetOcc SWIG module MathPoly: generated by netocc-gen, don't edit
#pragma once
#include <MathUtils_nested.hxx>
#include <MathPoly_Cubic.hxx>
#include <MathPoly_Laguerre.hxx>
#include <MathPoly_Quadratic.hxx>
#include <MathPoly_Quartic.hxx>
#include <MathPoly_nested.hxx>
