// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Aggregate header for the NetOcc SWIG module TopCnx: generated by netocc-gen, don't edit
#pragma once
#include <TopAbs_Orientation.hxx>
#include <gp_Dir.hxx>
#include <TopCnx_EdgeFaceTransition.hxx>
