// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Flat names of the nested and namespace types of TopOpeBRep for the NetOcc SWIG modules: generated by netocc-gen, don't edit
#pragma once
#include <NCollection_TListIterator.hxx>
#include <Standard_Handle.hxx>
#include <TopOpeBRepDS_Interference.hxx>

using TopOpeBRepDS_ListIteratorOfListOfInterference = NCollection_TListIterator<opencascade::handle<TopOpeBRepDS_Interference>>;
