// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Aggregate header for the NetOcc SWIG module UTL: generated by netocc-gen, don't edit
#pragma once
#include <OSD_FileIterator.hxx>
#include <OSD_Path.hxx>
#include <Resource_Manager.hxx>
#include <Storage_BaseDriver.hxx>
#include <Storage_Data.hxx>
#include <Storage_Error.hxx>
#include <Storage_OpenMode.hxx>
#include <UTL.hxx>
