// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Aggregate header for the NetOcc SWIG module VrmlAPI: generated by netocc-gen, don't edit
#pragma once
#include <NCollection_HArray1.hxx>
#include <Quantity_Color.hxx>
#include <RWMesh_CafReader.hxx>
#include <Standard_Type.hxx>
#include <TDocStd_Document.hxx>
#include <TopoDS_Shape.hxx>
#include <VrmlConverter_Drawer.hxx>
#include <Vrml_Material.hxx>
#include <VrmlAPI.hxx>
#include <VrmlAPI_CafReader.hxx>
#include <VrmlAPI_RepresentationOfShape.hxx>
#include <VrmlAPI_Writer.hxx>
