// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// MathRoot_NullInterval: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into MathRoot_NullInterval.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.MathRoot;

[StructLayout(LayoutKind.Explicit, Size = 24)]
public partial struct MathRoot_NullInterval
{
    [FieldOffset(0)] public double A;
    [FieldOffset(8)] public double B;
    [FieldOffset(16)] public int State;

    public MathRoot_NullInterval()
    {
        this = default;
        MathRootModule.NetOcc_MathRoot_NullInterval_New(ref this);
    }
}
