// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// MathInteg_MultipleConfig: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into MathInteg_MultipleConfig.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.MathInteg;

[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct MathInteg_MultipleConfig
{
    [FieldOffset(0)] public int MaxOrder;

    public MathInteg_MultipleConfig()
    {
        this = default;
        MathIntegModule.NetOcc_MathInteg_MultipleConfig_New(ref this);
    }
}
