// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// SelectMgr_TriangularFrustum_SelectionTriangle: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config.
// Managed members go into SelectMgr_TriangularFrustum_SelectionTriangle.cs, a partial of this struct; the generator leaves those out.

using System.Runtime.InteropServices;

namespace OCC.Core.SelectMgr;

using OCC.Core.gp;

[StructLayout(LayoutKind.Explicit, Size = 48)]
public partial struct SelectMgr_TriangularFrustum_SelectionTriangle
{
    [FieldOffset(0)] public gp_Pnt2d Points_0;
    [FieldOffset(16)] public gp_Pnt2d Points_1;
    [FieldOffset(32)] public gp_Pnt2d Points_2;

    public SelectMgr_TriangularFrustum_SelectionTriangle()
    {
        this = default;
        SelectMgrModule.NetOcc_SelectMgr_TriangularFrustum_SelectionTriangle_New(ref this);
    }
}
